/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   列表回顾界面
*
*/
// USER END

#include "DIALOG.h"
#include "HEADER.h"

#include "Public_menuDLG.h"
#include "file_operate.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

//ID
#define ID_WINDOW_LISTREVIEW                    (GUI_WINDOW_LIST_REVIEW_ID + 0x01)
#define ID_BUTTON_LISTREVIEW_RESULT             (GUI_WINDOW_LIST_REVIEW_ID + 0x02)
#define ID_BUTTON_LISTREVIEW_RefreshNet         (GUI_WINDOW_LIST_REVIEW_ID + 0x03)
#define ID_BUTTON_LIST_REVIEW_EDIT              (GUI_WINDOW_LIST_REVIEW_ID + 0x04)
#define ID_BUTTON_LIST_REVIEW_DELETE            (GUI_WINDOW_LIST_REVIEW_ID + 0x05)
#define ID_BUTTON_LIST_REVIEW_PRINT             (GUI_WINDOW_LIST_REVIEW_ID + 0x06)
#define ID_BUTTON_LIST_REVIEW_PATIENT           (GUI_WINDOW_LIST_REVIEW_ID + 0x07)
#define ID_BUTTON_LIST_REVIEW_LASTPAGE          (GUI_WINDOW_LIST_REVIEW_ID + 0x08)
#define ID_BUTTON_LIST_REVIEW_LASTRECORD        (GUI_WINDOW_LIST_REVIEW_ID + 0x09)
#define ID_BUTTON_LIST_REVIEW_NEXTRECORD        (GUI_WINDOW_LIST_REVIEW_ID + 0x0A)
#define ID_BUTTON_LIST_REVIEW_NEXTPAGE          (GUI_WINDOW_LIST_REVIEW_ID + 0x0B)
#define ID_LISTVIEW_LIST_REVIEW                 (GUI_WINDOW_LIST_REVIEW_ID + 0x0C)



#define   LISTREVIEW_BTN_DISABLE_COLOR              0x00f3f1ec
// list view
#define GUI_LISTREVIEW_DISABLE_COLOR		        0x00f3f1ec

// header
#define GUI_LISTREVIEW_HEADER_BK_COLOR		        0xf1e7d2



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
//static uint8_t g_ucListView_Row        = 0;     //List View控件选中的行号
uint8_t g_ucListView_DataIndex         = 0;     //List View控件选中的行号，对应的g_ucaListReview_DataTable[]下标 

// USER START (Optionally insert additional static data)
// USER END





/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO ListReview_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "",     ID_WINDOW_LISTREVIEW,               0, 60, 800, 393, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LISTREVIEW_RESULT,        20, 13, 110, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LISTREVIEW_RefreshNet,    140, 13, 110, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LIST_REVIEW_EDIT,         350, 13, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LIST_REVIEW_DELETE,       460, 13, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LIST_REVIEW_PRINT,        570, 13, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LIST_REVIEW_PATIENT,      680, 13, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LIST_REVIEW_LASTPAGE,     740, 60, 40, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LIST_REVIEW_LASTRECORD,   740, 140, 40, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LIST_REVIEW_NEXTRECORD,   740, 220, 40, 80, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",     ID_BUTTON_LIST_REVIEW_NEXTPAGE,     740, 300, 40, 82, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "",   ID_LISTVIEW_LIST_REVIEW,            20, 60, 720, 322, 0, 0x0, 0 },
  
  // USER START (Optionally insert additional widgets)
  // USER EN0
};
/*******************************************************************
0
0       Static code
0
0*********************************************************************
*/



/*
*   列表回顾数据中，当前选中的WBCHGB 信息
*/
__IO WBCHGB_TestInfo_t* ListView_Current_WBCHGB_Info(void)
{ 
   extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
   return &MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]];   
}


/*
*   列表回顾数据中，初始化数据的个数
*/
static uint8_t ListView_InitData_Num(void)
{ 
    extern __IO MachRunPara_s MachRunPara;
    
    uint8_t i = 0, ucNum = 0;
    for(i = 0; i < LIST_REVIEW_ROW_NUM; i++)
    {
        if(DATA_STATUS_INIT == MachRunPara.taListView_Data[i].eDataStatus && INVALID_DATA_SN == MachRunPara.taListView_Data[i].ulCurDataSN)
        {
            //无效数据，不显示出来
            ucNum++;
        }
    }
    
    //
    return ucNum; 
}


/*
*   根据当前的数据下标号，找到对应的list review控件的行号， 
*（g_ucaListReview_DataTable为SN降序，ucDataIndex为当前数据在g_ucaListReview_DataTable的下标号，满足下面转换关系）
*/
uint8_t ListView_DataIndex2Row(uint8_t ucDataIndex)
{ 
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
    uint8_t ucRow = 0;
 
    ucRow = ucDataIndex - ListView_InitData_Num();
    return ucRow;
    
}


/*
*   根据当前的list review控件的行号，找到对应的数据下标号
*/
uint8_t ListView_Row2DataIndex(uint8_t ucRow)
{ 
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
    uint8_t Index = 0;
        
    Index =  ListView_InitData_Num() + ucRow;
    
    return Index; 
}



/*
*   更新当前选中的数据表g_ucaListReview_DataTable[] 下标号g_ucListView_DataIndex
*/
uint32_t Update_ListView_DataIndex(WM_MESSAGE *pMsg)
{
    uint8_t ucTemp = 0, ucCurNum = 0, ucInitDataNum = 0;
    //
    ucInitDataNum = ListView_InitData_Num();
    if(ucInitDataNum >=  LIST_REVIEW_ROW_NUM)
    {
        //均为无效数据
        g_ucListView_DataIndex = LIST_REVIEW_ROW_NUM-1; //指向 taListView_Data[g_ucaListReview_DataTable[0]]，此时该数据为无效数据
        return LIST_REVIEW_ROW_NUM;
    }else{
        //存在有效数据
       
        //有效行数
        ucCurNum = LIST_REVIEW_ROW_NUM - ListView_InitData_Num();
        //当前选中的行号
        ucTemp = LISTVIEW_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_LIST_REVIEW));
        //
        if(ucTemp > ucCurNum-1)
        {
            //选中的为空白行，设置为有数据的最后一行
            LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_LIST_REVIEW), ucCurNum-1);    
            g_ucListView_DataIndex = ucInitDataNum + ucCurNum-1;
        }else{
            //选中有数据的行
            g_ucListView_DataIndex = ucInitDataNum + ucTemp;
        }
    }
    //
    return g_ucListView_DataIndex;
}
     





// list Review 按钮自定义 回调函数
static void ListReview_Btn_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        int Id;

        WM_GetClientRect(&Rect);
        Id = WM_GetId(pMsg->hWin);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            
            //根据区别不同btn
            //圆形btn
            if (ID_BUTTON_LISTREVIEW_RESULT <= Id && Id <= ID_BUTTON_LIST_REVIEW_PATIENT)
            {
                GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
                
                //往btn，写入字符或图标
                GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
            }
            //直角btn
            if (ID_BUTTON_LIST_REVIEW_LASTPAGE <= Id && Id <= ID_BUTTON_LIST_REVIEW_NEXTPAGE)
            {
                //enable
                GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
            }

            //
            if (ID_BUTTON_LISTREVIEW_RESULT == Id)
            {
                //结果详情
                GUI_DispStringInRect(g_ucaLng_ResultInfo[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(ID_BUTTON_LISTREVIEW_RefreshNet == Id){
				//刷新网络
                GUI_DispStringInRect(g_ucaLng_ReFreshNet[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			}
            else if (ID_BUTTON_LIST_REVIEW_EDIT == Id) {
                //编辑
                GUI_DispStringInRect(g_ucaLng_Edit[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_LIST_REVIEW_DELETE == Id) {
                //删除
                GUI_DispStringInRect(g_ucaLng_Delete[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_LIST_REVIEW_PRINT == Id) {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_LIST_REVIEW_PATIENT == Id) {
                //病人信息
                GUI_DispStringInRect(g_ucaLng_PatientInfo[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_LIST_REVIEW_LASTPAGE == Id) {                
				UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
            }else if (ID_BUTTON_LIST_REVIEW_LASTRECORD == Id) {
                 UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);               
            }else if (ID_BUTTON_LIST_REVIEW_NEXTRECORD == Id) {
                 UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
            }else if (ID_BUTTON_LIST_REVIEW_NEXTPAGE == Id) {
                 UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
            }
        }
        else {
            //根据区别不同btn
            //圆形btn
            if (ID_BUTTON_LISTREVIEW_RESULT <= Id && Id <= ID_BUTTON_LIST_REVIEW_PATIENT)
            {
                GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
				
                GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
                GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 19);
				
                //往btn，写入字符或图标
                GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
            }
            //直角btn
            if (ID_BUTTON_LIST_REVIEW_LASTPAGE <= Id && Id <= ID_BUTTON_LIST_REVIEW_NEXTPAGE)
            {
                if(WM_IsEnabled(pMsg->hWin))
                {
                    //enable
                    GUI_SetColor(MachInfo.companyInfo.skin.title);
                    GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
                    //frame
                    GUI_SetColor(MachInfo.companyInfo.skin.buttBoard); //画框
                    GUI_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
					
                    if (ID_BUTTON_LIST_REVIEW_LASTPAGE == Id) {
                         UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
                    }else if (ID_BUTTON_LIST_REVIEW_LASTRECORD == Id) {
                         UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
                    }else if (ID_BUTTON_LIST_REVIEW_NEXTRECORD == Id) {
                         UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
                    }else if (ID_BUTTON_LIST_REVIEW_NEXTPAGE == Id) {
                         UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
                    }
                }else{
                     //diable
                    GUI_SetColor(GUI_BTN_DISABLE_COLOR);
                    GUI_FillRectEx(&Rect);
                    GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
                    GUI_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
                    //
                    if (ID_BUTTON_LIST_REVIEW_LASTPAGE == Id) {
                         UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
                    }else if (ID_BUTTON_LIST_REVIEW_LASTRECORD == Id) {
                         UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
                    }else if (ID_BUTTON_LIST_REVIEW_NEXTRECORD == Id) {
                         UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
                    }else if (ID_BUTTON_LIST_REVIEW_NEXTPAGE == Id) {
                         UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
                    }
                                 
                }
            }

            //
            if (ID_BUTTON_LISTREVIEW_RESULT == Id)
            {
                //结果详情
                GUI_DispStringInRect(g_ucaLng_ResultInfo[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(ID_BUTTON_LISTREVIEW_RefreshNet == Id){
				//刷新网络
                GUI_DispStringInRect(g_ucaLng_ReFreshNet[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
			}
			else if (ID_BUTTON_LIST_REVIEW_EDIT == Id) {
                //编辑
                GUI_DispStringInRect(g_ucaLng_Edit[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_LIST_REVIEW_DELETE == Id) {
                //删除
                GUI_DispStringInRect(g_ucaLng_Delete[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_LIST_REVIEW_PRINT == Id) {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_LIST_REVIEW_PATIENT == Id) {
                //病人信息
                GUI_DispStringInRect(g_ucaLng_PatientInfo[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



// init
//#define LIST_REVIEW_ROW_NUM     7   //行,在msg_def.h中定义，一次最多显示LIST_REVIEW_ROW_NUM个结果
#define LIST_REVIEW_COLUMN        8   //列
static void ListReview_Msg_Init(WM_MESSAGE* pMsg)
{
	extern  MachInfo_s	MachInfo;
    uint8_t ucRow = 0;
    int i = 0;
    WM_HWIN hItem;
    GUI_RECT Rect;
	HEADER_SKINFLEX_PROPS pProps;
    
    GUI_GetClientRect(&Rect);
    //result info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LISTREVIEW_RESULT);
    WM_SetCallback(hItem, ListReview_Btn_Callback);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LISTREVIEW_RefreshNet);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetCallback(hItem, ListReview_Btn_Callback);
	}else{
		//英文版不显示刷新网络按钮
		WM_HideWindow(hItem);
	}
  
    //edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_EDIT);
    WM_SetCallback(hItem, ListReview_Btn_Callback);     
     //普通账号，没有编辑权限
    if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority)
    { 
        //隐藏编辑控件
        WM_HideWindow(hItem);
    }
    
    //delete
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_DELETE);
    WM_SetCallback(hItem, ListReview_Btn_Callback);
     //普通账号，没有删除权限
    if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority)
    { 
       //隐藏删除控件
        WM_HideWindow(hItem);
    }
    //print
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_PRINT);
    WM_SetCallback(hItem, ListReview_Btn_Callback);

    //patient
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_PATIENT);
    WM_SetCallback(hItem, ListReview_Btn_Callback);

    //last page
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_LASTPAGE);
    WM_SetCallback(hItem, ListReview_Btn_Callback);

    //last record
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_LASTRECORD);
    WM_SetCallback(hItem, ListReview_Btn_Callback);

    // next record
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_NEXTRECORD);
    //BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, LISTREVIEW_BTN_DISABLE_COLOR);
    WM_SetCallback(hItem, ListReview_Btn_Callback);

    // next page
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_NEXTPAGE);
    WM_SetCallback(hItem, ListReview_Btn_Callback);  

    //list review listview
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_LIST_REVIEW);
    WM_SetFocus(hItem);
	
	//设置HEADER皮肤属性
	LISTVIEW_GetHeader(hItem);
	HEADER_GetSkinFlexProps(&pProps,0);
	pProps.aColorLower[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorLower[1] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[1] = MachInfo.companyInfo.skin.title;
	HEADER_SetSkinFlexProps(&pProps,0);
    
    //WM_EnableWindow(hItem);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_UNSEL, GUI_WHITE);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SEL, MachInfo.companyInfo.skin.highlightKJNotSelect);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SELFOCUS, MachInfo.companyInfo.skin.highlightKJNotSelect);
    LISTVIEW_SetHeaderHeight(hItem, 40);
    LISTVIEW_SetRowHeight(hItem, 40);
    for (i = 0; i < LIST_REVIEW_ROW_NUM; i++)
    {
        // 7行
        LISTVIEW_AddRow(hItem, NULL);
    }
    
    //增加8列
    LISTVIEW_AddColumn(hItem, 80, g_ucaLng_SampleNum[MachInfo.systemSet.eLanguage],   GUI_TA_HCENTER | GUI_TA_VCENTER);   //样本编号
    LISTVIEW_AddColumn(hItem, 135, g_ucaLng_Name[MachInfo.systemSet.eLanguage],        GUI_TA_HCENTER | GUI_TA_VCENTER);  //姓名
    LISTVIEW_AddColumn(hItem, 160, g_ucaLng_CheckTime[MachInfo.systemSet.eLanguage],  GUI_TA_HCENTER | GUI_TA_VCENTER);   //检测时间
    LISTVIEW_AddColumn(hItem, 70, "WBC",        GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 70, "HGB",        GUI_TA_HCENTER | GUI_TA_VCENTER);
	switch(MachInfo.companyInfo.company){
		case COMPANY_JIN_RUI:
		{
			//锦瑞
			LISTVIEW_AddColumn(hItem, 70, "Neu%",      GUI_TA_HCENTER | GUI_TA_VCENTER);
		}break;
		
		default :
		{
			LISTVIEW_AddColumn(hItem, 70, "Gran%",      GUI_TA_HCENTER | GUI_TA_VCENTER);
		}break;
	}
    LISTVIEW_AddColumn(hItem, 70, "Mid%",       GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 70, "Lym%",       GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    //选中第*行
    ucRow = ListView_DataIndex2Row(g_ucListView_DataIndex);
    LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_LIST_REVIEW), ucRow);
}




/*
*   显示列表数据，降序显示（只显示有效的数据），
*   行号（升序）和g_ucaListReview_DataTable[]下标降序，
*/
static void ListReview_Msg_Paint(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s MachRunPara;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];

    WM_HWIN hItem;
    int i = 0, index = 0;
    char buffer[20] = {0};
    uint32_t ulHeadIndex = 0, ulTailIndex = 0, ulBeforeTailIndex = 0;
    
    ulHeadIndex = Get_WBCHGB_Head();
    ulBeforeTailIndex = Get_WBCHGB_BeforeTail();
    ulTailIndex = Get_WBCHGB_Tail();
    
    //更新g_ucListReview_DataTab[]下标号0-6，对应的taListView_Data[]下标号（按SN降序的下标号）
    Update_ListReview_DataTable();
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_LIST_REVIEW);
    //清除的内容
    for (i = LIST_REVIEW_ROW_NUM-1; i >=0; i--)
    {
        LISTVIEW_SetItemText(hItem, 0, i, " "); LISTVIEW_SetItemText(hItem, 1, i, " ");
        LISTVIEW_SetItemText(hItem, 2, i, " "); LISTVIEW_SetItemText(hItem, 3, i, " ");
        LISTVIEW_SetItemText(hItem, 4, i, " "); LISTVIEW_SetItemText(hItem, 5, i, " ");
        LISTVIEW_SetItemText(hItem, 6, i, " "); LISTVIEW_SetItemText(hItem, 7, i, " ");
    }
    
    //更新
    for (i = 0; i < LIST_REVIEW_ROW_NUM; i++)
    {
        //判断是否为有效数据
        if(MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]].ulCurDataSN != INVALID_DATA_SN && \
            MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]].eDataStatus != DATA_STATUS_INIT && \
            MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]].eDataStatus != DATA_STATUS_DELETE)
        {     
            //更新新
            //                        列号，行号
            //样本编号
            LISTVIEW_SetItemText(hItem, 0, index, (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]].ucaSampleSN); //SN降序
            //姓名
            LISTVIEW_SetItemText(hItem, 1, index, (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]].ucaName);
            //检测时间
            LISTVIEW_SetItemText(hItem, 2, index, (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]].ucaDateTime);
            //wbc
            memset(buffer, 0, sizeof(buffer));
            Display_Result_Info(buffer, WBCHGB_RST_WBC, &MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]]);
            LISTVIEW_SetItemText(hItem, 3, index, buffer);
            //hgb
            memset(buffer, 0, sizeof(buffer));
            Display_Result_Info(buffer, WBCHGB_RST_HGB, &MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]]);
            LISTVIEW_SetItemText(hItem, 4, index, buffer);
            //Gran%
            memset(buffer, 0, sizeof(buffer));
            Display_Result_Info(buffer, WBCHGB_RST_GranB, &MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]]);
            LISTVIEW_SetItemText(hItem, 5, index, buffer);
            //Mid%
            memset(buffer, 0, sizeof(buffer));
            Display_Result_Info(buffer, WBCHGB_RST_MidB, &MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]]);
            LISTVIEW_SetItemText(hItem, 6, index, buffer);
            //Lym%
            memset(buffer, 0, sizeof(buffer));
            Display_Result_Info(buffer, WBCHGB_RST_LymB, &MachRunPara.taListView_Data[g_ucaListReview_DataTable[i]]);
            LISTVIEW_SetItemText(hItem, 7, index, buffer);
            
            //下一，有效数据
            index++; 
        }
    }   

    //先使能
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_LASTPAGE));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_LASTRECORD));   
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_NEXTPAGE));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_NEXTRECORD)); 
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LISTREVIEW_RESULT));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_EDIT));   
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_DELETE));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_PRINT)); 
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_PATIENT)); 
    if(ulHeadIndex == ulTailIndex) //queue 空
    {     
        g_ucListView_DataIndex = 0;
        //失能上下翻页按键状态 设置
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_LASTPAGE));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_LASTRECORD));   
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_NEXTPAGE));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_NEXTRECORD)); 

        //失能结果详情、编辑、删除、打印、病人信息按键状态
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LISTREVIEW_RESULT));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_EDIT));   
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_DELETE));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_PRINT)); 
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_PATIENT)); 
        
    }else{ 
		if(MachRunPara.taListView_Data[g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM-1]].ulCurDataIndex == ulHeadIndex)  //到头
		{
			//当前页SN最小的数据，为最旧的有效数据
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_NEXTPAGE));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_NEXTRECORD)); 
		}
		//
		if(MachRunPara.taListView_Data[g_ucaListReview_DataTable[0]].ulCurDataIndex == ulBeforeTailIndex) //到尾
		{
			//当前页SN最大的数据 为最新的有效数据
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_LASTPAGE));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LIST_REVIEW_LASTRECORD)); 
		}
    }
    
    Update_ListView_DataIndex(pMsg);
}




//static 
// USER START (Optionally insert additional static code)
// USER END

//退出列表界面，发送消息给后端，更新到好最新
FeedBack_e Send_ListView_Menu_Exit_Msg(WM_MESSAGE *pMsg)
{
    char ucSendBuffer[UI_TO_BACKEND_MSG_BUFFER_LEN] = {0};
//    uint8_t ucIndex = LIST_REVIEW_ROW_NUM;
    
    ListReview_t *pListView = (ListReview_t*)ucSendBuffer;
    pListView->tMsgHead.usCmd        = CMD_LIST_REVIEW_MENU_OUT;
    pListView->tMsgHead.eErrorCode   = ERROR_CODE_SUCCESS; 
    pListView->tMsgHead.usMsgLen     = MSG_HEAD_LEN; 

    //pListView->ucIndex = ListView_Row2DataIndex(ucIndex);
    //
    UI_Put_Msg((uint8_t*)ucSendBuffer);
    //
    return FEED_BACK_SUCCESS;
}




/*
*   列表回顾，发送交互消息
*/
FeedBack_e ListView_Send_Msg(uint32_t ulCmd, WM_MESSAGE *pMsg)
{
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
    extern __IO MachRunPara_s MachRunPara;

    //更新g_ucListView_DataIndex
    if(Update_ListView_DataIndex(pMsg) >= LIST_REVIEW_ROW_NUM) 
    {
        //列表回顾没有，有效数据。不进行操作
        return FEED_BACK_FAIL;
    }
    
    ListReview_t tListView = {0};
    tListView.tMsgHead.usCmd        = ulCmd;
    tListView.tMsgHead.eErrorCode   = ERROR_CODE_SUCCESS; 
    tListView.tMsgHead.usMsgLen     = MSG_HEAD_LEN; 
    //
    //tListView.ulSN                = Get_Data_SN(ulCmd, pMsg);
    tListView.ucIndex               = g_ucListView_DataIndex;
    //tListView.ulSN                = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ulCurDataSN;
    
    //发送消息
    UI_Put_Msg((uint8_t*)&tListView);
    //
    return FEED_BACK_SUCCESS;
}





/*********************************************************************
*
*       _cbDialog
*/
static void ListReview_cbDialog(WM_MESSAGE * pMsg) {
//  WM_HWIN hItem;
  extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
  extern PrinterErrorType_e g_ePrinterErrorType;
    
  int     NCode;
  int     Id;
//  uint8_t ucTempIndex = 0, ucTemp = 0;
//  uint32_t ulSN = INVALID_DATA_SN;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
      ListReview_Msg_Init(pMsg);
      //设置窗口颜色
      WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_PAINT:
  {
      //画背景BMP图  
//      Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
      GUI_RECT Rect;
      WM_GetClientRect(&Rect); 
      GUI_SetColor(GUI_WHITE);
      GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
      
      //
      ListReview_Msg_Paint(pMsg);
      
      //更新g_ucListReview_DataIndex
      //Update_ListReview_DataTable();
  }
  break;
//  case WM_MENU_UPDATE:
//  {
//    ListReview_Msg_Paint(pMsg);
//  }
//  break;
  case WM_DELETE:
  {
//    Send_ListView_Menu_Exit_Msg(pMsg);
  }
  break;

  case WM_PRINTER_NO_PAPER:
  {
      //打印机缺纸
       g_ePrinterErrorType = PRINTER_NO_PAPER;
      //
      GUI_EndDialog(pMsg->hWin, 0);
      g_hActiveWin = Printer_Error_Prompt_PromptDLG();
  }
  break;
  case WM_PRINTER_CONN_ERR:
  {
      //打印机连接异常
      g_ePrinterErrorType = PRINTER_CONN_ERROR;
      //
      GUI_EndDialog(pMsg->hWin, 0);
      g_hActiveWin = Printer_Error_Prompt_PromptDLG();
  }break;
  case WM_MOTOR_ERROR_PROMPT:
  {
      Motor_Error_Prompt(pMsg, CreateListReview_Window);
  }
  break;
  case WM_ANALYSIS_LOAT_DATA_FAIL:
  {
        char buffer[96] = {0};
      CommonDialogPageData_s DialogPageData = {0};
      
    //先清除故障、再执行样本分析
    GUI_EndDialog(pMsg->hWin, 0);
    g_hActiveWin = CreateDialogPage();
      
    //保存对话框内容
    DialogPageData.bmpType = BMP_ALARM;
    DialogPageData.confimButt = HAS_CONFIM_BUTTON;
    DialogPageData.fun = Analysis_Menu;
    sprintf(buffer, "%s!", g_ucaLng_ClearErrorBeforCount[MachInfo.systemSet.eLanguage]);
    strcpy(DialogPageData.str, buffer);

    pMsg->MsgId = WM_USER_DATA;
    pMsg->Data.p = &DialogPageData;
    WM_SendMessage(g_hActiveWin,pMsg);  
  }
  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_LISTREVIEW_RESULT: // Notifications sent by 'ResultInfo_Btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Update_ListView_DataIndex(pMsg);
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = ResultInfo_Menu();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_LISTREVIEW_RefreshNet: // Notifications sent by '刷新网络'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  {
		  extern WM_HWIN CreateListReview_Window(void);
		  extern osMessageQueueId_t CATQueueHandle;
		  extern osMessageQueueId_t CATQueueOtherHandle;
		  extern osEventFlagsId_t GlobalEventCatGroupHandle;
		CATQueueInfoBuf_s CATQueueInfoBuf;
		CommonDialogPageData_s DialogPageData = {0};
		Msg_Head_t BackendMsg = {0};  
		
		//弹出对话框，等待服务端响应
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateDialogPage();
	  
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = CreateListReview_Window;
		strcpy(DialogPageData.str,g_ucaLng_WaitForRefresh[MachInfo.systemSet.eLanguage]);
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &DialogPageData;
		WM_SendMessage(g_hActiveWin,pMsg);
		
		//先清除事件标志
		osEventFlagsClear(GlobalEventCatGroupHandle,GLOBAL_EVENT_CAT_REFRESH_NET);
		
		//先清除网络异常事件标志
		osEventFlagsClear(GlobalEventCatGroupHandle,GLOBAL_EVENT_CAT_CONN_NET_ERR);
		osEventFlagsClear(GlobalEventCatGroupHandle,GLOBAL_EVENT_CAT_CONN_OTHER_NET_ERR);
		
		//往后台发送消息
		BackendMsg.usCmd = CMD_LIST_REVIEW_REFRESH_NET;
		UI_Put_Msg((uint8_t*)&BackendMsg);
		
		//唤醒CAT连接服务端
		CATQueueInfoBuf.msgType = REFRESH_NET_CAT_MSG_TYPE;
		osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
		
		//唤醒CAT连接第三方服务端
		switch(MachInfo.companyInfo.company){
			case COMPANY_YSB:
			{
				osMessageQueuePut(CATQueueOtherHandle,&CATQueueInfoBuf,0,0);
			}break;
			
			default :break;
		}
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
    case ID_BUTTON_LIST_REVIEW_EDIT: // Notifications sent by 'Edit_Btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Update_ListView_DataIndex(pMsg);
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = EditResult_CreateWindow(); //
        
        //ListView_Send_Msg(CMD_LIST_REVIEW_EDIT, pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LIST_REVIEW_DELETE: // Notifications sent by 'Delete_Btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
        // USER START (Optionally insert code for reacting on notification message)
        //获取删除的数据的SN
        Update_ListView_DataIndex(pMsg);
          //更新g_ucListView_DataIndex
        if(Update_ListView_DataIndex(pMsg) >= LIST_REVIEW_ROW_NUM) 
        {
            //列表回顾没有，有效数据。不进行操作
            return;
        }
        
        //删除提示
        GUI_EndDialog(pMsg->hWin, 0);
	    g_hActiveWin = CreateSwitchDialogPage();
        //
        CommonSwitchDialogPageData_s SwitchDialogData = {0};
        SwitchDialogData.switchDialogItem = LISTVIEW_DELETE_DATA;
        SwitchDialogData.u32 = 0;
        SwitchDialogData.dialogData.bmpType = BMP_ALARM;
        SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
        SwitchDialogData.dialogData.fun = CreateListReview_Window;					//保存进入对话框前的界面创建函数
        strcpy(SwitchDialogData.dialogData.str, g_ucaLng_IfDeleteData[MachInfo.systemSet.eLanguage]);
        
        pMsg->MsgId = WM_USER_DATA;
        pMsg->Data.p = &SwitchDialogData;
        WM_SendMessage(g_hActiveWin,pMsg);
        
       }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LIST_REVIEW_PRINT: // Notifications sent by 'Print_Btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //ulSN = Get_Data_SN(CMD_LIST_REVIEW_PRINT, pMsg);
        Update_ListView_DataIndex(pMsg);
        ListView_Send_Msg(CMD_LIST_REVIEW_PRINT, pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LIST_REVIEW_PATIENT: // Notifications sent by 'Patient_Info_Btm'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)    
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Update_ListView_DataIndex(pMsg);
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatePatient_Info_Window();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LIST_REVIEW_LASTPAGE: // Notifications sent by 'LastPage_Btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        
        //ulSN = Get_Data_SN(CMD_LIST_REVIEW_LAST_PAGE, pMsg);
        ListView_Send_Msg(CMD_LIST_REVIEW_LAST_PAGE, pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LIST_REVIEW_LASTRECORD: // Notifications sent by 'LastRecord_Btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        
        //ulSN = Get_Data_SN(CMD_LIST_REVIEW_LAST_RECORD, pMsg);
        ListView_Send_Msg(CMD_LIST_REVIEW_LAST_RECORD, pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LIST_REVIEW_NEXTRECORD: // Notifications sent by 'NextRecord_Btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //ulSN = Get_Data_SN(CMD_LIST_REVIEW_NEXT_RECORD, pMsg);
        ListView_Send_Msg(CMD_LIST_REVIEW_NEXT_RECORD, pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LIST_REVIEW_NEXTPAGE: // Notifications sent by 'NextPage_Btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //ulSN = Get_Data_SN(CMD_LIST_REVIEW_NEXT_PAGE, pMsg);
        ListView_Send_Msg(CMD_LIST_REVIEW_NEXT_PAGE, pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_LIST_REVIEW: // Notifications sent by 'ResultListview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        //
        Update_ListView_DataIndex(pMsg);
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        
        //@todo
      
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateListReview_Window
*/
WM_HWIN CreateListReview_Window(void);
WM_HWIN CreateListReview_Window(void) {
  WM_HWIN hWin;

  WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
  Public_Show_Widget(); //显示公共部分控件
	
	Disable_Algo_Task();
    
  Set_Cur_MenuID(GUI_WINDOW_LIST_REVIEW_ID);
  //列表回顾按键背景高亮
  Public_Reset_Btn_Status(BTN_LISTREVIEW);
  hWin = GUI_CreateDialogBox(ListReview_aDialogCreate, GUI_COUNTOF(ListReview_aDialogCreate), ListReview_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
