/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "WM.h"
#include "FRAMEWIN.h"
#include "BUTTON.h"
#include "LISTVIEW.h"
//#include "WINDOWS.h"
#include "TEXT.h"
#include "HEADER.h"

#include "cx_menu.h"
//#include "Analysis_MenuDLG.h"
#include "Public_menuDLG.h"

// USER START (Optionally insert additional defines)
/*
*
*   列表回顾界面中：结果详情界面
*
*/
// USER END

/*********************************************************************
*
*       Static data  列表回顾中--结果详情
*
**********************************************************************/



#define WBCHGB_LISTVIEW_LEN             330
#define WBCHGB_LISTVIEW_HEAD_LEN        34
#define WBCHGB_LISTVIEW_COLUMN_LEN      100

// color
// error prompt
#define GUI_BTN_ERROR_PROMPT_COLOR  0x004FA5FF


//ID
#define ID_WINDOW_RESULT_INFO          		(GUI_WINDOW_RESULT_INFO_ID + 0x01)
//#define ID_BUTTON_RESULT_INFO_WBCHGB   	(GUI_WINDOW_RESULT_INFO_ID + 0x02)     ////定义在public_WindowDLG.h 中
#define ID_BUTTON_RESULT_INFO_RETURE       	(GUI_WINDOW_RESULT_INFO_ID + 0x04)
#define ID_BUTTON_RESULT_INFO_EDIT          (GUI_WINDOW_RESULT_INFO_ID + 0x05)
#define ID_BUTTON_RESULT_INFO_DELETE        (GUI_WINDOW_RESULT_INFO_ID + 0x06)
#define ID_BUTTON_RESULT_INFO_PRINT         (GUI_WINDOW_RESULT_INFO_ID + 0x07)
#define ID_BUTTON_RESULT_INFO_PAINT_INFO    (GUI_WINDOW_RESULT_INFO_ID + 0x08)
//#define ID_TEXT_RESULT_INFO_WBC_PROMPT	(GUI_WINDOW_RESULT_INFO_ID + 0x09) //这两个定义在public_WindowDLG.h 中
//#define ID_TEXT_RESULT_INFO_HGB_PROMPT    (GUI_WINDOW_RESULT_INFO_ID + 0x0A)
#define ID_TEXT_RESULT_INFO_TEST_INFO       (GUI_WINDOW_RESULT_INFO_ID + 0x0B)
#define ID_TEXT_RESULT_INFO_WBC_HISTOGRAM   (GUI_WINDOW_RESULT_INFO_ID + 0x0C)



 
/*********************************************************************
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO ResultInfo_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "",  ID_WINDOW_RESULT_INFO,              0, 60, 800, 393, 0, 0, 0x0 },
  { BUTTON_CreateIndirect, "",  ID_BUTTON_RESULT_INFO_WBCHGB,       17, 60, 300, WBCHGB_LISTVIEW_LEN, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",  ID_BUTTON_RESULT_INFO_RETURE,       17, 12, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",  ID_BUTTON_RESULT_INFO_EDIT,         345, 12, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",  ID_BUTTON_RESULT_INFO_DELETE,       455, 12, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",  ID_BUTTON_RESULT_INFO_PRINT,        565, 12, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",  ID_BUTTON_RESULT_INFO_PAINT_INFO,   675, 12, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",    ID_TEXT_RESULT_INFO_WBC_PROMPT,     322, 60, 175, 200, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",    ID_TEXT_RESULT_INFO_HGB_PROMPT,     322, 265, 175, 125, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",    ID_TEXT_RESULT_INFO_TEST_INFO,      502, 60, 280, 110, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",    ID_TEXT_RESULT_INFO_WBC_HISTOGRAM,  502, 175, 280, 210, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*
*    ResultInfo  btn callback
*/
static void ResultInfo_Btn_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
                 
            //draw frame
            GUI_SetColor(MachInfo.companyInfo.skin.buttPress); //填充背景颜色
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
            
            //
            GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
            //
            if (ID_BUTTON_RESULT_INFO_RETURE == WM_GetId(pMsg->hWin))
            {  
                //返回
                GUI_DispStringAt(g_ucaLng_Return[MachInfo.systemSet.eLanguage], Rect.x0 + 40, Rect.y0 + 12);
            }
            else if (ID_BUTTON_RESULT_INFO_EDIT == WM_GetId(pMsg->hWin)) {  
                //编辑
                GUI_DispStringAt(g_ucaLng_Edit[MachInfo.systemSet.eLanguage], Rect.x0 + 35, Rect.y0 + 12);
            }
            else if (ID_BUTTON_RESULT_INFO_DELETE == WM_GetId(pMsg->hWin)) {
                //删除
                GUI_DispStringInRect(g_ucaLng_Delete[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_RESULT_INFO_PRINT == WM_GetId(pMsg->hWin)) {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_RESULT_INFO_PAINT_INFO == WM_GetId(pMsg->hWin)) {
                //病人信息
                GUI_DispStringInRect(g_ucaLng_PatientInfo[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
        else {
            //填充颜色
            GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
            GUI_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
            
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard); //画框
            GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 19);
			
            //
            GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
            if (ID_BUTTON_RESULT_INFO_RETURE == WM_GetId(pMsg->hWin))
            {  
                //返回
                GUI_DispStringAt(g_ucaLng_Return[MachInfo.systemSet.eLanguage], Rect.x0 + 40, Rect.y0 + 12);
            }
            else if (ID_BUTTON_RESULT_INFO_EDIT == WM_GetId(pMsg->hWin)) {  
                //编辑
                GUI_DispStringAt(g_ucaLng_Edit[MachInfo.systemSet.eLanguage], Rect.x0 + 35, Rect.y0 + 12);
            }
            else if (ID_BUTTON_RESULT_INFO_DELETE == WM_GetId(pMsg->hWin)) {
                //删除
                GUI_DispStringInRect(g_ucaLng_Delete[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_RESULT_INFO_PRINT == WM_GetId(pMsg->hWin)) {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_RESULT_INFO_PAINT_INFO == WM_GetId(pMsg->hWin)) {
                //病人信息
                GUI_DispStringInRect(g_ucaLng_PatientInfo[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
*   列表回顾，发送交互消息
*/
FeedBack_e ResultInfo_SendMsg(uint32_t ulCmd, WM_MESSAGE *pMsg)
{
    char ucSendBuffer[UI_TO_BACKEND_MSG_BUFFER_LEN] = {0};
    
    ListReview_t *pListView = (ListReview_t*)ucSendBuffer;
    pListView->tMsgHead.usCmd        = ulCmd;
    pListView->tMsgHead.eErrorCode   = ERROR_CODE_SUCCESS; 
    pListView->tMsgHead.usMsgLen     = MSG_HEAD_LEN; 
    //
    pListView->ucIndex               = g_ucListView_DataIndex;
    
    //发送消息
    UI_Put_Msg((uint8_t*)ucSendBuffer);
    //
    return FEED_BACK_SUCCESS;
     
//    return ListView_Send_Msg(ulCmd, pMsg);
}





/*
* 初始化回调
*/
static void ResultInfo_Msg_Init(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
	extern  MachInfo_s	MachInfo;
    WM_HWIN hItem;

    //WBC HGB Result
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RESULT_INFO_WBCHGB);
    WM_SetCallback(hItem, WBCHGB_Result_Btn_Callback);
    WM_InvalidateWindow(hItem);

    //
    // Initialization of 'wbc prompt '
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO_WBC_PROMPT);
    WM_SetCallback(hItem, WBCHGB_ErrorPrompt_Text_Callback);
    WM_InvalidateWindow(hItem);

    // Initialization of 'HGB prompt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO_HGB_PROMPT);
    WM_SetCallback(hItem, WBCHGB_ErrorPrompt_Text_Callback);
    WM_InvalidateWindow(hItem);
    
    // test info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO_TEST_INFO);
    WM_SetCallback(hItem, TestInfo_TEXT_Callback);
    WM_InvalidateWindow(hItem);

    // wbc histogram info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO_WBC_HISTOGRAM);
    WM_SetCallback(hItem, WBC_Histogram_TEXT_Callback);
    WM_InvalidateWindow(hItem);

    // return
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RESULT_INFO_RETURE);  
    WM_SetCallback(hItem, ResultInfo_Btn_Callback);
    WM_InvalidateWindow(hItem);
    
    // edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RESULT_INFO_EDIT);    
    WM_SetCallback(hItem, ResultInfo_Btn_Callback);
    //普通账号，没有编辑权限
    if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority)
    {
        WM_HideWindow(hItem);
    }
    
    // delete
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RESULT_INFO_DELETE);
    WM_SetCallback(hItem, ResultInfo_Btn_Callback);
    //普通账号，没有删除权限
    if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority)
    {
        WM_HideWindow(hItem);
    }
    
    // print btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RESULT_INFO_PRINT);
    //WM_SetCallback(hItem, Print_Btn_Callback);
    WM_SetCallback(hItem, ResultInfo_Btn_Callback);
    WM_InvalidateWindow(hItem);

    // patient info btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RESULT_INFO_PAINT_INFO);
    //WM_SetCallback(hItem, TesterInfo_Btn_Callback);
    WM_SetCallback(hItem, ResultInfo_Btn_Callback);
    WM_InvalidateWindow(hItem);

}






/*
*   界面、数据更新
*/
static void ResultInfo_Msg_Updata(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    WM_HWIN hItem;
//    int i = 0;
//    char ucBuffer[10] = { 0 };

    //wbc hgb Result
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RESULT_INFO_WBCHGB);
    WM_InvalidateWindow(hItem);
    //WM_DisableWindow(hItem);

    // wbc prompt listview
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO_WBC_PROMPT);
    WM_InvalidateWindow(hItem);

    // HGB prompt listview
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO_HGB_PROMPT);
    WM_InvalidateWindow(hItem);

    // test info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO_TEST_INFO);
    //WM_SetCallback(hItem, TestInfo_TEXT_Callback);
    WM_InvalidateWindow(hItem);

    // wbc histogram info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_RESULT_INFO_WBC_HISTOGRAM);
    //WM_SetCallback(hItem, WBC_Histogram_TEXT_Callback);
    WM_InvalidateWindow(hItem);
}




/*********************************************************************
*
*       _cbDialog
*/
static void ResultInfo_cbDialog(WM_MESSAGE * pMsg) {
    
  extern PrinterErrorType_e g_ePrinterErrorType;
    
//  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'wbc hgb reslut_Listview'
    //
    ResultInfo_Msg_Init(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    // USER END
    break;
  
  case WM_PAINT:
  {
      //Show_SDRAM_BMP(SDRAM_BMP_Frame, 0, 0);
      GUI_RECT Rect;
      WM_GetClientRect(&Rect); 
      GUI_SetColor(GUI_WHITE);
      GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
      
      ResultInfo_Msg_Updata(pMsg);
  }
  break;
  case WM_PRINTER_NO_PAPER:
  {
      //打印机缺纸
       g_ePrinterErrorType = PRINTER_NO_PAPER;
      //
      GUI_EndDialog(pMsg->hWin, 0);
      g_hActiveWin = Printer_Error_Prompt_PromptDLG();
  }
  break;
  case WM_PRINTER_CONN_ERR:
  {
      //打印机连接异常
      g_ePrinterErrorType = PRINTER_CONN_ERROR;
      //
      GUI_EndDialog(pMsg->hWin, 0);
      g_hActiveWin = Printer_Error_Prompt_PromptDLG();
  }
  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
   
//    case ID_BUTTON_RESULT_INFO_WBCHGB: // Notifications sent by 'wbc hgb reslut_Listview'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_SEL_CHANGED: // 
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      // USER START (Optionally insert additional code for further notification handling)
//      // USER END
//      }
//      break;
    case ID_BUTTON_RESULT_INFO_RETURE: // Notifications sent by 'return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        
		// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateListReview_Window();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_RESULT_INFO_EDIT: // Notifications sent by 'edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
      
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = EditResult_CreateWindow(); //
        //
        //ResultInfo_SendMsg(CMD_LIST_REVIEW_EDIT, pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_RESULT_INFO_DELETE: // Notifications sent by 'delete'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      {
            //ResultInfo_SendMsg(CMD_LIST_REVIEW_DELETE, pMsg);
        
            //删除提示
            GUI_EndDialog(pMsg->hWin, 0);
            g_hActiveWin = CreateSwitchDialogPage();
            //
            CommonSwitchDialogPageData_s SwitchDialogData = {0};
            SwitchDialogData.switchDialogItem = LISTVIEW_DELETE_DATA;
            SwitchDialogData.u32 = 0;
            SwitchDialogData.dialogData.bmpType = BMP_ALARM;
            SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
            SwitchDialogData.dialogData.fun = CreateListReview_Window;					//保存进入对话框前的界面创建函数
            strncpy(SwitchDialogData.dialogData.str, g_ucaLng_IfDeleteData[MachInfo.systemSet.eLanguage], sizeof(g_ucaLng_IfDeleteData[MachInfo.systemSet.eLanguage]));
            //strcpy(SwitchDialogData.dialogData.str, g_ucaLng_IfDeleteData[MachInfo.systemSet.eLanguage]);
            
            pMsg->MsgId = WM_USER_DATA;
            pMsg->Data.p = &SwitchDialogData;
            WM_SendMessage(g_hActiveWin,pMsg);
      }
      break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
     case ID_BUTTON_RESULT_INFO_PRINT: // Notifications sent by 'print'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
         ResultInfo_SendMsg(CMD_LIST_REVIEW_PRINT, pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_RESULT_INFO_PAINT_INFO: // Notifications sent by 'patient info'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatePatient_Info_Window();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       ResultInfo_Menu
*/
WM_HWIN ResultInfo_Menu(void);
WM_HWIN ResultInfo_Menu(void) {
    
  WM_HWIN hWin;
    
  WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
  Public_Show_Widget();
	
	Disable_Algo_Task();

  //记录当前界面ID
  Set_Cur_MenuID(GUI_WINDOW_RESULT_INFO_ID);
  hWin = GUI_CreateDialogBox(ResultInfo_aDialogCreate, GUI_COUNTOF(ResultInfo_aDialogCreate), ResultInfo_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
