/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

/*
*
*   弹框提示，是否确认关机（在界面菜单，点击关机后）
*
*/

// USER END
#include "DIALOG.h"
#include "WM.h"
#include "GUI.h"
#include "LISTBOX.h"


#include "Public_menuDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



//ID
#define ID_WINDOW_ENSURE_POWEROFF      	(GUI_WINDOW_ENSURE_POWEROFF_ID + 0x00)
#define ID_ENSURE_POWEROFF_TEXT         (ID_WINDOW_ENSURE_POWEROFF + 0x01)
#define ID_ENSURE_POWEROFF_BUTTON_YES   (ID_WINDOW_ENSURE_POWEROFF + 0x02)
#define ID_ENSURE_POWEROFF_BUTTON_NO    (ID_WINDOW_ENSURE_POWEROFF + 0x03)






// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/



// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/

static const GUI_WIDGET_CREATE_INFO Ensure_PowerOff_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "", 	ID_WINDOW_ENSURE_POWEROFF,    		180, 100, 440, 225, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "",  ID_ENSURE_POWEROFF_TEXT,     	80, 80, 280, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",  ID_ENSURE_POWEROFF_BUTTON_NO,   0, 185, 220, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",  ID_ENSURE_POWEROFF_BUTTON_YES,  220, 185, 220, 40, 0, 0x0, 0 },
  
};





/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


/*
*  Ensure_PowerOff  btn callback
*/
static void Ensure_PowerOff_Btn_Callback(WM_MESSAGE* pMsg)
{
    const unsigned char RoundRadius = 0; //显示区域圆角半径
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            //draw frame
            GUI_SetColor(GUI_BTN_PRESS_COLOR);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            GUI_SetColor(GUI_BTN_FRAME_COLOR);
            //GUI_AA_DrawRoundedRect(Rect.x0 + 1, Rect.y0 + 1, Rect.x1 + 1, Rect.y1 + 1, RoundRadius);
            GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);;

            // display char
            GUI_SetColor(GUI_BTN_PRESS_CHAR_COLOR);
            GUI_SetBkColor(GUI_BTN_PRESS_COLOR);
            if(ID_ENSURE_POWEROFF_BUTTON_YES == WM_GetId(pMsg->hWin))
            {
                //是
                GUI_DispStringInRect(g_ucaLng_Yes[g_tUI_Info.tSystemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(ID_ENSURE_POWEROFF_BUTTON_YES == WM_GetId(pMsg->hWin)){
                //否
                GUI_DispStringInRect(g_ucaLng_No[g_tUI_Info.tSystemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }                
        }
        else {
            // draw frame
            GUI_SetColor(GUI_BTN_RELEASE_COLOR);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            GUI_SetColor(GUI_BTN_FRAME_COLOR);
            //GUI_AA_DrawRoundedRect(Rect.x0 + 1, Rect.y0 + 1, Rect.x1, Rect.y1, RoundRadius);
            GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);;

            // display char
            GUI_SetColor(GUI_BTN_RELEASE_CHAR_COLOR);
            GUI_SetBkColor(GUI_BTN_RELEASE_COLOR);
            if(ID_ENSURE_POWEROFF_BUTTON_YES == WM_GetId(pMsg->hWin))
            {
                //是
                GUI_DispStringInRect(g_ucaLng_Yes[g_tUI_Info.tSystemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(ID_ENSURE_POWEROFF_BUTTON_NO == WM_GetId(pMsg->hWin)){
                //否
                GUI_DispStringInRect(g_ucaLng_No[g_tUI_Info.tSystemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }  
  
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}






/*********************************************************************
*
*       _cbDialog
*/
static void Ensure_PowerOff_cbDialog(WM_MESSAGE* pMsg) {
    
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    char buffer[100] = {0};


    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Remark_Multiedit'
        //...
		//btn NO
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ENSURE_POWEROFF_BUTTON_NO);
		WM_SetCallback(hItem, Ensure_PowerOff_Btn_Callback);
        WM_InvalidateWindow(hItem);
		
		//btn Yes
		hItem = WM_GetDialogItem(pMsg->hWin, ID_ENSURE_POWEROFF_BUTTON_YES);
		WM_SetCallback(hItem, Ensure_PowerOff_Btn_Callback);
        WM_InvalidateWindow(hItem);
		
        //是否重新测试
        hItem = WM_GetDialogItem(pMsg->hWin, ID_ENSURE_POWEROFF_TEXT);
        TEXT_SetTextAlign(hItem, GUI_TA_CENTER|GUI_TA_HCENTER);
        TEXT_SetFont(hItem, &HZ_SONGTI_24); 
        sprintf(buffer, "%s?", g_ucaLng_Ensure_PowerOff[g_tUI_Info.tSystemSet.eLanguage]);
        TEXT_SetText(hItem, buffer);

        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_ENSURE_POWEROFF_BUTTON_NO: // Notifications sent by 'No BUTTON '
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {
					GUI_EndDialog(pMsg->hWin, 0);
					g_hActiveWin = Analysis_Menu(); //Analysis_Menu();  Createmenu_Window();
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
			case ID_ENSURE_POWEROFF_BUTTON_YES: // Notifications sent by 'Yes BUTTON '
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {                
                    //切换到关机画面
                    WM_SetCallback(WM_HBKWIN, None_cbBkWin);
					GUI_EndDialog(pMsg->hWin, 0);
					g_hActiveWin = PowerOff_CreateWindow();                   
                    
					// USER START (Optionally insert code for reacting on notification message)
					//发送关机消息给后端，执行关机操作
					Msg_Head_t tMsgHead = {0};
					//构造关机消息
					tMsgHead.usCmd      = CMD_POWEROFF_EXEC;
					tMsgHead.eErrorCode = ERROR_CODE_SUCCESS;
					tMsgHead.usMsgLen   = MSG_HEAD_LEN;
					//发送消息给后端
					UI_Put_Msg((uint8_t*)&tMsgHead);
					GUI_Delay(10);
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        }
        break;
        // USER START (Optionally insert additional message handling)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       ReCount_Prompt
*/

//背景窗口 回调函数
void Ensure_PowerOff_cbBkWin(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
//        case WM_INIT_DIALOG:
//        {
//            GUI_SetAlpha(NEXT_SMAPLE_ALPHA);
//            GUI_SetColor(NEXT_SMAPLE_ALPHA_COLOR);
//            GUI_FillRect(0, 0, 800, 480);
//            GUI_SetAlpha(0);
//        }
        case WM_PAINT:
        {
            GUI_SetAlpha(30);
            GUI_SetColor(0x00525a4e);
            GUI_FillRect(0, 0, 800, 480);
            GUI_SetAlpha(0);
        }
        break;
        default:
        {
            WM_DefaultProc(pMsg);
        }
        break;
    }
}



WM_HWIN Ensure_PowerOff_Window(void);
WM_HWIN Ensure_PowerOff_Window(void) {
    WM_HWIN hWin;
    
    //GUI_Clear();
    Public_Hide_Widget(); //隐藏公共部分控件,
    WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin);
    
    hWin = GUI_CreateDialogBox(Ensure_PowerOff_aDialogCreate, GUI_COUNTOF(Ensure_PowerOff_aDialogCreate), Ensure_PowerOff_cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
