/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "WM.h"
#include "FRAMEWIN.h"
#include "BUTTON.h"
#include "LISTVIEW.h"
//#include "WINDOWS.h"
#include "TEXT.h"
#include "HEADER.h"

#include "cx_menu.h"
//#include "Analysis_MenuDLG.h"
#include "Public_menuDLG.h"
#include "Common.h"

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
//缓存WBCHGB测试错误码
__IO uint32_t g_ulErrorCode = ERROR_CODE_SUCCESS;

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define WBCHGB_LISTVIEW_LEN             330
#define WBCHGB_LISTVIEW_HEAD_LEN        34
#define WBCHGB_LISTVIEW_COLUMN_LEN      100


// error prompt
//#define GUI_BTN_ERROR_PROMPT_COLOR  0x004FA5FF
// list view
#define GUI_WBCHGB_RESULT_COLOR_BLUE    0x00f7f2e8
#define GUI_WBCHGB_RESULT_FRAME_COLOR   0x00cbcbcb





//ID
#define ID_WINDOW_ANALYSIS          (GUI_WINDOW_ANALYSIS_ID + 0x00)
#define ID_BUTTION_WBCHGB_RESULT    (GUI_WINDOW_ANALYSIS_ID + 0x06)
#define ID_BUTTON_LAST_RECORD       (GUI_WINDOW_ANALYSIS_ID + 0x07)
#define ID_BUTTON_NEXT_RECORD       (GUI_WINDOW_ANALYSIS_ID + 0x08)
#define ID_BUTTON_NEXT_SAMPLE       (GUI_WINDOW_ANALYSIS_ID + 0x09)
#define ID_BUTTON_PRINT             (GUI_WINDOW_ANALYSIS_ID + 0x0A)
#define ID_BUTTON_PATIENT_INFO      (GUI_WINDOW_ANALYSIS_ID + 0x0B)
#define ID_TEXT_WBC_PROMPT          (GUI_WINDOW_ANALYSIS_ID + 0x10)
#define ID_TEXT_HGB_PROMPT          (GUI_WINDOW_ANALYSIS_ID + 0x11)
#define ID_TEXT_TEST_INFO           (GUI_WINDOW_ANALYSIS_ID + 0x13)
#define ID_TEXT_WBC_HISTOGRAM       (GUI_WINDOW_ANALYSIS_ID + 0x14)


 
/*********************************************************************
*
*       _aDialogCreate
*/
//  { WINDOW_CreateIndirect, "",     	ID_WINDOW_ANALYSIS,             10, 60, 780, 400, 0, 0, 0x0 },
static const GUI_WIDGET_CREATE_INFO Analysis_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "",      ID_WINDOW_ANALYSIS,             0, 60, 800, 393, 0, 0, 0x0 },       /*背景图目前高度：392，需改为395  */
  { BUTTON_CreateIndirect, "", 	    ID_BUTTION_WBCHGB_RESULT,       17, 60, 300, 330, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",    	ID_BUTTON_LAST_RECORD,          17, 12, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",    	ID_BUTTON_NEXT_RECORD,          151, 12, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",      ID_BUTTON_NEXT_SAMPLE,          287, 12, 180, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",      ID_BUTTON_PRINT,                522, 12, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",    	ID_BUTTON_PATIENT_INFO,         657, 12, 120, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_WBC_PROMPT,             322, 60, 175, 200, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_HGB_PROMPT,             322, 265, 175, 125, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_TEST_INFO,              502, 60, 280, 110, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_WBC_HISTOGRAM,          502, 175, 280, 215, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "0",                   ID_TEXT_SCALE_0,        520, 425, 25, 15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "100",                 ID_TEXT_SCALE_100,      570, 425, 25, 15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "200",                 ID_TEXT_SCALE_200,      620, 425, 25, 15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "300",                 ID_TEXT_SCALE_300,      670, 425, 25, 15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "FL",                  ID_TEXT_SCALE_FL,       720, 425, 25, 15, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*
    test info callback
*/
void WBCHGB_ErrorPrompt_Text_Callback(WM_MESSAGE* pMsg)
{
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
	const unsigned char RoundRadius  = 5;  //显示区域圆角半径
	const unsigned char HeaderLen	 = 34; //显示头高度
    const unsigned char Leght	     = 175; //宽度
    
	GUI_RECT TempRect = {0};
	
	switch (pMsg->MsgId)
    {
        case WM_PAINT:
        {
            GUI_RECT Rect;
            GUI_GetClientRect(&Rect);
            //set hear background
            GUI_SetColor(MachInfo.companyInfo.skin.title);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x0+Leght, Rect.y0+RoundRadius+HeaderLen, RoundRadius);
			//set tail background
            GUI_SetColor(GUI_WHITE);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y1 - HeaderLen, Rect.x1, Rect.y1, RoundRadius);
			
            //set body and tail(expect RoundRadius)background
			GUI_SetColor(GUI_WHITE);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0+HeaderLen, Rect.x1, Rect.y1-RoundRadius, 0);
			
			//draw frame
            GUI_SetColor(GUI_TEXT_FRAME_COLOR);
            GUI_DrawHLine(Rect.y0+HeaderLen, Rect.x0, Rect.x1);
            GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            
            //char display
            TempRect.x0 = Rect.x0; TempRect.y0 = Rect.y0; //头显示区域
            TempRect.x1 = Rect.x1; TempRect.y1 = HeaderLen;
            GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.title); 
            //
			if(ID_TEXT_WBC_PROMPT == WM_GetId(pMsg->hWin) || ID_TEXT_RESULT_INFO_WBC_PROMPT == WM_GetId(pMsg->hWin))  //样本分析、列表回顾-结果详情
			{ 
                //显示头内容
				GUI_DispStringInRect(g_ucaLng_WBCErrorPrompt[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
				//WBC异常信息显示区域及内容
                TempRect.x0 = Rect.x0; TempRect.y0 = Rect.y0 + HeaderLen + RoundRadius;
                TempRect.x1 = Rect.x1; TempRect.y1 = Rect.y1;
                GUI_SetColor(GUI_BLACK);
                GUI_SetBkColor(GUI_WHITE);
                /***** 告警信息内容 *****/
                if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
                {
                    //样本分析界面的回调
                    MachRunPara.tWBCHGB_TestInfo.ucaWBC_ErrorPrompt[WBC_PROMPT_LEN-1] = 0;
                    GUI_DispStringInRect((char*)MachRunPara.tWBCHGB_TestInfo.ucaWBC_ErrorPrompt, &TempRect, GUI_TA_HCENTER | GUI_TA_TOP);
                }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                    //列表回顾相关界面的回调
                    MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaWBC_ErrorPrompt[WBC_PROMPT_LEN-1] = 0;
                    GUI_DispStringInRect((char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaWBC_ErrorPrompt, &TempRect, GUI_TA_HCENTER | GUI_TA_TOP);
                }
                
			}else if(ID_TEXT_HGB_PROMPT == WM_GetId(pMsg->hWin) || ID_TEXT_RESULT_INFO_HGB_PROMPT == WM_GetId(pMsg->hWin)){ //样本分析、列表回顾-结果详情
				
                //显示头内容
				GUI_DispStringInRect(g_ucaLng_HGBErrorPrompt[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
              	//HGB异常信息显示区域及内容
                TempRect.x0 = Rect.x0; TempRect.y0 = Rect.y0 + HeaderLen + RoundRadius;
                TempRect.x1 = Rect.x1; TempRect.y1 = Rect.y1;
                GUI_SetColor(GUI_BLACK);
                GUI_SetBkColor(GUI_WHITE);
                
                 /***** 告警信息内容 *****/
                if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
                {
                    //样本分析界面的回调
                    MachRunPara.tWBCHGB_TestInfo.ucaHGB_ErrorPrompt[HGB_PROMPT_LEN-1] = 0;
                    GUI_DispStringInRect((char*)MachRunPara.tWBCHGB_TestInfo.ucaHGB_ErrorPrompt, &TempRect, GUI_TA_HCENTER | GUI_TA_TOP);    
                }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                    //列表回顾相关界面的回调
                    MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaHGB_ErrorPrompt[HGB_PROMPT_LEN-1] = 0;
                    GUI_DispStringInRect((char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaHGB_ErrorPrompt, &TempRect, GUI_TA_HCENTER | GUI_TA_TOP);    
                } 
			}    
        }
        break;
        default:
            TEXT_Callback(pMsg);
        break;
    }
}


/*
    tester info callback
*/
void TestInfo_TEXT_Callback(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
//    const unsigned char SpareLineLen = 8; //分割线宽度
    const unsigned char RoundRadius  = 5; //显示区域圆角半径
    char buffer[128] = { 0 };
    char Agebuffer[10] = { 0 };
    AgeUnit_e eAgeUnit = AGE_UNIT_YEAR;
//    unsigned char i = 0;
    
    /*
    char testinfo[4][35] = { 
		{"样本编号: CBC-0001"},
        {"模式: WBC+HGB"},
        {"姓名: test"},
        {"检验时间: 2020/11/02 14:15"} };
    */

    /*char testinfo[4][35] = {
        {"姓名: %s"},
        {"年龄: %d       性别: %s"},
        {"样本编号: %s"},
        {"检验时间: %s"} };
    */
    //char testinfo[120] = {"样本编号: CBC-0001模式: WBC+HGB姓名: test检验时间: 2020/11/02 14:15"};

    switch (pMsg->MsgId)
    {
        case WM_PAINT:
        {
            GUI_RECT Rect;
            GUI_GetClientRect(&Rect);
            //background
            GUI_SetColor(GUI_WHITE);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            //frame board
            GUI_SetColor(GUI_TEXT_FRAME_COLOR);
            GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            //spare line
            /*
            GUI_SetColor(GUI_SPARE_LINE_COLOR_YELLOW);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, SpareLineLen, Rect.y1, RoundRadius);
            GUI_FillRect(RoundRadius, Rect.y0, SpareLineLen, Rect.y1);
            */
            //for (i = RoundRadius + 1; i < SpareLineLen; i++)
            //{
               // GUI_DrawVLine(Rect.x0 + i, Rect.y0, Rect.y1);
            //}
            //show msg
            GUI_SetColor(GUI_BLACK);
            GUI_SetBkColor(GUI_WHITE);
            //for (i = 0; i < 4; i++) //4行信息
            //{
                //GUI_DispStringAt(&testinfo[i][0], Rect.x0 + 20, Rect.y0 + 10 + i * 25);
                //Rect.x0 = Rect.x0 + SpareLineLen + 10;
                //GUI_DispStringInRect(testinfo, &Rect, GUI_TA_LEFT | GUI_TA_VCENTER);
            //}
            /***** 姓名 *****/
            memset(buffer, 0, sizeof(buffer));
            if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
            {
                //样本分析界面的回调
                MachRunPara.tWBCHGB_TestInfo.ucaName[PATIENT_NAME_LEN-1] = 0;
                sprintf(buffer, "%s: %s", g_ucaLng_Name[MachInfo.systemSet.eLanguage], (char*)MachRunPara.tWBCHGB_TestInfo.ucaName);  
            }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                //列表回顾相关界面的回调
                MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaName[PATIENT_NAME_LEN-1] = 0;
                sprintf(buffer, "%s: %s", g_ucaLng_Name[MachInfo.systemSet.eLanguage], (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaName);  
            }           
            GUI_DispStringAt(buffer, Rect.x0 + 20, Rect.y0 + 10);

            /*** 年龄单位 ***/
            if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID){
                eAgeUnit = MachRunPara.tWBCHGB_TestInfo.eAgeUnit;
            }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                eAgeUnit = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eAgeUnit;
            }
            switch(eAgeUnit)
            {
                case AGE_UNIT_YEAR:
                    sprintf(Agebuffer, "%s", g_ucaLng_Year[MachInfo.systemSet.eLanguage]);
                break;
                case AGE_UNIT_MONTH:
                    sprintf(Agebuffer, "%s", g_ucaLng_Month[MachInfo.systemSet.eLanguage]);
                break;
                case AGE_UNIT_WEEK:
                    sprintf(Agebuffer, "%s", g_ucaLng_Week[MachInfo.systemSet.eLanguage]);
                break;
                case AGE_UNIT_DAY:
                    sprintf(Agebuffer, "%s", g_ucaLng_Day[MachInfo.systemSet.eLanguage]);
                break;
                default:
                    sprintf(Agebuffer, "%s", g_ucaLng_Year[MachInfo.systemSet.eLanguage]);
                break;
            }
            
            /***** 年龄 性别 *****/
            memset(buffer, 0, sizeof(buffer));
            
            if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
            {               
                //样本分析界面的回调
                if (SEX_TYPE_MALE == MachRunPara.tWBCHGB_TestInfo.eSex && 0 == MachRunPara.tWBCHGB_TestInfo.ucAge) //男 0
                {
                    sprintf(buffer, "%s:           %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], (char*)g_ucaLng_SexMale[MachInfo.systemSet.eLanguage]);  
                }else if (SEX_TYPE_MALE == MachRunPara.tWBCHGB_TestInfo.eSex && 0 != MachRunPara.tWBCHGB_TestInfo.ucAge){ //男 N
                    sprintf(buffer, "%s: %d %s     %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], MachRunPara.tWBCHGB_TestInfo.ucAge, Agebuffer, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], (char*)g_ucaLng_SexMale[MachInfo.systemSet.eLanguage]);
                }else if(SEX_TYPE_FEMALE == MachRunPara.tWBCHGB_TestInfo.eSex && 0 == MachRunPara.tWBCHGB_TestInfo.ucAge){ //女 0
                    sprintf(buffer, "%s:           %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], (char*)g_ucaLng_SexFemale[MachInfo.systemSet.eLanguage]);
                }else if(SEX_TYPE_FEMALE == MachRunPara.tWBCHGB_TestInfo.eSex && 0 != MachRunPara.tWBCHGB_TestInfo.ucAge){ //女 N
                    sprintf(buffer, "%s: %d %s     %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], MachRunPara.tWBCHGB_TestInfo.ucAge, Agebuffer, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], (char*)g_ucaLng_SexFemale[MachInfo.systemSet.eLanguage]);
                }else if(SEX_TYPE_NONE == MachRunPara.tWBCHGB_TestInfo.eSex && 0 == MachRunPara.tWBCHGB_TestInfo.ucAge){ //空 0
                    sprintf(buffer, "%s:           %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], " ");
                }else if(SEX_TYPE_NONE == MachRunPara.tWBCHGB_TestInfo.eSex && 0 != MachRunPara.tWBCHGB_TestInfo.ucAge){ //空 N
                    sprintf(buffer, "%s: %d %s     %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], MachRunPara.tWBCHGB_TestInfo.ucAge, Agebuffer, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], " ");
                }
            }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                
                //列表回顾相关界面的回调
                if (SEX_TYPE_MALE == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eSex && 0 == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge) //男 0
                {
                    sprintf(buffer, "%s:           %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], (char*)g_ucaLng_SexMale[MachInfo.systemSet.eLanguage]);     
                }else if (SEX_TYPE_MALE == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eSex && 0 != MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge){ //男 N
                    sprintf(buffer, "%s: %d %s     %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge, Agebuffer, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], (char*)g_ucaLng_SexMale[MachInfo.systemSet.eLanguage]);  
                }else if (SEX_TYPE_FEMALE == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eSex && 0 == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge){ //女 0
                    sprintf(buffer, "%s:           %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], (char*)g_ucaLng_SexFemale[MachInfo.systemSet.eLanguage]);  
                }else if (SEX_TYPE_FEMALE == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eSex && 0 != MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge){ //女 N
                    sprintf(buffer, "%s: %d %s     %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge, Agebuffer, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], (char*)g_ucaLng_SexFemale[MachInfo.systemSet.eLanguage]);  
                }else if (SEX_TYPE_NONE == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eSex && 0 == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge){ //空 0
                    sprintf(buffer, "%s:           %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], " ");  
                }else if (SEX_TYPE_NONE == MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eSex && 0 != MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge){ //空 N
                    sprintf(buffer, "%s: %d %s     %s: %s", g_ucaLng_Age[MachInfo.systemSet.eLanguage], MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge, Agebuffer, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], " ");  
                }
            } 
            GUI_DispStringAt(buffer, Rect.x0 + 20, Rect.y0 + 10 + 1*25);

            
            /***** 样本编号 *****/
            memset(buffer, 0, sizeof(buffer));
            
            if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
            {
                //样本分析界面的回调
                MachRunPara.tWBCHGB_TestInfo.ucaSampleSN[SAMPLE_SN_LEN-1] = 0;
                sprintf(buffer, "%s: %s", g_ucaLng_SampleNum[MachInfo.systemSet.eLanguage], (char*)&MachRunPara.tWBCHGB_TestInfo.ucaSampleSN);
            }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                //列表回顾相关界面的回调
                MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaSampleSN[SAMPLE_SN_LEN-1] = 0;
                sprintf(buffer, "%s: %s", g_ucaLng_SampleNum[MachInfo.systemSet.eLanguage], (char*)&MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaSampleSN);
            } 
            GUI_DispStringAt(buffer, Rect.x0 + 20, Rect.y0 + 10 + 2 * 25);

            /***** 检测时间 *****/
            memset(buffer, 0, sizeof(buffer));
            if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
            {
                //样本分析界面的回调
                MachRunPara.tWBCHGB_TestInfo.ucaDateTime[DATE_TIME_LEN-1] = 0;
                sprintf(buffer, "%s: %s", g_ucaLng_CheckTime[MachInfo.systemSet.eLanguage], (char*)&MachRunPara.tWBCHGB_TestInfo.ucaDateTime);
            }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                //列表回顾相关界面的回调
                MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaDateTime[DATE_TIME_LEN-1] = 0;
                sprintf(buffer, "%s: %s", g_ucaLng_CheckTime[MachInfo.systemSet.eLanguage], (char*)&MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaDateTime);
                
            } 
            GUI_DispStringAt(buffer, Rect.x0 + 20, Rect.y0 + 10 + 3 * 25);
        }
        break;
        default:
            TEXT_Callback(pMsg);
        break;
    }
}



/*
*    wbc histogram callback ，直方图显示
*/
#define SCALE_CHAR_NUM      5
void WBC_Histogram_TEXT_Callback(WM_MESSAGE* pMsg)
{
	extern  MachInfo_s	MachInfo;
    extern __IO MachRunPara_s	MachRunPara;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
    int MaxPos_x = 0, MaxPos_y = 180;
//    const unsigned char SpareLineLen = 8; //分割线宽度
    const unsigned char RoundRadius = 5; //显示区域圆角半径
    const short axisX = 20, axisY = 180;
    unsigned short i = 0;
    char buffer[10] = {0};
    GUI_POINT Point[GRAPH_DATA_LEN + 1] = {0};
    char FL_Scale[SCALE_CHAR_NUM][4] = {
        {"0"},
        {"100"},
        {"200"},
        {"300"},
        {"FL"},
        /*{"FL"}*/ };

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        GUI_GetClientRect(&Rect);
        
        /* draw back */
        GUI_SetColor(GUI_WHITE);
        GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
        GUI_SetColor(GUI_TEXT_FRAME_COLOR);
        GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
        
        /* show mode */
        GUI_SetColor(GUI_BLACK);
        GUI_FillRoundedRect(Rect.x0 + 15, Rect.y0 + 10, 50, 30, 3);
        GUI_SetBkColor(GUI_BLACK);
        GUI_SetColor(GUI_WHITE);
        GUI_DispStringAt("WBC", Rect.x0 + 22, Rect.y0 + 12);
        //draw x y alxis
        GUI_SetColor(GUI_BLACK);
        GUI_DrawVLine(axisX, 40, axisY);  // y
        GUI_DrawHLine(axisY, axisX, 276);    // x
        
        /* draw dot line, 135 hight of histogram, 20:为相对原点的x轴偏移 */
        if(MachRunPara.tWBCHGB_TestInfo.fLines[0] != 0 && MachRunPara.tWBCHGB_TestInfo.fLines[1] != 0 && MachRunPara.tWBCHGB_TestInfo.fLines[2] !=0)
        {
            GUI_SetColor(GUI_GRAY);
            for (i = 0; i < 135; i++)
            {
                if ((i / 5) % 2 == 0)
                {
                    if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
                    {
                        //样本分析界面的回调
                        GUI_DrawPoint(axisX + MachRunPara.tWBCHGB_TestInfo.fLines[0], axisY - i); 
                        GUI_DrawPoint(axisX + MachRunPara.tWBCHGB_TestInfo.fLines[1], axisY - i);
                        GUI_DrawPoint(axisX + MachRunPara.tWBCHGB_TestInfo.fLines[2], axisY - i);
                    }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                        //列表回顾相关界面的回调
                        GUI_DrawPoint(axisX + MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].fLines[0], axisY - i); 
                        GUI_DrawPoint(axisX + MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].fLines[1], axisY - i);
                        GUI_DrawPoint(axisX + MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].fLines[2], axisY - i);
                    }else if(MachRunPara.ulMenuID == GUI_WINDOW_QC_ANALYSIS_ID){
                        //质控样本分析界面回调
                        GUI_DrawPoint(axisX + MachRunPara.tQC_WBCHGB_TestInfo.fLines[0], axisY - i); 
                        GUI_DrawPoint(axisX + MachRunPara.tQC_WBCHGB_TestInfo.fLines[1], axisY - i);
                        GUI_DrawPoint(axisX + MachRunPara.tQC_WBCHGB_TestInfo.fLines[2], axisY - i);      
                    }
                }
            }
        }
        
        /* draw histogram */
        GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
        for (i = 0; i < GRAPH_DATA_LEN; i++)
        {        
            Point[i].x = axisX + i;
            if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
            {
                //样本分析界面的回调
                Point[i].y = axisY - MachRunPara.tWBCHGB_TestInfo.fWBC_Histogram[i]*1.35f;
            }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                //列表回顾相关界面的回调
                Point[i].y = axisY - MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].fWBC_Histogram[i]*1.35f;
            }else if(MachRunPara.ulMenuID == GUI_WINDOW_QC_ANALYSIS_ID){
                //质控样本分析界面回调
                Point[i].y = axisY - MachRunPara.tQC_WBCHGB_TestInfo.fWBC_Histogram[i]*1.35f;
            }                
            
            //get MaxPos y axis
            if(MaxPos_y > Point[i].y) 
            {
                MaxPos_y = Point[i].y;
                MaxPos_x = i;
            }
        }
        //最后一个点(256+1)的Y值必须位175（x轴上），否则调用GUI_AA_FillPolygon， 会出现底部一段为空
        Point[i].y = axisY;
        Point[i].x = axisX + i;
        GUI_AA_FillPolygon(Point, GRAPH_DATA_LEN+1, 0, 0); //画直方图
                
        /* show max fl at max x, y axis */
        GUI_SetColor(GUI_BLACK);
        GUI_SetBkColor(GUI_WHITE);
        memset((void*)buffer, 0, sizeof(buffer));
        if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
        {
            //样本分析界面的回调
            sprintf(buffer, "%0.2f", MachRunPara.tWBCHGB_TestInfo.fWbcMaxPos);
        }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
            //列表回顾相关界面的回调
            sprintf(buffer, "%0.2f", MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].fWbcMaxPos);
        }else if(MachRunPara.ulMenuID == GUI_WINDOW_QC_ANALYSIS_ID){
            //质控样本分析界面回调
            sprintf(buffer, "%0.2f", MachRunPara.tQC_WBCHGB_TestInfo.fWbcMaxPos);
        }       
        //set maxfl display x y
        if(MaxPos_x < 80) //to left
        {
            MaxPos_x = 80;
        }else if(MaxPos_x > 200) //too right
        {
            MaxPos_x = 200;
        }
        if(ACCOUNT_TYPE_SUPER == MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type)
        {
            //超级管理员账户才显示最大fl值
            GUI_DispStringAt(buffer, MaxPos_x, MaxPos_y - 20);
        }
        
        /* draw fl scale value */
        GUI_SetColor(GUI_BLACK);
        GUI_SetBkColor(GUI_WHITE);
        //
        GUI_DispStringAt(&FL_Scale[0][0], axisX, axisY+10);         // 0
        GUI_DispStringAt(&FL_Scale[1][0], axisX + 50, axisY+5);    // 100
        GUI_DispStringAt(&FL_Scale[2][0], axisX + 115, axisY+5);   // 200
        GUI_DispStringAt(&FL_Scale[3][0], axisX + 180, axisY+5);   // 300
        GUI_DispStringAt(&FL_Scale[4][0], axisX + 240, axisY+5);   // 400
        //
        GUI_SetColor(GUI_RED);
        for(i = 1; i <SCALE_CHAR_NUM; i++)
        {
            GUI_DrawVLine(20 + i * 64, 172, axisY); //64->100 fl, scale for fl(100, 200, 300, 400)
        }
        //GUI_DispStringAt(&FL_Scale[i][0], Rect.x0 + 20 + i * 64, Rect.y0 + 185); //FL
    }
    break;
    default:
        TEXT_Callback(pMsg);
        break;
    }
}


/*
*  analysis  btn callback 
*/
static void Analysis_Btn_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        

        if (BUTTON_IsPressed(pMsg->hWin)) {
             
            WM_GetClientRect(&Rect);
            //draw frame
            GUI_SetColor(MachInfo.companyInfo.skin.buttPress); //填充背景颜色
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 19);
            
            //
            GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
            //
            if (ID_BUTTON_LAST_RECORD == WM_GetId(pMsg->hWin))
            {
                //上一记录
//				Show_BK_BMP(BK_SDRAM,ICON_ZJT_WHITE_BTN, 15, 14);
				UI_DrawSanJiao(ZUO_SAN_JIAO,12, 14,GUI_WHITE);
                if(LANGUAGE_ENGLISH == MachInfo.systemSet.eLanguage)
                {
                    GUI_DispStringAt(g_ucaLng_LastRecord[MachInfo.systemSet.eLanguage], Rect.x0 + 28, Rect.y0 + 12);
                }else{
                    GUI_DispStringAt(g_ucaLng_LastRecord[MachInfo.systemSet.eLanguage], Rect.x0 + 28, Rect.y0 + 12);
                }
            }
            else if (ID_BUTTON_NEXT_RECORD == WM_GetId(pMsg->hWin)) {
                //下一记录 
                if(LANGUAGE_ENGLISH == MachInfo.systemSet.eLanguage)
                {
                    GUI_DispStringAt(g_ucaLng_NextRecord[MachInfo.systemSet.eLanguage], Rect.x0 + 40, Rect.y0 + 12);
                }else{
                    GUI_DispStringAt(g_ucaLng_NextRecord[MachInfo.systemSet.eLanguage], Rect.x0 + 20, Rect.y0 + 12);
                }
//				Show_BK_BMP(BK_SDRAM,ICON_YJT_WHITE_BTN, 95, 14);
				UI_DrawSanJiao(YOU_SAN_JIAO,95, 14,GUI_WHITE);
            }
            else if (ID_BUTTON_NEXT_SAMPLE == WM_GetId(pMsg->hWin)) {
                //下一样本测试
                GUI_DispStringInRect(g_ucaLng_NextSample[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_PRINT == WM_GetId(pMsg->hWin)) {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_PATIENT_INFO == WM_GetId(pMsg->hWin)) {
                //病人信息
                GUI_DispStringInRect(g_ucaLng_PatientInfo[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
        else {
            WM_GetClientRect(&Rect);
            
            //填充颜色
            GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
            
			//画框
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRect(Rect.x0,Rect.y0,Rect.x1,Rect.y1, 19);
			
            //
            if (ID_BUTTON_LAST_RECORD == WM_GetId(pMsg->hWin))
            {  
                //上一记录
                if(WM_IsEnabled(pMsg->hWin))
                {
					UI_DrawSanJiao(ZUO_SAN_JIAO,12, 14,GUI_BLACK);
                }else{
					UI_DrawSanJiao(ZUO_SAN_JIAO,12, 14,GUI_LIGHTGRAY);
                }  
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				GUI_DispStringInRect(g_ucaLng_LastRecord[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_NEXT_RECORD == WM_GetId(pMsg->hWin)) {
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
                //下一记录
                if(LANGUAGE_ENGLISH == MachInfo.systemSet.eLanguage)
                {
                    GUI_DispStringAt(g_ucaLng_NextRecord[MachInfo.systemSet.eLanguage], Rect.x0 + 40, Rect.y0 + 12);
                }else{
                    GUI_DispStringAt(g_ucaLng_NextRecord[MachInfo.systemSet.eLanguage], Rect.x0 + 20, Rect.y0 + 12);
                }
                //
                if(WM_IsEnabled(pMsg->hWin))
                {
					UI_DrawSanJiao(YOU_SAN_JIAO,95, 14,GUI_BLACK);
                }else{
					UI_DrawSanJiao(YOU_SAN_JIAO,95, 14,GUI_LIGHTGRAY);
                } 
            }
            else if (ID_BUTTON_NEXT_SAMPLE == WM_GetId(pMsg->hWin)) {
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
                //下一样本测试
                GUI_DispStringInRect(g_ucaLng_NextSample[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_PRINT == WM_GetId(pMsg->hWin)) {
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_PATIENT_INFO == WM_GetId(pMsg->hWin)) {
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
                //病人信息
                GUI_DispStringInRect(g_ucaLng_PatientInfo[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            } 
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}


/*
*  添加报警信息及数值 到显示buffer
*/
void Display_Result_Info(char *pBuffer, char Index, __IO WBCHGB_TestInfo_t *ptWBCHGB_TestInfo)
{
    extern __IO MachRunPara_s MachRunPara;
	extern  MachInfo_s	MachInfo;
    
    if(Index >= WBCHGB_RST_END){
        LOG_Error("Index Morn That %d", WBCHGB_RST_END);
        return;
    }
    
    //HGB和WBC的结果相互之间，在显示是独立显示！
    if((DATA_STATUS_COUNT_INVALID == (ptWBCHGB_TestInfo->eDataStatus) && (Index!= WBCHGB_RST_HGB)) || DATA_STATUS_INIT == (ptWBCHGB_TestInfo->eDataStatus)) 
    {
        //如何当前数据再故障条件下产生，则WBC值显示 "---"， //当测试不成功或是初始数据时，显示'/'
        if(DATA_STATUS_INIT == (ptWBCHGB_TestInfo->eDataStatus))  sprintf(pBuffer, "/");
        else  sprintf(pBuffer, "---");
    }else if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority<MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority && (Index!= WBCHGB_RST_HGB) && ptWBCHGB_TestInfo->fWBCHGB_RstData[WBCHGB_RST_WBC] < 0.3f){   
        
        //普通账号 001,并且wbc值小于0.3，其他显示项都报*
        if(WBCHGB_RST_WBC == Index)
        {
            sprintf(pBuffer, "%0.2f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
        }else if(WBCHGB_RST_HGB == Index){
            sprintf(pBuffer, "%0.1f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
        }else{
            sprintf(pBuffer, "***");
        }
    }else if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority<MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority && (Index!= WBCHGB_RST_HGB)){   //普通账号 001
     
         //根据报警信息和数值，合成显示内容，（如果为普通账号（001）,不报* ？）            
        switch(ptWBCHGB_TestInfo->ucaWBCHGB_RstAlert[Index])
        {
            case WBCHGB_ALERT_INVALID://报*标志
            case WBCHGB_ALERT_NORMAL:
            {
                sprintf(pBuffer, "%0.2f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_SMALL:
            {
                sprintf(pBuffer, "%0.2f↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_BIG:
            {
                sprintf(pBuffer, "%0.2f↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW:
            {
                sprintf(pBuffer, "%0.2f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW_SMALL:
            {
                sprintf(pBuffer, "%0.2f↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW_BIG:
            {
                sprintf(pBuffer, "%0.2f↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
//            case WBCHGB_ALERT_INVALID:
//            {
//                sprintf(pBuffer, "***");           
//            }
//            break;        
        } 
     }else if(Index != WBCHGB_RST_HGB){
         //其他账号
         //根据报警信息和数值，合成显示内容，（报* ？）            
        switch(ptWBCHGB_TestInfo->ucaWBCHGB_RstAlert[Index])
        {
            case WBCHGB_ALERT_NORMAL:
            {
                sprintf(pBuffer, "%0.2f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_SMALL:
            {
                sprintf(pBuffer, "%0.2f↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_BIG:
            {
                sprintf(pBuffer, "%0.2f↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW:
            {
                sprintf(pBuffer, "%0.2f?", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW_SMALL:
            {
                sprintf(pBuffer, "%0.2f?↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW_BIG:
            {
                sprintf(pBuffer, "%0.2f?↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_INVALID:
            {
                sprintf(pBuffer, "***");           
            }
            break;        
        }     
     }else if(Index == WBCHGB_RST_HGB){
         //HGB
         
         //其他错误码（除以下错误码外），不显示HGB值
        if(ptWBCHGB_TestInfo->tMsgHead.eErrorCode != ERROR_CODE_TIMEOUT && ptWBCHGB_TestInfo->tMsgHead.eErrorCode != ERROR_CODE_RESULT_ASTERISK \
            && ptWBCHGB_TestInfo->tMsgHead.eErrorCode != ERROR_CODE_SUCCESS  &&  ptWBCHGB_TestInfo->tMsgHead.eErrorCode != ERROR_CODE_RE_CONN_2_T4_15S )
        {
            sprintf(pBuffer, "---");
            return;
        }
        
        
        //根据报警信息和数值，合成显示内容，（报* ？）   
        switch(ptWBCHGB_TestInfo->ucaWBCHGB_RstAlert[Index])
        {
            case WBCHGB_ALERT_NORMAL:
            {
                sprintf(pBuffer, "%0.1f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_SMALL:
            {
                sprintf(pBuffer, "%0.1f↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_BIG:
            {
                sprintf(pBuffer, "%0.1f↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW:
            {
                sprintf(pBuffer, "%0.1f?", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW_SMALL:
            {
                sprintf(pBuffer, "%0.1f?↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_REVIEW_BIG:
            {
                sprintf(pBuffer, "%0.1f?↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
            }
            break;
            case WBCHGB_ALERT_INVALID:
            {
                sprintf(pBuffer, "***");           
            }
            break;        
        }     
     }
     

}    





/*
*  analysis  wbc hgb result info，WBCHGB 结果信息显示
*/
void WBCHGB_Result_Btn_Callback(WM_MESSAGE* pMsg)
{
    extern uint8_t g_ucListView_DataIndex;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
    const unsigned char RoundRadius = 5;   //显示区域圆角半径
    const unsigned char HeaderHigh  = 34;  //显示头高度
    const unsigned char LineHigh    = 37;  //每行高度
    const unsigned char LineLen     = 100; //每一小格的长度
    char buffer[10] = {0};
    char i = 0, j = 0;
    GUI_RECT TempRect;
    
    
    const char ucaUnitBuf[WBCHGB_RST_END-1][8] = {
        "10^9/L", "10^9/L", "10^9/L", "10^9/L", "%", "%", "%",
    };
	
	char ucaParamBuf[WBCHGB_RST_END-1][8] = {0};
    
	switch(MachInfo.companyInfo.company){
		case COMPANY_JIN_RUI:
		{
			//锦瑞
			strcpy(&ucaParamBuf[0][0],"WBC");
			strcpy(&ucaParamBuf[1][0],"Neu#");
			strcpy(&ucaParamBuf[2][0],"Mid#");
			strcpy(&ucaParamBuf[3][0],"Lym#");
			strcpy(&ucaParamBuf[4][0],"Neu%");
			strcpy(&ucaParamBuf[5][0],"Mid%");
			strcpy(&ucaParamBuf[6][0],"Lym%");
		}break;
		
		default :
		{
			strcpy(&ucaParamBuf[0][0],"WBC");
			strcpy(&ucaParamBuf[1][0],"Gran#");
			strcpy(&ucaParamBuf[2][0],"Mid#");
			strcpy(&ucaParamBuf[3][0],"Lym#");
			strcpy(&ucaParamBuf[4][0],"Gran%");
			strcpy(&ucaParamBuf[5][0],"Mid%");
			strcpy(&ucaParamBuf[6][0],"Lym%");
		}break;
	}
	
    //
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);
        
        //画头，一行
        for(i = 0; i < 3; i++)
        {     
            //背景显示区域
            TempRect.x0 = Rect.x0 + i*LineLen;
            TempRect.y0 = Rect.y0;
            TempRect.x1 = TempRect.x0 + LineLen;
            TempRect.y1 = TempRect.y0 + HeaderHigh;
            
            GUI_SetColor(MachInfo.companyInfo.skin.title);
            if(i == 0)
            {
                //填充背景
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1+RoundRadius, RoundRadius);
                //显示字符,参数
                GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.title);
                GUI_DispStringInRect(g_ucaLng_Param[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(i == 1){
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1, 0);
                //显示字符。结果
                GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.title);
                GUI_DispStringInRect(g_ucaLng_Result[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(i == 2){
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1+RoundRadius, RoundRadius);
                //显示字符。单位
                GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.title);
                GUI_DispStringInRect(g_ucaLng_Unit[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
        //画尾，HGB一行（参数、结果、单位）
        for(i = 0; i < 3; i++)
        {     
            //设置字体及背景显示区域
            TempRect.x0 = Rect.x0 + i*LineLen;
            TempRect.y0 = Rect.y0 + HeaderHigh + 7*LineHigh;
            TempRect.x1 = TempRect.x0 + LineLen;
            TempRect.y1 = TempRect.y0 + LineHigh;
            
            GUI_SetColor(MachInfo.companyInfo.skin.bg);
            if(i == 0) //参数（HGB）
            {
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0 - RoundRadius, TempRect.x1, TempRect.y1, RoundRadius);
                GUI_SetColor(GUI_BLACK);
                GUI_SetBkColor(MachInfo.companyInfo.skin.bg);
                GUI_DispStringInRect("HGB", &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(i == 1){ //结果（大小）
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1, 0);
                GUI_SetColor(GUI_BLACK);
                GUI_SetBkColor(MachInfo.companyInfo.skin.bg);
                
                memset(buffer, 0, sizeof(buffer));
                if(GUI_WINDOW_ANALYSIS_ID == Get_Cur_MenuID()) //样本分析界面
                {           
                    Display_Result_Info(buffer, WBCHGB_RST_HGB, &MachRunPara.tWBCHGB_TestInfo);
                }else if(GUI_WINDOW_RESULT_INFO_ID == Get_Cur_MenuID()){ //列表回顾-结果详情
                    Display_Result_Info(buffer, WBCHGB_RST_HGB, &MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]]);
                }else if(GUI_WINDOW_QC_ANALYSIS_ID == Get_Cur_MenuID()){ //质控样本分析
                    QC_Display_Result_Info(buffer, WBCHGB_RST_HGB, &MachRunPara.tQC_WBCHGB_TestInfo);
                }
                GUI_DispStringInRect(buffer, &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);                
            }else if(i == 2){//单位
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0 - RoundRadius, TempRect.x1, TempRect.y1, RoundRadius);
                GUI_SetColor(GUI_BLACK);
                GUI_SetBkColor(MachInfo.companyInfo.skin.bg);
                GUI_DispStringInRect("g/L", &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
        
        //画WBC结果
        for(i = 0; i < 3; i++) //三列
        {    
            for(j = 0; j < 7; j++) //中间七行
            {                
                //操作区域
                TempRect.x0 = Rect.x0 + i*LineLen;
                TempRect.y0 = Rect.y0 + HeaderHigh + j*LineHigh;
                //
                TempRect.x1 = TempRect.x0 + LineLen;
                TempRect.y1 = TempRect.y0 + LineHigh;
                
                //填充背景
                if(j%2 == 0)
                {
                    GUI_SetColor(GUI_WHITE); //设置背景填充颜色
                    GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1, 0);
                    GUI_SetBkColor(GUI_WHITE); //为显示字符，设置背景颜色
                }else{
                    GUI_SetColor(MachInfo.companyInfo.skin.bg);  //设置背景填充颜色
                    GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1, 0);   
                    GUI_SetBkColor(MachInfo.companyInfo.skin.bg); //为显示字符，设置背景颜色                     
                }       
                
                //显示字符
                GUI_SetColor(GUI_BLACK);
                if(i == 0) //参数（WBC、Gran#、...）
                {
                    GUI_DispStringInRect(ucaParamBuf[j], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
                }else if(i == 1){ //结果（大小）
                    memset(buffer, 0, sizeof(buffer));
                    if(GUI_WINDOW_ANALYSIS_ID == Get_Cur_MenuID())    
                    {    
                        //样本分析界面                        
                        Display_Result_Info(buffer, j, &MachRunPara.tWBCHGB_TestInfo);
                        GUI_DispStringInRect(buffer, &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
                    }else if(GUI_WINDOW_RESULT_INFO_ID == Get_Cur_MenuID()){ 
                        //列表回顾-结果详情
                        Display_Result_Info(buffer, j, &MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]]);
                        GUI_DispStringInRect(buffer, &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);  
                    }else if(GUI_WINDOW_QC_ANALYSIS_ID == Get_Cur_MenuID()){ 
                        //质控样本分析
                        //结果偏大/偏小的参考不同，需参考上下限
                        QC_Display_Result_Info(buffer, j, &MachRunPara.tQC_WBCHGB_TestInfo);
                        GUI_DispStringInRect(buffer, &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);  
                    }     
                }else if(i == 2){   //单位（10^9/L、%、...）
                    GUI_DispStringInRect(ucaUnitBuf[j], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
                } 
            }
        }
        //画分割线,横线, 10条
        GUI_SetColor(GUI_WBCHGB_RESULT_FRAME_COLOR);
        GUI_DrawHLine(Rect.y0, Rect.x0, Rect.x1); //第一条
        //GUI_DrawHLine(Rect.y0+HeaderHigh, Rect.x0, Rect.x1); //第二条
        for(i = 0; i < 9; i++)
        {
            GUI_DrawHLine(Rect.y0+HeaderHigh+i*LineHigh, Rect.x0, Rect.x1);
            if(i == 8)  GUI_DrawHLine(Rect.y0+HeaderHigh+i*LineHigh - 1, Rect.x0, Rect.x1);
        }
        //画竖线，4条
        GUI_DrawVLine(Rect.x0, Rect.y0, Rect.y1);
        GUI_DrawVLine(Rect.x0+LineLen, Rect.y0+HeaderHigh, Rect.y1);
        GUI_DrawVLine(Rect.x0+LineLen*2, Rect.y0+HeaderHigh, Rect.y1);
        GUI_DrawVLine(Rect.x0+LineLen*3 - 1, Rect.y0, Rect.y1);

    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
* 初始化回调
*/
static void Analysis_Msg_Init(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    WM_HWIN hItem;

    //WBC HGB Result
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTION_WBCHGB_RESULT);
    WM_SetCallback(hItem, WBCHGB_Result_Btn_Callback);
    WM_InvalidateWindow(hItem);

    //
    // Initialization of 'wbc prompt '
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WBC_PROMPT);
    WM_SetCallback(hItem, WBCHGB_ErrorPrompt_Text_Callback);
    WM_InvalidateWindow(hItem);

    // Initialization of 'HGB prompt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HGB_PROMPT);
    WM_SetCallback(hItem, WBCHGB_ErrorPrompt_Text_Callback);
    WM_InvalidateWindow(hItem);
    
    // test info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TEST_INFO);
    WM_SetCallback(hItem, TestInfo_TEXT_Callback);
    WM_InvalidateWindow(hItem);

    // wbc histogram info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WBC_HISTOGRAM);
    WM_SetCallback(hItem, WBC_Histogram_TEXT_Callback);
    WM_InvalidateWindow(hItem);

    // last record btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LAST_RECORD);  
    BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, GUI_BLACK);
    WM_SetCallback(hItem, Analysis_Btn_Callback);//WM_SetCallback(hItem, Analysis_Btn_LastRecord_Callback); //WM_SetCallback(hItem, Analysis_Btn_Callback);//
    
    // next record btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEXT_RECORD);     
    WM_SetCallback(hItem, Analysis_Btn_Callback);//WM_SetCallback(hItem, Analysis_Btn_NextRecord_Callback); //WM_SetCallback(hItem, Analysis_Btn_Callback);
    
    // next sample btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEXT_SAMPLE);
    WM_SetCallback(hItem, Analysis_Btn_Callback);//WM_SetCallback(hItem, Analysis_Btn_NextSample_Callback); //WM_SetCallback(hItem, Analysis_Btn_Callback);
  
    // print btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT);
    WM_SetCallback(hItem, Analysis_Btn_Callback);//WM_SetCallback(hItem, Analysis_Btn_Print_Callback); //WM_SetCallback(hItem, Analysis_Btn_Callback);

    // patient info btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PATIENT_INFO);
    WM_SetCallback(hItem, Analysis_Btn_Callback);//WM_SetCallback(hItem, Analysis_Btn_Patient_Info_Callback); //WM_SetCallback(hItem, Analysis_Btn_Callback);
    
    //设置窗口背景色和桌面背景色一致
    WINDOW_SetBkColor(hItem, MachInfo.companyInfo.skin.bg);
}




/*
*   界面、数据更新
*/
static void Analysis_Msg_Updata(WM_MESSAGE* pMsg)
{
//    extern char* BKBmaDataBuf;
    extern __IO MachRunPara_s	MachRunPara;
    WM_HWIN hItem;
    
    uint32_t ulHeadIndex = 0, ulTailIndex = 0, ulCurDataSN = 0, ulCurDataIndex = 0, ulQueueMaxNum = 0; 
    
    ulHeadIndex = Get_WBCHGB_Head();
    ulTailIndex = Get_WBCHGB_Tail();
    ulCurDataSN = MachRunPara.tWBCHGB_TestInfo.ulCurDataSN;
    ulCurDataIndex = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
    
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTION_WBCHGB_RESULT);
    WM_InvalidateWindow(hItem);
    //WM_DisableWindow(hItem);

    // wbc prompt listview
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WBC_PROMPT);
    WM_InvalidateWindow(hItem);

    // HGB prompt listview
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_HGB_PROMPT);
    WM_InvalidateWindow(hItem);

    // test info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TEST_INFO);
    WM_InvalidateWindow(hItem);

    // wbc histogram info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WBC_HISTOGRAM);
    WM_InvalidateWindow(hItem);

    //无记录或是当前SN无效， 打印和病人信息，上下记录按键失能
	if(((ulHeadIndex == ulTailIndex)) || (ulCurDataSN == INVALID_DATA_SN) || ulCurDataIndex == INVALID_DATA_SN)
	{
		LOG_Info("No WBC HGB Data, DataManage: ulHeadIndex=%d, ulTailIndex=%d, ulCurDataSN=%d, ulCurDataIndex=%d", ulHeadIndex, ulTailIndex, ulCurDataSN, ulCurDataIndex);
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LAST_RECORD));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEXT_RECORD));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PATIENT_INFO));
	}else{
        //上一记录按键
        if(ulCurDataIndex == ulHeadIndex)
        {        
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LAST_RECORD));
        }else{
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LAST_RECORD));
        }
        
        //下一记录按键
        ulQueueMaxNum = Get_WBCHGB_Queue_MaxNum();
        if((ulCurDataIndex+1)%ulQueueMaxNum == ulTailIndex)
        {
            //已是最后一条有效数据，失能下一记录按键
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEXT_RECORD));
        }else{
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEXT_RECORD));
        }
        
        //
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT));
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PATIENT_INFO));
    }
}


/*
*    UI send last record msg to backend 
*/
static ErrorCode_e Analysis_LastRecord_Msg(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    uint32_t ulHeadIndex = 0, ulTailIndex = 0, ulCurDataIndex = 0;
    
    ulHeadIndex = Get_WBCHGB_Head();
    ulTailIndex = Get_WBCHGB_Tail();
    ulCurDataIndex = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
    
//    Printf_Free_StackSize();
    //不为空，没到头，当前数据为有效数据
    if((ulTailIndex != ulHeadIndex) && (ulHeadIndex != ulCurDataIndex) && (INVALID_DATA_SN != ulCurDataIndex))
    {   
        //存在上一条记录
        LastRecord_t tLastRecord = {0};
        //消息头
        tLastRecord.tMsgHead.usCmd       = CMD_ANALYSIS_LAST_RECORD;
        //消息体
        tLastRecord.ulCurDataIndex       = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
        //发送消息给后端
        if(osOK != UI_Put_Msg((uint8_t*)&tLastRecord)) //osOk != ...
        {
            LOG_Error("Send Msg Fail");
            return ERROR_CODE_FAILURE;
        }
    }

    return ERROR_CODE_SUCCESS;
}


/*
*    UI send next record msg to backend
*/
static ErrorCode_e Analysis_NextRecord_Msg(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    uint32_t ulHeadIndex = 0, ulTailIndex = 0, ulCurDataIndex = 0, ulBeforeTailIndex = 0;
    
    ulHeadIndex = Get_WBCHGB_Head();
    ulTailIndex = Get_WBCHGB_Tail();
    ulBeforeTailIndex = Get_WBCHGB_BeforeTail();
    ulCurDataIndex = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
    
//    Printf_Free_StackSize();
    //不为空，没到尾，当前数据为有效数据
    if((ulTailIndex != ulHeadIndex) && (ulBeforeTailIndex != ulCurDataIndex) && (INVALID_DATA_SN != ulCurDataIndex))
    {
        //存在下一条记录
        NextRecord_t tNextRecord = {0};
        //消息头
        tNextRecord.tMsgHead.usCmd      = CMD_ANALYSIS_NEXT_RECORD;
        //消息体
        tNextRecord.ulCurDataIndex      = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
        //
        //发送消息给后端
        if(0 != UI_Put_Msg((uint8_t*)&tNextRecord)) //osOk != ...
        {
            LOG_Error("Send Msg Fail");
            return ERROR_CODE_FAILURE;
        }
    }
    //
    return ERROR_CODE_SUCCESS;
}



/*
*    UI send print  msg to backend
*/
static ErrorCode_e Analysis_Print_Msg(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    uint32_t ulHeadIndex = 0, ulTailIndex = 0, ulCurDataIndex = 0;
    
    ulHeadIndex = Get_WBCHGB_Head();
    ulTailIndex = Get_WBCHGB_Tail();
    ulCurDataIndex = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
    
//    Printf_Free_StackSize();
    if((ulTailIndex == ulHeadIndex) && (INVALID_DATA_SN != ulCurDataIndex))
    {
        //为空，当前数据为无效数据
        LOG_Info("No WBC HGB Data, DataManage: ulHeadIndex=%d, ulTailIndex=%d, ulCurDataIndex=%d", ulHeadIndex, ulTailIndex, ulCurDataIndex);
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT));
		return ERROR_CODE_FAILURE;
    }      
 
    Print_t tPrint = {0};
    //消息头
    tPrint.tMsgHead.usCmd       = CMD_ANALYSIS_PRINT;
    //消息体
    tPrint.ulCurDataIndex       = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
    
    //发送消息给后端
    if(0 != UI_Put_Msg((uint8_t*)&tPrint)) //osOk != ...
    {
        LOG_Error("Send Msg Fail");
        return ERROR_CODE_FAILURE;
    }
    
    return ERROR_CODE_SUCCESS;
}



/*********************************************************************
*
*       _cbDialog
*/
static void Analysis_cbDialog(WM_MESSAGE * pMsg) {
    
  extern PrinterErrorType_e g_ePrinterErrorType;
    
//  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  {
      
    Analysis_Msg_Init(pMsg);
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
  }
  break;
  case WM_ANALYSIS_GZ_AUTO_MODE_UPDATE_DATA:
  {
     Analysis_Msg_Updata(pMsg);
  }
  break;
  case WM_PAINT:
  {
    GUI_RECT Rect;
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
      
    Analysis_Msg_Updata(pMsg);
  }
  break;
  case WM_ANALYSISI_ERROR_COUNT_NOT_ALLOW:
  {
      char buffer[96] = {0};
      CommonDialogPageData_s DialogPageData = {0};
      
    //先清除故障、再执行样本分析
    GUI_EndDialog(pMsg->hWin, 0);
    g_hActiveWin = CreateDialogPage();
      
    //保存对话框内容
    DialogPageData.bmpType = BMP_ALARM;
    DialogPageData.confimButt = HAS_CONFIM_BUTTON;
    DialogPageData.fun = Analysis_Menu;
    sprintf(buffer, "%s!", g_ucaLng_ClearErrorBeforCount[MachInfo.systemSet.eLanguage]);
    strcpy(DialogPageData.str, buffer);

    pMsg->MsgId = WM_USER_DATA;
    pMsg->Data.p = &DialogPageData;
    WM_SendMessage(g_hActiveWin,pMsg);  
  }
  break;
  case WM_DELETE:
  {
	Disable_Motor_Task();
  }
  break;
  case WM_MOTOR_ERROR_PROMPT:
  {
      Motor_Error_Prompt(pMsg, Analysis_Menu);
  }
  break;
  case WM_PRINTER_NO_PAPER:
  {
      //打印机缺纸
      g_ePrinterErrorType = PRINTER_NO_PAPER;
      //
      GUI_EndDialog(pMsg->hWin, 0);
      g_hActiveWin = Printer_Error_Prompt_PromptDLG();
      
      //GUI_MessageBox("Printer No Paper", "", 0);
  }
  break;
  case WM_PRINTER_CONN_ERR:
  {
      //打印机连接异常
      g_ePrinterErrorType = PRINTER_CONN_ERROR;
      //
      GUI_EndDialog(pMsg->hWin, 0);
      g_hActiveWin = Printer_Error_Prompt_PromptDLG();
      
      //GUI_MessageBox("Printer Conn Error", "", 0);
  }break;
  case WM_ANALYSIS_GIF_OPERATE_OUTIN_KEY:
  {
      extern __IO OutIn_Module_Position_e g_eOutIn_Key;
      extern __IO osSemaphoreId_t xSema_OutIn_Key;
      
      g_eOutIn_Key = OUTIN_MODULE_POSITION_IN;
      osSemaphoreRelease(xSema_OutIn_Key);
  }
  break;
  case WM_ANALYSIS_LOAT_DATA_FAIL:
  {
      //提示数据加载失败
    CommonDialogPageData_s DialogPageData = {0};
    WM_MESSAGE UserMsg;
    //
    GUI_EndDialog(pMsg->hWin, 0);
    g_hActiveWin = CreateDialogPage();
     //
    DialogPageData.bmpType = BMP_ALARM;
    DialogPageData.confimButt = HAS_CONFIM_BUTTON;
    DialogPageData.fun = Analysis_Menu;
    strcpy(DialogPageData.str, g_ucaLng_LoadDate_Err[MachInfo.systemSet.eLanguage]);

    UserMsg.MsgId = WM_USER_DATA;
    UserMsg.Data.p = &DialogPageData;
    WM_SendMessage(g_hActiveWin,&UserMsg);
      
  }
  break;
  case WM_ANALYSIS_GIF_OPERATE_COUNT_KEY:
  {
      extern __IO osSemaphoreId_t xSema_Count_Key;
      osSemaphoreRelease(xSema_Count_Key);
  }
  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
   
    case ID_BUTTION_WBCHGB_RESULT: // Notifications sent by 'reslut_Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LAST_RECORD: // Notifications sent by 'lastRecord_btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        
		// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Analysis_LastRecord_Msg(pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_NEXT_RECORD: // Notifications sent by 'nextRecord_btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Analysis_NextRecord_Msg(pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_NEXT_SAMPLE: // Notifications sent by 'nextTest_btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
            // USER START (Optionally insert code for reacting on notification message)
            if(PANEL_LED_STATUS_ERROR ==  g_ePanel_LED_Status)
            {
                //开机自检存在故障（影响计数），需先清除故障，再计数
                WM_SendMessageNoPara(g_hActiveWin, WM_ANALYSISI_ERROR_COUNT_NOT_ALLOW);
            }else{
				extern WM_HWIN CreateInputUserNumPage(void);
				
				switch(MachInfo.companyInfo.company){
					case COMPANY_YSB:
					{
						MachRunPara.flag.requestingPatient = 1;
						
						//药师帮
						extern osEventFlagsId_t GlobalEventCatGroupHandle;
						extern osMessageQueueId_t CATQueueOtherHandle;
						CommonDialogPageData_s DialogPageData = {0};
						Msg_Head_t BackendMsg = {0};
						CATQueueInfoBuf_s CATQueueInfoBuf = {0};
						
						GUI_EndDialog(pMsg->hWin, 0);
						g_hActiveWin = CreateDialogPage();
						
						//保存对话框内容
						DialogPageData.bmpType = BMP_ALARM;
						DialogPageData.confimButt = NO_CONFIM_BUTTON;
						DialogPageData.fun = Analysis_Menu;
						strcpy(DialogPageData.str,g_ucaLng_Analyse_RequestParientInfo[MachInfo.systemSet.eLanguage]);
						
						pMsg->MsgId = WM_USER_DATA;
						pMsg->Data.p = &DialogPageData;
						WM_SendMessage(g_hActiveWin,pMsg);
						
						//先清除网络异常事件标志
						osEventFlagsClear(GlobalEventCatGroupHandle,GLOBAL_EVENT_CAT_CONN_OTHER_NET_ERR);
						
						//往后台发送消息
						BackendMsg.usCmd = CMD_ANALYSIS_REQUEST_USER_NUM;
						UI_Put_Msg((uint8_t*)&BackendMsg);
						
						memset((uint8_t*)&MachRunPara.patientList,0,sizeof(MachRunPara.patientList));
						MachRunPara.patientList.pageNum = 1;
						
						CATQueueInfoBuf.msgType = REQUEST_PATIENT_ID_CAT_MSG_TYPE;
						CATQueueInfoBuf.para.TempU8 = MachRunPara.patientList.pageNum;				//请求第1页的患者信息
						
						//向第三方服务端请求患者信息
						osMessageQueuePut(CATQueueOtherHandle,&CATQueueInfoBuf,0, 0);
					}break;
					
					case COMPANY_HY:
					{
						MachRunPara.flag.requestingPatient = 1;
						
						//和映
						GUI_EndDialog(g_hActiveWin, 0);
						g_hActiveWin = CreateInputUserNumPage();
					}break;
					
					default :
					{
						GUI_EndDialog(pMsg->hWin, 0);
						g_hActiveWin = CreateNextSample_Window();
						WM_SendMessageNoPara(g_hActiveWin, WM_NEXT_SAMPLE_UPDATE);
					}break;
				}
            }
        }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_PRINT: // Notifications sent by 'print_btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Analysis_Print_Msg(pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_PATIENT_INFO: // Notifications sent by 'testerInfo_btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatePatient_Info_Window();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;


    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Analysis_Menu
*/
WM_HWIN Analysis_Menu(void);
WM_HWIN Analysis_Menu(void) {
    
	extern __IO osSemaphoreId_t xSema_Count_Key;
	WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();

	//使能电机任务，算法任务
	Enable_Motor_Task(TRUE);
	Enable_Algo_Task(TRUE);

	//记录当前界面ID
	Set_Cur_MenuID(GUI_WINDOW_ANALYSIS_ID);
	
	//UI 样本分析按键背景高亮
	Public_Reset_Btn_Status(BTN_ANALYSIS);

	hWin = GUI_CreateDialogBox(Analysis_aDialogCreate, GUI_COUNTOF(Analysis_aDialogCreate), Analysis_cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
