/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

/*
*
*   在样本分析后，弹出界面，提示“请确认检测模块是否取出”
*
*/

// USER END
#include "DIALOG.h"
#include "WM.h"
#include "GUI.h"
#include "LISTBOX.h"
#include "Public_menuDLG.h"
#include "file_operate.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



//ID
#define ID_WINDOW_CONFIRM_TAKEOUT_CELL 		(GUI_WINDOW_CONFIRMT_TAKEOUT_CELL + 0x00)
#define ID_CONFIRM_TAKEOUT_CELL_BTN_SURE    (ID_WINDOW_CONFIRM_TAKEOUT_CELL + 0x01)





// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/



// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/

static const GUI_WIDGET_CREATE_INFO Confirm_Takeout_Cell_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "", ID_WINDOW_CONFIRM_TAKEOUT_CELL,       180, 100, 440, 225, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_CONFIRM_TAKEOUT_CELL_BTN_SURE,  	 0, 185, 440, 40, 0, 0x0, 0 }, 
};





/*********************************************************************
*
*       Static code
*
**********************************************************************
*/



/*
*    btn callback
*/
static void Confirm_Takeout_Cell_Btn_Callback(WM_MESSAGE* pMsg)
{
    const unsigned char RoundRadius = 0; //显示区域圆角半径
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            //draw frame
            GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
            if(ID_CONFIRM_TAKEOUT_CELL_BTN_SURE == WM_GetId(pMsg->hWin))
            {
                //确定
                GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }                
        }
        else {
            // draw frame
            GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);

            GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
            if(ID_CONFIRM_TAKEOUT_CELL_BTN_SURE == WM_GetId(pMsg->hWin))
            {
                //确定
                GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }  
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}






/*********************************************************************
*
*       _cbDialog
*/
static void Confirm_Takeout_Cell_cbDialog(WM_MESSAGE* pMsg) {
    
    WM_HWIN hItem;
    int     NCode;
    int     Id;
//    char buffer[50] = {0};


    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
	{

		//btn sure
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CONFIRM_TAKEOUT_CELL_BTN_SURE);
		WM_SetCallback(hItem, Confirm_Takeout_Cell_Btn_Callback);
        WM_InvalidateWindow(hItem);
		

	}
    break;
    case WM_PAINT:
    {
        Show_BK_BMP(BK_FILE, BK_PICTURE_PRINTER_CONFIRM_TAKEOUT, 85, 38); 
    }
    break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_CONFIRM_TAKEOUT_CELL_BTN_SURE: // Notifications sent by ' '
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {
					if(CHECK_JSC_EXIST_STATUS == JSC_EXIST_STATUS_ACTIVE)
					{ 
						break;
					}
					
					//关闭计数池检测
					COUNT_CELL_SW_OFF;
					
					GUI_EndDialog(pMsg->hWin, 0);
					g_hActiveWin = NSec_OutIn_In_WindowDLG();
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        }
        break;
        // USER START (Optionally insert additional message handling)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       ReCount_Prompt
*/



WM_HWIN Confirm_Takeout_Cell_WindowDLG(void);
WM_HWIN Confirm_Takeout_Cell_WindowDLG(void) {
    WM_HWIN hWin;

	//开启计数池检测
	COUNT_CELL_SW_ON;
	
	Disable_Algo_Task();
    
    Public_Hide_Widget(); //隐藏公共部分控件,
    
    hWin = GUI_CreateDialogBox(Confirm_Takeout_Cell_aDialogCreate, GUI_COUNTOF(Confirm_Takeout_Cell_aDialogCreate), Confirm_Takeout_Cell_cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
