/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   提示“样本正在分析中，请稍等...”
*
*/
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_COUNTING_PROMPT   (GUI_WINDOW_COUNTING_PROMPT + 0x00)
#define ID_TEXT_COUNTING_PROMPT		(ID_WINDOW_COUNTING_PROMPT + 0x01)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO CountingPrompt_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "", ID_WINDOW_COUNTING_PROMPT, 180, 100, 440, 225, 0, 0x0, 0 },//140, 100, 520, 275, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "",   ID_TEXT_COUNTING_PROMPT,   80, 160, 280, 40, 0, 0x0, 0 },//190, 180, 200, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};




/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void CountingPrompt_cbDialog(WM_MESSAGE * pMsg) {
  // USER START (Optionally insert additional variables)
  // USER END
  extern __IO osSemaphoreId_t xSema_Count_Key;
  extern __IO uint32_t g_ulErrorCode;
//  WM_HWIN hItem;

  switch (pMsg->MsgId) {
      // USER START (Optionally insert additional message handling)
      // USER END
      case WM_INIT_DIALOG:
      {
        
      }
      break;
      case WM_PAINT:
      {
          Show_BK_BMP(BK_FILE, BK_PICTURE_COUNTING ,130, 35);     
      }
      break;
      case WM_DELETE:
      {
      }
      break;
      case WM_ANALYSIS_ERROR_PROMPT: //样本分析，错误提示
      {
          //获取错误码
          g_ulErrorCode = pMsg->Data.v;
          
          //隐藏公共UI按键（样本分析，列表回顾等）
          Public_Hide_Widget();
          
          //设置透明背景回调
          WM_SetCallback(WM_HBKWIN, None_cbBkWin); //AlphaBk_cbBkWin
          
          //关闭当前样本分析界面
          GUI_EndDialog(pMsg->hWin, 0);
          GUI_Exec();
          
          //显示样本分析无效静态界面,之后关闭
          g_hActiveWin = CountFail_CreateWindow();
          GUI_Exec();
          GUI_EndDialog(g_hActiveWin, 0);
          
          //切换背景回调函数
          g_hActiveWin = WM_HBKWIN;
          WM_SetCallback(WM_HBKWIN, GIF_Guide_cbBkWin);
          //发送消息给HBKWIN，计数失败，  显示："计数失败，请拿出计数池动画"
          WM_SendMessageNoPara(g_hActiveWin, WM_FAIL_OUTPUT_GUIDE_GIF2);
      }
      break;
      case WM_ANALYSIS_NORMAL_PROMPT: //样本分析，正常提示窗口
      {          
          //隐藏公共按键（样本分析，列表回顾等）
          Public_Hide_Widget();
          
          //设置透明背景回调
          WM_SetCallback(WM_HBKWIN, None_cbBkWin); //AlphaBk_cbBkWin
          
          //关闭当前正在样本分析界面
          GUI_EndDialog(pMsg->hWin, 0);
          GUI_Exec();
          
          //切换背景回调函数
          g_hActiveWin = WM_HBKWIN;
          WM_SetCallback(WM_HBKWIN, GIF_Guide_cbBkWin);
          //发送消息给HBKWIN，计数成功，请拿出计数池，操作引导动画
          WM_SendMessageNoPara(g_hActiveWin, WM_OK_OUTPUT_GUIDE_GIF);
      }
      break;
      default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CountingPrompt_CreateWindow(void);
WM_HWIN CountingPrompt_CreateWindow(void) {
  WM_HWIN hWin;

  extern __IO osSemaphoreId_t xSema_Count_Key;
    
  hWin = GUI_CreateDialogBox(CountingPrompt_aDialogCreate, GUI_COUNTOF(CountingPrompt_aDialogCreate), CountingPrompt_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
