/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/


/*
*
*   计数失败后，提示计数失败、请拿出计数池、错误码。
*  （该部分不包含GIF部分，GIF再单独显示，该界面和GIF构成一个完整的计数失败提示信息）
*
*/


// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "ui_files.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_WINDOW_COUNT_FAIL		(GUI_WINDOW_COUNT_FAIL_ID + 0x00)
#define ID_WINDOW_COUNT_FAIL_TEXT	(GUI_WINDOW_COUNT_FAIL_ID + 0x01)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO Count_Fail_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "", ID_WINDOW_COUNT_FAIL, 	  360, 60, 330, 360, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "", ID_WINDOW_COUNT_FAIL_TEXT, 70, 195, 180, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void Count_Fail_cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_WINDOW_COUNT_FAIL_TEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, " ");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	case WM_PAINT:
	{
        extern __IO uint32_t g_ulErrorCode;
        char buffer[30] = {0};
        
        //
        Show_BK_BMP(BK_FILE, BK_PICTURE_ANALYSIS_COUNT_FAIL, 0, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_WINDOW_COUNT_FAIL_TEXT);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        TEXT_SetFont(hItem, &HZ_SONGTI_16);
        
        if(g_ulErrorCode != ERROR_CODE_SUCCESS)
        {
            sprintf(buffer, "%s:E%04d", g_ucaLng_ErrorCode[MachInfo.systemSet.eLanguage], g_ulErrorCode);
            TEXT_SetTextColor(hItem, GUI_RED);
            TEXT_SetText(hItem, buffer);
            //TEXT_SetDec(hItem, g_ulErrorCode, 4, 0, 0, 0);
        }		
	}
	break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CountFail_CreateWindow(void);
WM_HWIN CountFail_CreateWindow(void) {
  WM_HWIN hWin;
  
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(Count_Fail_aDialogCreate, GUI_COUNTOF(Count_Fail_aDialogCreate), Count_Fail_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
