/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   开机自检后，错误信息提示界面，有样本分析中的 按“黄色感叹号按键”进入
*
*/
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_ERRORINFO 			(GUI_ERRORINFO_ID + 0x00)
#define ID_TEXT_ERRORINFO_TITLE 		(GUI_ERRORINFO_ID + 0x01)
#define ID_BUTTON_ERRORINFO_CLEAR_ERROR (GUI_ERRORINFO_ID + 0x02)
#define ID_BUTTON_RETURN 				(GUI_ERRORINFO_ID + 0x03)
#define ID_BUTTON_ERRORINFO_LAST 		(GUI_ERRORINFO_ID + 0x04)
#define ID_BUTTON_ERRORINFO_NEXT 		(GUI_ERRORINFO_ID + 0x05)
#define ID_LISTVIEW_ERRORINFO 			(GUI_ERRORINFO_ID + 0x06)
#define ID_TEXT_ERRORINFO_PROMPT 		(GUI_ERRORINFO_ID + 0x07)



//list review 行数
#define ERROR_INFO_LISTREWIEW_ROW_NUM       5

// USER START (Optionally insert additional defines)
// USER END




/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)

/*
* 显示数据index，用于上一条，下一条的起始下标，该值<= MachRunPara.tLogin_SelfCheck.ucErrorNum
* 一行一个数据
*/
static char g_scErrorInfo_Index = 0;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO ErrorInfo_aDialogCreate[] = {
//  { WINDOW_CreateIndirect, "", 	 ID_WINDOW_ERRORINFO, 		   10, 60, 780, 400, 0, 0x0, 0 },
  { WINDOW_CreateIndirect, "", 	 ID_WINDOW_ERRORINFO, 				0, 60, 800, 393, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", 	 ID_TEXT_ERRORINFO_TITLE, 			30, 20, 100, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",   ID_BUTTON_ERRORINFO_CLEAR_ERROR, 	565,12, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", 	 ID_BUTTON_RETURN, 					675,12, 100, 40, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "", ID_LISTVIEW_ERRORINFO, 			20, 60, 720, 240, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",   ID_BUTTON_ERRORINFO_LAST, 			741, 60, 40, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", 	 ID_BUTTON_ERRORINFO_NEXT, 			741, 180, 40, 120, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", 	 ID_TEXT_ERRORINFO_PROMPT, 			20, 310, 780, 80, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// list Review 按钮自定义 回调函数
static void ErrorInfo_Btn_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        int Id;
        
        WM_GetClientRect(&Rect);
        Id = WM_GetId(pMsg->hWin);
        
        if (BUTTON_IsPressed(pMsg->hWin)) {        
            //根据区别不同btn
            //圆形btn
            if (ID_BUTTON_ERRORINFO_CLEAR_ERROR == Id || Id == ID_BUTTON_RETURN)
            {
                GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
                
                //往btn，写入字符或图标
                GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
            }
            //直角btn
            if (ID_BUTTON_ERRORINFO_LAST == Id || Id == ID_BUTTON_ERRORINFO_NEXT)
            {
                GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
                //画框
                GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
                GUI_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
            }

            //
            if(ID_BUTTON_ERRORINFO_CLEAR_ERROR == Id)
            {
                //清除故障
                GUI_DispStringInRect(g_ucaLng_ClearError[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_RETURN == Id) {
                //返回
                GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_ERRORINFO_LAST == Id) {
				UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
             }else if (ID_BUTTON_ERRORINFO_NEXT == Id) {
				UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
            }
             
        } else {
            //根据区别不同btn
            //圆形btn
            if (ID_BUTTON_ERRORINFO_CLEAR_ERROR == Id || Id == ID_BUTTON_RETURN)
            {
				if(WM_IsEnabled(pMsg->hWin)){
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
					
					//画框
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 19);
					 
					//往btn，写入字符或图标
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				}else{
					//填充
					GUI_SetColor(GUI_WHITE);
					GUI_AA_FillRoundedRectEx(&Rect,20);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,19);
					
					//设置字符前景和背景色
					GUI_SetColor(GUI_LIGHTGRAY);
					GUI_SetBkColor(GUI_WHITE);
				}
            }
            //直角btn
            if (ID_BUTTON_ERRORINFO_LAST == Id || Id == ID_BUTTON_ERRORINFO_NEXT)
            {
                if(WM_IsEnabled(pMsg->hWin))
                {
					GUI_SetColor(MachInfo.companyInfo.skin.title);
					GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
					//画框
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
					
                    //enable
                    if (ID_BUTTON_ERRORINFO_LAST == Id) {
                        UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
                    }else if (ID_BUTTON_ERRORINFO_NEXT == Id) {
                        UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
                    }             
                }else{
					//淡色背景
					GUI_SetColor(0x00f3f1ec);
					GUI_FillRectEx(&Rect);
					GUI_SetColor(0x00cccccc);
					GUI_DrawRectEx(&Rect);
					
                    //disable
                    if (ID_BUTTON_ERRORINFO_LAST == Id) {
                        UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
                    }else if (ID_BUTTON_ERRORINFO_NEXT == Id) {
                        UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
                    } 
                }
            }

            //
            if (ID_BUTTON_ERRORINFO_CLEAR_ERROR == Id)
            {
                //清除故障
                GUI_DispStringInRect(g_ucaLng_ClearError[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_RETURN == Id) {
                //返回
                GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
    error info prompt text callback //具体的提示信息（底部）
*/
static void ErrorInfo_Text_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        GUI_GetClientRect(&Rect);

        GUI_SetColor(GUI_BLACK);
        GUI_SetBkColor(GUI_WHITE);

        //
        if(MachRunPara.tLogin_SelfCheck.ucErrorNum != 0)
        {
			Show_BK_BMP(BK_SDRAM,ICON_ERR_SJ_BTN, 10, 5);
            GUI_DispStringAt(g_ucaLng_Prompt_ClearErr[MachInfo.systemSet.eLanguage], Rect.x0 + 40, Rect.y0 + 9);
            
        }
    }
    break;
    default:
        TEXT_Callback(pMsg);
        break;
    }
}



/*
*   更新错误信息界面的listreview控件内容
*/
static void ErrorInfo_Update_Listreview(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int i = 0;
    char ErrCodeBuffer[10] = {0};
    const char *pErrorCodePrompt = NULL;
     
    //list 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_ERRORINFO);
    //清空
    for (i = 0; i < ERROR_INFO_LISTREWIEW_ROW_NUM; i++)
    {
        //                       列号，行号
        LISTVIEW_SetItemText(hItem, 0, i, " "); 
        LISTVIEW_SetItemText(hItem, 1, i, " "); 
    }
    
    //填充listreview显示内容，从g_scErrorInfo_Index开始显示
    for(int i = g_scErrorInfo_Index; i < MachRunPara.tLogin_SelfCheck.ucErrorNum; i++)
    {   
        sprintf(ErrCodeBuffer, "E%d", MachRunPara.tLogin_SelfCheck.eaErrorCodeBuffer[i]);
        pErrorCodePrompt = ErrorCode_Prompt_Info(MachRunPara.tLogin_SelfCheck.eaErrorCodeBuffer[i]);
        //                       列号，行号
        LISTVIEW_SetItemText(hItem, 0, i, ErrCodeBuffer);
        if(pErrorCodePrompt != NULL)
        {
          LISTVIEW_SetItemText(hItem, 1, i, pErrorCodePrompt);
          //LISTVIEW_SetItemText(hItem, 1, i, "Test");
        }
    }

    //没有异常，则失能"清除故障"按钮,（该按钮无法使用）
    if(MachRunPara.tLogin_SelfCheck.ucErrorNum <= 0)
    {
        //没有异常，则失能"清除故障"按钮,（该按钮无法使用）
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ERRORINFO_CLEAR_ERROR);
       // BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, GUI_BUTTON_ROUND_DISABLED_COLOR);
        WM_DisableWindow(hItem);
    }    
}



/*
*   错误信息初始化
*/
static void ErrorInfo_Msg_Init(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    HEADER_Handle HeadHandle;
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERRORINFO_TITLE);
    //故障处理
    TEXT_SetText(hItem, g_ucaLng_ErrorHandle[MachInfo.systemSet.eLanguage]);

    //ErrorCode Clear
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ERRORINFO_CLEAR_ERROR);
    WM_SetCallback(hItem, ErrorInfo_Btn_Callback);
    WM_InvalidateWindow(hItem);
  
    //return
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
    WM_SetCallback(hItem, ErrorInfo_Btn_Callback);
    WM_InvalidateWindow(hItem);
  
    //last one
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ERRORINFO_LAST);
    WM_SetCallback(hItem, ErrorInfo_Btn_Callback);
    BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, MachInfo.companyInfo.skin.buttPress);
    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, MachInfo.companyInfo.skin.buttNotPress);
    BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, GUI_BUTTON_ROUND_DISABLED_COLOR);
    WM_InvalidateWindow(hItem);
    
    //next one
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ERRORINFO_NEXT);
    WM_SetCallback(hItem, ErrorInfo_Btn_Callback);
    BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, MachInfo.companyInfo.skin.buttPress);
    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, MachInfo.companyInfo.skin.buttNotPress);
    BUTTON_SetBkColor(hItem, BUTTON_CI_DISABLED, GUI_BUTTON_ROUND_DISABLED_COLOR);
    WM_InvalidateWindow(hItem);
    
    //具体的提示信息
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERRORINFO_PROMPT);
    WM_SetCallback(hItem, ErrorInfo_Text_Callback);
    WM_InvalidateWindow(hItem); 
  
    //list review
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_ERRORINFO);
    HeadHandle = LISTVIEW_GetHeader(hItem);
    HEADER_SetBkColor(HeadHandle, MachInfo.companyInfo.skin.title);
    WM_SetFocus(hItem);
    //LISTVIEW_SetFont(hItem, &HZ_SONGTI_16);
     //
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_UNSEL, GUI_WHITE);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SEL, MachInfo.companyInfo.skin.highlightKJNotSelect);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SELFOCUS, MachInfo.companyInfo.skin.highlightKJNotSelect);
    LISTVIEW_SetRowHeight(hItem, 39);
    LISTVIEW_SetHeaderHeight(hItem, 40);
      
    /* 行 */  
    for(int i = 0; i < ERROR_INFO_LISTREWIEW_ROW_NUM; i++)
    {
         LISTVIEW_AddRow(hItem, NULL);
    }
    
    /*  两列 */
    //错误码
    LISTVIEW_AddColumn(hItem, 230, g_ucaLng_ErrorCode[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    //错误名称
    LISTVIEW_AddColumn(hItem, 488, g_ucaLng_ErrorName[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_SetSel(hItem, 0);
    
    //更新listreview
    if(MachRunPara.tLogin_SelfCheck.ucErrorNum > 0)
    {
        ErrorInfo_Update_Listreview(pMsg); 
    }else{
        //没有异常，则失能"清除故障"按钮,（该按钮无法使用）
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ERRORINFO_CLEAR_ERROR);
        WM_DisableWindow(hItem);
    }
    //
    g_scErrorInfo_Index = 0;    
    LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_ERRORINFO), g_scErrorInfo_Index);
}
    


// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void ErrorInfo_cbDialog(WM_MESSAGE * pMsg) {
//  WM_HWIN hItem;
  int     NCode;
  int     Id;
  extern __IO MachRunPara_s MachRunPara;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  {
    //
    ErrorInfo_Msg_Init(pMsg);

    //失能Public中错误提示按钮（进入错误提示界面后，该按键失效）
    Disable_Public_ErrPrompt_Btn();
    
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
  }
  break;
  case WM_PAINT:
  {   
      //画背景BMP图
      //extern char* BKBmaDataBuf;
      //GUI_BMP_Draw(BKBmaDataBuf,1,0);
      //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
      GUI_RECT Rect;
      WM_GetClientRect(&Rect); 
      GUI_SetColor(GUI_WHITE);
      GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
      
      //只有再自检完成后，才刷新
      if(MachRunPara.tLogin_SelfCheck.ucProgress == 100)
      {
          //刷新
          ErrorInfo_Update_Listreview(pMsg); 
          //
         //更新Public中错误码提示信息
         Update_Public_ErrPrompt_Btn();
      }
  }
  break;
  case WM_DELETE:
  {
     //使能Public中错误提示按钮（离开错误提示界面后，该按键有效）
     Enable_Public_ErrPrompt_Btn();
      //
  }
  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_ERRORINFO_CLEAR_ERROR: // Notifications sent by 'ClearCode'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
      
        //如果存在错误，则可以执行清除故障(重新执行登录自检)
        if(MachRunPara.tLogin_SelfCheck.ucErrorNum > 0)
        {   
           char buffer[128] = {0};
           CommonDialogPageData_s DialogPageData = {0};
           Msg_Head_t tMsgHead = {0};
           //构造自检消息
           tMsgHead.usCmd      = CMD_LOGIN_ERROR_CLEAR;
           tMsgHead.eErrorCode = ERROR_CODE_SUCCESS;
           tMsgHead.usMsgLen   = MSG_HEAD_LEN;
           //发送消息给后端           
           UI_Put_Msg((uint8_t*)&tMsgHead);
           
           
           //"正在消除故障..."提示
           GUI_EndDialog(pMsg->hWin, 0);
           g_hActiveWin = CreateDialogPage();
	  
            //保存对话框内容
            DialogPageData.bmpType = BMP_ALARM;
            DialogPageData.confimButt = NO_CONFIM_BUTTON;
            DialogPageData.fun = ErrorInfo_CreateWindow;
            sprintf(buffer, "%s...", g_ucaLng_ClearError[MachInfo.systemSet.eLanguage]);
            strcpy(DialogPageData.str, buffer);
            
            pMsg->MsgId = WM_USER_DATA;
            pMsg->Data.p = &DialogPageData;
            WM_SendMessage(g_hActiveWin,pMsg);  
        }
        
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_RETURN: // Notifications sent by 'Return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = Analysis_Menu();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_ERRORINFO: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_ERRORINFO_LAST: // Notifications sent by 'last_one'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if(g_scErrorInfo_Index > 0)
        {
            g_scErrorInfo_Index--;
        }
        
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_ERRORINFO_NEXT: // Notifications sent by 'next_one'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if(MachRunPara.tLogin_SelfCheck.ucErrorNum > ERROR_INFO_LISTREWIEW_ROW_NUM)
        {  
            //错误数大于行数
            if(MachRunPara.tLogin_SelfCheck.ucErrorNum - g_scErrorInfo_Index > ERROR_INFO_LISTREWIEW_ROW_NUM)
            {
                //有错误数未显示在listreview上
                g_scErrorInfo_Index++;
            }
        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN ErrorInfo_CreateWindow(void);
WM_HWIN ErrorInfo_CreateWindow(void) {
  WM_HWIN hWin;

  WM_SetCallback(WM_HBKWIN, None_cbBkWin);
  Public_Show_Widget(); //显示公共部分控件
  Set_Cur_MenuID(GUI_ERRORINFO_ID);
	
	Disable_Algo_Task();
    
  //样本分析、列表回顾、菜单按键背景不为高亮状态
  Public_Reset_Btn_Status(BTN_END);
  hWin = GUI_CreateDialogBox(ErrorInfo_aDialogCreate, GUI_COUNTOF(ErrorInfo_aDialogCreate), ErrorInfo_cbDialog, WM_HBKWIN, 0, 0);
     
  WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
