/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   下一样本测试界面
*
*/
// USER END

#include "DIALOG.h"
#include "WM.h"
#include "GUI.h"
#include "LISTBOX.h"

//#include "Analysis_MenuDLG.h"
#include "file_operate.h"
#include "Public_menuDLG.h"
#include "Parameter.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

//bk color
//#define NEXT_SMAPLE_ALPHA_COLOR                 0x00525a4e              //背景颜色
//#define  NEXT_SMAPLE_ALPHA                      30                      //透明值
//title color
#define NEXT_SAMPLE_TITLE_COLOR                 0x00B4783D              //标题颜色
#define NEXT_SAMPLE_TITLE_BK_COLOR              0x00EEDFB2              //标题背景颜色
//button color
#define NEXT_SAMPLE_BTN_FRAME_COLOR             0X00BEBEBE              //按钮边框颜色
#define NEXT_SAMPLE_BTN_CHAR_COLOR              GUI_GRAY                //按钮松开颜色
// dropdown color
#define NEXT_SAMPLE_DROPDOWN_UNSEL_COLOR        GUI_BLACK               
#define NEXT_SAMPLE_DROPDOWN_SELFOCUS_COLOR     0x00EEDFB2
#define NEXT_SAMPLE_DROPDOWN_FRAME_INIT_COLOR   0X00a2a09e               //下拉边框初始化颜色
#define NEXT_SAMPLE_DROPDOWN_FRAME_CLICK_COLOR  0x00EEDFB2               //下拉边框点击颜色
//edit
#define NEXT_SAMPLE_EDIT_FRAME_COLOR            0X00BEBEBE               //文本边框颜色




//ID
#define ID_WINDOW_NEXT_SAMPLE       (GUI_WINDOW_NEXT_SAMPLE_ID + 0x00)
#define ID_TEXT_TITILE              (GUI_WINDOW_NEXT_SAMPLE_ID + 0x01)
#define ID_TEXT_NAME                (GUI_WINDOW_NEXT_SAMPLE_ID + 0x02)
#define ID_TEXT_AGE                 (GUI_WINDOW_NEXT_SAMPLE_ID + 0x03)
#define ID_TEXT_BIRTH_DAY           (GUI_WINDOW_NEXT_SAMPLE_ID + 0x04)
#define ID_TEXT_SEX                 (GUI_WINDOW_NEXT_SAMPLE_ID + 0x05)
#define ID_TEXT_SAMPLE_SN           (GUI_WINDOW_NEXT_SAMPLE_ID + 0x06)
#define ID_TEXT_REFER               (GUI_WINDOW_NEXT_SAMPLE_ID + 0x07)
#define ID_TEXT_REMARK              (GUI_WINDOW_NEXT_SAMPLE_ID + 0x08)
// 注意不要保持编号的先后顺序，有用到该编号的顺序
#define ID_EDIT_NAME                (GUI_WINDOW_NEXT_SAMPLE_ID + 0x09) //id with functioin, don't modify without think
#define ID_EDIT_AGE                 (GUI_WINDOW_NEXT_SAMPLE_ID + 0x0A)
#define ID_EDIT_SAMPLE_SN           (GUI_WINDOW_NEXT_SAMPLE_ID + 0x0B)
#define ID_DROPDOWN_SEX             (GUI_WINDOW_NEXT_SAMPLE_ID + 0x0C)
#define ID_DROPDOWN_AGE             (GUI_WINDOW_NEXT_SAMPLE_ID + 0x0D)
#define ID_DROPDOWN_REFER           (GUI_WINDOW_NEXT_SAMPLE_ID + 0x0E)
#define ID_EDIT_BIRTH_DAY           (GUI_WINDOW_NEXT_SAMPLE_ID + 0x0F)
#define ID_BUTTON_CANCEL            (GUI_WINDOW_NEXT_SAMPLE_ID + 0x10)
#define ID_BUTTON_SURE              (GUI_WINDOW_NEXT_SAMPLE_ID + 0x11)
#define ID_MULTIEDIT_REMARK         (GUI_WINDOW_NEXT_SAMPLE_ID + 0x12)




// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static char g_sNS_MoveFlag              = 0;    //0:未移动窗口； 1：已移动窗口
static uint8_t g_sAgeUnit_TrigleFlag    = 0;    //年龄单位触发标志， 1：有触发， 0：无触发
#define     NS_Y_MOVE_LEN   80                  //界面Y方向移动的距离
#define     NS_X_MOVE_LEN   0                   //X方向移动的距离

 

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/


static const GUI_WIDGET_CREATE_INFO NextSameple_aDialogCreate[] = {
  { WINDOW_CreateIndirect,      "NextSample",           ID_WINDOW_NEXT_SAMPLE,      80, 50, 640, 380, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",                     ID_TEXT_TITILE,             0, 0, 640, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect,        "",                     ID_TEXT_NAME,               42, 85, 40, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",                     ID_TEXT_AGE,                42, 135, 40, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",                     ID_TEXT_BIRTH_DAY,          12, 180, 80, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",                     ID_TEXT_SEX,                380, 135, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",                     ID_TEXT_REFER,              365, 85, 90, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",                     ID_TEXT_SAMPLE_SN,          350, 181, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",                     ID_TEXT_REMARK,             40, 230, 65, 20, 0, 0x0, 0 },
  //
  { EDIT_CreateIndirect,        "",                     ID_EDIT_NAME,               80, 80, 180, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect,        "",                     ID_EDIT_AGE,                80, 130, 120, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect,        "",                     ID_EDIT_SAMPLE_SN,          420, 175, 180, 30, 0, 0x64, 0 },
  { DROPDOWN_CreateIndirect,    "",                     ID_DROPDOWN_REFER,          420, 80, 180, 110, 0, 0x64, 0 },
  { DROPDOWN_CreateIndirect,    "",                     ID_DROPDOWN_SEX,            420, 130, 180, 60, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect,    "",                     ID_DROPDOWN_AGE,            200, 130, 40, 85, 0, 0x0, 0 },
  //
  { EDIT_CreateIndirect     ,   "",                     ID_EDIT_BIRTH_DAY,          80, 175, 180, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "",                     ID_BUTTON_CANCEL,           0, 340, 320, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "",                     ID_BUTTON_SURE,             320, 340, 320, 40, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect,   "",                     ID_MULTIEDIT_REMARK,        80, 230, 520, 80, 0, 0x0, 0 },
  

};




/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


/*
*  next sample  btn callback
*/
static void NextSample_Btn_Callback(WM_MESSAGE* pMsg)
{
    const unsigned char RoundRadius = 0; //显示区域圆角半径
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            if(ID_BUTTON_SURE == WM_GetId(pMsg->hWin))
            {
                //确定 
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_CANCEL == WM_GetId(pMsg->hWin)) {
                //取消
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }     
        }
        else {
           
            if(ID_BUTTON_SURE == WM_GetId(pMsg->hWin))
            {
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
                //确定  g_ucaLng_Sure[LANGUAGE_END]
                GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_CANCEL == WM_GetId(pMsg->hWin)) {
                //取消
                GUI_SetColor(BTN_RELEASE_GRAY);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(BTN_CHAR_COLOR);
                GUI_SetBkColor(BTN_RELEASE_GRAY);
                GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



/*
*   从ui获取下一样信息到ui结构体，前后端通过UI_Info结构体全局共享
*/
static ErrorCode_e Get_NextSample_Info(WM_MESSAGE* pMsg)
{  
    extern __IO MachRunPara_s	MachRunPara;
    WM_HWIN hItem;
    char buffer[REMARK_LEN] = { 0 };
    
    //name
    memset(buffer, 0, REMARK_LEN);
    memset((void*)MachRunPara.tNextSample.ucaName, 0, sizeof(MachRunPara.tNextSample.ucaName));
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_NAME);
    EDIT_GetText(hItem, buffer, PATIENT_NAME_LEN);
    strncpy((char*)MachRunPara.tNextSample.ucaName, buffer, PATIENT_NAME_LEN);

    //age
    memset(buffer, 0, REMARK_LEN);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE);
    EDIT_GetText(hItem, buffer, 4);
    MachRunPara.tNextSample.ucAge = atoi(buffer);
    //age unit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE);
    MachRunPara.tNextSample.eAgeUnit = (AgeUnit_e)DROPDOWN_GetSel(hItem);
    
    //sex 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
    MachRunPara.tNextSample.eSex = (SexType_e)DROPDOWN_GetSel(hItem);

    //birth day
    memset(buffer, 0, REMARK_LEN);
    memset((void*)MachRunPara.tNextSample.ucaBirthDay, 0, sizeof(MachRunPara.tNextSample.ucaBirthDay));
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY);
    EDIT_GetText(hItem, buffer, ID_EDIT_BIRTH_DAY);
    strncpy((char*)MachRunPara.tNextSample.ucaBirthDay, buffer, PATIENT_BIRTHE_DAY_MAX_LEN);
    
    // refer group 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
    MachRunPara.tNextSample.eReferGroup = DROPDOWN_GetSel(hItem);
    
    //remark
    memset(buffer, 0, REMARK_LEN);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_REMARK);
    MULTIEDIT_GetText(hItem, buffer, REMARK_LEN);
    strncpy((char*)MachRunPara.tNextSample.ucaRemark, buffer, REMARK_LEN);

    //
//    Print_NextSample(&MachRunPara.tNextSample);
    
    return ERROR_CODE_SUCCESS;
}



/*
* 初始化
*/
static void Next_Sample_Msg_Init(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    WM_HWIN hItem;
	char Str[60] = {0};
//    DROPDOWN_SKINFLEX_PROPS pProps;

    /*
    * Initialization of 'Name_text'
    */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TITILE);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, MachInfo.companyInfo.skin.titleFont);  
    TEXT_SetBkColor(hItem, MachInfo.companyInfo.skin.title);
	switch(MachInfo.companyInfo.company){
		case COMPANY_HY:
		{
			//和映
			sprintf(Str,"%s%s)",g_ucaLng_NextSampleDownloadInfo[MachInfo.systemSet.eLanguage],MachRunPara.tNextSample.patientID);
			TEXT_SetText(hItem, Str);
		}break;
		
		default :
		{
			TEXT_SetText(hItem, g_ucaLng_NextSample[MachInfo.systemSet.eLanguage]);
		}break;
	}

    // name text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_NAME);
    //姓名
    TEXT_SetText(hItem, g_ucaLng_Name[MachInfo.systemSet.eLanguage]);
    // name edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_NAME);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetMaxLen(hItem, PATIENT_NAME_LEN-1);
    EDIT_EnableBlink(hItem, 500, 1);
    EDIT_SetText(hItem, (char*)MachRunPara.tNextSample.ucaName);
    WM_SetCallback(hItem, Public_Edit_Callback);
    

    /*
    * Initialization of 'Age_Edit'
    */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetMaxLen(hItem, 3);
    EDIT_EnableBlink(hItem, 500, 1);
	memset(Str,0,60);
	sprintf(Str,"%u",MachRunPara.tNextSample.ucAge);
	EDIT_SetText(hItem,Str);
    WM_SetCallback(hItem, Public_Edit_Callback);
    //age text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_AGE);
    //年龄
    TEXT_SetText(hItem, g_ucaLng_Age[MachInfo.systemSet.eLanguage]);
    
    /*** 年龄下拉框 ***/
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE);
    WM_SetSize(hItem, 60, 30);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_UNSEL, DROPDOWN_UNSEL_COLOR);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SELFOCUS, DROPDOWN_SELFOCUS_COLOR);
    DROPDOWN_SetItemSpacing(hItem, DROPDOWN_SPACE_LEN);
    DROPDOWN_SetListHeight(hItem, 92);
    DROPDOWN_AddString(hItem, g_ucaLng_Year[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Month[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Week[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Day[MachInfo.systemSet.eLanguage]);
	switch(MachRunPara.tNextSample.eAgeUnit){
		case AGE_UNIT_YEAR:
			DROPDOWN_SetSel(hItem,0);
		break;
		case AGE_UNIT_MONTH:
			DROPDOWN_SetSel(hItem,1);
		break;
		case AGE_UNIT_WEEK:
			DROPDOWN_SetSel(hItem,2);
		break;
		case AGE_UNIT_DAY:
			DROPDOWN_SetSel(hItem,3);
		break;
		default :
			DROPDOWN_SetSel(hItem,0);
		break;
	}
    WM_SetCallback(hItem, Public_Dropdown_Callback);

    /*
    * Initialization of 'Sex'
    */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SEX);
    //性别
    TEXT_SetText(hItem, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage]);
    /*** 性别下拉框 ***/
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
    WM_SetSize(hItem, 180, 30);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_UNSEL, DROPDOWN_UNSEL_COLOR);
    //DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SEL, GUI_BLUE);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SELFOCUS, DROPDOWN_SELFOCUS_COLOR);
    //设置元素之间的间距
    DROPDOWN_SetItemSpacing(hItem, DROPDOWN_SPACE_LEN);
    // 空 男 女
    DROPDOWN_AddString(hItem, " ");//空
    DROPDOWN_AddString(hItem, g_ucaLng_SexMale[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_SexFemale[MachInfo.systemSet.eLanguage]);
	switch(MachRunPara.tNextSample.eSex){
		case SEX_TYPE_NONE:
			DROPDOWN_SetSel(hItem,0);
		break;
		case SEX_TYPE_MALE:
			DROPDOWN_SetSel(hItem,1);
		break;
		case SEX_TYPE_FEMALE:
			DROPDOWN_SetSel(hItem,2);
		break;
		default :
			DROPDOWN_SetSel(hItem,0);
		break;
	}
    WM_SetCallback(hItem, Public_Dropdown_Callback);

    /*
    * Initialization of 'SampleSN_Edit'
    */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SAMPLE_SN);
    //样本编号
    TEXT_SetText(hItem, g_ucaLng_SampleNum[MachInfo.systemSet.eLanguage]);
    //样本编号
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_SAMPLE_SN);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetText(hItem, (char*)MachRunPara.tNextSample.ucaNextSampleSN);
    WM_SetCallback(hItem, Public_Edit_Callback);
    WM_DisableWindow(hItem);
    /*
    * Initialization of 'Refer'
    */
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_REFER);
    //参考组
    TEXT_SetText(hItem, g_ucaLng_ReferGroup[MachInfo.systemSet.eLanguage]);
    /*** 参考组下拉框 ***/
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
    WM_SetSize(hItem, 180, 30);

    //set color
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_UNSEL, DROPDOWN_UNSEL_COLOR);
    //DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SEL, DROPDOWN_SELFOCUS_COLOR);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SELFOCUS, DROPDOWN_SELFOCUS_COLOR);
    //
    //设置元素之间的间距
    DROPDOWN_SetItemSpacing(hItem, DROPDOWN_SPACE_LEN);
    // 通用 成男 成女 小孩 新生儿
    DROPDOWN_AddString(hItem, g_ucaLng_General[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_AdultMale[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_AdultFemale[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Child[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Neonatus[MachInfo.systemSet.eLanguage]);
	switch(MachRunPara.tNextSample.eReferGroup){
		case REFER_GROUP_CMOMMON:
			DROPDOWN_SetSel(hItem,0);
		break;
		case REFER_GROUP_MALE:
			DROPDOWN_SetSel(hItem,1);
		break;
		case REFER_GROUP_FEMALE:
			DROPDOWN_SetSel(hItem,2);
		break;
		case REFER_GROUP_CHILDREN:
			DROPDOWN_SetSel(hItem,3);
		break;
		case REFER_GROUP_BOBY:
			DROPDOWN_SetSel(hItem,4);
		break;
		
		default :
			DROPDOWN_SetSel(hItem,0);
		break;
	}
    WM_SetCallback(hItem, Public_Dropdown_Callback);


    // Remark Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_REMARK);
    //备注
    TEXT_SetText(hItem,  g_ucaLng_ReMark[MachInfo.systemSet.eLanguage]);
    //multiEdit  remark
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_REMARK);
    MULTIEDIT_SetTextAlign(hItem, GUI_TA_LEFT);
    MULTIEDIT_SetFont(hItem, &HZ_SONGTI_16);
    MULTIEDIT_SetMaxLen(hItem, REMARK_LEN);
    MULTIEDIT_SetText(hItem, "");

    //button cansel  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
    WM_SetCallback(hItem, NextSample_Btn_Callback);
    //BUTTON_SetText(hItem, "取消");

    //button  sure
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SURE);
    WM_SetCallback(hItem, NextSample_Btn_Callback);
    //BUTTON_SetText(hItem, "确定");

    /*
    * Initialization of ' '
    */
    //出生年月
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BIRTH_DAY);
    TEXT_SetText(hItem, g_ucaLng_BirthDay[MachInfo.systemSet.eLanguage]);
    // Birth Day
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY);
    EDIT_SetMaxLen(hItem, PATIENT_BIRTHE_DAY_MAX_LEN);
    WM_SetCallback(hItem, Public_Edit_Callback);
    
    //当为英文时，需要微调显示位置
    if(LANGUAGE_ENGLISH == MachInfo.systemSet.eLanguage)
    {
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_REFER);
        WM_MoveWindow(hItem, -38, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_AGE);
        WM_MoveWindow(hItem, 8, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SEX);
        WM_MoveWindow(hItem, -15, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BIRTH_DAY);
        WM_MoveWindow(hItem, -3, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SAMPLE_SN);
        WM_MoveWindow(hItem, -12, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_REMARK);
        WM_MoveWindow(hItem, -14, 0);
    }
    
    //界面移动标志位
    g_sNS_MoveFlag = 0;
}







/*
*   刷新
*/
static void Next_Sample_Msg_Update(WM_MESSAGE* pMsg)
{  
    extern __IO MachRunPara_s	MachRunPara;
    WM_HWIN hItem;
    char buffer[REMARK_LEN] = { 0 };
    
    //name
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_NAME);
    EDIT_SetText(hItem, (char*)MachRunPara.tNextSample.ucaName);

    //age
    memset(buffer, 0, REMARK_LEN);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE);
    if(MachRunPara.tNextSample.ucAge != 0)
    {
        sprintf(buffer, "%d", MachRunPara.tNextSample.ucAge);
        EDIT_SetText(hItem, buffer);
    }else{
        EDIT_SetText(hItem, "");
    }
    
    //age unit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE);
    DROPDOWN_SetSel(hItem, MachRunPara.tNextSample.eAgeUnit);
 
    //sex 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
    DROPDOWN_SetSel(hItem, MachRunPara.tNextSample.eSex);    

    //birth day
    memset(buffer, 0, REMARK_LEN);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY);
    EDIT_SetText(hItem, (char*)MachRunPara.tNextSample.ucaBirthDay);

    // refer group 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
    DROPDOWN_SetSel(hItem, MachRunPara.tNextSample.eReferGroup);   
    
    //remark
    memset(buffer, 0, REMARK_LEN);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_REMARK);
    MULTIEDIT_SetText(hItem, (char*)MachRunPara.tNextSample.ucaRemark);

}




// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void Next_Sameple_cbDialog(WM_MESSAGE* pMsg) {
    
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    int     i = 0;
    // USER START (Optionally insert additional variables)
	static uint8_t TimerCreateFlag = 0;				//标志定时器是否已经创建的标志，为1表示已经创建，为0表示尚未创建
    // USER END

    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
    {
        Next_Sample_Msg_Init(pMsg);
    }
    break;
    case WM_NEXT_SAMPLE_UPDATE:
    {
        Next_Sample_Msg_Update(pMsg);
    }
    break;
    case WM_KEYBOARD_UPDATE: 
    {
        char buffer[PATIENT_NAME_LEN] = {0};
        uint8_t ucAge = 0;
        /***** 键盘输入交互信息处理 *****/    
        hItem = WM_GetFocusedWindow();
        Id = WM_GetId(hItem);
        
        //
        i = strlen(pMsg->Data.p);
        if(i == 1) //ASCII码
        {
            char c = *((char*)pMsg->Data.p);
            //输入字符到当前聚焦控件
            if(hItem)
            {
                //
                if(ID_EDIT_NAME == Id){ //Name
                    if((c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '.')
                    {
                        EDIT_GetText(hItem, buffer, PATIENT_NAME_LEN);
                        if(PATIENT_NAME_LEN - strlen(buffer) > 1) 
                        {
                            GUI_StoreKeyMsg(c, 1);
                        }
                    }
                }else if(ID_EDIT_AGE == Id) //年龄必须是数字
                {
                    if(c >= '0' && c <= '9')
                    {
                        //输入字符到聚焦控件
                        EDIT_GetText(hItem, buffer, 10);
                        ucAge = atoi(buffer);
                        if(ucAge <= 14) //小于150岁
                            GUI_StoreKeyMsg(c, 1);
                        break;
                    }
                }else if(ID_EDIT_BIRTH_DAY == Id){
                    //输入字符到聚焦控件
                     GUI_StoreKeyMsg(c, 1); 
                     break;
                }else if(ID_MULTIEDIT_REMARK == Id){
                    //输入字符到聚焦控件
                    if(MULTIEDIT_GetTextSize(hItem)+1 < REMARK_LEN)
                    {
                        MULTIEDIT_AddText(hItem, pMsg->Data.p);
                    }
                }
            }
        }else if(i == 3){ //一个汉字的UTF-8编码长度,3字节，以下是同时具有有中文输入功能的控件
            //hItem = WM_GetFocusedWindow();
            if(hItem)
            {
                if(ID_MULTIEDIT_REMARK == Id)  //Remark
                {
                    if(MULTIEDIT_GetTextSize(hItem)+3 < REMARK_LEN)
                    {
                        MULTIEDIT_AddText(hItem, pMsg->Data.p);
                    }
                }else if(ID_EDIT_NAME == Id){ //Name
                    uint16_t usTotalNum = 0, usPrevious = 0;
                    
                    memset(buffer, 0, PATIENT_NAME_LEN);
                    usTotalNum = EDIT_GetNumChars(hItem);
                    usPrevious = EDIT_GetCursorCharPos(hItem);

                    EDIT_GetText(hItem, buffer, PATIENT_NAME_LEN);
                    if(PATIENT_NAME_LEN - strlen(buffer) > 3) 
                    {
                        if(usTotalNum != usPrevious)
                        {
                            char acLastBuffer[PATIENT_NAME_LEN] = {0}, acNextBuffer[PATIENT_NAME_LEN] = {0}, i = 0, j = 0, ucCharNum = 0;
                            //上半段字符
                            for(ucCharNum = 0, i = 0; ucCharNum < usPrevious; ucCharNum++)
                            {
                                if(buffer[i] > 0x7E)
                                {
                                    acLastBuffer[i] = buffer[i]; i++;
                                    acLastBuffer[i] = buffer[i]; i++;
                                    acLastBuffer[i] = buffer[i]; i++;
                                }else{
                                    acLastBuffer[i] = buffer[i]; i++;
                                }
                            }
                            //下半段字符
                            for(; ucCharNum < usTotalNum; ucCharNum++)
                            {
                                if(buffer[i] > 0x7E)
                                {
                                    acNextBuffer[j] = buffer[i]; j++; i++;
                                    acNextBuffer[j] = buffer[i]; j++; i++;
                                    acNextBuffer[j] = buffer[i]; j++; i++;
                                }else{
                                    acNextBuffer[j] = buffer[i]; j++; i++;
                                }
                            }
                            //黏贴三段
                            strcat(acLastBuffer, pMsg->Data.p);
                            strcat(acLastBuffer, acNextBuffer); 
                            EDIT_SetText(hItem, acLastBuffer); //
                        }else{
                            //最大长度的限制
                            strcat(buffer, pMsg->Data.p);
                            EDIT_SetText(hItem, buffer); //
                        }
                        
                    }                                  
                }              
            }
        }else{
            LOG_Error("Msg Len(%d) Error", i);
        }
    }
    break;
    case WM_KEYBOARD_END: 
    {
       //
       if(g_sNS_MoveFlag == 1)
       {
           WM_MoveTo(pMsg->hWin, 80, 50);
           g_sNS_MoveFlag = 0;
       }
        
        
    }
    break;
    case WM_DELETE:
    {
        g_sNS_MoveFlag = 0;
        g_sAgeUnit_TrigleFlag = 0;
        //
		
		//重置定时器标志
		TimerCreateFlag = 0;
    }
    break;
	
	//窗口定时器消息
	case WM_TIMER:
	{
		if(DROPDOWN_GetListbox(WM_GetDialogItem(pMsg->hWin,ID_DROPDOWN_AGE)) != 0){
			//重启计时器
			WM_RestartTimer(pMsg->Data.v,500);
		}else{
			TimerCreateFlag = 0;
			
			WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_EDIT_BIRTH_DAY));
			WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_MULTIEDIT_REMARK));
		}
	}break;
	
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_MULTIEDIT_REMARK: // Notifications sent by 'Remark_Multiedit'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
            {
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
            }
            break;
            case WM_NOTIFICATION_RELEASED:
            {
                // USER START (Optionally insert code for reacting on notification message)
                WM_SetFocus(pMsg->hWinSrc);
                
                AgeUnit_e eAgeUnit; 
                eAgeUnit = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE));
                if(!(1 == g_sAgeUnit_TrigleFlag && AGE_UNIT_DAY == eAgeUnit))
                {
                    //需移动窗口
                    if(g_sNS_MoveFlag == 0)
                    {
                        WM_MoveWindow(pMsg->hWin, NS_X_MOVE_LEN, -NS_Y_MOVE_LEN+20);
                        g_sNS_MoveFlag = 1;
                    }
                    
                    //打开键盘
					MachRunPara.keyboardInitJM = KEYBOARD_HZ;
                    CreateKeyboard_Window();
                }
                g_sAgeUnit_TrigleFlag = 0;
            }
            break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_EDIT_NAME: // Notifications sent by 'Name_Edit'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
            {
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
            }
            break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                
                //
                if (ERROR_CODE_SUCCESS != Get_NextSample_Info(pMsg))
                {
                    LOG_Error("Error");
                }
                
                WM_SetFocus(pMsg->hWinSrc);
                
                //打开键盘
				MachRunPara.keyboardInitJM = KEYBOARD_HZ;
                CreateKeyboard_Window();
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_EDIT_AGE: // Notifications sent by 'Age_Edit'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
          
                //获取当前已输入的信息，防止被刷新后，丢弃
                if (ERROR_CODE_SUCCESS != Get_NextSample_Info(pMsg))
                {
                    LOG_Error("");
                }
                
                WM_SetFocus(pMsg->hWinSrc);
                
                //打开键盘
				MachRunPara.keyboardInitJM = KEYBOARD_NUM;
                CreateKeyboard_Window();
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
			{
				//输入年龄,同步更新出生日期
				uint32_t ulCurDays = 0, ulDiffDays = 0, ulDstDays = 0;
				uint16_t usAge = 0, usYear = 0, usMonth = 0, usDay = 0;
				uint8_t ucAgeUnit = 0;
				char buffer[5] = {0};
				RTC_HYM8563Info_s RTCInfo = {0};
				
				//input age
				EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE), buffer, 5);
				usAge = atoi(buffer);
				MachRunPara.tNextSample.ucAge = usAge;
				//age unit
				ucAgeUnit = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE));
				
				//current date time
				RTC_HYM8563GetTime(&RTCInfo);
				usYear = 2000 + RTCInfo.year.bcd_h*10 + RTCInfo.year.bcd_l;
				usMonth = RTCInfo.month.bcd_h*10 + RTCInfo.month.bcd_l;
				usDay  = RTCInfo.day.bcd_h*10 + RTCInfo.day.bcd_l;
				ulCurDays = usYear*365+usMonth*30+usDay;
				
				//时间转换计算
				if(usAge > 0)
				{
					switch(ucAgeUnit)
					{
						case AGE_UNIT_DAY:
						{
							ulDiffDays = MachRunPara.tNextSample.ucAge;
						}
						break;
						case AGE_UNIT_WEEK:
						{
							ulDiffDays = MachRunPara.tNextSample.ucAge*7;
						}
						break;
						case AGE_UNIT_MONTH:
						{
							ulDiffDays = MachRunPara.tNextSample.ucAge*30;
						}
						break;
						case AGE_UNIT_YEAR:
						{
							ulDiffDays = MachRunPara.tNextSample.ucAge*365;
						}
						break;
						default:break;
					}
					//
					ulDstDays = ulCurDays - ulDiffDays;
					if(ulDstDays > 0)
					{
						usYear  = ulDstDays/365;                   
						//
						usMonth = ulDstDays%365/30; 
						if(usMonth == 0) usMonth = 1;
						//
						usDay   = ulDstDays%30;
						if(usDay == 0) usDay = 1;
						
						memset((void*)MachRunPara.tNextSample.ucaBirthDay, 0, sizeof(MachRunPara.tNextSample.ucaBirthDay));
						sprintf((char*)MachRunPara.tNextSample.ucaBirthDay, "%d/%d/%d", usYear, usMonth, usDay);
						//
						EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY), (char*)MachRunPara.tNextSample.ucaBirthDay);
					}
				}else{
					EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY), "");
				}
				
				//更新参考组
				//自动匹配参考组
				MachRunPara.tNextSample.eReferGroup = AgeToRefGroup(MachRunPara.tNextSample.ucAge,MachRunPara.tNextSample.eAgeUnit,MachRunPara.tNextSample.eSex);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
				switch(MachRunPara.tNextSample.eReferGroup){
					case REFER_GROUP_CMOMMON:
						DROPDOWN_SetSel(hItem,0);
					break;
					case REFER_GROUP_MALE:
						DROPDOWN_SetSel(hItem,1);
					break;
					case REFER_GROUP_FEMALE:
						DROPDOWN_SetSel(hItem,2);
					break;
					case REFER_GROUP_CHILDREN:
						DROPDOWN_SetSel(hItem,3);
					break;
					case REFER_GROUP_BOBY:
						DROPDOWN_SetSel(hItem,4);
					break;
					
					default :
						DROPDOWN_SetSel(hItem,0);
					break;
				}
			}
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_EDIT_SAMPLE_SN: // Notifications sent by 'SampleSN_Edit'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_DROPDOWN_SEX: // Notifications sent by 'Sex_Dropdown'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
				MachRunPara.tNextSample.eSex = DROPDOWN_GetSel(hItem);
			
				//更新参考组
				//自动匹配参考组
				MachRunPara.tNextSample.eReferGroup = AgeToRefGroup(MachRunPara.tNextSample.ucAge,MachRunPara.tNextSample.eAgeUnit,MachRunPara.tNextSample.eSex);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
				switch(MachRunPara.tNextSample.eReferGroup){
					case REFER_GROUP_CMOMMON:
						DROPDOWN_SetSel(hItem,0);
					break;
					case REFER_GROUP_MALE:
						DROPDOWN_SetSel(hItem,1);
					break;
					case REFER_GROUP_FEMALE:
						DROPDOWN_SetSel(hItem,2);
					break;
					case REFER_GROUP_CHILDREN:
						DROPDOWN_SetSel(hItem,3);
					break;
					case REFER_GROUP_BOBY:
						DROPDOWN_SetSel(hItem,4);
					break;
					
					default :
						DROPDOWN_SetSel(hItem,0);
					break;
				}
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_DROPDOWN_AGE: // Notifications sent by 'Age_Dropdown'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                //该控件有触发
                g_sAgeUnit_TrigleFlag = 1;
//                WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY));
                //WM_ReleaseCapture(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY));
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				//创建定时器，监测下拉框是否已经收起状态
				if(TimerCreateFlag == 0){
					TimerCreateFlag = 1;
					
					//创建窗口定时器,500ms触发一次
					WM_CreateTimer(pMsg->hWin,0,500,0);
					
					WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_EDIT_BIRTH_DAY));
					WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_MULTIEDIT_REMARK));
				}
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
            {
                //uint32_t ulTotalDay = 0;
				if(MachRunPara.tNextSample.ucAge != 0){
					uint16_t usYear = 0, usMonth, usDay = 0;
					uint8_t ucAgeUnit = 0;
					uint32_t ulCurDays = 0, ulDstDays = 0, ulDiffDays = 0;
					RTC_HYM8563Info_s RTCInfo = {0};
					
					//age unit
					ucAgeUnit = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE));
					// current date time
					RTC_HYM8563GetTime(&RTCInfo);
					usYear = (2000 + RTCInfo.year.bcd_h*10 + RTCInfo.year.bcd_l);
					usMonth = RTCInfo.month.bcd_h*10 + RTCInfo.month.bcd_l;
					usDay  = RTCInfo.day.bcd_h*10 + RTCInfo.day.bcd_l;
					ulCurDays = usYear*365+usMonth*30+usDay;
					//
					switch(ucAgeUnit)
					{
						case AGE_UNIT_DAY:
						{
							ulDiffDays = MachRunPara.tNextSample.ucAge;
						}
						break;
						case AGE_UNIT_WEEK:
						{
							ulDiffDays = MachRunPara.tNextSample.ucAge*7;
						}
						break;
						case AGE_UNIT_MONTH:
						{
							ulDiffDays = MachRunPara.tNextSample.ucAge*30;
						}
						break;
						case AGE_UNIT_YEAR:
						{
							ulDiffDays = MachRunPara.tNextSample.ucAge*365;
						}
						break;
						default:break;
					}
					//
					ulDstDays = ulCurDays - ulDiffDays;
					
					if(ulDstDays > 0)
					{
						usYear  = ulDstDays/365;
						//
						usMonth = ulDstDays%365/30; 
						if(usMonth == 0) usMonth = 1;
						//
						usDay   = ulDstDays%30;
						if(usDay == 0) usDay = 1;
						//
						memset((void*)MachRunPara.tNextSample.ucaBirthDay, 0, sizeof(MachRunPara.tNextSample.ucaBirthDay));
						sprintf((char*)MachRunPara.tNextSample.ucaBirthDay, "%d/%d/%d", usYear, usMonth, usDay);
						//
						EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY), (char*)MachRunPara.tNextSample.ucaBirthDay);
					}
				}else{
					EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY), "");
				}
				
				//更新参考组
				//自动匹配参考组
				MachRunPara.tNextSample.eReferGroup = AgeToRefGroup(MachRunPara.tNextSample.ucAge,MachRunPara.tNextSample.eAgeUnit,MachRunPara.tNextSample.eSex);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
				switch(MachRunPara.tNextSample.eReferGroup){
					case REFER_GROUP_CMOMMON:
						DROPDOWN_SetSel(hItem,0);
					break;
					case REFER_GROUP_MALE:
						DROPDOWN_SetSel(hItem,1);
					break;
					case REFER_GROUP_FEMALE:
						DROPDOWN_SetSel(hItem,2);
					break;
					case REFER_GROUP_CHILDREN:
						DROPDOWN_SetSel(hItem,3);
					break;
					case REFER_GROUP_BOBY:
						DROPDOWN_SetSel(hItem,4);
					break;
					
					default :
						DROPDOWN_SetSel(hItem,0);
					break;
				}
            }
            break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_DROPDOWN_REFER: // Notifications sent by 'Refer_Dropdown'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
            {
                uint8_t ucIndex = 0;
                // USER START (Optionally insert code for reacting on notification message)
                hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
                ucIndex = DROPDOWN_GetSel(hItem);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
                if(ucIndex == REFER_GROUP_MALE)
                {
                    //参考组成年男士 --》修改性别为男
                    DROPDOWN_SetSel(hItem, SEX_TYPE_MALE);

                }else if(ucIndex == REFER_GROUP_FEMALE){
                    //参考组成年女士 --》修改性别为女
                     DROPDOWN_SetSel(hItem, SEX_TYPE_FEMALE);
                }
                // USER END
            }
            break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_CANCEL: // Notifications sent by 'Cansel_Button'
            switch (NCode) {
                case WM_NOTIFICATION_CLICKED:
                    // USER START (Optionally insert code for reacting on notification message)

                    // USER END
                    break;
                case WM_NOTIFICATION_RELEASED:
                {
                    GUI_EndDialog(pMsg->hWin, 0);
                    g_hActiveWin = Analysis_Menu();
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_SURE: // Notifications sent by 'Sure_Button'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)

                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {
                    if (ERROR_CODE_SUCCESS == Get_NextSample_Info(pMsg))
                    {
						Msg_Head_t tMsgHead = {0};

						//下一样本信息标志有效化
						MachRunPara.tNextSample.validFlag = 1;

						//出仓
						tMsgHead.usCmd = CMD_OTHERS_OUTIN_OUT;
						UI_Put_Msg((uint8_t*)&tMsgHead);                    

						GUI_EndDialog(pMsg->hWin, 0);
						GUI_Exec();
						
						g_hActiveWin = WM_HBKWIN;
						WM_SetCallback(WM_HBKWIN, GIF_Guide_cbBkWin);
						//
						//发送消息给HBKWIN，显示放入血细胞检测模块动画
						WM_SendMessageNoPara(g_hActiveWin, WM_INPUT_GUIDE_GIF);   
                    }else {
                        //@todo 
                    }

                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            case ID_EDIT_BIRTH_DAY: // Notifications sent by 'Edit Birth Day'
                switch (NCode) {
                case WM_NOTIFICATION_CLICKED:
                    // USER START (Optionally insert code for reacting on notification message)
                    // USER END
                    break;
                case WM_NOTIFICATION_RELEASED:
                {
                    // USER START (Optionally insert code for reacting on notification message)                
                    AgeUnit_e eAgeUnit; 
                    eAgeUnit = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE));
                    if(!(1 == g_sAgeUnit_TrigleFlag && AGE_UNIT_MONTH == eAgeUnit))
                    {
                        //获取当前已输入的信息，防止被刷新后，丢弃
                        if (ERROR_CODE_SUCCESS != Get_NextSample_Info(pMsg))
                        {
                            LOG_Error("");
                        }
                    
                        GUI_EndDialog(pMsg->hWin, 0);
                        g_hActiveWin = CreatedataTimeSetPage();
                      
                        pMsg->MsgId = WM_USER_DATA;
                        pMsg->Data.v = 2;
                        WM_SendMessage(g_hActiveWin,pMsg);
                    }
                    //恢复
                    g_sAgeUnit_TrigleFlag = 0;
                }
                break;

            // USER START (Optionally insert additional code for further Ids)
            // USER END
            }
        }
        break;
        // USER START (Optionally insert additional message handling)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}



WM_HWIN CreateNextSample_Window(void);
WM_HWIN CreateNextSample_Window(void) {
    WM_HWIN hWin;
    
    //GUI_Clear();
    Public_Hide_Widget(); //隐藏公共部分控件
    WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin);   
    Set_Cur_MenuID(GUI_WINDOW_NEXT_SAMPLE_ID);
	
	Disable_Algo_Task();

    hWin = GUI_CreateDialogBox(NextSameple_aDialogCreate, GUI_COUNTOF(NextSameple_aDialogCreate), Next_Sameple_cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
