/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   病人信息界面
*
*/
// USER END

#include "DIALOG.h"
#include "WM.h"
#include "GUI.h"
#include "LISTBOX.h"


#include "cx_menu.h"
#include "Public_menuDLG.h"
#include "cmsis_os2.h"
#include "bsp_motor.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

//bk color
#define  PATIENT_INFO_ALPHA_COLOR                0x00525a4e              //背景颜色
#define  PATIENT_INFO_ALPHA                      30                      //透明值
//title color
#define PATIENT_INFO_TITLE_COLOR                 0x00B4783D              //标题颜色
#define PATIENT_INFO_TITLE_BK_COLOR              0x00EEDFB2              //标题背景颜色
//button color
#define PATIENT_INFO_BTN_PRESS_COLOR             0x00EEDFB2              //按钮按下颜色
#define PATIENT_INFO_BTN_RELEASE_COLOR           GUI_WHITE               //按钮松开颜色
#define PATIENT_INFO_BTN_FRAME_COLOR             0X00BEBEBE              //按钮边框颜色
#define PATIENT_INFO_BTN_CHAR_COLOR              GUI_GRAY                //按钮松开颜色
// dropdown color
#define PATIENT_INFO_DROPDOWN_UNSEL_COLOR        GUI_BLACK               
#define PATIENT_INFO_DROPDOWN_SELFOCUS_COLOR     0x00EEDFB2
//edit
#define PATIENT_INFO_EDIT_FRAME_COLOR            0X00BEBEBE               //文本边框颜色
// dropdown
#define PATIENT_INFO_DROPDOWN_FRAME_INIT_COLOR   0X00BEBEBE               //下拉边框初始化颜色
#define PATIENT_INFO_DROPDOWN_FRAME_CLICK_COLOR  0x00EEDFB2               //下拉边框点击颜色


//
//#define WM_BIRTH_DAY_EDIT_ENABLE    (WM_PATIENT_INFO_UPDATE+1)


//ID
#define ID_WINDOW_PATIENT_INFO      (GUI_PATIENT_INFO_ID + 0x00)
#define ID_TEXT_TITILE              (GUI_PATIENT_INFO_ID + 0x01)
#define ID_TEXT_NAME                (GUI_PATIENT_INFO_ID + 0x02)
#define ID_TEXT_AGE                 (GUI_PATIENT_INFO_ID + 0x03)
#define ID_TEXT_BIRTH_DAY           (GUI_PATIENT_INFO_ID + 0x04)
#define ID_TEXT_SEX                 (GUI_PATIENT_INFO_ID + 0x05)
#define ID_TEXT_SAMPLE_SN           (GUI_PATIENT_INFO_ID + 0x06)
#define ID_TEXT_REFER               (GUI_PATIENT_INFO_ID + 0x07)
#define ID_TEXT_REMARK              (GUI_PATIENT_INFO_ID + 0x08)
#define ID_TEXT_OPERATOR            (GUI_PATIENT_INFO_ID + 0x09) //
#define ID_TEXT_CHECK_DATE_TIME     (GUI_PATIENT_INFO_ID + 0x0A) //
// 注意不要保持编号的先后顺序，有用到该编号的顺序
#define ID_EDIT_NAME                (GUI_PATIENT_INFO_ID + 0x0B)
#define ID_EDIT_AGE                 (GUI_PATIENT_INFO_ID + 0x0C)
#define ID_EDIT_SAMPLE_SN           (GUI_PATIENT_INFO_ID + 0x0D)
#define ID_DROPDOWN_SEX             (GUI_PATIENT_INFO_ID + 0x0E)
#define ID_DROPDOWN_AGE             (GUI_PATIENT_INFO_ID + 0x0F)
#define ID_DROPDOWN_REFER           (GUI_PATIENT_INFO_ID + 0x10)
#define ID_EDIT_BIRTH_DAY		    (GUI_PATIENT_INFO_ID + 0x11) //
#define ID_BUTTON_PATIENT_CANCEL    (GUI_PATIENT_INFO_ID + 0x12)
#define ID_BUTTON_PATIENT_SURE      (GUI_PATIENT_INFO_ID + 0x13)
#define ID_EDIT_OPERATOR            (GUI_PATIENT_INFO_ID + 0x14) //
#define ID_EDIT_CHECK_DATE_TIME     (GUI_PATIENT_INFO_ID + 0x15) //
#define ID_MULTIEDIT_REMARK         (GUI_PATIENT_INFO_ID + 0x16)









// USER START (Optionally insert additional static data)
static char g_sPI_MoveFlag              = 0;    //0:未移动窗口； 1：已移动窗口
static uint8_t g_sAgeUnit_TrigleFlag    = 0;    //年龄单位触发标志， 1：有触发， 0：无触发
#define     PI_Y_MOVE_LEN   100                 //界面Y方向移动的距离
#define     PI_X_MOVE_LEN   0                   //X方向移动的距离

//病人信息
__IO Patient_Info_t g_tPatinet_Info = {0};

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO Patient_Info_aDialogCreate[] = {
  { WINDOW_CreateIndirect,      "",     ID_WINDOW_PATIENT_INFO,     80, 50, 640, 380, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_TITILE,             0, 0, 640, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_NAME,               42, 55, 40, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_AGE,                42, 105, 40, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_OPERATOR,           25, 205, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_BIRTH_DAY,          10, 155, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_SEX,                375, 55, 50, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_SAMPLE_SN,          352, 155, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_REFER,              365, 105, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "",     ID_TEXT_CHECK_DATE_TIME,    350, 205, 100, 40, 0, 0x0, 0 },
  
  { TEXT_CreateIndirect,        "",     ID_TEXT_REMARK,             38, 250, 65, 20, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect,   "",     ID_MULTIEDIT_REMARK,        80, 250, 520, 80, 0, 0x0, 0 },
  { EDIT_CreateIndirect,        "",     ID_EDIT_NAME,               80, 50, 180, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect,        "",     ID_EDIT_AGE,                80, 100, 120, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect,        "",     ID_EDIT_SAMPLE_SN,          420, 150, 180, 30, 0, 0x10, 0 },
  { EDIT_CreateIndirect,        "",     ID_EDIT_CHECK_DATE_TIME,    420, 200, 180, 30, 0, 0x64, 0 }, 
  { EDIT_CreateIndirect,        "",     ID_EDIT_OPERATOR,           80, 200, 180, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect,        "",     ID_EDIT_BIRTH_DAY,          80, 150, 180, 30, 0, 0x64, 0 },
  { DROPDOWN_CreateIndirect,    "",     ID_DROPDOWN_SEX,            420, 50, 180, 60, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect,    "",     ID_DROPDOWN_AGE,            200, 100, 40, 70, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect,    "",     ID_DROPDOWN_REFER,          420, 100, 180, 30, 0, 0x64, 0 },
  { BUTTON_CreateIndirect,      "",     ID_BUTTON_PATIENT_CANCEL,   0, 340, 320, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "",     ID_BUTTON_PATIENT_SURE,     320, 340, 320, 40, 0, 0x0, 0 },


  // USER START (Optionally insert additional widgets)
  // USER END
};



/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*
*   初始化病人信息
*/
void Patient_Info_Init(void)
{
    memset((void*)&g_tPatinet_Info, 0, sizeof(Patient_Info_t));
    g_tPatinet_Info.ulCurDataIndex = INVALID_DATA_SN;
}



/*
*  next sample  btn callback
*/
static void Patient_Info_Btn_Callback(WM_MESSAGE* pMsg)
{
    const unsigned char RoundRadius = 0; //显示区域圆角半径
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            if(ID_BUTTON_PATIENT_SURE == WM_GetId(pMsg->hWin))
            {
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_PATIENT_CANCEL == WM_GetId(pMsg->hWin)) {
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }   
        }
        else {
            if (ID_BUTTON_PATIENT_SURE == WM_GetId(pMsg->hWin))
            {
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
                GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_PATIENT_CANCEL == WM_GetId(pMsg->hWin)) {
                GUI_SetColor(GUI_LIGHTGRAY);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(BTN_CHAR_COLOR);
                GUI_SetBkColor(GUI_LIGHTGRAY);
                GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}






/*
*   病人信息界面样式、数据初始化
*/
static void Patient_Info_Msg_Init(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    extern uint8_t g_ucListView_DataIndex;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
    
    WM_HWIN hItem;
    //int i = 0;
//    char buffer[REMARK_LEN] = {0};

    //病人信息
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TITILE);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, MachInfo.companyInfo.skin.titleFont);  
    TEXT_SetBkColor(hItem,MachInfo.companyInfo.skin.title);
	switch(MachInfo.companyInfo.company){
		case COMPANY_HY:
		{
			//和映
			char Str[60] = {0};
			sprintf(Str,"%s%s)",g_ucaLng_PatientInfoDownloadInfo[MachInfo.systemSet.eLanguage],MachRunPara.tNextSample.patientID);
			TEXT_SetText(hItem, Str);
		}break;
		
		default :
		{
			TEXT_SetText(hItem, g_ucaLng_PatientInfo[MachInfo.systemSet.eLanguage]);
		}break;
	}

    //姓名Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_NAME);
    TEXT_SetText(hItem, g_ucaLng_Name[MachInfo.systemSet.eLanguage]);
    //姓名edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_NAME);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetMaxLen(hItem, PATIENT_NAME_LEN-1);
    EDIT_EnableBlink(hItem, 500, 1);
    WM_SetCallback(hItem, Public_Edit_Callback);
    

    /*
    * Initialization of 'Age_Edit'
    */
    //年龄 Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_AGE);
    TEXT_SetText(hItem, g_ucaLng_Age[MachInfo.systemSet.eLanguage]);
    //年龄 Edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetMaxLen(hItem, 3);
    EDIT_EnableBlink(hItem, 500, 1);
    WM_SetCallback(hItem, Public_Edit_Callback);
    //年龄 Dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE);
    WM_SetSize(hItem, 60, 30);
    DROPDOWN_SetItemSpacing(hItem, 3);
    DROPDOWN_SetListHeight(hItem, 85);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_UNSEL, PATIENT_INFO_DROPDOWN_UNSEL_COLOR);
    //DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SEL, GUI_BLUE);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SELFOCUS, PATIENT_INFO_DROPDOWN_SELFOCUS_COLOR);
    //岁 月 周 天
    DROPDOWN_AddString(hItem, g_ucaLng_Year[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Month[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Week[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Day[MachInfo.systemSet.eLanguage]);
    WM_SetCallback(hItem, Public_Dropdown_Callback);

    //性别 Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SEX);
    TEXT_SetText(hItem, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage]);
    //性别 Dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
    WM_SetSize(hItem, 180, 30);
    DROPDOWN_SetItemSpacing(hItem, 3);
//    DROPDOWN_SetListHeight(hItem, 45);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_UNSEL, PATIENT_INFO_DROPDOWN_UNSEL_COLOR);
    //DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SEL, GUI_BLUE);
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SELFOCUS, PATIENT_INFO_DROPDOWN_SELFOCUS_COLOR);
    // 男 女
    DROPDOWN_AddString(hItem, " ");
    DROPDOWN_AddString(hItem, g_ucaLng_SexMale[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_SexFemale[MachInfo.systemSet.eLanguage]);
    WM_SetCallback(hItem, Public_Dropdown_Callback);
 //   DROPDOWN_SetSel(hItem, MachRunPara.tWBCHGB_TestInfo.eSex);

    //样本编号 Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SAMPLE_SN);
    TEXT_SetText(hItem, g_ucaLng_SampleNum[MachInfo.systemSet.eLanguage]);
    //样本编号 Edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_SAMPLE_SN);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    WM_SetCallback(hItem, Public_Edit_Callback);

    //出生年月 Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BIRTH_DAY);
    TEXT_SetText(hItem, g_ucaLng_BirthDay[MachInfo.systemSet.eLanguage]);
    //出生年月 Edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    WM_SetCallback(hItem, Public_Edit_Callback);
 
    //参考组 Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_REFER);
    TEXT_SetText(hItem, g_ucaLng_ReferGroup[MachInfo.systemSet.eLanguage]);
    //参考组 Dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
    WM_SetSize(hItem, 180, 30);
    DROPDOWN_SetItemSpacing(hItem, 3);
    DROPDOWN_SetListHeight(hItem, 100);
    //set color
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_UNSEL, PATIENT_INFO_DROPDOWN_UNSEL_COLOR);//PATIENT_INFO_DROPDOWN_UNSEL_COLOR
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SEL, MachInfo.companyInfo.skin.buttNotPress);//PATIENT_INFO_DROPDOWN_UNSEL_COLOR
    DROPDOWN_SetTextColor(hItem, DROPDOWN_CI_SELFOCUS, MachInfo.companyInfo.skin.buttNotPress);
    // 通用 成男 成女 小孩 新生儿
    DROPDOWN_AddString(hItem, g_ucaLng_General[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_AdultMale[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_AdultFemale[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Child[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Neonatus[MachInfo.systemSet.eLanguage]);
    WM_SetCallback(hItem, Public_Dropdown_Callback);
//  DROPDOWN_SetSel(hItem, MachRunPara.tWBCHGB_TestInfo.eReferGroup);

    //操作者 Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_OPERATOR);
    TEXT_SetText(hItem, g_ucaLng_Operator[MachInfo.systemSet.eLanguage]);
    //操作者 Edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_OPERATOR);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    WM_SetCallback(hItem, Public_Edit_Callback);

    //检测时间 Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CHECK_DATE_TIME);
    TEXT_SetText(hItem, g_ucaLng_CheckTime[MachInfo.systemSet.eLanguage]);
    //检测时间 Edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_CHECK_DATE_TIME);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    WM_SetCallback(hItem, Public_Edit_Callback);

    //备注 Text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_REMARK);
    TEXT_SetText(hItem, g_ucaLng_ReMark[MachInfo.systemSet.eLanguage]);
    //备注 MultiEdit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_REMARK);
    MULTIEDIT_SetFont(hItem, &HZ_SONGTI_16);
//    MULTIEDIT_SetText(hItem, (char*)MachRunPara.tWBCHGB_TestInfo.ucaRemark);

    //取消 Bttuon  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PATIENT_CANCEL);
    WM_SetCallback(hItem, Patient_Info_Btn_Callback);

    //确定 button 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PATIENT_SURE);
    WM_SetCallback(hItem, Patient_Info_Btn_Callback);
    
    //当为英文时，需要微调显示位置
    if(LANGUAGE_ENGLISH == MachInfo.systemSet.eLanguage)
    {
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SEX);
        WM_MoveWindow(hItem, -10, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_AGE);
        WM_MoveWindow(hItem, 5, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_REFER);
        WM_MoveWindow(hItem, -37, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_BIRTH_DAY);
        WM_MoveWindow(hItem, -3, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SAMPLE_SN);
        WM_MoveWindow(hItem, -15, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_OPERATOR);
        WM_MoveWindow(hItem, 10, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CHECK_DATE_TIME);
        WM_MoveWindow(hItem, -12, 0);
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_REMARK);
        WM_MoveWindow(hItem, -12, 0);
    }
    
    //
    if(MachRunPara.ulMenuID == GUI_WINDOW_LIST_REVIEW_ID || MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID)
    { 
        //列表回顾-->病人信息，或者，列表回顾-->结果详情-->病人信息
        if(g_tPatinet_Info.ulCurDataIndex != MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ulCurDataIndex)
        {
            //当查询不同的数据时，才更新g_tPatinet_Inft
            g_tPatinet_Info.ulCurDataIndex = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ulCurDataIndex;
            g_tPatinet_Info.eAgeUnit       = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eAgeUnit;
            g_tPatinet_Info.ucAge          = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucAge;
            g_tPatinet_Info.eReferGroup    = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eReferGroup;
            g_tPatinet_Info.eSex           = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eSex;
            g_tPatinet_Info.eTestMode      = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eTestMode;
            g_tPatinet_Info.eAccountType   = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].eAccountType;
            g_tPatinet_Info.ulCurDataIndex = MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ulCurDataIndex;
            //
			strcpy((char*)g_tPatinet_Info.orderNum,(char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].orderNum);
			strcpy((char*)g_tPatinet_Info.patientID,(char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].patientID);
            strncpy((char*)g_tPatinet_Info.ucaName, (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaName, PATIENT_NAME_LEN);
            strncpy((char*)g_tPatinet_Info.ucaBirthDay, (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaBirthDay, PATIENT_BIRTHE_DAY_MAX_LEN);
            strncpy((char*)g_tPatinet_Info.ucaDateTime, (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaDateTime, DATE_TIME_LEN);
            strncpy((char*)g_tPatinet_Info.ucaRemark, (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaRemark, REMARK_LEN);
            strncpy((char*)g_tPatinet_Info.ucaSampleSN, (char*)MachRunPara.taListView_Data[g_ucaListReview_DataTable[g_ucListView_DataIndex]].ucaSampleSN, SAMPLE_SN_LEN);
        }
    }else if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID){ 
        //样本分析中界面中的“病人信息”
        if(g_tPatinet_Info.ulCurDataIndex != MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex)
        {
            //当查询不同的数据时，才更新g_tPatinet_Inft
            g_tPatinet_Info.ulCurDataIndex = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
            g_tPatinet_Info.eAgeUnit       = MachRunPara.tWBCHGB_TestInfo.eAgeUnit;
            g_tPatinet_Info.ucAge          = MachRunPara.tWBCHGB_TestInfo.ucAge;
            g_tPatinet_Info.eReferGroup    = MachRunPara.tWBCHGB_TestInfo.eReferGroup;
            g_tPatinet_Info.eSex           = MachRunPara.tWBCHGB_TestInfo.eSex;
            g_tPatinet_Info.eTestMode      = MachRunPara.tWBCHGB_TestInfo.eTestMode;
            g_tPatinet_Info.eAccountType   = MachRunPara.tWBCHGB_TestInfo.eAccountType;
            g_tPatinet_Info.ulCurDataIndex = MachRunPara.tWBCHGB_TestInfo.ulCurDataIndex;
            //
			strcpy((char*)g_tPatinet_Info.orderNum,(char*)MachRunPara.tWBCHGB_TestInfo.orderNum);
			strcpy((char*)g_tPatinet_Info.patientID,(char*)MachRunPara.tWBCHGB_TestInfo.patientID);
            strncpy((char*)g_tPatinet_Info.ucaName,     (char*)MachRunPara.tWBCHGB_TestInfo.ucaName, PATIENT_NAME_LEN);
            strncpy((char*)g_tPatinet_Info.ucaBirthDay, (char*)MachRunPara.tWBCHGB_TestInfo.ucaBirthDay, PATIENT_BIRTHE_DAY_MAX_LEN);
            strncpy((char*)g_tPatinet_Info.ucaDateTime, (char*)MachRunPara.tWBCHGB_TestInfo.ucaDateTime, DATE_TIME_LEN);
            strncpy((char*)g_tPatinet_Info.ucaRemark,   (char*)MachRunPara.tWBCHGB_TestInfo.ucaRemark, REMARK_LEN);
            strncpy((char*)g_tPatinet_Info.ucaSampleSN, (char*)MachRunPara.tWBCHGB_TestInfo.ucaSampleSN, SAMPLE_SN_LEN);
        }
    }
}



/*
*   病人信息界面，显示数据刷新
*/
static void Patient_Info_Msg_Paint(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
	extern  MachInfo_s	MachInfo;
    extern uint8_t g_ucListView_DataIndex;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
    WM_HWIN hItem;
//    int i = 0;
    char Buffer[30] = { 0 };
    
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_TITILE);
	switch(MachInfo.companyInfo.company){
		case COMPANY_HY:
		{
			//和映
			char Str[60] = {0};
			sprintf(Str,"%s%s)",g_ucaLng_PatientInfoDownloadInfo[MachInfo.systemSet.eLanguage],g_tPatinet_Info.patientID);
			TEXT_SetText(hItem, Str);
		}break;
		
		default :
		{
			TEXT_SetText(hItem, g_ucaLng_PatientInfo[MachInfo.systemSet.eLanguage]);
		}break;
	}
	
     // name edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_NAME); 
    EDIT_SetText(hItem, (char*)g_tPatinet_Info.ucaName);
    WM_SetFocus(hItem);
    
    //Age_Edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE);
    memset(Buffer, 0, sizeof(Buffer));
    if(g_tPatinet_Info.ucAge != 0)
    {
        sprintf(Buffer, "%d", g_tPatinet_Info.ucAge);
        EDIT_SetText(hItem, Buffer);
    }else{
        EDIT_SetText(hItem, "");
    }
    //EDIT_SetValue(hItem, MachRunPara.tWBCHGB_TestInfo.ucAge);
    //age unit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE);
    DROPDOWN_SetSel(hItem, g_tPatinet_Info.eAgeUnit);

    // birth day edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY);
    EDIT_SetText(hItem, (char*)g_tPatinet_Info.ucaBirthDay);

    //operator
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_OPERATOR);     
    EDIT_SetText(hItem,MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].user);
    WM_DisableWindow(hItem);

    //sex
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
    DROPDOWN_SetSel(hItem, g_tPatinet_Info.eSex);

    //sample sn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_SAMPLE_SN);
    EDIT_SetText(hItem, (char*)g_tPatinet_Info.ucaSampleSN);
    WM_DisableWindow(hItem);
    
    //refer group
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_REFER);
    DROPDOWN_SetSel(hItem, g_tPatinet_Info.eReferGroup);
    WM_DisableWindow(hItem);
	
    //check time
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_CHECK_DATE_TIME);
    EDIT_SetText(hItem, (char*)g_tPatinet_Info.ucaDateTime);
    WM_DisableWindow(hItem);
    
    //remark
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_REMARK);
    MULTIEDIT_SetText(hItem, (char*)g_tPatinet_Info.ucaRemark);     
}



/*
*   获取界面的信息，
*/
FeedBack_e Update_Patient_Input_Info(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
    extern __IO MachRunPara_s MachRunPara;
    //char ucSendBuffer[UI_TO_BACKEND_MSG_BUFFER_LEN] = {0};
    char buffer[10] = {0};
    char index = 0;
   
    //Patient_Info_t *ptPatient_Info = (Patient_Info_t*)ucSendBuffer;
    __IO Patient_Info_t *ptPatient_Info  = &g_tPatinet_Info;
    //
    
    //name
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_NAME); 
    EDIT_GetText(hItem, (char*)ptPatient_Info->ucaName, PATIENT_NAME_LEN);
    
    //sex,
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
    index = DROPDOWN_GetSel(hItem);
    if(index == SEX_TYPE_MALE)
    {   // index和DROPDOWN初始化赋值一一对应
        ptPatient_Info->eSex = SEX_TYPE_MALE;
    }else if(index == SEX_TYPE_FEMALE){
        ptPatient_Info->eSex = SEX_TYPE_FEMALE;
    }else{
        ptPatient_Info->eSex = SEX_TYPE_NONE;
    }
    
     //Age_Edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE);
    EDIT_GetText(hItem, buffer, 4);
    ptPatient_Info->ucAge = atoi(buffer);
    
    //age unit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE);
    index = DROPDOWN_GetSel(hItem);
    if(0 == index)
    {   // index和DROPDOWN初始化赋值一一对应
        ptPatient_Info->eAgeUnit = AGE_UNIT_YEAR;
    }else if(1 == index){
        ptPatient_Info->eAgeUnit = AGE_UNIT_MONTH;
    }else if(2 == index){
        ptPatient_Info->eAgeUnit = AGE_UNIT_WEEK;
    }else if(3 == index){
        ptPatient_Info->eAgeUnit = AGE_UNIT_DAY;    
    }
    
    // birth day edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY);
    EDIT_GetText(hItem, (char*)ptPatient_Info->ucaBirthDay, PATIENT_BIRTHE_DAY_MAX_LEN);

    //remark
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_REMARK);
    MULTIEDIT_GetText(hItem, (char*)ptPatient_Info->ucaRemark, REMARK_LEN);    
       
    return FEED_BACK_SUCCESS;
}



/*
*   获取界面的信息（可能修改后）
*/
FeedBack_e Get_Patient_Info(uint32_t ulSN, WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
    extern __IO MachRunPara_s MachRunPara;
    //char ucSendBuffer[UI_TO_BACKEND_MSG_BUFFER_LEN] = {0};
    char buffer[10] = {0};
    char index = 0;
   
    //Patient_Info_t *ptPatient_Info = (Patient_Info_t*)ucSendBuffer;
    __IO Patient_Info_t *ptPatient_Info  = &g_tPatinet_Info;
    //
    ptPatient_Info->tMsgHead.usCmd        = CMD_ANALYSIS_UPDATE_PATIENT_INFO;
    ptPatient_Info->tMsgHead.eErrorCode   = ERROR_CODE_SUCCESS; 
    ptPatient_Info->tMsgHead.usMsgLen     = MSG_HEAD_LEN;      
    //
    ptPatient_Info->ulCurDataIndex          = ulSN;
    //strncpy((char*)ptPatient_Info->ucaSampleSN, (char*)MachRunPara.tWBCHGB_TestInfo.ucaSampleSN, SAMPLE_SN_LEN);
    
    //name
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_NAME); 
    EDIT_GetText(hItem, (char*)ptPatient_Info->ucaName, PATIENT_NAME_LEN);
    
    //sex,
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_SEX);
    index = DROPDOWN_GetSel(hItem);
    if(index == SEX_TYPE_MALE)
    {   // index和DROPDOWN初始化赋值一一对应
        ptPatient_Info->eSex = SEX_TYPE_MALE;
    }else if(index == SEX_TYPE_FEMALE){
        ptPatient_Info->eSex = SEX_TYPE_FEMALE;
    }else{
        ptPatient_Info->eSex = SEX_TYPE_NONE;
    }
    
     //Age_Edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE);
    EDIT_GetText(hItem, buffer, 4);
    ptPatient_Info->ucAge = atoi(buffer);
    
    //age unit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE);
    index = DROPDOWN_GetSel(hItem);
    if(0 == index)
    {   // index和DROPDOWN初始化赋值一一对应
        ptPatient_Info->eAgeUnit = AGE_UNIT_YEAR;
    }else if(1 == index){
        ptPatient_Info->eAgeUnit = AGE_UNIT_MONTH;
    }else if(2 == index){
        ptPatient_Info->eAgeUnit = AGE_UNIT_WEEK;
    }else if(3 == index){
        ptPatient_Info->eAgeUnit = AGE_UNIT_DAY;    
    }
    
    // birth day edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY);
    EDIT_GetText(hItem, (char*)ptPatient_Info->ucaBirthDay, PATIENT_BIRTHE_DAY_MAX_LEN);

    //remark
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_REMARK);
    MULTIEDIT_GetText(hItem, (char*)ptPatient_Info->ucaRemark, REMARK_LEN);    
       
    /*
    * 同步到MachRunPara.tWBCHBG_TestInfo中
    */
    if(ulSN == MachRunPara.tWBCHGB_TestInfo.ulCurDataSN)
    {
        strncpy((char*)MachRunPara.tWBCHGB_TestInfo.ucaName, (char*)ptPatient_Info->ucaName, PATIENT_NAME_LEN);
        MachRunPara.tWBCHGB_TestInfo.eSex = ptPatient_Info->eSex;
        MachRunPara.tWBCHGB_TestInfo.ucAge = ptPatient_Info->ucAge;
        MachRunPara.tWBCHGB_TestInfo.eAgeUnit = ptPatient_Info->eAgeUnit;
        strncpy((char*)MachRunPara.tWBCHGB_TestInfo.ucaBirthDay, (char*)ptPatient_Info->ucaBirthDay, PATIENT_BIRTHE_DAY_MAX_LEN);
        strncpy((char*)MachRunPara.tWBCHGB_TestInfo.ucaRemark, (char*)ptPatient_Info->ucaRemark, REMARK_LEN);
        
    }
    
    /*
    * 如果当前修改的病人信息，在MachRunPara.taListView_Data中，则也需要进行同步
    */      
    for(int i = 0; i < LIST_REVIEW_ROW_NUM; i++)
    {
        if(MachRunPara.taListView_Data[i].ulCurDataSN == ulSN)
        {
            strncpy((char*)MachRunPara.taListView_Data[i].ucaName, (char*)ptPatient_Info->ucaName, PATIENT_NAME_LEN);
            MachRunPara.taListView_Data[i].eSex = ptPatient_Info->eSex;
            MachRunPara.taListView_Data[i].ucAge = ptPatient_Info->ucAge;
            MachRunPara.taListView_Data[i].eAgeUnit = ptPatient_Info->eAgeUnit;
            strncpy((char*)MachRunPara.taListView_Data[i].ucaBirthDay, (char*)ptPatient_Info->ucaBirthDay, PATIENT_BIRTHE_DAY_MAX_LEN);
            strncpy((char*)MachRunPara.taListView_Data[i].ucaRemark, (char*)ptPatient_Info->ucaRemark, REMARK_LEN);
        }
    }
    
    //发送消息到后台，更新数据文件中的病人信息
    UI_Put_Msg((uint8_t*)&g_tPatinet_Info);
    return FEED_BACK_SUCCESS;
}



// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void Patient_Info_cbDialog(WM_MESSAGE* pMsg) {
    WM_HWIN hItem;
    int     NCode;
    int     Id, i = 0;
    char    buffer[PATIENT_NAME_LEN] = {0};
    //
    extern __IO MachRunPara_s	MachRunPara;
    extern uint8_t g_ucListView_DataIndex;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
	static uint8_t TimerCreateFlag = 0;				//标志定时器是否已经创建的标志，为1表示已经创建，为0表示尚未创建

    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
    {
        //
        // Initialization of 'Remark_Multiedit'
        //...

        // USER START (Optionally insert additional code for further widget initialization)
        Patient_Info_Msg_Init(pMsg);
        Patient_Info_Msg_Paint(pMsg);
        // USER END
    }
    break;
    case WM_PATIENT_INFO_UPDATE:
    { 
        Update_Patient_Input_Info(pMsg);
    }
    break;
    case WM_DELETE:
    {
        g_sPI_MoveFlag = 0;
        g_sAgeUnit_TrigleFlag = 0;
        
		//重置定时器标志
		TimerCreateFlag = 0;
    }
    break;
    case WM_KEYBOARD_UPDATE: 
    {
        /***** 键盘输入交互信息处理 *****/   
        uint8_t ucAge = 0;
        hItem = WM_GetFocusedWindow();
        Id = WM_GetId(hItem);
        
        i = strlen(pMsg->Data.p);
        if(i == 1) //ASCII码
        {
            char c = *((char*)pMsg->Data.p);
            //输入字符到当前聚焦控件
            if(hItem)
            {
                //
                if(ID_EDIT_NAME == Id){ //Name
                    if((c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '.')
                    {
                        EDIT_GetText(hItem, buffer, PATIENT_NAME_LEN);
                        if(PATIENT_NAME_LEN - strlen(buffer) > 1) 
                        {
                            GUI_StoreKeyMsg(c, 1);
                        }
                    }
                }else if(Id == ID_EDIT_AGE){ //年龄必须是数字
                
                    if(c >= '0' && c <= '9')
                    {
                        //输入字符到聚焦控件
                        EDIT_GetText(hItem, buffer, 10);
                        ucAge = atoi(buffer);
                        if(ucAge <= 14) //小于150岁
                            GUI_StoreKeyMsg(c, 1);
                        break;
                    }
                }else if(Id == ID_MULTIEDIT_REMARK){ //
                    if(MULTIEDIT_GetTextSize(hItem)+1 < REMARK_LEN)
                    {
                        MULTIEDIT_AddText(hItem, pMsg->Data.p);
                    }
                }else{
                    //输入字符到聚焦控件
                     GUI_StoreKeyMsg(c, 1); 
                }
            }
        }else if(i == 3){ //一个汉字的UTF-8编码长度,3字节，以下是同时具有有中文输入功能的控件
            //hItem = WM_GetFocusedWindow();
            if(hItem)
            {
                if(Id == ID_MULTIEDIT_REMARK)  //Remark
                {
                    if(MULTIEDIT_GetTextSize(hItem)+3 < REMARK_LEN)
                    {
                        MULTIEDIT_AddText(hItem, pMsg->Data.p);
                    }
                }else if(Id == ID_EDIT_NAME){ //Name
                    uint16_t usTotalNum = 0, usPrevious = 0;
                    
                    memset(buffer, 0, PATIENT_NAME_LEN);
                    usTotalNum = EDIT_GetNumChars(hItem);
                    usPrevious = EDIT_GetCursorCharPos(hItem);
//                    LOG_Info("Num=%d,Pre=%d", usNum, usPrevious);

                    EDIT_GetText(hItem, buffer, PATIENT_NAME_LEN);
                    if(PATIENT_NAME_LEN - strlen(buffer) > 3) 
                    {
                        if(usTotalNum != usPrevious)
                        {
                            char acLastBuffer[PATIENT_NAME_LEN] = {0}, acNextBuffer[PATIENT_NAME_LEN] = {0}, i = 0, j = 0, ucCharNum = 0;
                            //上半段字符
                            for(ucCharNum = 0, i = 0; ucCharNum < usPrevious; ucCharNum++)
                            {
                                if(buffer[i] > 0x7E)
                                {
                                    acLastBuffer[i] = buffer[i]; i++;
                                    acLastBuffer[i] = buffer[i]; i++;
                                    acLastBuffer[i] = buffer[i]; i++;
                                }else{
                                    acLastBuffer[i] = buffer[i]; i++;
                                }
                            }
                            //下半段字符
                            for(; ucCharNum < usTotalNum; ucCharNum++)
                            {
                                if(buffer[i] > 0x7E)
                                {
                                    acNextBuffer[j] = buffer[i]; j++; i++;
                                    acNextBuffer[j] = buffer[i]; j++; i++;
                                    acNextBuffer[j] = buffer[i]; j++; i++;
                                }else{
                                    acNextBuffer[j] = buffer[i]; j++; i++;
                                }
                            }
                            //黏贴三段
                            strcat(acLastBuffer, pMsg->Data.p);
                            strcat(acLastBuffer, acNextBuffer); 
                            EDIT_SetText(hItem, acLastBuffer); //
                        }else{
                            //最大长度的限制
                            strcat(buffer, pMsg->Data.p);
                            EDIT_SetText(hItem, buffer); //
                        }
                        
                    }
                }              
            }
        }else{
            LOG_Error("Msg Len(%d) Error", i);
        }
    }
    break;
    case WM_KEYBOARD_END: 
    {
        //
        if(g_sPI_MoveFlag == 1)
        {
           WM_MoveTo(pMsg->hWin, 80, 50);
           g_sPI_MoveFlag = 0;
        }
        
        //输入年龄,同步更新出生日期
        hItem = WM_GetFocusedWindow();
        if(WM_GetId(hItem) == ID_EDIT_AGE || WM_GetId(hItem) == ID_DROPDOWN_AGE)
        {
            uint32_t ulCurDays = 0, ulDiffDays = 0, ulDstDays = 0;
            uint16_t usAge = 0, usYear = 0, usMonth = 0, usDay = 0;
            uint8_t ucAgeUnit = 0;
            char buffer[5] = {0};
            RTC_HYM8563Info_s RTCInfo = {0};
            
            //input age
            EDIT_GetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_AGE), buffer, 5);
            usAge = atoi(buffer);
            g_tPatinet_Info.ucAge = usAge;
            //age unit
            ucAgeUnit = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE));
            
            //current date time
            RTC_HYM8563GetTime(&RTCInfo);
            usYear = 2000 + RTCInfo.year.bcd_h*10 + RTCInfo.year.bcd_l;
            usMonth = RTCInfo.month.bcd_h*10 + RTCInfo.month.bcd_l;
            usDay  = RTCInfo.day.bcd_h*10 + RTCInfo.day.bcd_l;
            ulCurDays = usYear*365+usMonth*30+usDay;
            
            //时间转换计算
            if(usAge > 0)
            {
                switch(ucAgeUnit)
                {
                    case AGE_UNIT_DAY:
                    {
                        ulDiffDays = g_tPatinet_Info.ucAge;
                    }
                    break;
                    case AGE_UNIT_WEEK:
                    {
                        ulDiffDays = g_tPatinet_Info.ucAge*7;
                    }
                    break;
                    case AGE_UNIT_MONTH:
                    {
                        ulDiffDays = g_tPatinet_Info.ucAge*30;
                    }
                    break;
                    case AGE_UNIT_YEAR:
                    {
                        ulDiffDays = g_tPatinet_Info.ucAge*365;
                    }
                    break;
                    default:break;
                }
                //
                ulDstDays = ulCurDays - ulDiffDays;
                if(ulDstDays > 0)
                {
                    usYear  = ulDstDays/365;
                    //
                    usMonth = ulDstDays%365/30; 
                    if(usMonth == 0) usMonth = 1;
                    //
                    usDay   = ulDstDays%30;
                    if(usDay == 0) usDay = 1;
                    
                    memset((void*)g_tPatinet_Info.ucaBirthDay, 0, sizeof(g_tPatinet_Info.ucaBirthDay));
                    sprintf((char*)g_tPatinet_Info.ucaBirthDay, "%d/%d/%d", usYear, usMonth, usDay);
                    //
                    EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY), (char*)g_tPatinet_Info.ucaBirthDay);
                }
            }
                
        }

    }
    break;
	
	//窗口定时器消息
	case WM_TIMER:
	{
		if(DROPDOWN_GetListbox(WM_GetDialogItem(pMsg->hWin,ID_DROPDOWN_AGE)) != 0){
			//重启计时器
			WM_RestartTimer(pMsg->Data.v,500);
		}else{
			TimerCreateFlag = 0;
			
			WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_EDIT_BIRTH_DAY));
		}
	}break;
	
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_MULTIEDIT_REMARK: // Notifications sent by 'Remark_Multiedit'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                WM_SetFocus(pMsg->hWinSrc);
                
                //需移动窗口
                if(g_sPI_MoveFlag == 0)
                {
                    WM_MoveWindow(pMsg->hWin, PI_X_MOVE_LEN, -PI_Y_MOVE_LEN);
                    g_sPI_MoveFlag = 1;
                }
                
                //打开键盘
				MachRunPara.keyboardInitJM = KEYBOARD_HZ;
                CreateKeyboard_Window();
            
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_EDIT_NAME: // Notifications sent by 'Name_Edit'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                WM_SetFocus(pMsg->hWinSrc);
                
                //打开键盘
				MachRunPara.keyboardInitJM = KEYBOARD_HZ;
                CreateKeyboard_Window();
            
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_EDIT_AGE: // Notifications sent by 'Age_Edit'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                WM_SetFocus(pMsg->hWinSrc);
                
                //打开键盘
				MachRunPara.keyboardInitJM = KEYBOARD_NUM;
                CreateKeyboard_Window();
            
            // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_EDIT_SAMPLE_SN: // Notifications sent by 'SampleSN_Edit'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_VALUE_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_DROPDOWN_SEX: // Notifications sent by 'Sex_Dropdown'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
            {
            }
            break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_DROPDOWN_AGE: // Notifications sent by 'Age_Dropdown'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                g_sAgeUnit_TrigleFlag = 1;
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
				//创建定时器，监测下拉框是否已经收起状态
				if(TimerCreateFlag == 0){
					TimerCreateFlag = 1;
					
					//创建窗口定时器,500ms触发一次
					WM_CreateTimer(pMsg->hWin,0,500,0);
					
					WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_EDIT_BIRTH_DAY));
				}
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
            {
                uint16_t usYear = 0, usMonth, usDay = 0;
                uint8_t ucAgeUnit = 0;
                uint32_t ulCurDays = 0, ulDstDays = 0, ulDiffDays = 0;
                RTC_HYM8563Info_s RTCInfo = {0};
                
                //age
                ucAgeUnit = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE));
                // current date time
                RTC_HYM8563GetTime(&RTCInfo);
                usYear = (2000 + RTCInfo.year.bcd_h*10 + RTCInfo.year.bcd_l);
                usMonth = RTCInfo.month.bcd_h*10 + RTCInfo.month.bcd_l;
                usDay  = RTCInfo.day.bcd_h*10 + RTCInfo.day.bcd_l;
                ulCurDays = usYear*365+usMonth*30+usDay;
                //
                switch(ucAgeUnit)
                {
                    case AGE_UNIT_DAY:
                    {
                        ulDiffDays = g_tPatinet_Info.ucAge;
                    }
                    break;
                    case AGE_UNIT_WEEK:
                    {
                        ulDiffDays = g_tPatinet_Info.ucAge*7;
                    }
                    break;
                    case AGE_UNIT_MONTH:
                    {
                        ulDiffDays = g_tPatinet_Info.ucAge*30;
                    }
                    break;
                    case AGE_UNIT_YEAR:
                    {
                        ulDiffDays = g_tPatinet_Info.ucAge*365;
                    }
                    break;
                    default:break;
                }
                //
                ulDstDays = ulCurDays - ulDiffDays;
                
                if(ulDstDays > 0)
                {
                    usYear  = ulDstDays/365;
                    usMonth = ulDstDays%365/30;
                    usDay   = ulDstDays%30;
                    memset((void*)g_tPatinet_Info.ucaBirthDay, 0, sizeof(g_tPatinet_Info.ucaBirthDay));
                    sprintf((char*)g_tPatinet_Info.ucaBirthDay, "%d/%d/%d", usYear, usMonth, usDay);
                    //
                    EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY), (char*)g_tPatinet_Info.ucaBirthDay);
                }
                //
//                WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_BIRTH_DAY));
//                Patient_Info_Msg_Paint(pMsg);

                //WM_SendMessageNoPara(pMsg->hWin, WM_BIRTH_DAY_EDIT_ENABLE);
              }
              break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_DROPDOWN_REFER: // Notifications sent by 'Refer_Dropdown'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_PATIENT_CANCEL: // Notifications sent by 'Cansel_Button'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {
                    // USER START (Optionally insert code for reacting on notification message)
                    GUI_EndDialog(pMsg->hWin, 0); 
                    if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
                    {
                        g_hActiveWin = Analysis_Menu();
                    }else if(MachRunPara.ulMenuID == GUI_WINDOW_LIST_REVIEW_ID){
                        g_hActiveWin = CreateListReview_Window();
                    }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                        g_hActiveWin = ResultInfo_Menu();
                    }
                    // USER END
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_PATIENT_SURE: // Notifications sent by 'Sure_Button'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {
                     //发送消息到后台，根据修改后的MachRunPara.tWBCHGB_TestInfo信息到文件
                    uint32_t ulSN = 0;
                    
                    // USER START (Optionally insert code for reacting on notification message)
                    GUI_EndDialog(pMsg->hWin, 0); 
                    if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
                    {
                        ulSN = MachRunPara.tWBCHGB_TestInfo.ulCurDataSN;
                        Get_Patient_Info(ulSN, pMsg);
                        g_hActiveWin = Analysis_Menu();                      
                    }else if(MachRunPara.ulMenuID == GUI_WINDOW_LIST_REVIEW_ID){
                        
                        ulSN = ListView_Current_WBCHGB_Info()->ulCurDataSN;
                        Get_Patient_Info(ulSN, pMsg);
                        g_hActiveWin = CreateListReview_Window();                        
                    }else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
                        
                        ulSN = ListView_Current_WBCHGB_Info()->ulCurDataSN;
                        Get_Patient_Info(ulSN, pMsg);
                        g_hActiveWin = ResultInfo_Menu();
                    }
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_EDIT_CHECK_DATE_TIME: // Notifications sent by ''
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        case ID_EDIT_BIRTH_DAY: // Notifications sent by 'Month_Listwheel'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
            {
                    AgeUnit_e eAgeUnit; 
                    eAgeUnit = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_AGE));
                    if(!(1 == g_sAgeUnit_TrigleFlag && AGE_UNIT_MONTH == eAgeUnit))
                    {
                        
                        //获取当前已输入的信息，防止被刷新后，丢弃
                        if (ERROR_CODE_SUCCESS != Update_Patient_Input_Info(pMsg))
                        {
                            LOG_Error("");
                        }
                    
                        GUI_EndDialog(pMsg->hWin, 0);
                        g_hActiveWin = CreatedataTimeSetPage();
                      
                        pMsg->MsgId = WM_USER_DATA;
                        pMsg->Data.v = 4;
                        WM_SendMessage(g_hActiveWin,pMsg);
                    }
                    g_sAgeUnit_TrigleFlag = 0;
                }
                break;
            case WM_NOTIFICATION_SEL_CHANGED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
        // USER START (Optionally insert additional message handling)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateNextSample_Framewin
*/
WM_HWIN CreatePatient_Info_Window(void);
WM_HWIN CreatePatient_Info_Window(void) {
    WM_HWIN hWin;
    
    Public_Hide_Widget(); //隐藏公共部分控件
    WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin);
	
	Disable_Algo_Task();
    
    hWin = GUI_CreateDialogBox(Patient_Info_aDialogCreate, GUI_COUNTOF(Patient_Info_aDialogCreate), Patient_Info_cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
