/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (PAGE_ID_PATIENT_LIST + 0x00)
#define ID_BUTTON_0    (PAGE_ID_PATIENT_LIST + 0x01)
#define ID_BUTTON_1    (PAGE_ID_PATIENT_LIST + 0x02)
#define ID_LISTVIEW_0    (PAGE_ID_PATIENT_LIST + 0x03)
#define ID_BUTTON_2    (PAGE_ID_PATIENT_LIST + 0x04)
#define ID_BUTTON_3    (PAGE_ID_PATIENT_LIST + 0x05)
#define ID_BUTTON_4    (PAGE_ID_PATIENT_LIST + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "PatientListPage", ID_WINDOW_0, 80, 65, 640, 380, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEL_b", ID_BUTTON_0, 0, 340, 320, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Confirm_b", ID_BUTTON_1, 320, 340, 320, 40, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 60, 60, 480, 242, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Last_b", ID_BUTTON_2, 540, 60, 40, 121, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Next_b", ID_BUTTON_3, 540, 181, 40, 121, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Refresh", ID_BUTTON_4, 540, 4, 80, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _ButtonRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			switch(WM_GetId(pMsg->hWin)){
				//取消按钮
				case ID_BUTTON_0:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//确认按钮
				case ID_BUTTON_1:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//上按钮
				case ID_BUTTON_2:
					GUI_SetColor(MachInfo.companyInfo.skin.title);
					GUI_FillRectEx(&Rect);
					GUI_SetColor(0x00cccccc);
					GUI_DrawRectEx(&Rect);
					UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
				break;
				
				//下按钮
				case ID_BUTTON_3:
					GUI_SetColor(MachInfo.companyInfo.skin.title);
					GUI_FillRectEx(&Rect);
					GUI_SetColor(0x00cccccc);
					GUI_DrawRectEx(&Rect);
					UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
				break;
				
				//刷新按钮
				case ID_BUTTON_4:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_AA_FillRoundedRectEx(&Rect,15);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Refresh[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			switch(WM_GetId(pMsg->hWin)){
				//取消按钮
				case ID_BUTTON_0:
					GUI_SetColor(GUI_LIGHTGRAY);
					GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
					GUI_SetColor(BTN_CHAR_COLOR);
					GUI_SetBkColor(GUI_LIGHTGRAY);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//确认按钮
				case ID_BUTTON_1:
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
					GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//上按钮
				case ID_BUTTON_2:
					//深色背景
					GUI_SetColor(MachInfo.companyInfo.skin.title);
					GUI_FillRectEx(&Rect);
					GUI_SetColor(0x00cccccc);
					GUI_DrawRectEx(&Rect);
					
					UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
				break;
				
				//下按钮
				case ID_BUTTON_3:
					GUI_SetColor(MachInfo.companyInfo.skin.title);
					GUI_FillRectEx(&Rect);
					GUI_SetColor(0x00cccccc);
					GUI_DrawRectEx(&Rect);
					
					UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
				break;
				
				//刷新按钮
				case ID_BUTTON_4:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.title);
					GUI_AA_FillRoundedRectEx(&Rect,15);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,14);
					
					//设置字符前景和背景色
					GUI_SetColor(GUI_BLACK);
					GUI_SetBkColor(MachInfo.companyInfo.skin.title);
				
					GUI_DispStringInRect(g_ucaLng_Refresh[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



static void _ButtonRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
	//取消按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
    //确定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//上一页按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//下一页按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//刷新按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	HEADER_SKINFLEX_PROPS pProps;
	uint8_t RowNum = 0;
	char Str[20] = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    //设置HEADER皮肤属性
	LISTVIEW_GetHeader(hItem);
	HEADER_GetSkinFlexProps(&pProps,0);
	pProps.aColorLower[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorLower[1] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[1] = MachInfo.companyInfo.skin.title;
	HEADER_SetSkinFlexProps(&pProps,0);
	
	LISTVIEW_SetFont(hItem,&HZ_SONGTI_16);
	LISTVIEW_AddColumn(hItem, 150, g_ucaLng_Name[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 60, g_ucaLng_Sexual[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, g_ucaLng_Age[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_AddColumn(hItem, 190, g_ucaLng_Num[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_SetRowHeight(hItem, 40);
    LISTVIEW_SetHeaderHeight(hItem, 40);
	LISTVIEW_SetBkColor(hItem,LISTVIEW_CI_SELFOCUS,MachInfo.companyInfo.skin.buttPress);
	LISTVIEW_SetAutoScrollV(hItem,0);
	
	for(RowNum=0;RowNum<MachRunPara.patientList.num;RowNum++){
		LISTVIEW_AddRow(hItem, NULL);
		
		//姓名
		LISTVIEW_SetItemText(hItem,0,RowNum,(char*)MachRunPara.patientList.info[RowNum].name);
		
		//性别
		switch(MachRunPara.patientList.info[RowNum].eSex){
			case SEX_TYPE_MALE:
			{
				LISTVIEW_SetItemText(hItem,1,RowNum,g_ucaLng_SexMale[MachInfo.systemSet.eLanguage]);
			}break;
			
			case SEX_TYPE_FEMALE:
			{
				LISTVIEW_SetItemText(hItem,1,RowNum,g_ucaLng_SexFemale[MachInfo.systemSet.eLanguage]);
			}break;
			
			default :
			{
				LISTVIEW_SetItemText(hItem,1,RowNum,"");
			}break;
		}
		
		//年龄，年龄单位
		memset(Str,0,20);
		switch(MachRunPara.patientList.info[RowNum].eAgeUnit){
			case AGE_UNIT_YEAR:
			{
				sprintf(Str,"%u%s",MachRunPara.patientList.info[RowNum].age,g_ucaLng_Year[MachInfo.systemSet.eLanguage]);
			}break;
			
			case AGE_UNIT_MONTH:
			{
				sprintf(Str,"%u%s",MachRunPara.patientList.info[RowNum].age,g_ucaLng_Month[MachInfo.systemSet.eLanguage]);
			}break;
			
			case AGE_UNIT_WEEK:
			{
				sprintf(Str,"%u%s",MachRunPara.patientList.info[RowNum].age,g_ucaLng_Week[MachInfo.systemSet.eLanguage]);
			}break;
			
			case AGE_UNIT_DAY:
			{
				sprintf(Str,"%u%s",MachRunPara.patientList.info[RowNum].age,g_ucaLng_Day[MachInfo.systemSet.eLanguage]);
			}break;
			
			default :
			{
				sprintf(Str,"%u%s",MachRunPara.patientList.info[RowNum].age,g_ucaLng_Year[MachInfo.systemSet.eLanguage]);
			}break;
		}
		LISTVIEW_SetItemText(hItem,2,RowNum,Str);
		
		//订单号
		LISTVIEW_SetItemText(hItem,3,RowNum,(char*)MachRunPara.patientList.info[RowNum].orderNum);
	}
    
	//重绘按钮样式
	_ButtonRedrawWidgetType(pMsg);
    break;
  
  case WM_PAINT:
	//先设置弹窗和背景为相同的透明度
	GUI_SetAlpha(30);
	GUI_SetColor(0x00525a4e);
	GUI_FillRectEx(&Rect);
	GUI_SetAlpha(0);
  
	//重绘弹窗为圆角矩形
	GUI_SetColor(0x00ffffff);
	GUI_AA_FillRoundedRectEx(&Rect,6);
  
	//重绘顶部标题栏，采用重叠法
	GUI_SetColor(MachInfo.companyInfo.skin.title);
	GUI_AA_FillRoundedRect(Rect.x0,Rect.y0,Rect.x1,Rect.y0+15,6);
	GUI_FillRect(Rect.x0,Rect.y0+10,Rect.x1,Rect.y0+38);
	
	//标题
	GUI_SetFont(&HZ_SONGTI_16);
	GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
	GUI_SetBkColor(MachInfo.companyInfo.skin.title);
	GUI_DispStringHCenterAt(g_ucaLng_Analyse_PatientList[MachInfo.systemSet.eLanguage],320,10);
  break;
  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'CEL_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  {
		extern WM_HWIN Analysis_Menu(void);
		  
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = Analysis_Menu();
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Confirm_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		  extern WM_HWIN CreatePatientListPage(void);
		  extern WM_HWIN DialogWin;
		  extern osMessageQueueId_t CATQueueOtherHandle;
		  uint16_t TempU16 = 0;
		  CommonDialogPageData_s DialogPageData = {0};
		  Msg_Head_t tMsgHead = {0};
		  CATQueueInfoBuf_s CATQueueInfoBuf = {0};
		  
		  //获取列表选中项
		  hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		  TempU16 = LISTVIEW_GetSel(hItem);
		  
		  if(TempU16 == 0xFFFF){
			//请选中选项
			GUI_EndDialog(g_hActiveWin, 0);
			g_hActiveWin = CreateDialogPage();

			//保存对话框内容
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = CreatePatientListPage;
			strcpy(DialogPageData.str,g_ucaLng_SET_DianjiXuanxiang[MachInfo.systemSet.eLanguage]);

			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &DialogPageData;
			WM_SendMessage(g_hActiveWin,pMsg);
		  }else{
			//直接进入样本分析流程
			//姓名
			memset((void*)MachRunPara.tNextSample.ucaName, 0, sizeof(MachRunPara.tNextSample.ucaName));
			strncpy((char*)MachRunPara.tNextSample.ucaName,(char*)MachRunPara.patientList.info[TempU16].name,PATIENT_NAME_LEN);

			//年龄
			MachRunPara.tNextSample.ucAge = MachRunPara.patientList.info[TempU16].age;
			  
			//年龄单位
			MachRunPara.tNextSample.eAgeUnit = MachRunPara.patientList.info[TempU16].eAgeUnit;

			//性别
			MachRunPara.tNextSample.eSex = MachRunPara.patientList.info[TempU16].eSex;

			//出生年月
			memset((void*)MachRunPara.tNextSample.ucaBirthDay, 0, sizeof(MachRunPara.tNextSample.ucaBirthDay));
			  
			//参考组
			//自动匹配参考组
			MachRunPara.tNextSample.eReferGroup = AgeToRefGroup(MachRunPara.tNextSample.ucAge,MachRunPara.tNextSample.eAgeUnit,MachRunPara.tNextSample.eSex);

			//备注
			memset((void*)MachRunPara.tNextSample.ucaRemark, 0, sizeof(MachRunPara.tNextSample.ucaRemark));
			
			//订单号
			memset((void*)MachRunPara.tNextSample.orderNum, 0, sizeof(MachRunPara.tNextSample.orderNum));
			strncpy((char*)MachRunPara.tNextSample.orderNum,(char*)MachRunPara.patientList.info[TempU16].orderNum,ORDER_NUM_MAX_LEN);
			
			//下一样本信息标志有效化
			MachRunPara.tNextSample.validFlag = 1;
			
			//向药师帮服务端发送即将测试的患者信息
			CATQueueInfoBuf.msgType = SEND_PATIENT_ORDER_NUM_CAT_MSG_TYPE;
			memset(CATQueueInfoBuf.para.Str,0,ORDER_NUM_MAX_LEN);
			strncpy(CATQueueInfoBuf.para.Str,(char*)MachRunPara.tNextSample.orderNum,ORDER_NUM_MAX_LEN);
			osMessageQueuePut(CATQueueOtherHandle,&CATQueueInfoBuf,0, 0);

			//出仓
			tMsgHead.usCmd = CMD_OTHERS_OUTIN_OUT;
			UI_Put_Msg((uint8_t*)&tMsgHead);

			GUI_EndDialog(pMsg->hWin, 0);
			GUI_Exec();
			
			g_hActiveWin = WM_HBKWIN;
			WM_SetCallback(WM_HBKWIN, GIF_Guide_cbBkWin);
			
			//发送消息给HBKWIN，显示放入血细胞检测模块动画
			WM_SendMessageNoPara(g_hActiveWin, WM_INPUT_GUIDE_GIF);
		  }
	  }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Last_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern osEventFlagsId_t GlobalEventCatGroupHandle;
		extern osMessageQueueId_t CATQueueOtherHandle;
		CommonDialogPageData_s DialogPageData = {0};
		Msg_Head_t BackendMsg = {0};
		CATQueueInfoBuf_s CATQueueInfoBuf = {0};
		
		//判断是否已经是第一页了，是，则不需要再请求了
		if(MachRunPara.patientList.pageNum == 1){
			break;
		}

		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateDialogPage();

		//保存对话框内容
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = Analysis_Menu;
		strcpy(DialogPageData.str,g_ucaLng_Analyse_RequestParientInfo[MachInfo.systemSet.eLanguage]);

		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &DialogPageData;
		WM_SendMessage(g_hActiveWin,pMsg);

		//先清除网络异常事件标志
		osEventFlagsClear(GlobalEventCatGroupHandle,GLOBAL_EVENT_CAT_CONN_OTHER_NET_ERR);

		//往后台发送消息
		BackendMsg.usCmd = CMD_ANALYSIS_REQUEST_USER_NUM;
		UI_Put_Msg((uint8_t*)&BackendMsg);

		CATQueueInfoBuf.msgType = REQUEST_PATIENT_ID_CAT_MSG_TYPE;
		CATQueueInfoBuf.para.TempU8 = (MachRunPara.patientList.pageNum-1)==0?1:(MachRunPara.patientList.pageNum-1);
		
		memset((uint8_t*)&MachRunPara.patientList,0,sizeof(MachRunPara.patientList));
		MachRunPara.patientList.pageNum = CATQueueInfoBuf.para.TempU8;

		//向第三方服务端请求患者信息
		osMessageQueuePut(CATQueueOtherHandle,&CATQueueInfoBuf,0, 0);
	  }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Next_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern osEventFlagsId_t GlobalEventCatGroupHandle;
		extern osMessageQueueId_t CATQueueOtherHandle;
		CommonDialogPageData_s DialogPageData = {0};
		Msg_Head_t BackendMsg = {0};
		CATQueueInfoBuf_s CATQueueInfoBuf = {0};
		
		//判断是否还存在患者信息，当不存在时，则不需要再发送请求了
		if(MachRunPara.patientList.num < 5){
			break;
		}

		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateDialogPage();

		//保存对话框内容
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = Analysis_Menu;
		strcpy(DialogPageData.str,g_ucaLng_Analyse_RequestParientInfo[MachInfo.systemSet.eLanguage]);

		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &DialogPageData;
		WM_SendMessage(g_hActiveWin,pMsg);

		//先清除网络异常事件标志
		osEventFlagsClear(GlobalEventCatGroupHandle,GLOBAL_EVENT_CAT_CONN_OTHER_NET_ERR);

		//往后台发送消息
		BackendMsg.usCmd = CMD_ANALYSIS_REQUEST_USER_NUM;
		UI_Put_Msg((uint8_t*)&BackendMsg);

		CATQueueInfoBuf.msgType = REQUEST_PATIENT_ID_CAT_MSG_TYPE;
		CATQueueInfoBuf.para.TempU8 = MachRunPara.patientList.pageNum+1;
		
		memset((uint8_t*)&MachRunPara.patientList,0,sizeof(MachRunPara.patientList));
		MachRunPara.patientList.pageNum = CATQueueInfoBuf.para.TempU8;

		//向第三方服务端请求患者信息
		osMessageQueuePut(CATQueueOtherHandle,&CATQueueInfoBuf,0, 0);
	  }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    
	case ID_BUTTON_4: // Notifications sent by '刷新'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern osEventFlagsId_t GlobalEventCatGroupHandle;
		extern osMessageQueueId_t CATQueueOtherHandle;
		CommonDialogPageData_s DialogPageData = {0};
		Msg_Head_t BackendMsg = {0};
		CATQueueInfoBuf_s CATQueueInfoBuf = {0};

		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateDialogPage();

		//保存对话框内容
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = Analysis_Menu;
		strcpy(DialogPageData.str,g_ucaLng_Analyse_RequestParientInfo[MachInfo.systemSet.eLanguage]);

		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &DialogPageData;
		WM_SendMessage(g_hActiveWin,pMsg);

		//先清除网络异常事件标志
		osEventFlagsClear(GlobalEventCatGroupHandle,GLOBAL_EVENT_CAT_CONN_OTHER_NET_ERR);

		//往后台发送消息
		BackendMsg.usCmd = CMD_ANALYSIS_REQUEST_USER_NUM;
		UI_Put_Msg((uint8_t*)&BackendMsg);

		CATQueueInfoBuf.msgType = REQUEST_PATIENT_ID_CAT_MSG_TYPE;
		CATQueueInfoBuf.para.TempU8 = MachRunPara.patientList.pageNum;
		
		memset((uint8_t*)&MachRunPara.patientList,0,sizeof(MachRunPara.patientList));
		MachRunPara.patientList.pageNum = CATQueueInfoBuf.para.TempU8;

		//向第三方服务端请求患者信息
		osMessageQueuePut(CATQueueOtherHandle,&CATQueueInfoBuf,0, 0);
	  }
      break;
      }
      break;
	  
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePatientListPage
*/
WM_HWIN CreatePatientListPage(void);
WM_HWIN CreatePatientListPage(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, NotAlphaBk_cbBkWin);
	Public_Hide_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
