/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

/*
*
*   打印机错误提示界面（打印机缺纸，打印机连接错误）
*
*/

// USER END
#include "DIALOG.h"
#include "WM.h"
#include "GUI.h"
#include "LISTBOX.h"


#include "Public_menuDLG.h"
#include "file_operate.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



//ID
#define ID_WINDOW_PRINTER_ERROR_PORMPT      	(GUI_WINDOW_PRINTER_ERROR_PORMPT + 0x00)
#define ID_PRINTER_ERROR_PORMPT_BUTTON_SURE   	(GUI_WINDOW_PRINTER_ERROR_PORMPT + 0x01)





// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// 打印机缺纸， 打印机连接错误，标志
PrinterErrorType_e g_ePrinterErrorType = PRINTER_END;


// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/

static const GUI_WIDGET_CREATE_INFO Printer_Error_Prompt_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "", 				 ID_WINDOW_PRINTER_ERROR_PORMPT,    	180, 100, 440, 225, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",         		 ID_PRINTER_ERROR_PORMPT_BUTTON_SURE, 	0, 185, 440, 40, 0, 0x0, 0 },
  
};





/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


/*
*  ReCount_Prompt  btn callback
*/
static void Printer_Error_Prompt_btn_Callback(WM_MESSAGE* pMsg)
{
    const unsigned char RoundRadius = 0; //显示区域圆角半径
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            //draw frame
            GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
//          GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
//          //GUI_AA_DrawRoundedRect(Rect.x0 + 1, Rect.y0 + 1, Rect.x1 + 1, Rect.y1 + 1, RoundRadius);
//          GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);;

            // display char
            GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
            
//            //draw frame
//            GUI_SetColor(GUI_BTN_PRESS_COLOR);
//            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
//            GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
//            //GUI_AA_DrawRoundedRect(Rect.x0 + 1, Rect.y0 + 1, Rect.x1 + 1, Rect.y1 + 1, RoundRadius);
//            GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);;

//            // display char
//            GUI_SetColor(GUI_BTN_PRESS_CHAR_COLOR);
//            GUI_SetBkColor(GUI_BTN_PRESS_COLOR);
            if(ID_PRINTER_ERROR_PORMPT_BUTTON_SURE == WM_GetId(pMsg->hWin))
            {
                //确定
                GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }               
        }
        else {
            GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
//            GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
//            //GUI_AA_DrawRoundedRect(Rect.x0 + 1, Rect.y0 + 1, Rect.x1, Rect.y1, RoundRadius);
//            GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);;

            // display char
            GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
            
     
//            // draw frame
//            GUI_SetColor(GUI_BTN_RELEASE_COLOR);
//            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
//            GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
//            //GUI_AA_DrawRoundedRect(Rect.x0 + 1, Rect.y0 + 1, Rect.x1, Rect.y1, RoundRadius);
//            GUI_DrawRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);;

//            // display char
//            GUI_SetColor(GUI_BTN_RELEASE_CHAR_COLOR);
//            GUI_SetBkColor(GUI_BTN_RELEASE_COLOR);
            if(ID_PRINTER_ERROR_PORMPT_BUTTON_SURE == WM_GetId(pMsg->hWin))
            {
                //确定
                GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }  
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}






/*********************************************************************
*
*       _cbDialog
*/
static void Printer_Error_Prompt_cbDialog(WM_MESSAGE* pMsg) {
    
    WM_HWIN hItem;
    int     NCode;
    int     Id;
//    char buffer[50] = {0};


    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Remark_Multiedit'
        //...
		
		//btn sure
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PRINTER_ERROR_PORMPT_BUTTON_SURE);
		WM_SetCallback(hItem, Printer_Error_Prompt_btn_Callback);
        WM_InvalidateWindow(hItem);
		
        break;
	case WM_DELETE:
	{
		g_ePrinterErrorType = PRINTER_END;
	}
	break;
    case WM_PAINT:
    {
		if(PRINTER_NO_PAPER == g_ePrinterErrorType)
		{
			Show_BK_BMP(BK_FILE, BK_PICTURE_PRINTER_NO_PAPER, 155, 35);
		}else if(PRINTER_CONN_ERROR == g_ePrinterErrorType){
			Show_BK_BMP(BK_FILE, BK_PICTURE_PRINTER_CONN_ERROR, 135, 35);	
		}
    }
    break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_PRINTER_ERROR_PORMPT_BUTTON_SURE: // Notifications sent by 'SURE BUTTON '
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {
					extern __IO MachRunPara_s MachRunPara;
					GUI_EndDialog(pMsg->hWin, 0);
					if(MachRunPara.ulMenuID == GUI_WINDOW_ANALYSIS_ID)
					{
						//上一个界面为样本分析
						g_hActiveWin = Analysis_Menu();
						
					}else if(MachRunPara.ulMenuID == GUI_WINDOW_LIST_REVIEW_ID){
						//上一个界面为，列表回顾
						g_hActiveWin = CreateListReview_Window();
						
					}else if(MachRunPara.ulMenuID == GUI_WINDOW_RESULT_INFO_ID){
						//上一个界面为，列表回顾
						g_hActiveWin = ResultInfo_Menu();
					}else if(MachRunPara.ulMenuID == GUI_WINDOW_QC_ANALYSIS_ID){
                        //质控样本分析
                        g_hActiveWin = QC_Analysis_Menu();
                    }
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        }
        break;
        // USER START (Optionally insert additional message handling)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       ReCount_Prompt
*/



WM_HWIN Printer_Error_Prompt_PromptDLG(void);
WM_HWIN Printer_Error_Prompt_PromptDLG(void) {
    WM_HWIN hWin;
    
    //GUI_Clear();
    Public_Hide_Widget(); //隐藏公共部分控件,
    WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin);
	
	Disable_Algo_Task();
	
    hWin = GUI_CreateDialogBox(Printer_Error_Prompt_aDialogCreate, GUI_COUNTOF(Printer_Error_Prompt_aDialogCreate), Printer_Error_Prompt_cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
