/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

/*
*
*   在样本分析失败后，弹出界面，提示是否重新计数
*
*/

// USER END
#include "DIALOG.h"
#include "WM.h"
#include "GUI.h"
#include "LISTBOX.h"


#include "Public_menuDLG.h"
#include "file_operate.h"
#include "parameter.h"
#include "backend_msg.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



//ID
#define ID_WINDOW_RE_CONUT_PROMPT      	(GUI_WINDOW_RE_COUNT_PROMPT + 0x00)
#define ID_RE_COUNT_PROMPT_TEXT         (ID_WINDOW_RE_CONUT_PROMPT + 0x01)
#define ID_RE_COUNT_PROMPT_BUTTON_YES   (ID_WINDOW_RE_CONUT_PROMPT + 0x02)
#define ID_RE_COUNT_PROMPT_BUTTON_NO    (ID_WINDOW_RE_CONUT_PROMPT + 0x03)




// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/



// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/

static const GUI_WIDGET_CREATE_INFO ReCount_Prompt_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ReCount_Prompt", ID_WINDOW_RE_CONUT_PROMPT,    	180, 100, 440, 225, 0, 0x0, 0 },
//  { TEXT_CreateIndirect,   "",       	     ID_RE_COUNT_PROMPT_TEXT,     	80, 80, 280, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",         		 ID_RE_COUNT_PROMPT_BUTTON_NO,  0, 185, 220, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",         		 ID_RE_COUNT_PROMPT_BUTTON_YES, 220, 185, 220, 40, 0, 0x0, 0 },
  
};





/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*
*  ReCount_Prompt  btn callback
*/
static void ReCount_Prompt_Btn_Callback(WM_MESSAGE* pMsg)
{
    const unsigned char RoundRadius = 0; //显示区域圆角半径
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            if(ID_RE_COUNT_PROMPT_BUTTON_YES == WM_GetId(pMsg->hWin))
            {
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
                //是
                GUI_DispStringInRect(g_ucaLng_Yes[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_RE_COUNT_PROMPT_BUTTON_NO == WM_GetId(pMsg->hWin)) {
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
                //否
                GUI_DispStringInRect(g_ucaLng_No[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }     
        }
        else {
            if(ID_RE_COUNT_PROMPT_BUTTON_YES == WM_GetId(pMsg->hWin))
            {
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
                //是
                GUI_DispStringInRect(g_ucaLng_Yes[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_RE_COUNT_PROMPT_BUTTON_NO == WM_GetId(pMsg->hWin)) {
                GUI_SetColor(GUI_LIGHTGRAY);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
                GUI_SetColor(GUI_WHITE);
                GUI_SetBkColor(GUI_LIGHTGRAY);
                //否
                GUI_DispStringInRect(g_ucaLng_No[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }         
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}






/*********************************************************************
*
*       _cbDialog
*/
static void ReCount_Prompt_cbDialog(WM_MESSAGE* pMsg) {
    
    extern __IO DataManage_t g_tDataManage;
    WM_HWIN hItem;
    int     NCode;
    int     Id;
//    char buffer[50] = {0};


    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Remark_Multiedit'
        //...
		//btn NO
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RE_COUNT_PROMPT_BUTTON_NO);
		WM_SetCallback(hItem, ReCount_Prompt_Btn_Callback);
        WM_InvalidateWindow(hItem);
		
		//btn Yes
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RE_COUNT_PROMPT_BUTTON_YES);
		WM_SetCallback(hItem, ReCount_Prompt_Btn_Callback);
        WM_InvalidateWindow(hItem);
        break;
    case WM_PAINT:
    {
        Show_BK_BMP(BK_FILE, BK_PICTURE_IF_RE_COUNT, 140, 35);
    }
    break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_RE_COUNT_PROMPT_BUTTON_NO: // Notifications sent by 'No BUTTON '
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {
                    //清理下一样本的输入信息（会更新编号信息）。 
                    if(MachRunPara.tWBCHGB_TestInfo.tMsgHead.eErrorCode != ERROR_CODE_FLASH_DATA_CALIBRATE_ERR)
                    {
                        //当不是储数据校验错误时，才更新
                        Update_NexSample_Info(TRUE, &MachRunPara.tNextSample, &g_tDataManage);
                        LOG_Debug(" SN=%d, SampleSN=%s", MachRunPara.tNextSample.ulNextDataSN, MachRunPara.tNextSample.ucaNextSampleSN);	
                    }

                    //
					GUI_EndDialog(pMsg->hWin, 0);
                    g_hActiveWin = Confirm_Takeout_Cell_WindowDLG();
					//g_hActiveWin = Analysis_Menu();
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
			case ID_RE_COUNT_PROMPT_BUTTON_YES: // Notifications sent by 'Yes BUTTON '
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
                case WM_NOTIFICATION_RELEASED:
                {
					extern __IO OutIn_Module_Position_e g_eOutIn_Key;
				    extern __IO osSemaphoreId_t xSema_OutIn_Key;
					Msg_Head_t tMsgHead = {0};
					
                    //保持下一样本的输入信息（会更新编号信息）。
                    if(MachRunPara.tWBCHGB_TestInfo.tMsgHead.eErrorCode != ERROR_CODE_FLASH_DATA_CALIBRATE_ERR)
                    {
                        //当不是储数据校验错误时，才更新
                        Update_NexSample_Info(FALSE, &MachRunPara.tNextSample, &g_tDataManage);
                        LOG_Debug(" SN=%d, SampleSN=%s", MachRunPara.tNextSample.ulNextDataSN, MachRunPara.tNextSample.ucaNextSampleSN);	
                    }

					//出仓
					tMsgHead.usCmd = CMD_OTHERS_OUTIN_OUT;
					UI_Put_Msg((uint8_t*)&tMsgHead);
					
                    //关闭当前样本分析界面
                    GUI_EndDialog(pMsg->hWin, 0);
                    GUI_Exec();

                    //切换背景回调函数
                    g_hActiveWin = WM_HBKWIN;
                    WM_SetCallback(WM_HBKWIN, GIF_Guide_cbBkWin);
                    WM_SendMessageNoPara(g_hActiveWin, WM_RE_INPUT_GUIDE_GIF);
					GUI_Exec();
                }
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        }
        break;
        // USER START (Optionally insert additional message handling)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       ReCount_Prompt
*/



WM_HWIN ReCount_PromptDLG(void);
WM_HWIN ReCount_PromptDLG(void) {
    WM_HWIN hWin;
	
    Public_Hide_Widget(); //隐藏公共部分控件,
    WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin); //None_cbBkWin  AlphaBk_cbBkWin

	Disable_Algo_Task();
	
    hWin = GUI_CreateDialogBox(ReCount_Prompt_aDialogCreate, GUI_COUNTOF(ReCount_Prompt_aDialogCreate), ReCount_Prompt_cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
