/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "WM.h"
#include "FRAMEWIN.h"
#include "BUTTON.h"
#include "LISTVIEW.h"
#include "TEXT.h"
#include "HEADER.h"

#include "cx_menu.h"
#include "Public_menuDLG.h"
#include "process.h"
#include "msg_def.h"

// USER START (Optionally insert additional defines)
// USER END

/*
*	质控样本分析界面
*/

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static __IO CountMode_e gs_eLastCountMode = COUNT_MODE_NORMAL;
//
//__IO QC_FILENUM_INDEX_e g_eQC_Analysis_FileNum_Index = QC_FILENUM_INDEX_END; //质控样本分析，当前使用的文件号，索引

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define WBCHGB_LISTVIEW_LEN             330
#define WBCHGB_LISTVIEW_HEAD_LEN        34
#define WBCHGB_LISTVIEW_COLUMN_LEN      100


// error prompt
//#define GUI_BTN_ERROR_PROMPT_COLOR  0x004FA5FF
// list view
#define GUI_WBCHGB_RESULT_COLOR_BLUE    0x00f7f2e8
#define GUI_WBCHGB_RESULT_FRAME_COLOR   0x00cbcbcb




//ID
#define ID_WINDOW_QC_ANALYSIS       (GUI_WINDOW_QC_ANALYSIS_ID + 0x00)
#define ID_BUTTION_WBCHGB_RESULT    (GUI_WINDOW_QC_ANALYSIS_ID + 0x06)
//#define ID_BUTTON_LAST_RECORD       (GUI_WINDOW_QC_ANALYSIS_ID + 0x07)
//#define ID_BUTTON_NEXT_RECORD       (GUI_WINDOW_QC_ANALYSIS_ID + 0x08)
#define ID_DROPDOWN_FILE_NO         (GUI_WINDOW_QC_ANALYSIS_ID + 0x09)
#define ID_BUTTON_PRINT             (GUI_WINDOW_QC_ANALYSIS_ID + 0x0A)
#define ID_BUTTON_RETURN            (GUI_WINDOW_QC_ANALYSIS_ID + 0x0B)
#define ID_TEXT_QC                  (GUI_WINDOW_QC_ANALYSIS_ID + 0x10)
#define ID_TEXT_QC_ANALYSIS         (GUI_WINDOW_QC_ANALYSIS_ID + 0x11)
#define ID_TEXT_QC_PROMPT           (GUI_WINDOW_QC_ANALYSIS_ID + 0x12)
#define ID_TEXT_FILE_NO             (GUI_WINDOW_QC_ANALYSIS_ID + 0x13)
#define ID_TEXT_QC_TEST_INFO        (GUI_WINDOW_QC_ANALYSIS_ID + 0x14)
#define ID_TEXT_QC_WBC_HISTOGRAM    (GUI_WINDOW_QC_ANALYSIS_ID + 0x15)


 
/*********************************************************************
*
*       _aDialogCreate
*/
//  { WINDOW_CreateIndirect, "",     	ID_WINDOW_ANALYSIS,             10, 60, 780, 400, 0, 0, 0x0 },
static const GUI_WIDGET_CREATE_INFO QC_Analysis_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "",      ID_WINDOW_QC_ANALYSIS,          0, 60, 800, 393, 0, 0, 0x0 },       /*背景图目前高度：392，需改为395  */
  { TEXT_CreateIndirect, "",         ID_TEXT_QC,                     25,  20, 60, 60, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_QC_ANALYSIS,            70, 15, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", 	    ID_BUTTION_WBCHGB_RESULT,       17, 60, 300, 330, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "",    	ID_BUTTON_LAST_RECORD,          17, 12, 120, 40, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "",    	ID_BUTTON_NEXT_RECORD,          151, 12, 120, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_FILE_NO,                265, 12, 120, 40, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "",    ID_DROPDOWN_FILE_NO,            400, 12, 100, 160, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",      ID_BUTTON_PRINT,                522, 12, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",    	ID_BUTTON_RETURN,               657, 12, 120, 40, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "",        ID_TEXT_WBC_PROMPT,               322, 60, 175, 200, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "",        ID_TEXT_HGB_PROMPT,               322, 265, 175, 125, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "",        ID_TEXT_QC_PROMPT,                322, 265, 175, 125, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_QC_PROMPT,                  322, 175, 175, 215, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "",        ID_TEXT_QC_TEST_INFO,             502, 60, 280, 110, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_QC_TEST_INFO,               322, 60, 455, 110, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",        ID_TEXT_QC_WBC_HISTOGRAM,           502, 175, 280, 215, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "0",                   ID_TEXT_SCALE_0,        520, 425, 25, 15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "100",                 ID_TEXT_SCALE_100,      570, 425, 25, 15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "200",                 ID_TEXT_SCALE_200,      620, 425, 25, 15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "300",                 ID_TEXT_SCALE_300,      670, 425, 25, 15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "FL",                  ID_TEXT_SCALE_FL,       720, 425, 25, 15, 0, 0x0, 0 },

};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


/*
*  添加报警信息及数值 到显示buffer
*/
void QC_Display_Result_Info(char *pBuffer, char Index, __IO QC_WBCHGB_TestInfo_t *ptWBCHGB_TestInfo)
{
    extern __IO MachRunPara_s MachRunPara;
    
    if(Index >= WBCHGB_RST_END){
        LOG_Error("Index Morn That %d", WBCHGB_RST_END);
        return;
    }
    
    
//    if(ACCOUNT_TYPE_NORMAL == MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type && ptWBCHGB_TestInfo->fWBCHGB_RstData[WBCHGB_RST_WBC] < 0.3)   //普通账号 001,并且wbc值小于0.3，其他显示项都报*
//    {
//        if(WBCHGB_RST_WBC == Index)
//        {
//            sprintf(pBuffer, "%0.2f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
//        }else{
//            sprintf(pBuffer, "***");
//        }
//    }else if(ACCOUNT_TYPE_NORMAL == MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type){   //普通账号 001
     
//         //根据报警信息和数值，合成显示内容，（如果为普通账号（001）,不报* ？）            
//        switch(ptWBCHGB_TestInfo->ucaWBCHGB_RstAlert[Index])
//        {
//            case WBCHGB_ALERT_INVALID://报*标志
//            case WBCHGB_ALERT_NORMAL:
//            {
//                sprintf(pBuffer, "%0.2f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
//            }
//            break;
//            case WBCHGB_ALERT_SMALL:
//            {
//                sprintf(pBuffer, "%0.2f↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
//            }
//            break;
//            case WBCHGB_ALERT_BIG:
//            {
//                sprintf(pBuffer, "%0.2f↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
//            }
//            break;
//            case WBCHGB_ALERT_REVIEW:
//            {
//                sprintf(pBuffer, "%0.2f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
//            }
//            break;
//            case WBCHGB_ALERT_REVIEW_SMALL:
//            {
//                sprintf(pBuffer, "%0.2f↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
//            }
//            break;
//            case WBCHGB_ALERT_REVIEW_BIG:
//            {
//                sprintf(pBuffer, "%0.2f↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
//            }
//            break;
////            case WBCHGB_ALERT_INVALID:
////            {
////                sprintf(pBuffer, "***");           
////            }
////            break;        
//        } 
//     }else{

        //HGB和WBC的结果相互之间，在显示是独立显示！
        if((DATA_STATUS_COUNT_INVALID == (ptWBCHGB_TestInfo->eDataStatus) && (Index!= WBCHGB_RST_HGB)) || DATA_STATUS_INIT == (ptWBCHGB_TestInfo->eDataStatus)) 
        {
            //如何当前数据再故障条件下产生，则WBC值显示 "---"， //当测试不成功或是初始数据时，显示'/'
            if(DATA_STATUS_INIT == (ptWBCHGB_TestInfo->eDataStatus))  sprintf(pBuffer, "/");
            else  sprintf(pBuffer, "---");
        }
        
        //
        if(Index == WBCHGB_RST_HGB)
        {
            //HGB
            //根据报警信息和数值，合成显示内容，（报* ？）            
            switch(ptWBCHGB_TestInfo->ucaWBCHGB_RstAlert[Index])
            {
                case WBCHGB_ALERT_NORMAL:
                {
                    sprintf(pBuffer, "%0.1f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_SMALL:
                {
                    sprintf(pBuffer, "%0.1f↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_BIG:
                {
                    sprintf(pBuffer, "%0.1f↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_REVIEW:
                {
                    sprintf(pBuffer, "%0.1f?", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_REVIEW_SMALL:
                {
                    sprintf(pBuffer, "%0.1f?↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_REVIEW_BIG:
                {
                    sprintf(pBuffer, "%0.1f?↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_INVALID:
                {
                    sprintf(pBuffer, "***");           
                }
                break;        
            }    
        }else{
            //其他值
            //根据报警信息和数值，合成显示内容，（报* ？）            
            switch(ptWBCHGB_TestInfo->ucaWBCHGB_RstAlert[Index])
            {
                case WBCHGB_ALERT_NORMAL:
                {
                    sprintf(pBuffer, "%0.2f", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_SMALL:
                {
                    sprintf(pBuffer, "%0.2f↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_BIG:
                {
                    sprintf(pBuffer, "%0.2f↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_REVIEW:
                {
                    sprintf(pBuffer, "%0.2f?", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_REVIEW_SMALL:
                {
                    sprintf(pBuffer, "%0.2f?↓", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_REVIEW_BIG:
                {
                    sprintf(pBuffer, "%0.2f?↑", ptWBCHGB_TestInfo->fWBCHGB_RstData[Index]);
                }
                break;
                case WBCHGB_ALERT_INVALID:
                {
                    sprintf(pBuffer, "***");           
                }
                break;        
            } 
        
        }            
     
}    



/*
    test info callback
*/
void QC_ErrorPrompt_Text_Callback(WM_MESSAGE* pMsg)
{
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
	const unsigned char RoundRadius  = 5;  //显示区域圆角半径
	const unsigned char HeaderLen	 = 34; //显示头高度
    const unsigned char Leght	     = 175; //宽度
    char Buffer[WBC_PROMPT_LEN+HGB_PROMPT_LEN+32] = {0};
    
	GUI_RECT TempRect = {0};
	
	switch (pMsg->MsgId)
    {
        case WM_PAINT:
        {
            GUI_RECT Rect;
            GUI_GetClientRect(&Rect);
            //set hear background
            GUI_SetColor(MachInfo.companyInfo.skin.title);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x0+Leght, Rect.y0+RoundRadius+HeaderLen, RoundRadius);
			//set tail background
            GUI_SetColor(GUI_WHITE);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y1 - HeaderLen, Rect.x1, Rect.y1, RoundRadius);
			
            //set body and tail(expect RoundRadius)background
			GUI_SetColor(GUI_WHITE);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0+HeaderLen, Rect.x1, Rect.y1-RoundRadius, 0);
			
			//draw frame
            GUI_SetColor(GUI_TEXT_FRAME_COLOR);
            GUI_DrawHLine(Rect.y0+HeaderLen, Rect.x0, Rect.x1);
            GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            
            //char display
            TempRect.x0 = Rect.x0; TempRect.y0 = Rect.y0; //头显示区域
            TempRect.x1 = Rect.x1; TempRect.y1 = HeaderLen;
            GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.title); 
            
            //显示头内容, 异常提示
            GUI_DispStringInRect(g_ucaLng_ErrorPrompt[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            //WBC异常信息显示区域及内容
            TempRect.x0 = Rect.x0; TempRect.y0 = Rect.y0 + HeaderLen + RoundRadius;
            TempRect.x1 = Rect.x1; TempRect.y1 = Rect.y1;
            GUI_SetColor(GUI_BLACK);
            GUI_SetBkColor(GUI_WHITE);
            /***** 告警信息内容 *****/
 
            //样本分析界面的回调
            if(MachRunPara.tQC_WBCHGB_TestInfo.ulCurDataIndex != INVALID_DATA_SN && MachRunPara.tQC_WBCHGB_TestInfo.eDataStatus != DATA_STATUS_INIT)
            {
                if(QC_CTRL_STATUS_IN == MachRunPara.tQC_WBCHGB_TestInfo.eQC_Ctrl_Status)
                {
                    sprintf(Buffer, "%s%s\r\n%s", (char*)MachRunPara.tQC_WBCHGB_TestInfo.ucaWBC_ErrorPrompt, (char*)MachRunPara.tQC_WBCHGB_TestInfo.ucaHGB_ErrorPrompt, g_ucaLng_ResultInCtrl[MachInfo.systemSet.eLanguage]);
                }else if(QC_CTRL_STATUS_OUT == MachRunPara.tQC_WBCHGB_TestInfo.eQC_Ctrl_Status){
                    sprintf(Buffer, "%s%s\r\n%s", (char*)MachRunPara.tQC_WBCHGB_TestInfo.ucaWBC_ErrorPrompt, (char*)MachRunPara.tQC_WBCHGB_TestInfo.ucaHGB_ErrorPrompt, g_ucaLng_ResultOutCtrl[MachInfo.systemSet.eLanguage]);
                }
                GUI_DispStringInRect(Buffer, &TempRect, GUI_TA_HCENTER | GUI_TA_TOP);
            }else{
                GUI_DispStringInRect("", &TempRect, GUI_TA_HCENTER | GUI_TA_TOP);
            }
  
        }
        break;
        default:
            TEXT_Callback(pMsg);
        break;
    }
}


/*
    QC info callback
*/
void QC_Info_TEXT_Callback(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
	extern  MachInfo_s	MachInfo;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
//    const unsigned char SpareLineLen = 8; //分割线宽度
    const unsigned char RoundRadius  = 5; //显示区域圆角半径
//    unsigned char i = 0;
    
    /*
    char testinfo[4][35] = { 
		{"样本编号: CBC-0001"},
        {"模式: WBC+HGB"},
        {"姓名: test"},
        {"检验时间: 2020/11/02 14:15"} };
    */
    
    char buffer[64] = { 0 };
    /*char testinfo[4][35] = {
        {"姓名: %s"},
        {"年龄: %d       性别: %s"},
        {"样本编号: %s"},
        {"检验时间: %s"} };
    */
    //char testinfo[120] = {"样本编号: CBC-0001模式: WBC+HGB姓名: test检验时间: 2020/11/02 14:15"};

    switch (pMsg->MsgId)
    {
        case WM_PAINT:
        {
            GUI_RECT Rect;
            GUI_GetClientRect(&Rect);
            //background
            GUI_SetColor(GUI_WHITE);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            //frame board
            GUI_SetColor(GUI_TEXT_FRAME_COLOR);
            GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);
            //spare line
            
            GUI_SetFont(&HZ_SONGTI_12);
            GUI_SetColor(GUI_BLACK);
            GUI_SetBkColor(GUI_WHITE);
            if(INVALID_DATA_SN == MachRunPara.tQC_WBCHGB_TestInfo.ulCurDataIndex || QC_FILENUM_INDEX_END == MachRunPara.tQC_WBCHGB_TestInfo.eFileNumIndex)
            {
                //无效数
                /*** 第一列 ***/
                //文件号
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:", g_ucaLng_FileNO[MachInfo.systemSet.eLanguage]);
                GUI_DispStringAt(buffer, Rect.x0 + 10, Rect.y0 + 10);       
                //水平
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:", g_ucaLng_Level[MachInfo.systemSet.eLanguage]);
//                if(QC_LEVEL_HIGH == MachRunPara.taQC_SetInfo[MachRunPara.tQC_WBCHGB_TestInfo.eFileNumIndex].eQC_Level)
//                {
//                    sprintf(buffer, "%s:%s", g_ucaLng_Level[MachInfo.systemSet.eLanguage], g_ucaLng_High[MachInfo.systemSet.eLanguage]);
//                }else if(QC_LEVEL_MIDDLE == MachRunPara.taQC_SetInfo[MachRunPara.tQC_WBCHGB_TestInfo.eFileNumIndex].eQC_Level){
//                    sprintf(buffer, "%s:%s", g_ucaLng_Level[MachInfo.systemSet.eLanguage], g_ucaLng_Middle[MachInfo.systemSet.eLanguage]);
//                }else if(QC_LEVEL_LOW == MachRunPara.taQC_SetInfo[MachRunPara.tQC_WBCHGB_TestInfo.eFileNumIndex].eQC_Level){
//                    sprintf(buffer, "%s:%s", g_ucaLng_Level[MachInfo.systemSet.eLanguage], g_ucaLng_Low[MachInfo.systemSet.eLanguage]);
//                }
                GUI_DispStringAt(buffer, Rect.x0 + 10, Rect.y0 + 35);         
                //批号
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:", g_ucaLng_LotNO[MachInfo.systemSet.eLanguage]);
                GUI_DispStringAt(buffer, Rect.x0 + 10, Rect.y0 + 60);
                //有效期
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:", g_ucaLng_ValidDate[MachInfo.systemSet.eLanguage]);
                GUI_DispStringAt(buffer, Rect.x0 + 10, Rect.y0 + 85);
                
                /*** 第二列 ***/
                //设定者
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:", g_ucaLng_Seter[MachInfo.systemSet.eLanguage]);
                GUI_DispStringAt(buffer, Rect.x0 + 160, Rect.y0 + 10);       
                //操作者
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:", g_ucaLng_Operator[MachInfo.systemSet.eLanguage]);
                GUI_DispStringAt(buffer, Rect.x0 + 160, Rect.y0 + 35);         
                //检测时间
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:", g_ucaLng_CheckTime[MachInfo.systemSet.eLanguage]);
                GUI_DispStringAt(buffer, Rect.x0 + 160, Rect.y0 + 60);
                
                /*** 第三列 ***/
                //数据/容量
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s/%s:", g_ucaLng_Data[MachInfo.systemSet.eLanguage], g_ucaLng_Capacity[MachInfo.systemSet.eLanguage]);
                GUI_DispStringAt(buffer, Rect.x0 + 300, Rect.y0 + 10);               
                //质控样本编号
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:", g_ucaLng_QCSampleSN[MachInfo.systemSet.eLanguage]);
                GUI_DispStringAt(buffer, Rect.x0 + 300, Rect.y0 + 35);
            }else{
                //有效数、
                /*** 第一列 ***/
                //文件号
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:%d", g_ucaLng_FileNO[MachInfo.systemSet.eLanguage], MachRunPara.tQC_WBCHGB_TestInfo.usFileNum);
                GUI_DispStringAt(buffer, Rect.x0 + 10, Rect.y0 + 10);       
                //水平
                memset(buffer, 0, sizeof(buffer));
                if(QC_LEVEL_HIGH == MachRunPara.tQC_WBCHGB_TestInfo.eQC_Level)
                {
                    sprintf(buffer, "%s:%s", g_ucaLng_Level[MachInfo.systemSet.eLanguage], g_ucaLng_High[MachInfo.systemSet.eLanguage]);
                }else if(QC_LEVEL_MIDDLE == MachRunPara.tQC_WBCHGB_TestInfo.eQC_Level){
                    sprintf(buffer, "%s:%s", g_ucaLng_Level[MachInfo.systemSet.eLanguage], g_ucaLng_Middle[MachInfo.systemSet.eLanguage]);
                }else if(QC_LEVEL_LOW == MachRunPara.tQC_WBCHGB_TestInfo.eQC_Level){
                    sprintf(buffer, "%s:%s", g_ucaLng_Level[MachInfo.systemSet.eLanguage], g_ucaLng_Low[MachInfo.systemSet.eLanguage]);
                }
                GUI_DispStringAt(buffer, Rect.x0 + 10, Rect.y0 + 30);         
                //批号
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:%s", g_ucaLng_LotNO[MachInfo.systemSet.eLanguage], MachRunPara.tQC_WBCHGB_TestInfo.ucaLotNum);
                GUI_DispStringAt(buffer, Rect.x0 + 10, Rect.y0 + 50);
                //有效期
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:%s", g_ucaLng_ValidDate[MachInfo.systemSet.eLanguage], MachRunPara.tQC_WBCHGB_TestInfo.ucaValidDate);
                GUI_DispStringAt(buffer, Rect.x0 + 10, Rect.y0 + 70);
                
                /*** 第二列 ***/
                //设定者
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:%s", g_ucaLng_Seter[MachInfo.systemSet.eLanguage], 
                        MachInfo.accountMM.accountInfo[MachRunPara.tQC_WBCHGB_TestInfo.eSeter].user);
                GUI_DispStringAt(buffer, Rect.x0 + 160, Rect.y0 + 10);       
                //操作者
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:%s", g_ucaLng_Operator[MachInfo.systemSet.eLanguage], \
                        MachInfo.accountMM.accountInfo[MachRunPara.tQC_WBCHGB_TestInfo.eOperator].user);
                GUI_DispStringAt(buffer, Rect.x0 + 160, Rect.y0 + 30);         
                //检测时间
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:%s", g_ucaLng_CheckTime[MachInfo.systemSet.eLanguage], MachRunPara.tQC_WBCHGB_TestInfo.ucaDateTime);
                GUI_DispStringAt(buffer, Rect.x0 + 160, Rect.y0 + 50);
                
                /*** 第三列 ***/
                //数据/容量
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s/%s:%d/%d", g_ucaLng_Data[MachInfo.systemSet.eLanguage], g_ucaLng_Capacity[MachInfo.systemSet.eLanguage], \
                    Get_QC_ValidNum(MachRunPara.tQC_WBCHGB_TestInfo.eFileNumIndex),\
                    MachRunPara.tQC_WBCHGB_TestInfo.usTestCapacity);
                GUI_DispStringAt(buffer, Rect.x0 + 300, Rect.y0 + 10);               
                //质控样本编号
                memset(buffer, 0, sizeof(buffer));
                sprintf(buffer, "%s:%s", g_ucaLng_QCSampleSN[MachInfo.systemSet.eLanguage], 
                    MachRunPara.tQC_WBCHGB_TestInfo.ucaSampleSN);
                GUI_DispStringAt(buffer, Rect.x0 + 300, Rect.y0 + 30);    
            }
            
            GUI_SetColor(GUI_RED);
            //错误提示信息
            if(ERROR_CODE_INVALID_FILENUM == MachRunPara.tQC_WBCHGB_TestInfo.tMsgHead.eErrorCode)
            {
                //质控，无效的文件号
                GUI_DispStringAt(g_ucaLng_FileNOInvalid[MachInfo.systemSet.eLanguage], Rect.x0 + 160, Rect.y0 + 80);
            
            }else if(ERROR_CODE_FILENUM_CAPACITY_IS_FULL == MachRunPara.tQC_WBCHGB_TestInfo.tMsgHead.eErrorCode){
                //质控，文件号下存储数据已满
                GUI_DispStringAt(g_ucaLng_FileNOIsFull[MachInfo.systemSet.eLanguage], Rect.x0 + 160, Rect.y0 + 80);
            }else{
                //无异常提示信息，空
                GUI_DispStringAt(" ", Rect.x0 + 160, Rect.y0 + 80);
            }
            GUI_SetFont(&HZ_SONGTI_16);
        }
        break;
        default:
            TEXT_Callback(pMsg);
        break;
    }
}





/*
*  analysis  btn callback
*/
static void QC_Analysis_Btn_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        

        if (BUTTON_IsPressed(pMsg->hWin)) {
             
            WM_GetClientRect(&Rect);
            //draw frame
            GUI_SetColor(MachInfo.companyInfo.skin.buttPress); //填充背景颜色
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
            
            //
            GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
            //
            if (ID_BUTTON_PRINT == WM_GetId(pMsg->hWin)) {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_RETURN == WM_GetId(pMsg->hWin)) {
                //返回
                GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            } 
        }
        else {
            WM_GetClientRect(&Rect);
			
			if(WM_IsEnabled(pMsg->hWin) == 1){
				//填充颜色
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
				GUI_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard); //画框
				GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 19);
				
				//
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			}else{
				//填充
				GUI_SetColor(GUI_WHITE);
				GUI_AA_FillRoundedRectEx(&Rect,20);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRectEx(&Rect,19);
				
				//设置字符前景和背景色
				GUI_SetColor(GUI_LIGHTGRAY);
				GUI_SetBkColor(GUI_WHITE);
			}
            
            //
            if (ID_BUTTON_PRINT == WM_GetId(pMsg->hWin)) {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            else if (ID_BUTTON_RETURN == WM_GetId(pMsg->hWin)) {
                //返回
                GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            } 
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
*  QC analysis  wbc hgb result info
*/
void QC_WBCHGB_Result_Btn_Callback(WM_MESSAGE* pMsg)
{
    extern uint8_t g_ucListView_DataIndex;
    extern uint8_t g_ucaListReview_DataTable[LIST_REVIEW_ROW_NUM];
    const unsigned char RoundRadius = 5;   //显示区域圆角半径
    const unsigned char HeaderHigh  = 34;  //显示头高度
    const unsigned char LineHigh    = 37;  //每行高度
    const unsigned char LineLen     = 100; //每一小格的长度
    char buffer[10] = {0};
    char i = 0, j = 0;
    GUI_RECT TempRect;
    
    const char ucaUnitBuf[WBCHGB_RST_END-1][8] = {
        "10^9/L", "10^9/L", "10^9/L", "10^9/L", "%", "%", "%",
    };
	
	char ucaParamBuf[WBCHGB_RST_END-1][8] = {0};
	
	switch(MachInfo.companyInfo.company){
		case COMPANY_JIN_RUI:
		{
			//锦瑞
			strcpy(&ucaParamBuf[0][0],"WBC");
			strcpy(&ucaParamBuf[1][0],"Neu#");
			strcpy(&ucaParamBuf[2][0],"Mid#");
			strcpy(&ucaParamBuf[3][0],"Lym#");
			strcpy(&ucaParamBuf[4][0],"Neu%");
			strcpy(&ucaParamBuf[5][0],"Mid%");
			strcpy(&ucaParamBuf[6][0],"Lym%");
		}break;
		
		default :
		{
			strcpy(&ucaParamBuf[0][0],"WBC");
			strcpy(&ucaParamBuf[1][0],"Gran#");
			strcpy(&ucaParamBuf[2][0],"Mid#");
			strcpy(&ucaParamBuf[3][0],"Lym#");
			strcpy(&ucaParamBuf[4][0],"Gran%");
			strcpy(&ucaParamBuf[5][0],"Mid%");
			strcpy(&ucaParamBuf[6][0],"Lym%");
		}break;
	}
    
    //
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);
        
        //画头，一行
        for(i = 0; i < 3; i++)
        {     
            //背景显示区域
            TempRect.x0 = Rect.x0 + i*LineLen;
            TempRect.y0 = Rect.y0;
            TempRect.x1 = TempRect.x0 + LineLen;
            TempRect.y1 = TempRect.y0 + HeaderHigh;
            
            GUI_SetColor(MachInfo.companyInfo.skin.title);
            if(i == 0)
            {
                //填充背景
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1+RoundRadius, RoundRadius);
                //显示字符,参数
                GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.title);
                GUI_DispStringInRect(g_ucaLng_Param[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(i == 1){
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1, 0);
                //显示字符。结果
                GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.title);
                GUI_DispStringInRect(g_ucaLng_Result[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(i == 2){
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1+RoundRadius, RoundRadius);
                //显示字符。单位
                GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.title);
                GUI_DispStringInRect(g_ucaLng_Unit[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
        //画尾，HGB一行（参数、结果、单位）
        for(i = 0; i < 3; i++)
        {     
            //设置字体及背景显示区域
            TempRect.x0 = Rect.x0 + i*LineLen;
            TempRect.y0 = Rect.y0 + HeaderHigh + 7*LineHigh;
            TempRect.x1 = TempRect.x0 + LineLen;
            TempRect.y1 = TempRect.y0 + LineHigh;
            
            GUI_SetColor(GUI_WBCHGB_RESULT_COLOR_BLUE);
            if(i == 0) //参数（HGB）
            {
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0 - RoundRadius, TempRect.x1, TempRect.y1, RoundRadius);
                GUI_SetColor(GUI_BLACK);
                GUI_SetBkColor(GUI_WBCHGB_RESULT_COLOR_BLUE);
                GUI_DispStringInRect("HGB", &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if(i == 1){ //结果（大小）
               
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1, 0);
                GUI_SetColor(GUI_BLACK);
                GUI_SetBkColor(GUI_WBCHGB_RESULT_COLOR_BLUE);

                memset(buffer, 0, sizeof(buffer));
                if(DATA_STATUS_INIT == MachRunPara.tQC_ListView_Data.eDataStatus)
                {
                    sprintf(buffer, "/"); 
                }else{
                    sprintf(buffer, "%0.2f", MachRunPara.tQC_WBCHGB_TestInfo.fWBCHGB_RstData[WBCHGB_RST_HGB]); 
                }
                
                GUI_DispStringInRect(buffer, &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);                
            }else if(i == 2){//单位
                GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0 - RoundRadius, TempRect.x1, TempRect.y1, RoundRadius);
                GUI_SetColor(GUI_BLACK);
                GUI_SetBkColor(GUI_WBCHGB_RESULT_COLOR_BLUE);
                GUI_DispStringInRect("g/L", &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
        
        //画WBC结果
        for(i = 0; i < 3; i++) //三列
        {    
            for(j = 0; j < 7; j++) //中间七行
            {                
                //操作区域
                TempRect.x0 = Rect.x0 + i*LineLen;
                TempRect.y0 = Rect.y0 + HeaderHigh + j*LineHigh;
                //
                TempRect.x1 = TempRect.x0 + LineLen;
                TempRect.y1 = TempRect.y0 + LineHigh;
                
                //填充背景
                if(j%2 == 0)
                {
                    GUI_SetColor(GUI_WHITE); //设置背景填充颜色
                    GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1, 0);
                    GUI_SetBkColor(GUI_WHITE); //为显示字符，设置背景颜色
                }else{
                    //GUI_SetColor(GUI_BLACK);
                    GUI_SetColor(GUI_WBCHGB_RESULT_COLOR_BLUE);  //设置背景填充颜色
                    GUI_AA_FillRoundedRect(TempRect.x0, TempRect.y0, TempRect.x1, TempRect.y1, 0);   
                    GUI_SetBkColor(GUI_WBCHGB_RESULT_COLOR_BLUE); //为显示字符，设置背景颜色                     
                }       
                
                //显示字符
                GUI_SetColor(GUI_BLACK);
                if(i == 0) //参数（WBC、Gran#、...）
                {
                    GUI_DispStringInRect(ucaParamBuf[j], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
                }else if(i == 1){ //结果（大小）
                    
                    memset(buffer, 0, sizeof(buffer));
                    QC_Display_Result_Info(buffer, j, &MachRunPara.tQC_WBCHGB_TestInfo);
                    GUI_DispStringInRect(buffer, &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
                    
                }else if(i == 2){   //单位（10^9/L、%、...）
                    GUI_DispStringInRect(ucaUnitBuf[j], &TempRect, GUI_TA_HCENTER | GUI_TA_VCENTER);
                } 
            }
        }
        //画分割线,横线, 10条
        GUI_SetColor(GUI_WBCHGB_RESULT_FRAME_COLOR);
        GUI_DrawHLine(Rect.y0, Rect.x0, Rect.x1); //第一条
        //GUI_DrawHLine(Rect.y0+HeaderHigh, Rect.x0, Rect.x1); //第二条
        for(i = 0; i < 9; i++)
        {
            GUI_DrawHLine(Rect.y0+HeaderHigh+i*LineHigh, Rect.x0, Rect.x1);
            if(i == 8)  GUI_DrawHLine(Rect.y0+HeaderHigh+i*LineHigh - 1, Rect.x0, Rect.x1);
        }
        //画竖线，4条
        GUI_DrawVLine(Rect.x0, Rect.y0, Rect.y1);
        GUI_DrawVLine(Rect.x0+LineLen, Rect.y0+HeaderHigh, Rect.y1);
        GUI_DrawVLine(Rect.x0+LineLen*2, Rect.y0+HeaderHigh, Rect.y1);
        GUI_DrawVLine(Rect.x0+LineLen*3 - 1, Rect.y0, Rect.y1);

    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
* 初始化回调
*/
static void QC_Analysis_Msg_Init(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara;
    WM_HWIN hItem;
    uint8_t ucIndex = 0;
    char Buffer[32] = {0};

    //qc text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC);
    if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE)
    {
        TEXT_SetFont(hItem, &HZ_SONGTI_24);
    }else{
        TEXT_SetFont(hItem, &GUI_Font24_ASCII);
    }
    //TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, g_ucaLng_QC[MachInfo.systemSet.eLanguage]);

    //qc set text
    char buffer[64] = {0};
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_ANALYSIS);
    TEXT_SetFont(hItem, &HZ_SONGTI_16);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    sprintf(buffer, ">%s", g_ucaLng_QC_Analysis[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, buffer);
      
    //file no select, text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FILE_NO);
    TEXT_SetFont(hItem, &HZ_SONGTI_16);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, g_ucaLng_FileNOSelect[MachInfo.systemSet.eLanguage]);

    // file no ,dropdown
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_FILE_NO);
    DROPDOWN_SetFont(hItem, GUI_FONT_24_ASCII);
    DROPDOWN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    WM_SetSize(hItem, 100, 40);
    WM_SetCallback(hItem, Public_Dropdown_Callback);
    //初始化
    MachRunPara.eQC_Analysis_FileNum_Index = QC_FILENUM_INDEX_END;
    for(ucIndex = QC_FILENUM_INDEX_0; ucIndex < QC_FILENUM_INDEX_END; ucIndex++)
    {
        if(MachRunPara.taQC_SetInfo[ucIndex].eFileNumIndex < QC_FILENUM_INDEX_END)
        {
            MachRunPara.eQC_Analysis_FileNum_Index = MachRunPara.taQC_SetInfo[ucIndex].eFileNumIndex;
            memset(Buffer, 0, sizeof(Buffer));
            sprintf(Buffer, "%d", MachRunPara.taQC_SetInfo[ucIndex].usFileNum);
            DROPDOWN_AddString(hItem, Buffer);
        } 
    }
    if(MachRunPara.eQC_Analysis_FileNum_Index == QC_FILENUM_INDEX_END)
    {
        //无效的文件号, 确保显示数据无效化，
        memset((void*)&MachRunPara.tQC_WBCHGB_TestInfo, 0, sizeof(QC_WBCHGB_TestInfo_t));
        MachRunPara.tQC_WBCHGB_TestInfo.eFileNumIndex = QC_FILENUM_INDEX_END;
        MachRunPara.tQC_WBCHGB_TestInfo.ulCurDataIndex = INVALID_DATA_SN;
        //
        DROPDOWN_SetSel(hItem, 0);
    }else{
        DROPDOWN_SetSel(hItem, MachRunPara.eQC_Analysis_FileNum_Index);
    }
         
    //WBC HGB Result
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTION_WBCHGB_RESULT);
    WM_SetCallback(hItem, WBCHGB_Result_Btn_Callback);
    WM_InvalidateWindow(hItem);

    // Initialization of 'Error prompt'
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_PROMPT);
    WM_SetCallback(hItem, QC_ErrorPrompt_Text_Callback);
    WM_InvalidateWindow(hItem);
    
    // qc test info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_TEST_INFO);
    WM_SetCallback(hItem, QC_Info_TEXT_Callback);
    WM_InvalidateWindow(hItem);

    //qc wbc histogram info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_WBC_HISTOGRAM);
    WM_SetCallback(hItem, WBC_Histogram_TEXT_Callback);
    WM_InvalidateWindow(hItem);

    // print btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT);
    WM_SetCallback(hItem, QC_Analysis_Btn_Callback);

    // patient info btn
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
    WM_SetCallback(hItem, QC_Analysis_Btn_Callback);
    
    //设置窗口背景色和桌面背景色一致
    WINDOW_SetBkColor(hItem, MachInfo.companyInfo.skin.bg);
}




/*
*   界面、数据更新
*/
static void QC_Analysis_Msg_Updata(WM_MESSAGE* pMsg)
{
//    extern char* BKBmaDataBuf;
    extern __IO MachRunPara_s	MachRunPara;
    WM_HWIN hItem;
    
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTION_WBCHGB_RESULT);
    WM_InvalidateWindow(hItem);
    //WM_DisableWindow(hItem);

    // wbc prompt listview
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_WBC_PROMPT);
//    WM_InvalidateWindow(hItem);

    // qc prompt 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_PROMPT);
    WM_InvalidateWindow(hItem);

    // qc test info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_TEST_INFO);
    WM_InvalidateWindow(hItem);

    //Qc wbc histogram info
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_WBC_HISTOGRAM);
    WM_InvalidateWindow(hItem);
    
    //print button
    if(MachRunPara.tQC_WBCHGB_TestInfo.ulCurDataIndex != INVALID_DATA_SN)
    {
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT));
    }else{
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT));
    }
}





/*
*    QC Analysis send print  msg to backend
*/
static ErrorCode_e QC_Analysis_Print_Msg(WM_MESSAGE* pMsg)
{
    extern __IO MachRunPara_s	MachRunPara; 
    
    if(MachRunPara.tQC_WBCHGB_TestInfo.eFileNumIndex < QC_FILENUM_INDEX_END)
    {    
        QC_Record_t tQC_Record = {0};
        //消息头
        tQC_Record.tMsgHead.usCmd       = CMD_QC_PRINT;
        //消息体
        tQC_Record.ulCurDataIndex       = MachRunPara.tQC_WBCHGB_TestInfo.ulCurDataIndex;
        tQC_Record.eFileNumIndex        = MachRunPara.tQC_WBCHGB_TestInfo.eFileNumIndex;
        //发送消息给后端
        if(osOK != UI_Put_Msg((uint8_t*)&tQC_Record)) //osOk != ...
        {
            LOG_Error("Send Msg Fail");
            return ERROR_CODE_FAILURE;
        }
    }
    
    return ERROR_CODE_SUCCESS;
}



/*
*    质控，在控股，失控判断
*/
void Dis_Ctrol_Judge(__IO QC_WBCHGB_TestInfo_t *ptQC_WBCHGB_TestInfo)
{
    extern __IO MachRunPara_s MachRunPara;
    QC_FILENUM_INDEX_e eFileIndex = MachRunPara.eQC_Analysis_FileNum_Index;
    uint8_t i = 0;
    
    //
    ptQC_WBCHGB_TestInfo->eQC_Ctrl_Status = QC_CTRL_STATUS_IN;
    if(eFileIndex < QC_FILENUM_INDEX_END)
    {
        for(i = 0; i < WBCHGB_RST_END; i++)
        {
            if(MachRunPara.taQC_SetInfo[eFileIndex].faUpperLimit[i] <= ptQC_WBCHGB_TestInfo->fWBCHGB_RstData[i] || \
                ptQC_WBCHGB_TestInfo->fWBCHGB_RstData[i] <= MachRunPara.taQC_SetInfo[eFileIndex].faLowerLimit[i])
            {
                ptQC_WBCHGB_TestInfo->eQC_Ctrl_Status = QC_CTRL_STATUS_OUT;
                break;
            }
        }
    }
}    




/*********************************************************************
*
*       _cbDialog
*/
static void QC_Analysis_cbDialog(WM_MESSAGE * pMsg) {
    
  extern PrinterErrorType_e g_ePrinterErrorType;
  extern __IO MachRunPara_s MachRunPara;
    
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  {
      
    QC_Analysis_Msg_Init(pMsg);
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
      
    //进入质控分析时，切换计数模式为质控模式（在退出时，恢复到原来值）
    gs_eLastCountMode = Get_CountMode_Info()->ulCountMode;
    Set_CountMode(COUNT_MODE_QC_NORMAL);
    //Set_CountMode(COUNT_MODE_QC_OUTSIDE);
     
	  //禁止掉桌面按键
	AbortPublishDestopButton();
  }
  break;
  case WM_DELETE:
  {
	//退出质控分析时，恢复到原来模式
	Set_CountMode(gs_eLastCountMode);

	
  }
  break;
  case WM_ANALYSIS_GZ_AUTO_MODE_UPDATE_DATA:
  {     
  }
  break;
  case WM_PAINT:
  {
    //画背景BMP图
    //GUI_BMP_Draw(BKBmaDataBuf,1,0);
    //WINDOW_SetBkColor(hItem, MachInfo.companyInfo.skin.bg);

    //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
    GUI_RECT Rect;
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
      
    QC_Analysis_Msg_Updata(pMsg);
  }
  break;
  
  case WM_PRINTER_NO_PAPER:
  {
      //打印机缺纸
      g_ePrinterErrorType = PRINTER_NO_PAPER;
      //
      GUI_EndDialog(pMsg->hWin, 0);
      g_hActiveWin = Printer_Error_Prompt_PromptDLG();
      
      //GUI_MessageBox("Printer No Paper", "", 0);
  }
  break;
  case WM_PRINTER_CONN_ERR:
  {
      //打印机连接异常
      g_ePrinterErrorType = PRINTER_CONN_ERROR;
      //
      GUI_EndDialog(pMsg->hWin, 0);
      g_hActiveWin = Printer_Error_Prompt_PromptDLG();
      
      //GUI_MessageBox("Printer Conn Error", "", 0);
  }break;
  case WM_ANALYSIS_GIF_OPERATE_OUTIN_KEY:
  {
      extern __IO OutIn_Module_Position_e g_eOutIn_Key;
      extern __IO osSemaphoreId_t xSema_OutIn_Key;
      
      g_eOutIn_Key = OUTIN_MODULE_POSITION_IN;
      osSemaphoreRelease(xSema_OutIn_Key);
  }
  break;
  case WM_ANALYSIS_GIF_OPERATE_COUNT_KEY:
  {
      extern __IO osSemaphoreId_t xSema_Count_Key;
      osSemaphoreRelease(xSema_Count_Key);
  }
  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
   
    case ID_BUTTION_WBCHGB_RESULT: // Notifications sent by 'reslut_Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;

    case ID_BUTTON_RETURN: // Notifications sent by 'return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		Disable_Motor_Task();
	  
		//恢复桌面按键
		RecoverPublishDestopButton();
	  
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = QC_WindowDlG();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_PRINT: // Notifications sent by 'print_btn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
         QC_Analysis_Print_Msg(pMsg);
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
   case ID_DROPDOWN_FILE_NO: // Notifications sent by 'DROPDOWN FIlE NUM'
    switch (NCode) {
    case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
    case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
    case WM_NOTIFICATION_SEL_CHANGED:
    {
        // USER START (Optionally insert code for reacting on notification message)
        uint8_t ucTemp = 0;
        QC_Msg_t tQC_Msg = {0};
        
        ucTemp = DROPDOWN_GetSel(pMsg->hWinSrc);
        LOG_Info("Select Index=%d", ucTemp);
        if(ucTemp < QC_FILENUM_INDEX_END)
        {
            MachRunPara.eQC_Analysis_FileNum_Index = ucTemp;
          
            //构造消息，加载对于文件号对于的测试数据
            tQC_Msg.tMsgHead.usCmd = CMD_QC_UPDATE_ANALYSIS_DATA;
            tQC_Msg.ulIndex        = ucTemp; //文件号，下标
            //
            UI_Put_Msg((uint8_t*)&tQC_Msg); 
        }
        // USER END
    }
    break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
    }
    break;
            
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Analysis_Menu
*/
WM_HWIN QC_Analysis_Menu(void);
WM_HWIN QC_Analysis_Menu(void) {
    
  extern __IO osSemaphoreId_t xSema_Count_Key;
  WM_HWIN hWin;
  
  WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
  Public_Show_Widget();

  //使能算法任务
  Enable_Algo_Task(TRUE);
  
  //使能电机任务
  Enable_Motor_Task(TRUE); 
    
  //记录当前界面ID
  Set_Cur_MenuID(GUI_WINDOW_QC_ANALYSIS_ID);
	
  //UI 样本分析按键背景高亮
  Public_Reset_Btn_Status(BTN_MENU);
	
  hWin = GUI_CreateDialogBox(QC_Analysis_aDialogCreate, GUI_COUNTOF(QC_Analysis_aDialogCreate), QC_Analysis_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
