/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/


/*
*   质控列表界面
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_QC_LIST             (GUI_WINDOW_QC_LIST_ID + 0x00)
#define ID_BUTTON_PRINT               (GUI_WINDOW_QC_LIST_ID + 0x01)
#define ID_BUTTON_DELETE              (GUI_WINDOW_QC_LIST_ID + 0x02)
#define ID_BUTTON_DISCTROL            (GUI_WINDOW_QC_LIST_ID + 0x03)
#define ID_BUTTON_RETURN              (GUI_WINDOW_QC_LIST_ID + 0x04)
#define ID_TEXT_QC                    (GUI_WINDOW_QC_LIST_ID + 0x05)
#define ID_TEXT_QC_LIST               (GUI_WINDOW_QC_LIST_ID + 0x06)
#define ID_LISTVIEW_QC_DATA           (GUI_WINDOW_QC_LIST_ID + 0x07)
#define ID_BUTTON_LAST_RECORD         (GUI_WINDOW_QC_LIST_ID + 0x08)
#define ID_BUTTON_NEXT_RECORD         (GUI_WINDOW_QC_LIST_ID + 0x09)
#define ID_TEXT_FILE_NUM_TITLE        (GUI_WINDOW_QC_LIST_ID + 0x0A)
#define ID_TEXT_LOT_NUM               (GUI_WINDOW_QC_LIST_ID + 0x0B)
#define ID_TEXT_LEVEL                 (GUI_WINDOW_QC_LIST_ID + 0x0C)
#define ID_TEXT_SETER                 (GUI_WINDOW_QC_LIST_ID + 0x0D)
#define ID_TEXT_VALID_DATE            (GUI_WINDOW_QC_LIST_ID + 0x0E)
#define ID_TEXT_CAPACITY              (GUI_WINDOW_QC_LIST_ID + 0x0F)
#define ID_TEXT_OPERATOR              (GUI_WINDOW_QC_LIST_ID + 0x10)
#define ID_TEXT_QC_SN                 (GUI_WINDOW_QC_LIST_ID + 0x11)
#define ID_TEXT_CHECKTIME             (GUI_WINDOW_QC_LIST_ID + 0x12)
#define ID_DROPDOWN_FILE_NUM          (GUI_WINDOW_QC_LIST_ID + 0x13)
#define ID_TEXT_FILE_NUM_CONTEXT      (GUI_WINDOW_QC_LIST_ID + 0x14)
#define ID_TEXT_LEVEL_CONTEXT         (GUI_WINDOW_QC_LIST_ID + 0x15)
#define ID_TEXT_CAPACITY_CONTEXT      (GUI_WINDOW_QC_LIST_ID + 0x16)
#define ID_TEXT_QC_SN_CONTEXT         (GUI_WINDOW_QC_LIST_ID + 0x17)
#define ID_TEXT_CHECKTIME_CONTEXT     (GUI_WINDOW_QC_LIST_ID + 0x18)
#define ID_TEXT_OPERATOR_CONTEXT      (GUI_WINDOW_QC_LIST_ID + 0x19)
#define ID_TEXT_SETER_CONTEXT         (GUI_WINDOW_QC_LIST_ID + 0x1A)
#define ID_TEXT_VALID_DATE_CONTEXT    (GUI_WINDOW_QC_LIST_ID + 0x1B)


// USER START (Optionally insert additional defines)
// USER END


#define   LISTREVIEW_BTN_DISABLE_COLOR              0x00f3f1ec
// list view
#define GUI_LISTREVIEW_DISABLE_COLOR		        0x00f3f1ec

// header
#define GUI_LISTREVIEW_HEADER_BK_COLOR		        0xf1e7d2


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO QC_List_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "QC_List",   ID_WINDOW_QC_LIST,              0, 65, 800, 393, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",          ID_BUTTON_DISCTROL,             320, 8, 100, 40, 0, 0x0, 0 }, 
  { BUTTON_CreateIndirect, "",          ID_BUTTON_PRINT,                440, 8, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",          ID_BUTTON_DELETE,               560, 8, 100, 40, 0, 0x0, 0 }, 
  { BUTTON_CreateIndirect, "",          ID_BUTTON_RETURN,               680, 8, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_QC,                     25,  20, 60, 60, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_QC_LIST,                70, 15, 120, 40, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "",        ID_LISTVIEW_QC_DATA,            20, 180, 730, 200, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",          ID_BUTTON_LAST_RECORD,          742, 180, 40, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "",          ID_BUTTON_NEXT_RECORD,          742, 280, 40, 100, 0, 0x0, 0 },
  //
  { TEXT_CreateIndirect, "",            ID_TEXT_FILE_NUM_TITLE,         15, 75, 90, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_LOT_NUM,                20, 145, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_LEVEL,                  245, 75, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_SETER,                  235, 110, 75, 30, 0, 0x0, 0 }, //operate
  { TEXT_CreateIndirect, "",            ID_TEXT_VALID_DATE,             190, 145, 130, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_CAPACITY,               375, 75, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_OPERATOR,               360, 110, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_QC_SN,                  520, 75, 120, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_CHECKTIME,              530, 110, 100, 30, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "",        ID_DROPDOWN_FILE_NUM,           105, 80, 100, 160, 0, 0x0, 0 },
  //
  { TEXT_CreateIndirect, "",            ID_TEXT_FILE_NUM_CONTEXT,       90, 145, 115, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_LEVEL_CONTEXT,          310, 75, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_CAPACITY_CONTEXT,       465, 75, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_QC_SN_CONTEXT,          650, 75, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_CHECKTIME_CONTEXT,      635, 110, 160, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_OPERATOR_CONTEXT,       460, 110, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_SETER_CONTEXT,          315, 110, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",            ID_TEXT_VALID_DATE_CONTEXT,     325, 145, 120, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// QC List  按钮自定义 回调函数
static void QC_List_Btn_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        int Id;

        WM_GetClientRect(&Rect);
        Id = WM_GetId(pMsg->hWin);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            
            //根据区别不同btn
            //圆形btn
            if (ID_BUTTON_PRINT <= Id && Id <= ID_BUTTON_RETURN)
            {
                GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
                //往btn，写入字符或图标
                GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
                GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
            }
            //直角btn
            if (ID_BUTTON_LAST_RECORD == Id || Id == ID_BUTTON_NEXT_RECORD) //last/next one
            {
                GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
                GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
            }

            //
            if (ID_BUTTON_PRINT == Id)
            {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_DELETE == Id) {
                //删除
                GUI_DispStringInRect(g_ucaLng_Delete[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_DISCTROL == Id) {
                //失控
                GUI_DispStringInRect(g_ucaLng_LoseControl[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_RETURN == Id) {
                //返回
                GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_LAST_RECORD == Id) {
                //上一记录
				UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
            }else if (ID_BUTTON_NEXT_RECORD == Id) {
                //下一记录
				UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
            }
        }
        else {
            //根据区别不同btn
            //圆形btn
            if (ID_BUTTON_PRINT <= Id && Id <= ID_BUTTON_RETURN)
            {
				if(WM_IsEnabled(pMsg->hWin) == 1){
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 19);
					
					//往btn，写入字符或图标
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				}else{
					//填充
					GUI_SetColor(GUI_WHITE);
					GUI_AA_FillRoundedRectEx(&Rect,20);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,19);
					
					//设置字符前景和背景色
					GUI_SetColor(GUI_LIGHTGRAY);
					GUI_SetBkColor(GUI_WHITE);
				}
            }
            //直角btn
            if (ID_BUTTON_LAST_RECORD == Id || Id == ID_BUTTON_NEXT_RECORD)
            {        
				if(WM_IsEnabled(pMsg->hWin) == 1){
					GUI_SetColor(MachInfo.companyInfo.skin.title);
					GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
					//frame
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard); //画框
					GUI_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 0);
				}else{
					//淡色背景
					GUI_SetColor(0x00f3f1ec);
					GUI_FillRectEx(&Rect);
					GUI_SetColor(0x00cccccc);
					GUI_DrawRectEx(&Rect);
				}
            }

            if (ID_BUTTON_PRINT == Id)
            {
                //打印
                GUI_DispStringInRect(g_ucaLng_Print[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_DELETE == Id) {
                //删除
                GUI_DispStringInRect(g_ucaLng_Delete[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_DISCTROL == Id) {
                //失控
                GUI_DispStringInRect(g_ucaLng_LoseControl[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_RETURN == Id) {
                //返回
                GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_LAST_RECORD == Id) {
				if(WM_IsEnabled(pMsg->hWin) == 1){
					//上一记录
					UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
				}else{
					//上一记录
					UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
				}
            }else if (ID_BUTTON_NEXT_RECORD == Id) {
				if(WM_IsEnabled(pMsg->hWin) == 1){
					//下一记录
					UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
				}else{
					//下一记录
					UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
				}
            }
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
*    QC Analysis send  msg to backend 
*/
static ErrorCode_e QC_List_Send_Msg(WM_MESSAGE* pMsg, uint32_t usCmd)
{
    extern __IO MachRunPara_s	MachRunPara;
    
    //不为空，没到头，当前数据为有效数据
    if(MachRunPara.tQC_ListView_Data.eFileNumIndex < QC_FILENUM_INDEX_END)
    {   
        //
        QC_Record_t tQC_Record = {0};
        //消息头
        tQC_Record.tMsgHead.usCmd       = usCmd;
        //消息体
        tQC_Record.ulCurDataIndex       = MachRunPara.tQC_ListView_Data.ulCurDataIndex;
        tQC_Record.eFileNumIndex        = MachRunPara.tQC_ListView_Data.eFileNumIndex;
        //发送消息给后端
        if(osOK != UI_Put_Msg((uint8_t*)&tQC_Record)) //osOk != ...
        {
            LOG_Error("Send Msg Fail");
            return ERROR_CODE_FAILURE;
        }
    }

    return ERROR_CODE_SUCCESS;
}



/*
*   质控列表初始化
*/
static void QC_List_Msg_Init(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    uint8_t ucIndex = 0;
    char Buffer[64] = {0};
	HEADER_SKINFLEX_PROPS pProps;
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_QC_DATA);
	
    //设置HEADER皮肤属性
	LISTVIEW_GetHeader(hItem);
	HEADER_GetSkinFlexProps(&pProps,0);
	pProps.aColorLower[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorLower[1] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[1] = MachInfo.companyInfo.skin.title;
	HEADER_SetSkinFlexProps(&pProps,0);
	
    LISTVIEW_SetHeaderHeight(hItem, 50);
    //
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_UNSEL, GUI_WHITE);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SEL, MachInfo.companyInfo.skin.highlightKJNotSelect);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SELFOCUS, MachInfo.companyInfo.skin.highlightKJNotSelect);

    //3行
    LISTVIEW_SetRowHeight(hItem, 49);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_AddRow(hItem, NULL);
    LISTVIEW_AddRow(hItem, NULL);
    //9列
    LISTVIEW_AddColumn(hItem, 104, " ", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 77, "WBC", GUI_TA_HCENTER | GUI_TA_VCENTER);
	switch(MachInfo.companyInfo.company){
		case COMPANY_JIN_RUI:
		{
			//锦瑞
			LISTVIEW_AddColumn(hItem, 77, "Neu#", GUI_TA_HCENTER | GUI_TA_VCENTER);
		}break;
		
		default :
		{
			LISTVIEW_AddColumn(hItem, 77, "Gran#", GUI_TA_HCENTER | GUI_TA_VCENTER);
		}break;
	}
    LISTVIEW_AddColumn(hItem, 77, "Mid#", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 77, "Lym#", GUI_TA_HCENTER | GUI_TA_VCENTER);
	switch(MachInfo.companyInfo.company){
		case COMPANY_JIN_RUI:
		{
			//锦瑞
			LISTVIEW_AddColumn(hItem, 77, "Neu%", GUI_TA_HCENTER | GUI_TA_VCENTER);
		}break;
		
		default :
		{
			LISTVIEW_AddColumn(hItem, 77, "Gran%", GUI_TA_HCENTER | GUI_TA_VCENTER);
		}break;
	}
    LISTVIEW_AddColumn(hItem, 77, "Mid%", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 77, "Lym%", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 77, "HGB", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);

    //qc text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC);
    if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE)
    {
        TEXT_SetFont(hItem, &HZ_SONGTI_24);
    }else{
        TEXT_SetFont(hItem, &GUI_Font24_ASCII);
    }
    //TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, g_ucaLng_QC[MachInfo.systemSet.eLanguage]);

    //qc list text
    char buffer[64] = {0};
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_LIST);
    TEXT_SetFont(hItem, &HZ_SONGTI_16);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    sprintf(buffer, ">%s", g_ucaLng_QC_List[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, buffer);
    
    //dropdown 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_FILE_NUM);
    DROPDOWN_SetFont(hItem, GUI_FONT_24_ASCII);
    DROPDOWN_SetTextAlign(hItem, GUI_TA_VCENTER | GUI_TA_HCENTER);
    WM_SetSize(hItem, 100, 30);
    WM_SetCallback(hItem, Public_Dropdown_Callback);
    //
    MachRunPara.eQC_List_FileNum_Index = QC_FILENUM_INDEX_END;
    for(ucIndex = QC_FILENUM_INDEX_0; ucIndex < QC_FILENUM_INDEX_END; ucIndex++)
    {
        if(MachRunPara.taQC_SetInfo[ucIndex].eFileNumIndex < QC_FILENUM_INDEX_END)
        {
            MachRunPara.eQC_List_FileNum_Index = MachRunPara.taQC_SetInfo[ucIndex].eFileNumIndex;
            memset(Buffer, 0, sizeof(Buffer));
            sprintf(Buffer, "%d", MachRunPara.taQC_SetInfo[ucIndex].usFileNum);
            DROPDOWN_AddString(hItem, Buffer);
        } 
    }
    //
    if(MachRunPara.eQC_List_FileNum_Index == QC_FILENUM_INDEX_END)
    {
        //无效的文件号, 确保显示数据无效化，
        memset((void*)&MachRunPara.tQC_ListView_Data, 0, sizeof(QC_WBCHGB_TestInfo_t));
        MachRunPara.tQC_ListView_Data.eFileNumIndex = QC_FILENUM_INDEX_END;
        MachRunPara.tQC_ListView_Data.ulCurDataIndex = INVALID_DATA_SN;
        //
        DROPDOWN_SetSel(hItem, 0);
    }else{
        DROPDOWN_SetSel(hItem, MachRunPara.eQC_List_FileNum_Index);
    }
    
    //
    // Initialization of 'FileNum'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FILE_NUM_TITLE);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_FileNO[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);
    //
    // Initialization of 'LotNum'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LOT_NUM);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_LotNO[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);    

    //
    // Initialization of 'level'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LEVEL);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_Level[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);

    //
    // Initialization of 'seter'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SETER);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_Seter[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);
    
    //
    // Initialization of 'validdate'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VALID_DATE);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_ValidDate[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);

    //
    // Initialization of 'capacity'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CAPACITY);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_Capacity[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);

    //
    // Initialization of 'operator'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_OPERATOR);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_Operator[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);

    //
    // Initialization of 'QC_SN'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_SN);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_QCSampleSN[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);

    //
    // Initialization of 'checktime'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CHECKTIME);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    memset(Buffer, 0, sizeof(Buffer));
    sprintf(Buffer, "%s:", g_ucaLng_CheckTime[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, Buffer);
    
    //
    // Initialization of 'LotNum_c'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FILE_NUM_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //TEXT_SetText(hItem, g_ucaLng_LotNO[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'middle'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LEVEL_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //TEXT_SetText(hItem, g_ucaLng_QCSampleSN[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'capacity_c'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CAPACITY_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'QC_SN_C'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_SN_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'checktime_c'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CHECKTIME_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'operator_c'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_OPERATOR_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'admin'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SETER_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    
    //
    // Initialization of 'validdate_c'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VALID_DATE_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    
    //btn print
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT);
    WM_SetCallback(hItem, QC_List_Btn_Callback);
    //btn edit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE);
    WM_SetCallback(hItem, QC_List_Btn_Callback);
    //btn disctrol
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DISCTROL);
    WM_SetCallback(hItem, QC_List_Btn_Callback);
    WM_HideWindow(hItem); /////////////////////////
    
    //btn return
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
    WM_SetCallback(hItem, QC_List_Btn_Callback);
    //btn last one
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LAST_RECORD);
    WM_SetCallback(hItem, QC_List_Btn_Callback);
    //btn next one
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEXT_RECORD);
    WM_SetCallback(hItem, QC_List_Btn_Callback);
    
}



/*
*   质控，重绘
*/
static void QC_List_Paint_Msg(WM_MESSAGE *pMsg)
{
	extern  MachInfo_s	MachInfo;
    WM_HWIN hItem;
    uint8_t i = 0;
    uint8_t ucFileNum = 0;
    
//    uint32_t ulID = 0;
    char Buffer[32] = {0};
  
    //
    ucFileNum = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_FILE_NUM));
    if(ucFileNum < QC_FILENUM_INDEX_END)
    {
        //Lot Num
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FILE_NUM_CONTEXT);
    //    sprintf(Buffer, "%s", MachRunPara.taQC_SetInfo[MachRunPara.tQC_ListView_Data.eFileNumIndex].ucaLotNum);
        sprintf(Buffer, "%s", MachRunPara.taQC_SetInfo[ucFileNum].ucaLotNum);
        TEXT_SetText(hItem, Buffer);
        
        //valid date
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VALID_DATE_CONTEXT);
    //    sprintf(Buffer, "%s", MachRunPara.taQC_SetInfo[MachRunPara.tQC_ListView_Data.eFileNumIndex].ucaValidDate);
        sprintf(Buffer, "%s", MachRunPara.taQC_SetInfo[ucFileNum].ucaValidDate);
        TEXT_SetText(hItem, Buffer);

             //level
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LEVEL_CONTEXT);
        if(QC_LEVEL_HIGH == MachRunPara.tQC_ListView_Data.eQC_Level)
        {
           TEXT_SetText(hItem, g_ucaLng_High[MachInfo.systemSet.eLanguage]);
        }else if(QC_LEVEL_MIDDLE == MachRunPara.tQC_ListView_Data.eQC_Level){
           TEXT_SetText(hItem, g_ucaLng_Middle[MachInfo.systemSet.eLanguage]);
        }else if(QC_LEVEL_LOW == MachRunPara.tQC_ListView_Data.eQC_Level){
           TEXT_SetText(hItem, g_ucaLng_Low[MachInfo.systemSet.eLanguage]);
        }
        
        //seter
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SETER_CONTEXT);
        
        //
       sprintf(Buffer, "%s", MachInfo.accountMM.accountInfo[MachRunPara.taQC_SetInfo[ucFileNum].eSeter].user);
        
        TEXT_SetText(hItem, Buffer);
    }
    
    //
    if(MachRunPara.tQC_ListView_Data.eFileNumIndex < QC_FILENUM_INDEX_END && MachRunPara.tQC_ListView_Data.ulCurDataIndex != INVALID_DATA_SN)
    {
        //有数据可以显示
        //check time
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CHECKTIME_CONTEXT);
        sprintf(Buffer, "%s", MachRunPara.tQC_ListView_Data.ucaDateTime);
        TEXT_SetText(hItem, Buffer);
        
        //qc sn
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_SN_CONTEXT);
        sprintf(Buffer, "%s", MachRunPara.tQC_ListView_Data.ucaSampleSN);
        TEXT_SetText(hItem, Buffer);
        
        
         //oeprator
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_OPERATOR_CONTEXT);
        sprintf(Buffer, "%s", MachInfo.accountMM.accountInfo[MachRunPara.tQC_ListView_Data.eSeter].user);
        TEXT_SetText(hItem, Buffer);
        
        //data capacity 
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CAPACITY_CONTEXT);
        sprintf(Buffer, "%d/%d", Get_QC_ValidNum(MachRunPara.tQC_ListView_Data.eFileNumIndex), MachRunPara.tQC_ListView_Data.usTestCapacity);    //
        TEXT_SetText(hItem, Buffer);
        
        //list view
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_QC_DATA);
        //清除的内容
        for (i = 0; i < WBCHGB_RST_END+1; i++)
        {                            //列 //行
            LISTVIEW_SetItemText(hItem, i, 0, " "); 
            LISTVIEW_SetItemText(hItem, i, 1, " "); 
            LISTVIEW_SetItemText(hItem, i, 2, " "); 
        }
        
        //
        //第一列                       
        LISTVIEW_SetItemText(hItem, 0, 0, g_ucaLng_UpperLimit[MachInfo.systemSet.eLanguage]); 
        LISTVIEW_SetItemText(hItem, 0, 1, g_ucaLng_LowerLimit[MachInfo.systemSet.eLanguage]); 
        for(i = 0; i < WBCHGB_RST_END; i++)
        {
            //第二到九列
            memset(Buffer, 0, sizeof(Buffer));
            sprintf(Buffer, "%.2f", MachRunPara.taQC_SetInfo[MachRunPara.tQC_ListView_Data.eFileNumIndex].faUpperLimit[i]);
            LISTVIEW_SetItemText(hItem, i+1, 0, Buffer); 
            memset(Buffer, 0, sizeof(Buffer));
            sprintf(Buffer, "%.2f", MachRunPara.taQC_SetInfo[MachRunPara.tQC_ListView_Data.eFileNumIndex].faLowerLimit[i]);
            LISTVIEW_SetItemText(hItem, i+1, 1, Buffer); 
            memset(Buffer, 0, sizeof(Buffer));
            QC_Display_Result_Info(Buffer, i, &MachRunPara.tQC_ListView_Data);
            LISTVIEW_SetItemText(hItem, i+1, 2, Buffer); 
        
        } 
    }else{
        //无数据，显示标题等
        //Lot Num
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FILE_NUM_CONTEXT);
//        TEXT_SetText(hItem, " ");
//        
//        //valid date
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VALID_DATE_CONTEXT);
//        TEXT_SetText(hItem, Buffer);
        
        //check time
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CHECKTIME_CONTEXT);
        TEXT_SetText(hItem, " ");
        
        //qc sn
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_SN_CONTEXT);
        TEXT_SetText(hItem, " ");
        
         //level
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LEVEL_CONTEXT);
//        TEXT_SetText(hItem, " ");
        
        //seter
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_SETER_CONTEXT);
//        TEXT_SetText(hItem, " ");
        
         //oeprator
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_OPERATOR_CONTEXT);
        TEXT_SetText(hItem, " ");
        
        //data capacity 
        memset(Buffer, 0, sizeof(Buffer));
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_CAPACITY_CONTEXT);
        sprintf(Buffer, "%d/%d", Get_QC_ValidNum(MachRunPara.tQC_ListView_Data.eFileNumIndex), MachRunPara.tQC_ListView_Data.usTestCapacity);
        TEXT_SetText(hItem, Buffer);
        
        //list view
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_QC_DATA);
        //清除的内容
        for (i = 0; i < 9; i++)
        {                            //列 //行
            LISTVIEW_SetItemText(hItem, i, 0, " "); 
            LISTVIEW_SetItemText(hItem, i, 1, " "); 
            LISTVIEW_SetItemText(hItem, i, 1, " "); 
        }
        
        //
        ucFileNum = DROPDOWN_GetSel(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_FILE_NUM));
        //第一列                       
        LISTVIEW_SetItemText(hItem, 0, 0, g_ucaLng_UpperLimit[MachInfo.systemSet.eLanguage]); 
        LISTVIEW_SetItemText(hItem, 0, 1, g_ucaLng_LowerLimit[MachInfo.systemSet.eLanguage]); 
        for(i = 0; i < WBCHGB_RST_END; i++)
        {
            //第二到九列(无数据时，会显示上下限的值)
            memset(Buffer, 0, sizeof(Buffer));
            //sprintf(Buffer, "%.2f", MachRunPara.taQC_SetInfo[MachRunPara.tQC_ListView_Data.eFileNumIndex].faUpperLimit[i]);
            sprintf(Buffer, "%.2f", MachRunPara.taQC_SetInfo[ucFileNum].faUpperLimit[i]);
            LISTVIEW_SetItemText(hItem, i+1, 0, Buffer); 
            memset(Buffer, 0, sizeof(Buffer));
            sprintf(Buffer, "%.2f", MachRunPara.taQC_SetInfo[ucFileNum].faLowerLimit[i]);
            LISTVIEW_SetItemText(hItem, i+1, 1, Buffer); 
            memset(Buffer, 0, sizeof(Buffer));
            //QC_Display_Result_Info(Buffer, i, &MachRunPara.tQC_ListView_Data);
            LISTVIEW_SetItemText(hItem, i+1, 2, " "); 
        
        }     
    }
    
    //上下记录，控件处理
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LAST_RECORD));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEXT_RECORD));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE));
    //失能上一记录
    if(MachRunPara.tQC_ListView_Data.ulLastValidIndex == INVALID_DATA_SN)
    {
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_LAST_RECORD));
    }
    //失能下一记录
    if(MachRunPara.tQC_ListView_Data.ulNextValidIndex == INVALID_DATA_SN)
    {
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEXT_RECORD));
    }
    //
    if(MachRunPara.tQC_ListView_Data.ulCurDataIndex == INVALID_DATA_SN)
    {
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_PRINT));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE));
    }
    
}

// USER START (Optionally insert additional static code)
// USER END


/*********************************************************************
*
*       _cbDialog
*/
static void QC_List_cbDialog(WM_MESSAGE * pMsg) 
{
  extern __IO MachRunPara_s MachRunPara;
  
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listview'
    //
    QC_List_Msg_Init(pMsg);
    
    //设置窗口颜色
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_PAINT:
  {
    //画背景BMP图  
    //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
    GUI_RECT Rect;
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
      
    //画线
    WM_GetClientRect(&Rect);   
    GUI_SetColor(GUI_SPLINE_LINE_COLOR);
    GUI_DrawHLine(Rect.y0+55, Rect.x0+10, Rect.x1-10);
      
    //
    QC_List_Paint_Msg(pMsg);
    
  }
  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_PRINT: // Notifications sent by 'print'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
         // USER START (Optionally insert code for reacting on notification message) 
          if(MachRunPara.tQC_ListView_Data.ulCurDataIndex != INVALID_DATA_SN)
          {
            QC_List_Send_Msg(pMsg, CMD_QC_PRINT);
          }
         // USER END.
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_DELETE: // Notifications sent by 'delete'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
          QC_List_Send_Msg(pMsg, CMD_QC_LIST_DELETE);
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_DISCTROL: // Notifications sent by 'disctrol'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_RETURN: // Notifications sent by 'return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin,0);
        g_hActiveWin = QC_WindowDlG();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_QC_DATA: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_LAST_RECORD: // Notifications sent by 'lastone'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {

         QC_List_Send_Msg(pMsg, CMD_QC_LIST_LAST_RECORD);    //较新的一个
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_NEXT_RECORD: // Notifications sent by 'nextone'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
         QC_List_Send_Msg(pMsg, CMD_QC_LIST_NEXT_RECORD);   //较旧的一个
      }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_FILE_NUM: // Notifications sent by 'FileNum'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
      {
          //切换文件号时，需更新列表显示数据          
          uint8_t ucIndex = 0;
          QC_Msg_t tQC_Msg = {0};
          //
          ucIndex = DROPDOWN_GetSel(pMsg->hWinSrc);
          MachRunPara.eQC_List_FileNum_Index = ucIndex; //更新下标
          
          //构造消息，加载对于文件号对于的测试数据
          tQC_Msg.tMsgHead.usCmd = CMD_QC_UPDATE_LIST_DATA;
          tQC_Msg.ulIndex        = ucIndex; //文件号，下标
          //
          UI_Put_Msg((uint8_t*)&tQC_Msg);
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN QC_List_CreateWindow(void);
WM_HWIN QC_List_CreateWindow(void) {
  WM_HWIN hWin;

	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(QC_List_aDialogCreate, GUI_COUNTOF(QC_List_aDialogCreate), QC_List_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
