/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"

/*
*   质控设定界面
*/



/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_QC_SET        (GUI_WINDOW_QC_SET_ID + 0x00)
#define ID_BUTTON_NEW           (GUI_WINDOW_QC_SET_ID + 0x01)
#define ID_BUTTON_EDIT          (GUI_WINDOW_QC_SET_ID + 0x02)
#define ID_BUTTON_DELETE        (GUI_WINDOW_QC_SET_ID + 0x03)
#define ID_BUTTON_RETURN        (GUI_WINDOW_QC_SET_ID + 0x04)
#define ID_TEXT_QC              (GUI_WINDOW_QC_SET_ID + 0x05)
#define ID_TEXT_QC_SET          (GUI_WINDOW_QC_SET_ID + 0x06)
#define ID_LISTVIEW_FILE_NUM    (GUI_WINDOW_QC_SET_ID + 0x07)
#define ID_TEXT_FILE_NUM        (GUI_WINDOW_QC_SET_ID + 0x08)
#define ID_TEXT_LOT_NUM         (GUI_WINDOW_QC_SET_ID + 0x09)
#define ID_TEXT_LEVEL           (GUI_WINDOW_QC_SET_ID + 0x0A)
#define ID_TEXT_VALID_DATE      (GUI_WINDOW_QC_SET_ID + 0x0B)
#define ID_DROPDOWN_LEVEL       (GUI_WINDOW_QC_SET_ID + 0x0E)
#define ID_TEXT_ERROR_PROMPT    (GUI_WINDOW_QC_SET_ID + 0x0F)
#define ID_BUTTON_CANCEL        (GUI_WINDOW_QC_SET_ID + 0x10)
#define ID_BUTTON_SAVE          (GUI_WINDOW_QC_SET_ID + 0x11)
//
#define ID_TEXT_FILE_NUM_CONTEXT (GUI_WINDOW_QC_SET_ID + 0x12)
#define ID_TEXT_VALID_DATE_FORMAT (GUI_WINDOW_QC_SET_ID + 0x13)

//以下系列号，需保持连续
#define ID_EDIT_VALID_DATE      (GUI_WINDOW_QC_SET_ID + 0x14)
#define ID_EDIT_LOT_NUM_1       (GUI_WINDOW_QC_SET_ID + 0x15)
//
#define ID_EDIT_WBC_LOWER       (GUI_WINDOW_QC_SET_ID + 0x16)
#define ID_EDIT_WBC_UPPER       (GUI_WINDOW_QC_SET_ID + 0x17)
#define ID_EDIT_GranJ_LOWER     (GUI_WINDOW_QC_SET_ID + 0x18)
#define ID_EDIT_GranJ_UPPER     (GUI_WINDOW_QC_SET_ID + 0x19)
#define ID_EDIT_MidJ_LOWER      (GUI_WINDOW_QC_SET_ID + 0x1A)
#define ID_EDIT_MidJ_UPPER      (GUI_WINDOW_QC_SET_ID + 0x1B)
#define ID_EDIT_LymJ_LOWER      (GUI_WINDOW_QC_SET_ID + 0x1C)
#define ID_EDIT_LymJ_UPPER      (GUI_WINDOW_QC_SET_ID + 0x1D)
#define ID_EDIT_GranB_LOWER     (GUI_WINDOW_QC_SET_ID + 0x1E)
#define ID_EDIT_GranB_UPPER     (GUI_WINDOW_QC_SET_ID + 0x1F)
#define ID_EDIT_MidB_LOWER      (GUI_WINDOW_QC_SET_ID + 0x20)
#define ID_EDIT_MidB_UPPER      (GUI_WINDOW_QC_SET_ID + 0x21)
#define ID_EDIT_LymB_LOWER      (GUI_WINDOW_QC_SET_ID + 0x22)
#define ID_EDIT_LymB_UPPER      (GUI_WINDOW_QC_SET_ID + 0x23)
#define ID_EDIT_HGB_LOWER       (GUI_WINDOW_QC_SET_ID + 0x24)
#define ID_EDIT_HGB_UPPER       (GUI_WINDOW_QC_SET_ID + 0x25)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/



static __IO uint8_t gs_ucFlag = 0xFF;                                          //质控设定状态，0：新建状态，1：编辑状态，其他。。。
//static uint8_t gs_ucFileNum_ListVew_Index         = QC_FILENUM_INDEX_END; //质控设定中 列表控件中，已选中的文件号（当前最多六行）
__IO uint8_t gs_ucFileNum_ListVew_Index             = QC_FILENUM_INDEX_END;        //质控设定中 列表控件中，已选中的文件号（当前最多六行）的index
//static uint8_t gs_ucFileNum_ListView_MaxIndex     = QC_FILENUM_INDEX_END; //当前最大的文件号，索引值，（当前最大6个，有效放在前面）
static __IO uint8_t gs_ucFileNum_ListView_MaxIndex  = QC_FILENUM_INDEX_END; //列表控件中，最大的索引值，（当前最大6个，有效放在前面）

static __IO uint8_t gs_QC_Set_MoveFlag    = 0;             //窗口移动标志位，0：未移动，1：已移动
#define QC_SET_X_MOVE_LEN                 0
#define QC_SET_Y_MOVE_LEN                 33

#define QC_SET_EDIT_CHAR_MAX_LEN          7
/*********************************************************************
*
*       _aDialogCreate
*/
#define LIMIT_EDIT_LEN      80
#define LIMIT_EDIT_HIGH     27
#define LIMIT_EDIT_Y        111
static const GUI_WIDGET_CREATE_INFO QC_Set_aDialogCreate[] = {
  { WINDOW_CreateIndirect,      "", ID_WINDOW_QC_SET,       0, 65, 800, 393, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "", ID_BUTTON_NEW,          320, 8, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "", ID_BUTTON_EDIT,         440, 8, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "", ID_BUTTON_DELETE,       560, 8, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "", ID_BUTTON_RETURN,       680, 8, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_QC,             25,  20, 60, 60, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_QC_SET,         70, 15, 120, 40, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect,    "", ID_LISTVIEW_FILE_NUM,   20, 65, 170, 310, 0, 0x0, 0 },
  //
//  { EDIT_CreateIndirect,        "", ID_EDIT_NONE,           290, 80, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_FILE_NUM,       225, 111, 70, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_LOT_NUM,        230, 151, 60, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_LEVEL,          230, 191, 60, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_VALID_DATE,     180, 235, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_VALID_DATE_FORMAT,295, 260, 120, 20, 0, 0x0, 0 },
//  { EDIT_CreateIndirect,        "", ID_EDIT_FILE_NUM,       290, 111, 120, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_FILE_NUM_CONTEXT, 300, 111, 120, 30, 0, 0x0, 0 },
  
  { EDIT_CreateIndirect,        "", ID_EDIT_LOT_NUM_1,        300, 151, 130, 30, 0, 0x64, 0 },
  { DROPDOWN_CreateIndirect,    "", ID_DROPDOWN_LEVEL,      300, 191, 120, 60, 0, 0x0, 0 },

//  { DROPDOWN_CreateIndirect,    "", ID_DROPDOWN_LEVEL,      290, 151, 120, 60, 0, 0x0, 0 }, 
//  { EDIT_CreateIndirect,        "", ID_EDIT_LOT_NUM_1,      290, 191, 120, 30, 0, 0x64, 0 },
  { EDIT_CreateIndirect,        "", ID_EDIT_VALID_DATE,     295, 231, 130, 30, 0, 0x64, 0 },
//  { TEXT_CreateIndirect,      "", ID_TEXT_LIMIT,          450, 75, 300, 300, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "", ID_BUTTON_CANCEL,       218, 295, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,      "", ID_BUTTON_SAVE,         338, 295, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect,        "", ID_TEXT_ERROR_PROMPT,   220, 335, 200, 55, 0, 0x0, 0 },
  //下限
  { EDIT_CreateIndirect, "", ID_EDIT_WBC_LOWER,     560, LIMIT_EDIT_Y+33*0, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_GranJ_LOWER,   560, LIMIT_EDIT_Y+33*1, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },  
  { EDIT_CreateIndirect, "", ID_EDIT_MidJ_LOWER,    560, LIMIT_EDIT_Y+33*2, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_LymJ_LOWER,    560, LIMIT_EDIT_Y+33*3, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 }, 
  { EDIT_CreateIndirect, "", ID_EDIT_GranB_LOWER,   560, LIMIT_EDIT_Y+33*4, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_MidB_LOWER,    560, LIMIT_EDIT_Y+33*5, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },  
  { EDIT_CreateIndirect, "", ID_EDIT_LymB_LOWER,    560, LIMIT_EDIT_Y+33*6, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_HGB_LOWER,     560, LIMIT_EDIT_Y+33*7, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  //上限
  { EDIT_CreateIndirect, "", ID_EDIT_WBC_UPPER,     660, LIMIT_EDIT_Y+33*0, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_GranJ_UPPER,   660, LIMIT_EDIT_Y+33*1, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },  
  { EDIT_CreateIndirect, "", ID_EDIT_MidJ_UPPER,    660, LIMIT_EDIT_Y+33*2, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_LymJ_UPPER,    660, LIMIT_EDIT_Y+33*3, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 }, 
  { EDIT_CreateIndirect, "", ID_EDIT_GranB_UPPER,   660, LIMIT_EDIT_Y+33*4, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_MidB_UPPER,    660, LIMIT_EDIT_Y+33*5, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },  
  { EDIT_CreateIndirect, "", ID_EDIT_LymB_UPPER,    660, LIMIT_EDIT_Y+33*6, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_HGB_UPPER,     660, LIMIT_EDIT_Y+33*7, LIMIT_EDIT_LEN, LIMIT_EDIT_HIGH, 0, 0x64, 0 },
  
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END



/*
*   使能所有edit，
*/
static void Enable_Edit_All(WM_MESSAGE *pMsg)
{
    uint32_t i = 0;
    
    for(i = ID_EDIT_VALID_DATE; i <= ID_EDIT_HGB_UPPER; i++)
    {
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, i));
    }
}


/*
*   使能所有edit，
*/
static void Disable_Edit_All(WM_MESSAGE *pMsg)
{
    uint32_t i = 0;
    
    for(i = ID_EDIT_VALID_DATE; i <= ID_EDIT_HGB_UPPER; i++)
    {
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, i));
    }
}



/*
*QC Set  按钮自定义 回调函数
*/
static void QC_Set_Btn_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        int Id;

        WM_GetClientRect(&Rect);
        Id = WM_GetId(pMsg->hWin);

        if (BUTTON_IsPressed(pMsg->hWin)) {
            
            GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
            GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
            
			//往btn，写入字符或图标
            GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
            GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
            
            //
            if (ID_BUTTON_NEW == Id)
            {
                //新建
                GUI_DispStringInRect(g_ucaLng_New[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_EDIT == Id) {
                //编辑
                GUI_DispStringInRect(g_ucaLng_Edit[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_DELETE == Id) {
                //删除
                GUI_DispStringInRect(g_ucaLng_Delete[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_RETURN == Id) {
                //返回
                GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_CANCEL == Id) {
                //取消
                GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);              
            }else if (ID_BUTTON_SAVE == Id) {
                //保存
                GUI_DispStringInRect(g_ucaLng_Save[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
        else {
			if(WM_IsEnabled(pMsg->hWin) == 1){
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
				GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 20);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 19);
				
				//往btn，写入字符或图标
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			}else{
				//填充
				GUI_SetColor(GUI_WHITE);
				GUI_AA_FillRoundedRectEx(&Rect,20);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRectEx(&Rect,19);
				
				//设置字符前景和背景色
				GUI_SetColor(GUI_LIGHTGRAY);
				GUI_SetBkColor(GUI_WHITE);
			}

            //
            if (ID_BUTTON_NEW == Id)
            {
                //新建
                GUI_DispStringInRect(g_ucaLng_New[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_EDIT == Id) {
                //编辑
                GUI_DispStringInRect(g_ucaLng_Edit[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_DELETE == Id) {
                //删除
                GUI_DispStringInRect(g_ucaLng_Delete[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_RETURN == Id) {
                //返回
                GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }else if (ID_BUTTON_CANCEL == Id) {
                //取消
                GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);              
            }else if (ID_BUTTON_SAVE == Id) {
                //保存
                GUI_DispStringInRect(g_ucaLng_Save[MachInfo.systemSet.eLanguage], &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}


/*
*  上下限输入 自定义 回调函数
*/
static void Draw_Upper_Lower_Limit_Background(WM_MESSAGE* pMsg)
{
    //
    extern __IO MachRunPara_s MachRunPara;
    const unsigned char RoundRadius  = 3; //倒角弧度
    const unsigned char Hight	     = 33; //每行高度
    const unsigned short Lenght	     = 300; //每行长度
    int i = 0;
	
	char TitleBuffer[7][6] = {0};
	
	switch(MachInfo.companyInfo.company){
		case COMPANY_JIN_RUI:
		{
			//锦瑞
			strcpy(&TitleBuffer[0][0],"WBC");
			strcpy(&TitleBuffer[1][0],"Neu#");
			strcpy(&TitleBuffer[2][0],"Mid#");
			strcpy(&TitleBuffer[3][0],"Lym#");
			strcpy(&TitleBuffer[4][0],"Neu%");
			strcpy(&TitleBuffer[5][0],"Mid%");
			strcpy(&TitleBuffer[6][0],"Lym%");
		}break;
		
		default :
		{
			strcpy(&TitleBuffer[0][0],"WBC");
			strcpy(&TitleBuffer[1][0],"Gran#");
			strcpy(&TitleBuffer[2][0],"Mid#");
			strcpy(&TitleBuffer[3][0],"Lym#");
			strcpy(&TitleBuffer[4][0],"Gran%");
			strcpy(&TitleBuffer[5][0],"Mid%");
			strcpy(&TitleBuffer[6][0],"Lym%");
		}break;
	}
    
    GUI_RECT Rect, TempRect = {0};
    // WM_GetClientRect(&Rect);
    Rect.x0 = 450;
    Rect.y0 = 75;
    Rect.x1 = Rect.x0 + 300;
    Rect.y1 = Rect.y0 + 297;

    //第一行，标题、背景
    GUI_SetColor(MachInfo.companyInfo.skin.title);
    GUI_AA_FillRoundedRect(Rect.x0, Rect.y0, Rect.x0+Lenght, Rect.y0+Hight+RoundRadius, RoundRadius);
    //字体颜色
    GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
    GUI_SetBkColor(MachInfo.companyInfo.skin.title);
    //参数
    TempRect.x0 = Rect.x0;           TempRect.y0 = Rect.y0;
    TempRect.x1 = Rect.x0+100;       TempRect.y1 = Rect.y0+Hight;
    GUI_DispStringInRect(g_ucaLng_Param[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);
    //下限
    TempRect.x0 = Rect.x0+100;       TempRect.y0 = Rect.y0;
    TempRect.x1 = Rect.x0+200;       TempRect.y1 = Rect.y0+Hight;
    GUI_DispStringInRect(g_ucaLng_LowerLimit[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);
    //上限
    TempRect.x0 = Rect.x0+200;       TempRect.y0 = Rect.y0;
    TempRect.x1 = Rect.x0+300;       TempRect.y1 = Rect.y0+Hight;
    GUI_DispStringInRect(g_ucaLng_UpperLimit[MachInfo.systemSet.eLanguage], &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);
               

    //第九行（最后一行），HGB
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0, Rect.y0+Hight*2-RoundRadius, Rect.x0+Lenght, Rect.y0+Hight*3+RoundRadius, RoundRadius);
    //字体颜色
    GUI_SetColor(GUI_BLACK);
    GUI_SetBkColor(GUI_WHITE);
    //HGB
    TempRect.x0 = Rect.x0;           TempRect.y0 = Rect.y0+Hight*8;
    TempRect.x1 = Rect.x0+100;       TempRect.y1 = Rect.y0+Hight*9;
    GUI_DispStringInRect("HGB", &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);
    //HGB下限
    TempRect.x0 = Rect.x0+100;       TempRect.y0 = Rect.y0+Hight*8;
    TempRect.x1 = Rect.x0+200;       TempRect.y1 = Rect.y0+Hight*9;
    //GUI_DispStringInRect((char*)"HGB Lower", &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);
    //HGB上限
    TempRect.x0 = Rect.x0+200;       TempRect.y0 = Rect.y0+Hight*8;
    TempRect.x1 = Rect.x0+300;       TempRect.y1 = Rect.y0+Hight*9;
    //GUI_DispStringInRect((char*)"HGB Upper", &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);


    //第二到八行，背景
    for(i = 2; i < 9; i++)
    {
        GUI_SetColor(GUI_WHITE);
        GUI_AA_FillRoundedRect(Rect.x0, Rect.y0+Hight*(i-1), Rect.x0+Lenght, Rect.y0+Hight*i, RoundRadius);
        //字体颜色
        GUI_SetColor(GUI_BLACK);
        GUI_SetBkColor(GUI_WHITE);
        
        //参数
        TempRect.x0 = Rect.x0;           TempRect.y0 = Rect.y0+Hight*(i-1);
        TempRect.x1 = Rect.x0+100;       TempRect.y1 = Rect.y0+Hight*i;
        GUI_DispStringInRect(TitleBuffer[i-2], &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);
        
        //下限
        TempRect.x0 = Rect.x0+100;       TempRect.y0 = Rect.y0+Hight*(i-1);
        TempRect.x1 = Rect.x0+200;       TempRect.y1 = Rect.y0+Hight*i;
        //GUI_DispStringInRect("UP", &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);

        //上限
        TempRect.x0 = Rect.x0+200;       TempRect.y0 = Rect.y0+Hight*(i-1);
        TempRect.x1 = Rect.x0+300;       TempRect.y1 = Rect.y0+Hight*i;
        //GUI_DispStringInRect((char*)"Down ", &TempRect, GUI_TA_VCENTER | GUI_TA_HCENTER);
    }

    //外框
    GUI_SetColor(GUI_TEXT_FRAME_COLOR);
    GUI_AA_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, RoundRadius);

    //水平分割线
    GUI_DrawHLine(Rect.y0+Hight, Rect.x0, Rect.x1);
    for(i = 2; i < 9; i++)
    {     
        GUI_DrawHLine(Rect.y0+Hight*i, Rect.x0, Rect.x1);
    }
    //垂直分割线
    GUI_DrawVLine(Rect.x0+100, Rect.y0, Rect.y1);
    GUI_DrawVLine(Rect.x0+200, Rect.y0, Rect.y1);
    //GUI_DrawVLine(Rect.x0+300, Rect.y0, Rect.y1);
}



/*
*   质控、刷新接口
*/
static void QC_Set_Msg_Init(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int i = 0;
    char buffer[128] = {0};
	HEADER_SKINFLEX_PROPS pProps;
    //
    // Initialization of 'Listview'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM);
    //设置HEADER皮肤属性
	LISTVIEW_GetHeader(hItem);
	HEADER_GetSkinFlexProps(&pProps,0);
	pProps.aColorLower[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorLower[1] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[1] = MachInfo.companyInfo.skin.title;
	HEADER_SetSkinFlexProps(&pProps,0);
	
    LISTVIEW_SetHeaderHeight(hItem, 44);
    //
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_UNSEL, GUI_WHITE);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SEL, MachInfo.companyInfo.skin.highlightKJNotSelect);
    LISTVIEW_SetBkColor(hItem, LISTVIEW_CI_SELFOCUS, MachInfo.companyInfo.skin.highlightKJNotSelect);
    LISTVIEW_SetGridVis(hItem, 1);
    //两列
    LISTVIEW_AddColumn(hItem, 70, g_ucaLng_FileNO[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 100, g_ucaLng_Capacity[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    //六行
    LISTVIEW_SetRowHeight(hItem, 44);
    for(i = 0; i < QC_FILENUM_INDEX_END; i++)
    {
        LISTVIEW_AddRow(hItem, NULL);
    }
    //清除的内容
    for (i = 0; i < QC_FILENUM_INDEX_END; i++)
    {
        LISTVIEW_SetItemText(hItem, 0, i, " "); 
        LISTVIEW_SetItemText(hItem, 1, i, " ");
    }
    //
    gs_ucFileNum_ListVew_Index = QC_FILENUM_INDEX_END;
    for (i = 0; i < QC_FILENUM_INDEX_END; i++)
    {
        //当usFileNum == QC_FILENUM_INDEX_END表示改行文件号未使用（不需要显示）
        if(QC_FILENUM_INDEX_END != MachRunPara.taQC_SetInfo[i].eFileNumIndex)
        {
            if(QC_FILENUM_INDEX_END == gs_ucFileNum_ListVew_Index)  gs_ucFileNum_ListVew_Index = 0;
            else gs_ucFileNum_ListVew_Index++;
            
            //显示已使用的文件号
            memset(buffer, 0, sizeof(buffer));
            sprintf(buffer, "%d", MachRunPara.taQC_SetInfo[i].usFileNum);
            LISTVIEW_SetItemText(hItem, 0, i, buffer); 
            memset(buffer, 0, sizeof(buffer));
            sprintf(buffer, "%d/%d",  Get_QC_ValidNum(i), MachRunPara.taQC_SetInfo[i].usTestCapacity);
            LISTVIEW_SetItemText(hItem, 1, i, buffer); 
        }
    }
    //
    gs_ucFileNum_ListView_MaxIndex = gs_ucFileNum_ListVew_Index;
    //listview控件选中最后一个
    if(QC_FILENUM_INDEX_END != gs_ucFileNum_ListVew_Index)
    {
        LISTVIEW_SetSel(hItem, gs_ucFileNum_ListVew_Index);
    }else{
        //空
        LISTVIEW_SetSel(hItem, 0);
    }
    
    //qc text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC);
    if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE)
    {
        TEXT_SetFont(hItem, &HZ_SONGTI_24);
    }else{
        TEXT_SetFont(hItem, &GUI_Font24_ASCII);
    }
    //TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, g_ucaLng_QC[MachInfo.systemSet.eLanguage]);

    //qc set text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_SET);
    TEXT_SetFont(hItem, &HZ_SONGTI_16);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    sprintf(buffer, ">%s", g_ucaLng_QC_Set[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, buffer);
      
    //error prompt text
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_RED);
    TEXT_SetFont(hItem, &HZ_SONGTI_12);
    TEXT_SetText(hItem, " ");
    
    //dropdown level
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_LEVEL);
    DROPDOWN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    WM_SetSize(hItem, 120, 30);
    DROPDOWN_AddString(hItem, g_ucaLng_Low[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_Middle[MachInfo.systemSet.eLanguage]);
    DROPDOWN_AddString(hItem, g_ucaLng_High[MachInfo.systemSet.eLanguage]);
    WM_SetCallback(hItem, Public_Dropdown_Callback);
    
    //
    // Initialization of 'FileNum'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FILE_NUM);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, g_ucaLng_FileNO[MachInfo.systemSet.eLanguage]);
    //FileNum Context
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FILE_NUM_CONTEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, " ");
    //
    // Initialization of 'LotNum'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LOT_NUM);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, g_ucaLng_LotNO[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'Level'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_LEVEL);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, g_ucaLng_Level[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'ValidDate'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VALID_DATE);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &HZ_SONGTI_12);
    TEXT_SetText(hItem, g_ucaLng_ValidDate[MachInfo.systemSet.eLanguage]);
    // ValidData Format Prompt
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_VALID_DATE_FORMAT);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &HZ_SONGTI_12);
    memset(buffer, 0, sizeof(buffer));
    sprintf(buffer, "%s:2021/1/1", g_ucaLng_DateTime_Format[MachInfo.systemSet.eLanguage]);
    TEXT_SetText(hItem, buffer);
    
    //
    //
    // Initialization of 'LOT NO'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_LOT_NUM_1);
 //   WM_SetCallback(hItem, Public_Edit_Callback);
    EDIT_SetMaxLen(hItem, QC_LOT_NUM_LEN-1);
    EDIT_SetText(hItem, " ");
    //
    // Initialization of 'Valid Date'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_VALID_DATE);
//    WM_SetCallback(hItem, Public_Edit_Callback);
    EDIT_SetMaxLen(hItem, DATE_TIME_LEN-1);
    EDIT_SetText(hItem, " ");
    
    //btn QC_Set_Btn_Callback
    //新建
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEW);
    WM_SetCallback(hItem, QC_Set_Btn_Callback);
    //编辑
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT);
    WM_SetCallback(hItem, QC_Set_Btn_Callback);
    //删除
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE);
    WM_SetCallback(hItem, QC_Set_Btn_Callback);
    //返回
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_RETURN);
    WM_SetCallback(hItem, QC_Set_Btn_Callback);
    //取消
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
    WM_SetCallback(hItem, QC_Set_Btn_Callback);
    WM_HideWindow(hItem);
    WM_DisableWindow(hItem);
    //保存
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
    WM_SetCallback(hItem, QC_Set_Btn_Callback);
    WM_HideWindow(hItem);
    WM_DisableWindow(hItem);
    
    //上下限，edit
    for(i = ID_EDIT_WBC_LOWER; i <= ID_EDIT_HGB_UPPER; i++)
    {
        hItem = WM_GetDialogItem(pMsg->hWin, i);
        EDIT_SetMaxLen(hItem, 7);
        //EDIT_EnableBlink(hItem, 800, 1);
        //WM_SetCallback(hItem, Public_Edit_Callback);
    }

}


/*
*   质控，刷新输入参数 Edit
*/
static void Update_Input_Param(WM_MESSAGE *pMsg)
{
        extern __IO MachRunPara_s MachRunPara;
        WM_HWIN hItem;
        char Buffer[32] = {0};
        uint8_t i = 0;
        uint32_t ulID = 0;
        
        //edit File Num
        memset(Buffer, 0, sizeof(Buffer));
        sprintf(Buffer, "%d", MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].usFileNum);
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_FILE_NUM);
//        EDIT_SetText(hItem, Buffer);        
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_FILE_NUM_CONTEXT);
        TEXT_SetText(hItem, Buffer);
        
        //edit Lot Num
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_LOT_NUM_1);
//      EDIT_SetText(hItem, "123");
        if(gs_ucFileNum_ListVew_Index < QC_FILENUM_INDEX_END)
        {
            EDIT_SetText(hItem, (char*)MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].ucaLotNum);
        }else{
            EDIT_SetText(hItem, " ");
        }
		
        //dropdown level
		 hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_LEVEL);
        DROPDOWN_SetSel(hItem, MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].eQC_Level);
        
        //valid date
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_VALID_DATE);
        if(gs_ucFileNum_ListVew_Index < QC_FILENUM_INDEX_END)
        {
            EDIT_SetText(hItem, (char*)MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].ucaValidDate);   
        }else{
            EDIT_SetText(hItem, " ");
        }          

        /*** 上下限，edit ***/
        ulID = ID_EDIT_WBC_LOWER;
        for(i = 0; i < WBCHGB_RST_END; i++)
        {           
             // lower
            memset(Buffer, 0, sizeof(Buffer));
            sprintf(Buffer, "%.2f", MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].faLowerLimit[i]);
            hItem = WM_GetDialogItem(pMsg->hWin, ulID+i*2);
            EDIT_SetText(hItem, Buffer);
            // upper
            memset(Buffer, 0, sizeof(Buffer));
            sprintf(Buffer, "%.2f", MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].faUpperLimit[i]);
            hItem = WM_GetDialogItem(pMsg->hWin, ulID+i*2+1);
            EDIT_SetText(hItem, Buffer);   
        } 
       
}

/*
*   质控、刷新接口
*/
static void QC_Set_Msg_Paint(WM_MESSAGE *pMsg)
{
    extern __IO MachRunPara_s MachRunPara;
    extern __IO DataManage_t g_tDataManage;
    WM_HWIN hItem;
    char i = 0;
    char Buffer[32] = {0};
    
    //list review
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM);
    //清除的内容
    for (i = 0; i < QC_FILENUM_INDEX_END; i++)
    {
        LISTVIEW_SetItemText(hItem, 0, i, " "); 
        LISTVIEW_SetItemText(hItem, 1, i, " ");
    }
    //
    for (i = 0; i <= gs_ucFileNum_ListView_MaxIndex && gs_ucFileNum_ListView_MaxIndex < QC_FILENUM_INDEX_END; i++)
    {
        //显示已使用的文件号
        memset(Buffer, 0, sizeof(Buffer));
        sprintf(Buffer, "%d", MachRunPara.taQC_SetInfo[i].usFileNum);
        LISTVIEW_SetItemText(hItem, 0, i, Buffer); 
        memset(Buffer, 0, sizeof(Buffer));
        sprintf(Buffer, "%d/%d",  Get_QC_ValidNum(i), MachRunPara.taQC_SetInfo[i].usTestCapacity);
        LISTVIEW_SetItemText(hItem, 1, i, Buffer); 

    }
    
    //没有可以用文件号,或者当前处于新增/编辑状态下
    if(QC_FILENUM_INDEX_END == gs_ucFileNum_ListView_MaxIndex || gs_ucFlag == 0 || gs_ucFlag == 1)
    {
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT));
        WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE));
    }else{
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT));
        WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE));
    }
    
     //上下限，背景
    Draw_Upper_Lower_Limit_Background(pMsg);
    //gs_ucFileNum_ListVew_Index 有效，且不处于编辑/新建状态
    if(QC_FILENUM_INDEX_END > gs_ucFileNum_ListVew_Index && gs_ucFlag != 0 && gs_ucFlag != 1)
    {
        //更新输入参数 edit
        Update_Input_Param(pMsg);
    }
    //
    //不再新增/编辑状态，则使能所有edit
    if(gs_ucFlag == 0 || gs_ucFlag == 1)
    {
        Enable_Edit_All(pMsg);
    }else{
        Disable_Edit_All(pMsg);
    }
    
    //
//    TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), "");
}



/*
*   获取界面输入的QC SetInfo
*/
static FeedBack_e Get_Input_QC_SetInfo(WM_MESSAGE *pMsg, QC_SetInfo_s *ptQC_SetInfo)
{
    WM_HWIN hItem;
    char Buffer[64] = {0};
    uint8_t ucIndex = 0, i = 0;
    uint32_t ulID = 0;
    FeedBack_e eFeedBack = FEED_BACK_SUCCESS;
    
    if(gs_ucFileNum_ListVew_Index < QC_FILENUM_INDEX_END)
    {
        //edit Lot Num
        memset(Buffer, 0, sizeof(Buffer));    
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_LOT_NUM_1);
        EDIT_GetText(hItem, Buffer, QC_LOT_NUM_LEN);
        strncpy((char*)ptQC_SetInfo->ucaLotNum, Buffer, QC_LOT_NUM_LEN);
        ptQC_SetInfo->ucaLotNum[QC_LOT_NUM_LEN-1] = 0;
        
        //dropdown level
        hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_LEVEL);
        ucIndex = DROPDOWN_GetSel(hItem);
        ptQC_SetInfo->eQC_Level = (QC_LEVEL_e)ucIndex;
        
        //edit Valid Date 
        memset(Buffer, 0, sizeof(Buffer));    
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_VALID_DATE);
        EDIT_GetText(hItem, Buffer, DATE_TIME_LEN);
        strncpy((char*)ptQC_SetInfo->ucaValidDate, Buffer, DATE_TIME_LEN);
        ptQC_SetInfo->ucaValidDate[DATE_TIME_LEN-1] = 0;      
        
        /*** 上下限，edit ***/
        ulID = ID_EDIT_WBC_LOWER;
        for(i = 0; i < WBCHGB_RST_END; i++)
        {
            // lower
            memset(Buffer, 0, sizeof(Buffer));
            hItem = WM_GetDialogItem(pMsg->hWin, ulID+i*2);
            EDIT_GetText(hItem, Buffer, QC_SET_EDIT_CHAR_MAX_LEN);
            ptQC_SetInfo->faLowerLimit[i] = atof(Buffer);
            
            // upper
            memset(Buffer, 0, sizeof(Buffer));
            hItem = WM_GetDialogItem(pMsg->hWin, ulID+i*2+1);
            EDIT_GetText(hItem, Buffer, QC_SET_EDIT_CHAR_MAX_LEN);
            ptQC_SetInfo->faUpperLimit[i] = atof(Buffer);
            
            if(ptQC_SetInfo->faLowerLimit[i] > ptQC_SetInfo->faUpperLimit[i]) return FEED_BACK_ERROR;
        }
        
    }else{
        eFeedBack = FEED_BACK_FAIL;
    }
    
    return eFeedBack;
}


/*
*   取消操作处理
*/
void Cancel_Handle(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    
    if(0 == gs_ucFlag)
    {
        //新建之后，取消
        memset((void*)&MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex], 0, sizeof(QC_SetInfo_s));
        MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].eFileNumIndex = QC_FILENUM_INDEX_END;
        MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].usFileNum = 0;
        if(QC_FILENUM_INDEX_0 == gs_ucFileNum_ListView_MaxIndex) gs_ucFileNum_ListView_MaxIndex = QC_FILENUM_INDEX_END;
        else gs_ucFileNum_ListView_MaxIndex--;     
        
        //更新
        gs_ucFileNum_ListVew_Index = gs_ucFileNum_ListView_MaxIndex;
        LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM), gs_ucFileNum_ListVew_Index);
        
    }else if(1 == gs_ucFlag){
        //编辑之后，取消
    }
    Update_Input_Param(pMsg);
    gs_ucFlag = 0xFF;

    //使能能新建按键
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEW));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT));
    WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE));
    //
    WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL));
    WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE));
    //Disable_Edit_All(pMsg);      

    //取消后，隐藏取消、保存按键
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
    WM_HideWindow(hItem);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
    WM_HideWindow(hItem);

}



/*
*   有效期校验
*/
static FeedBack_e ValidDate_Format_Check(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    int Id;
    FeedBack_e eFeedBack =  FEED_BACK_SUCCESS;
    char buffer[DATE_TIME_LEN] = {0};
    char ucaMonthBuffer[5] = {0}, ucaDayBuffer[5] = {0};
    uint8_t i = 0, ucLen = 0, ucFlag = 0, ucNum = 0, m = 0, d = 0;
    
    //对有效期校验
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_VALID_DATE);
    Id = WM_GetId(hItem);
    if(Id == ID_EDIT_VALID_DATE){
        EDIT_GetText(hItem, buffer, DATE_TIME_LEN);
        ucLen = strlen(buffer);
        if(ucLen >10) ucFlag = 1;
        for(i = 0; i < ucLen; i++)
        {
            if(i <= 3 && buffer[i] == '/') ucFlag = 1;
            if(i== 4 && buffer[i] != '/')  ucFlag = 1;
            if(buffer[i] == '/') ucNum++;
            if(ucNum == 1 && buffer[i] != '/') ucaMonthBuffer[m++] = buffer[i];
            if(ucNum == 2 && buffer[i] != '/') ucaDayBuffer[d++] = buffer[i];
        }
    }
    
    //输入月份和日期不符合范围
    if(atoi(ucaMonthBuffer) > 12 || atoi(ucaDayBuffer) > 31) ucFlag = 1;
    //
    if(ucLen > 0)
    {
        if(ucFlag != 0 || ucNum != 2)
        {
            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), g_ucaLng_DataTime_InputError[MachInfo.systemSet.eLanguage]);
            eFeedBack = FEED_BACK_FAIL;
        }else{
            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), "");
        }
    }
    
    //
    return eFeedBack;
}

/*
*
*       _cbDialog
*/
static void QC_Set_cbDialog(WM_MESSAGE * pMsg) 
{    
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  int     i = 0;
	extern  MachInfo_s	MachInfo;
  
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  {
    //
    QC_Set_Msg_Init(pMsg);
    //设置窗口颜色
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
   
    Disable_Edit_All(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
  }
  break;
  case WM_PAINT:
  {
    GUI_RECT Rect;
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
    
    //画线
    WM_GetClientRect(&Rect);   
    GUI_SetColor(GUI_SPLINE_LINE_COLOR);
    GUI_DrawHLine(Rect.y0+55, Rect.x0+10, Rect.x1-10);
      
    //
    QC_Set_Msg_Paint(pMsg);
    //外框
//    GUI_SetColor(EDIT_FRAME_COLOR);
//    GUI_AA_DrawRoundedRect(210, 65, 775, 385, 5);     
  }
  break;
  case WM_DELETE:
  {
      gs_QC_Set_MoveFlag = 0;
      //退出时，需发送消息给后端，重新读取QC_SetInfo, 更新QC_SetInfo(避免在新建/编辑，且未保存时，退出)
      Msg_Head_t tMsg_Head = {0};
      tMsg_Head.usCmd = CMD_QC_SET_RE_READ_QC_INFO;
      UI_Put_Msg((uint8_t*)&tMsg_Head);
  }
  break;
  case WM_KEYBOARD_UPDATE: 
  {
    uint8_t ucNum = 0;
    char buffer[DATE_TIME_LEN] = {0};
    //清除错误提示
    TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), " ");
    //当前输入的edit
    hItem = WM_GetFocusedWindow();
    Id = WM_GetId(hItem);
      
    i = strlen(pMsg->Data.p);
    if(i == 1) //ASCII码
    {
        char c = *((char*)pMsg->Data.p);   
        if((Id >= ID_EDIT_WBC_LOWER && Id <= ID_EDIT_HGB_UPPER))
        {
            //上下限，只能输入数字和'.'
            if((c >= '0' && c <= '9') || c == '.')
            {
                EDIT_GetText(hItem, buffer, 10); 
                for(i = 0; i < sizeof(buffer); i++)
                {
                    //统计.个数
                    if(buffer[i] ==  '.')
                    {
                        ucNum++;
                    }
                }
                //过滤重复多余的.
                if(!(ucNum >= 1 && c == '.'))
                {
                    GUI_StoreKeyMsg(c, 1);
                }
            }
        }else if(Id == ID_EDIT_LOT_NUM_1){
            //批号和有效
            if((c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))
            {
                GUI_StoreKeyMsg(c, 1);
            }
        }else if(Id == ID_EDIT_VALID_DATE){
            if((c >= '0' && c <= '9') || c == '/')
            {
                GUI_StoreKeyMsg(c, 1);
            }
        }else{
            GUI_StoreKeyMsg(c, 1);
        }
    }else{
        LOG_Error("Msg Len(%d) Error", i);
    }
   }
   break;
   case WM_KEYBOARD_END: 
   {
       Enable_Edit_All(pMsg);
       if(gs_QC_Set_MoveFlag == 1)
       {
           WM_MoveTo(pMsg->hWin, 0, 65);
           gs_QC_Set_MoveFlag = 0;
       }
       //
//       ValidDate_Format_Check(pMsg);

   }
   break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_NEW: // Notifications sent by 'new'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {        
            uint16_t usTemp = 0;
            // USER START (Optionally insert code for reacting on notification message)
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE));
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL));
            Enable_Edit_All(pMsg);
            //失能新建按键
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE));
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT));
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEW));

            //
            if(gs_ucFileNum_ListView_MaxIndex >= QC_FILENUM_INDEX_END)
            {
                gs_ucFileNum_ListVew_Index = 0;
                gs_ucFileNum_ListView_MaxIndex = 0;
                MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].usFileNum = 1;
            }else if(QC_FILENUM_INDEX_5 == gs_ucFileNum_ListView_MaxIndex){
                // 提示异常，文件列表已满，请先删除后，再添加 
                TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), g_ucaLng_FileNOIsFull[MachInfo.systemSet.eLanguage]);
                break;
            }else{
                gs_ucFileNum_ListView_MaxIndex++;
                gs_ucFileNum_ListVew_Index = gs_ucFileNum_ListView_MaxIndex;
                usTemp = MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex-1].usFileNum;
                //文件号递增
                MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].usFileNum = usTemp>=0xFFFF-1?0:usTemp+1;
            }
            //初始化，QC_SetInfo的公共部分
            MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].eFileNumIndex = gs_ucFileNum_ListView_MaxIndex;        
            MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].usTestCapacity = QC_PER_FILE_NUM_MAX_CAPACITY;
            MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].eSeter = MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type;

            //更新listview显示
            gs_ucFileNum_ListVew_Index = gs_ucFileNum_ListView_MaxIndex;
            LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM), gs_ucFileNum_ListVew_Index);
            //更新输入参数 edit
            Update_Input_Param(pMsg);
            gs_ucFlag = 0;
            
            //新增后，显示取消、保存按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
            WM_ShowWindow(hItem);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
            WM_ShowWindow(hItem);
       }
       break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_EDIT: // Notifications sent by 'edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        case WM_NOTIFICATION_RELEASED:
        {
            //清除错误提示
            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), " ");
            //编辑后，显示取消、保存按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
            WM_ShowWindow(hItem);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
            WM_ShowWindow(hItem);
                        
            // USER START (Optionally insert code for reacting on notification message)
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE));
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL));
            Enable_Edit_All(pMsg);
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEW));
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE));
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT));
            // USER END
            gs_ucFlag = 1;
        }
        break;
      }
      break;
    case ID_BUTTON_DELETE: // Notifications sent by 'delete'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
          //清除错误提示
            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), " ");
        // USER START (Optionally insert code for reacting on notification message)
        if(gs_ucFileNum_ListVew_Index < QC_FILENUM_INDEX_END)
        {
            uint8_t ucIndex = 0;
            QC_SetInfo_Msg_t tQC_SetInfo_Msg = {0};
            
            if(QC_FILENUM_INDEX_END > gs_ucFileNum_ListVew_Index && QC_FILENUM_INDEX_END > gs_ucFileNum_ListView_MaxIndex) //当前选项为有效数据
            {
                //无效后选中的质控设定信息
                memset((void*)&MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index], 0, sizeof(QC_SetInfo_s));
                MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].eFileNumIndex = QC_FILENUM_INDEX_END;
                    
                //构造交互消息
                tQC_SetInfo_Msg.tMsgHead.usCmd = CMD_QC_SET_DELETE;
                if(gs_ucFileNum_ListVew_Index < QC_FILENUM_INDEX_END)
                {
                    tQC_SetInfo_Msg.ucCurIndex        = gs_ucFileNum_ListVew_Index;
                    tQC_SetInfo_Msg.ucMaxIndex        = gs_ucFileNum_ListView_MaxIndex;
                }else{
                    break;
                }
                //发送消息给后端
                UI_Put_Msg((uint8_t*)&tQC_SetInfo_Msg);
                
                //更新文件数组信息（索引号由低到高排列（旧到新），多余项为无效后数据）
                ucIndex = gs_ucFileNum_ListVew_Index;
                while(ucIndex < gs_ucFileNum_ListView_MaxIndex)
                {
                    /*** 删除的文件号，不是最新的一个 ***/
                    
                    //把后续项，覆盖前面项
                    memmove((void*)&MachRunPara.taQC_SetInfo[ucIndex], (void*)&MachRunPara.taQC_SetInfo[ucIndex+1], sizeof(QC_SetInfo_s));
                    ucIndex++;
                }
                //无效后，最后一项
                memmove((void*)&MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex], (void*)&MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex+1], sizeof(QC_SetInfo_s));
                MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].eFileNumIndex = QC_FILENUM_INDEX_END;
                MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].usFileNum = 0;
                
                //更新 gs_ucFileNum_ListView_MaxIndex
                if(QC_FILENUM_INDEX_0 == gs_ucFileNum_ListView_MaxIndex)
                {
                    gs_ucFileNum_ListVew_Index = QC_FILENUM_INDEX_END;
                    
                }else{
                    gs_ucFileNum_ListView_MaxIndex--;
                }
                
                //更新 gs_ucFileNum_ListVew_Index
                if(QC_FILENUM_INDEX_0 == gs_ucFileNum_ListVew_Index)
                {
					gs_ucFileNum_ListVew_Index = QC_FILENUM_INDEX_0;
//                    if(gs_ucFileNum_ListView_MaxIndex >= QC_FILENUM_INDEX_0)
//                    {
//                        gs_ucFileNum_ListVew_Index = QC_FILENUM_INDEX_0;        
//                    }else{
//                        gs_ucFileNum_ListVew_Index = QC_FILENUM_INDEX_END;
//                    }
                    LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM), 0);       
                }else{
                    gs_ucFileNum_ListVew_Index--;
                    LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM), gs_ucFileNum_ListVew_Index);
                }  
            }
            Update_Input_Param(pMsg);
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEW));
        }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_RETURN: // Notifications sent by 'return'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        Cancel_Handle(pMsg);
        GUI_EndDialog(pMsg->hWin,0);
        g_hActiveWin = QC_WindowDlG();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTVIEW_FILE_NUM: // Notifications sent by 'file num ,Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
        // USER START (Optionally insert code for reacting on notification message)
          uint8_t ucTemp = 0;
          ucTemp = LISTVIEW_GetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM));
          if(ucTemp <= gs_ucFileNum_ListView_MaxIndex)
          {
             gs_ucFileNum_ListVew_Index = ucTemp;
             LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM), gs_ucFileNum_ListVew_Index);
          }else{
            LISTVIEW_SetSel(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_FILE_NUM), gs_ucFileNum_ListView_MaxIndex);
            gs_ucFileNum_ListVew_Index = gs_ucFileNum_ListView_MaxIndex;   
          }
          Update_Input_Param(pMsg);
        // USER END
      }
      break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_LEVEL: // Notifications sent by 'Level'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
        // USER START (Optionally insert code for reacting on notification message)
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_LEVEL);
//        uint8_t ucIndex = DROPDOWN_GetSel(hItem);
//        MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].eQC_Level = (QC_LEVEL_e)ucIndex;
        // USER END
      }
      break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_CANCEL: // Notifications sent by 'cancel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
        // USER START (Optionally insert code for reacting on notification message)
        Cancel_Handle(pMsg);
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_SAVE: // Notifications sent by 'save'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
            FeedBack_e eFeedBack = FEED_BACK_SUCCESS;
            QC_SetInfo_Msg_t tQC_SetInfo_Msg = {0};                
            
            LOG_Info("QC_SetInfo_Msg_t:%d", sizeof(QC_SetInfo_Msg_t));
            tQC_SetInfo_Msg.tMsgHead.usCmd = CMD_QC_SET_SAVE;            
            //判断 gs_ucFileNum_ListVew_Index
            if(gs_ucFileNum_ListVew_Index < QC_FILENUM_INDEX_END /*&& gs_ucFileNum_ListVew_Index >= QC_FILENUM_INDEX_0*/)
            {
              tQC_SetInfo_Msg.ucCurIndex = gs_ucFileNum_ListVew_Index;
            }else{
              break;
            } 
            
            //获取参数
            eFeedBack = Get_Input_QC_SetInfo(pMsg, &tQC_SetInfo_Msg.tQC_SetInfo);
            if(eFeedBack == FEED_BACK_FAIL)
            {
                TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), g_ucaLng_InputParamError[MachInfo.systemSet.eLanguage]);
                break;
            }else if(eFeedBack == FEED_BACK_ERROR){
                TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_ERROR_PROMPT), g_ucaLng_InputParamError[MachInfo.systemSet.eLanguage]);
                break;
            }
            //有效期验证失败
            if(FEED_BACK_SUCCESS != ValidDate_Format_Check(pMsg)) break;
            //
            //Get_Input_QC_SetInfo(pMsg, (QC_SetInfo_s*)&MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index]);
            //
            tQC_SetInfo_Msg.tQC_SetInfo.eFileNumIndex  = MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].eFileNumIndex;
            tQC_SetInfo_Msg.tQC_SetInfo.usFileNum      = MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].usFileNum;
            tQC_SetInfo_Msg.tQC_SetInfo.usTestCapacity = MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].usTestCapacity;
//            tQC_SetInfo_Msg.tQC_SetInfo.eQC_Level      = MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].eQC_Level;
            tQC_SetInfo_Msg.tQC_SetInfo.eSeter         = MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type;////MachRunPara.taQC_SetInfo[gs_ucFileNum_ListView_MaxIndex].eSeter;
            //
            memmove((void*)&MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index], (void*)&tQC_SetInfo_Msg.tQC_SetInfo, sizeof(QC_SetInfo_s));
            
            //
            //Printf_Free_StackSize();
            UI_Put_Msg((uint8_t*)&tQC_SetInfo_Msg);

            //使能能新建按键
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_NEW));
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_EDIT));
            WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DELETE));
            //
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL));
            WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE));
            //Disable_Edit_All(pMsg);
            //
            gs_ucFlag = 0xFF;
            
            //取消后，隐藏取消、保存按键
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SAVE);
            WM_HideWindow(hItem);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
            WM_HideWindow(hItem);
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
    }
    break;
//    case ID_EDIT_FILE_NUM: // Notifications sent by 'FileNum'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        // USER START (Optionally insert code for reacting on notification message)
////         WM_SetFocus(pMsg->hWinSrc);
////         Disable_Edit_Except(pMsg, ID_EDIT_FILE_NUM);
////         CreateKeyboard_Window();
//        // USER END
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_VALUE_CHANGED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      // USER START (Optionally insert additional code for further notification handling)
//      // USER END
//      }
//      break;
    case ID_EDIT_LOT_NUM_1: // Notifications sent by 'LotNum'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:  
        // USER START (Optionally insert code for reacting on notification message)       

         WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_EDIT_LOT_NUM_1));
         if(WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_EDIT_LOT_NUM_1)))
         {
            LOG_Info("Edit Lot Num, has focus");
         }else{   
             LOG_Info("Edit Lot Num, not has focus");
            WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_EDIT_LOT_NUM_1)); 
         }
		 
		 MachRunPara.keyboardInitJM = KEYBOARD_NUM;
         CreateKeyboard_Window();
      break;
      case WM_NOTIFICATION_RELEASED:

        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
     case ID_EDIT_VALID_DATE: // Notifications sent by 'validDate'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      {
        // USER START (Optionally insert code for reacting on notification message)
         if(gs_QC_Set_MoveFlag == 0)
         {
            gs_QC_Set_MoveFlag = 1;
            WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*2);
         }
         WM_SetFocus(pMsg->hWinSrc);
         //Disable_Edit_Except(pMsg, ID_EDIT_VALID_DATE);
		 MachRunPara.keyboardInitJM = KEYBOARD_NUM;
         CreateKeyboard_Window();
        
//        //获取当前已输入的信息
//        //Get_Input_QC_SetInfo(pMsg, )
//          
//        GUI_EndDialog(pMsg->hWin, 0);
//        g_hActiveWin = CreatedataTimeSetPage();
//      
//        pMsg->MsgId = WM_USER_DATA;
//        pMsg->Data.v = 3;
//        WM_SendMessage(g_hActiveWin,pMsg);
      }
      break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_WBC_LOWER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_WBC_LOWER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_WBC_UPPER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_WBC_UPPER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        
        }
        break;
    }
    break;
    case ID_EDIT_GranJ_LOWER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_GranJ_LOWER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_GranJ_UPPER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_GranJ_UPPER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_MidJ_LOWER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_MidJ_LOWER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_MidJ_UPPER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_MidJ_UPPER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_LymJ_LOWER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*2);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_LymJ_LOWER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_LymJ_UPPER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*2);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_LymJ_UPPER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;      
    case ID_EDIT_GranB_LOWER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*3);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_GranB_LOWER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_GranB_UPPER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*3);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_GranB_UPPER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break; 
    case ID_EDIT_MidB_LOWER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*4);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_MidB_LOWER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_MidB_UPPER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*4);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_MidB_UPPER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break; 
    case ID_EDIT_LymB_LOWER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*5);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_LymB_LOWER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_LymB_UPPER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*5);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_LymB_UPPER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break; 
    case ID_EDIT_HGB_LOWER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*6);
            }
            WM_SetFocus(pMsg->hWinSrc);
//            Disable_Edit_Except(pMsg, ID_EDIT_HGB_LOWER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
    }
    break;
    case ID_EDIT_HGB_UPPER: // Notifications sent by ''
      switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
        {
            if(gs_QC_Set_MoveFlag == 0)
            {
                gs_QC_Set_MoveFlag = 1;
                WM_MoveWindow(pMsg->hWin, QC_SET_X_MOVE_LEN, -QC_SET_Y_MOVE_LEN*6);
            }
            WM_SetFocus(pMsg->hWinSrc);
 //           Disable_Edit_Except(pMsg, ID_EDIT_HGB_UPPER);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
            CreateKeyboard_Window();
        }
        break;
     }
     break; 

    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN QC_Set_CreateWindow(void);
WM_HWIN QC_Set_CreateWindow(void) {
  WM_HWIN hWin;
    
  WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
  Public_Show_Widget();
    
	Disable_Algo_Task();
	
  Set_Cur_MenuID(GUI_WINDOW_QC_SET_ID);
  hWin = GUI_CreateDialogBox(QC_Set_aDialogCreate, GUI_COUNTOF(QC_Set_aDialogCreate), QC_Set_cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
