/*********************************************************************
*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   质控界面（质控主界面）
*
*/
// USER END
#include "DIALOG.h"

#include "Public_menuDLG.h"
#include "ui_files.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_QC 			(GUI_WINDOW_QC_ID + 0x00)
#define ID_BUTTON_QC_SET 		(GUI_WINDOW_QC_ID + 0x01)
#define ID_BUTTON_QC_ANALYSIS 	(GUI_WINDOW_QC_ID + 0x02)
//#define ID_BUTTON_QC_CHART 		(GUI_WINDOW_QC_ID + 0x03)
#define ID_BUTTON_QC_LIST 		(GUI_WINDOW_QC_ID + 0x04)
#define ID_TEXT_QC 				(GUI_WINDOW_QC_ID + 0x05)
#define ID_TEXT_QC_TYPE 		(GUI_WINDOW_QC_ID + 0x06)


//
#define QC_LINE_COLOR		0x00dbdbdb
#define QC_TEXT_COLOR		0x00999999
#define QC_TEXT_BK_COLOR	GUI_WHITE

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO QC_aDialogCreate[] = {
  { WINDOW_CreateIndirect, "", ID_WINDOW_QC, 			0, 60, 800, 393, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_QC_SET, 		165, 130, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_QC_ANALYSIS, 	295, 130, 100, 100, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "", ID_BUTTON_QC_CHART, 		425, 130, 100, 100, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "", ID_BUTTON_QC_LIST, 		560, 130, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_QC_LIST, 		425, 130, 100, 100, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",   ID_TEXT_QC, 				25,  20, 60, 60, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "",   ID_TEXT_QC_TYPE, 		70, 25, 120, 40, 0, 0x0, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};


/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

//
static void QC_Btn_Callback(WM_MESSAGE* pMsg)
{
//	const unsigned char RoundRadius = 2; //显示区域圆角半径
		
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
	
		    Show_BK_BMP(BK_SDRAM, BK_PICTURE_OTHERS_IconBkSmall, 0, 0);          
            //显示字体颜色
            GUI_SetColor(QC_TEXT_COLOR);
            GUI_SetBkColor(GUI_WHITE);                            
			switch(WM_GetId(pMsg->hWin))
            {
				case ID_BUTTON_QC_SET:
				{
                    if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE)
                    {
                        GUI_DispStringAt(g_ucaLng_QC_Set[MachInfo.systemSet.eLanguage], 18, 70);
                    }else{
                        GUI_DispStringAt(g_ucaLng_QC_Set[MachInfo.systemSet.eLanguage], 12, 70);
                    }
				}
				break;
				case ID_BUTTON_QC_ANALYSIS:
				{
//					Show_BK_BMP(BK_SDRAM, BK_PICTURE_QC_ANALYSIS, 25, 15);
                    if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE)
                    {
                        GUI_DispStringAt(g_ucaLng_QC_Analysis[MachInfo.systemSet.eLanguage], 15, 70);
                    }else{
                        GUI_DispStringAt(g_ucaLng_QC_Analysis[MachInfo.systemSet.eLanguage], 8, 70);
                    }
					
				}
				break;				
				case ID_BUTTON_QC_LIST:
				{            
//					Show_BK_BMP(BK_SDRAM, BK_PICTURE_QC_LIST, 25, 15);
					GUI_DispStringAt(g_ucaLng_QC_List[MachInfo.systemSet.eLanguage], 18, 70);
				}
				break;				
				default :break;
			}
        } else {				
            //Show_BK_BMP(BK_PICTURE_OTHERS_IconBkSmall, 0, 0);  
            Show_BK_BMP(BK_SDRAM, BK_PICTURE_OTHERS_IconBkSmall, 0, 0);            
			//显示字体颜色
			GUI_SetColor(QC_TEXT_COLOR); //QC_TEXT_COLOR QC_TEXT_BK_COLOR
            GUI_SetBkColor(GUI_WHITE);            
			switch(WM_GetId(pMsg->hWin)){

				case ID_BUTTON_QC_SET:
				{
					Show_BK_BMP(BK_SDRAM, BK_PICTURE_QC_SET, 30, 15);
//					GUI_DispStringAt(g_ucaLng_QC_Set[MachInfo.systemSet.eLanguage], 18, 70);
                    if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE)
                    {
                        GUI_DispStringAt(g_ucaLng_QC_Set[MachInfo.systemSet.eLanguage], 18, 70);
                    }else{
                        GUI_DispStringAt(g_ucaLng_QC_Set[MachInfo.systemSet.eLanguage], 12, 70);
                    }
				}
				break;
				case ID_BUTTON_QC_ANALYSIS:
				{
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_QC_ANALYSIS, 25, 15);
                    if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE)
                    {
                        GUI_DispStringAt(g_ucaLng_QC_Analysis[MachInfo.systemSet.eLanguage], 15, 70);
                    }else{
                        GUI_DispStringAt(g_ucaLng_QC_Analysis[MachInfo.systemSet.eLanguage], 8, 70);
                    }
				}
				break;				
//				case ID_BUTTON_QC_CHART:
//				{
//					Show_BK_BMP(BK_PICTURE_QC_CHART, 25, 15);
//					GUI_DispStringAt(g_ucaLng_QC_Chart[MachInfo.systemSet.eLanguage], 24, 70);
//				}
//				break;				
				case ID_BUTTON_QC_LIST:
				{
					Show_BK_BMP(BK_SDRAM, BK_PICTURE_QC_LIST, 30, 15);
					GUI_DispStringAt(g_ucaLng_QC_List[MachInfo.systemSet.eLanguage], 18, 70);
				}
				break;				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}






// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void QC_cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
 
	
//	extern GUI_HMEM hMemICONBMP;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  {      
      //
	  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_QC_SET);
	  WM_SetCallback(hItem, QC_Btn_Callback);
      WM_InvalidateWindow(hItem);
      //
      hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_QC_ANALYSIS);
	  WM_SetCallback(hItem, QC_Btn_Callback);
      
      hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_QC_LIST);
	  WM_SetCallback(hItem, QC_Btn_Callback);
      
//      hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_QC_CHART);
//	  WM_SetCallback(hItem, QC_Btn_Callback);
      
      //qc
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC);
      if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE)
      {
          TEXT_SetFont(hItem, &HZ_SONGTI_24);
      }else{
          TEXT_SetFont(hItem, &GUI_Font24_ASCII);
      }
      //TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
      TEXT_SetText(hItem, g_ucaLng_QC[MachInfo.systemSet.eLanguage]);
      
      //qc type
      char buffer[64] = {0};
      hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_QC_TYPE);
      TEXT_SetFont(hItem, &HZ_SONGTI_16);
      //TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
      sprintf(buffer, ">%s", g_ucaLng_QC_Type[MachInfo.systemSet.eLanguage]);
      TEXT_SetText(hItem, buffer);
      
      //设置窗口背景色
      WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
      //
  }
  break;
  case WM_PAINT:
  {
    //GUI_RECT Rect;
	//画背景BMP图
    //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
            
    GUI_RECT Rect;
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
      
	//画线
    WM_GetClientRect(&Rect);   
    GUI_SetColor(QC_LINE_COLOR);
    GUI_DrawHLine(Rect.y0+55, Rect.x0+10, Rect.x1-10);    
  }
  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_QC_SET: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
        // USER START (Optionally insert code for reacting on notification message)
          GUI_EndDialog(pMsg->hWin, 0);
          g_hActiveWin = QC_Set_CreateWindow();
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_QC_ANALYSIS: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = QC_Analysis_Menu();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
//    case ID_BUTTON_QC_CHART: // Notifications sent by ''
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      // USER START (Optionally insert additional code for further notification handling)
//      // USER END
//      }
//      break;
    case ID_BUTTON_QC_LIST: // Notifications sent by ''
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = QC_List_CreateWindow();
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;

    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateservicePage
*/
WM_HWIN QC_WindowDlG(void);
WM_HWIN QC_WindowDlG(void) {
					
	WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();

    Set_Cur_MenuID(GUI_WINDOW_QC_ID);
    hWin = GUI_CreateDialogBox(QC_aDialogCreate, GUI_COUNTOF(QC_aDialogCreate), QC_cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
