/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   服务界面中：组件老化测试界面
*
*/
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "GUI_Type.h"
#include "agingTestPageDLG.h"
#include "PrinterTask.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0        (AGING_TEST_PAGE_ID + 0x00)
#define ID_TEXT_0        (AGING_TEST_PAGE_ID + 0x01)
#define ID_TEXT_1        (AGING_TEST_PAGE_ID + 0x02)
#define ID_TEXT_2        (AGING_TEST_PAGE_ID + 0x03)
#define ID_TEXT_3        (AGING_TEST_PAGE_ID + 0x04)
#define ID_BUTTON_0        (AGING_TEST_PAGE_ID + 0x05)
#define ID_BUTTON_1        (AGING_TEST_PAGE_ID + 0x06)
#define ID_BUTTON_2        (AGING_TEST_PAGE_ID + 0x07)
#define ID_BUTTON_3        (AGING_TEST_PAGE_ID + 0x08)
#define ID_BUTTON_4        (AGING_TEST_PAGE_ID + 0x09)
#define ID_BUTTON_5        (AGING_TEST_PAGE_ID + 0x0A)
#define ID_BUTTON_6        (AGING_TEST_PAGE_ID + 0x0B)
#define ID_BUTTON_7        (AGING_TEST_PAGE_ID + 0x0C)
#define ID_BUTTON_8        (AGING_TEST_PAGE_ID + 0x0D)
#define ID_BUTTON_9        (AGING_TEST_PAGE_ID + 0x0E)
#define ID_BUTTON_10        (AGING_TEST_PAGE_ID + 0x0F)
#define ID_BUTTON_11        (AGING_TEST_PAGE_ID + 0x10)
#define ID_BUTTON_12        (AGING_TEST_PAGE_ID + 0x11)
#define ID_BUTTON_13        (AGING_TEST_PAGE_ID + 0x12)
#define ID_BUTTON_14        (AGING_TEST_PAGE_ID + 0x13)
#define ID_EDIT_0        	(AGING_TEST_PAGE_ID + 0x14)
#define ID_MULTIEDIT_0        (AGING_TEST_PAGE_ID + 0x15)


// USER START (Optionally insert additional defines)
//定义用于后台数据在老化界面上显示的全局变量
ServiceAgingTestUIInfo_s ServiceAgingTestUIInfo;
static uint8_t StartTestFlag = 0;

//定义是否开启CAT数据测试功能
#define CAT_DATA_TEST						1			
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "agingTestPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "服务", ID_TEXT_0, 30, 13, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> 组件老化", ID_TEXT_1, 90, 20, 104, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "老化次数", ID_TEXT_2, 262, 89, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "执行项目", ID_TEXT_3, 263, 124, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "打印老化数据", ID_BUTTON_0, 390, 11, 148, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "停止", ID_BUTTON_1, 558, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "返回", ID_BUTTON_2, 678, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "气嘴密闭性测试", ID_BUTTON_3, 343, 126, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "研发流程", ID_BUTTON_4, 485, 126, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "探针老化测试", ID_BUTTON_5, 625, 336, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "气阀测试", ID_BUTTON_6, 343, 196, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "液阀测试", ID_BUTTON_7, 485, 196, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "建压测试", ID_BUTTON_8, 625, 196, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "定量电极测试", ID_BUTTON_9, 343, 266, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "进出仓运动", ID_BUTTON_10, 485, 266, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CAT数据测试", ID_BUTTON_11, 625, 266, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "随机点击测试", ID_BUTTON_12, 343, 336, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "常温老化", ID_BUTTON_13, 485, 336, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "数据存储测试", ID_BUTTON_14, 625, 126, 120, 40, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Count_e", ID_EDIT_0, 343, 82, 290, 32, 0, 0x9, 0 },
  { MULTIEDIT_CreateIndirect, "dispData_Me", ID_MULTIEDIT_0, 20, 59, 200, 330, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
//自定义此窗口所有按钮控件的回调函数
static void AgingTestPage_Btn_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
        }
        else {
			//控件失能时，则置灰
			if(WM_IsEnabled(pMsg->hWin) == 1){
				//填充
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
				GUI_AA_FillRoundedRectEx(&Rect,20);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRectEx(&Rect,19);
				
				//设置字符前景和背景色
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			}else{
				//填充
				GUI_SetColor(GUI_WHITE);
				GUI_AA_FillRoundedRectEx(&Rect,20);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRectEx(&Rect,19);
				
				//设置字符前景和背景色
				GUI_SetColor(GUI_LIGHTGRAY);
				GUI_SetBkColor(GUI_WHITE);
			}
        }
		
		switch(WM_GetId(pMsg->hWin)){
			case ID_BUTTON_0:
				GUI_DispStringInRect("打印老化数据",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_1:
			{
				if(StartTestFlag == 1){
					if(BUTTON_IsPressed(pMsg->hWin)){
						//填充
						GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
						GUI_AA_FillRoundedRectEx(&Rect,20);
						
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
						
						//设置字符前景和背景色
						GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
						GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
					}else{
						//填充
						GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
						GUI_AA_FillRoundedRectEx(&Rect,20);
						
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
						
						//设置字符前景和背景色
						GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
						GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
					}
				}
				GUI_DispStringInRect("停止",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			}
			break;
			
			case ID_BUTTON_2:
				GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_3:
				GUI_DispStringInRect("气嘴密闭性测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_4:
				GUI_DispStringInRect("研发流程",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_5:
				GUI_DispStringInRect("探针老化测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_6:
				GUI_DispStringInRect("气阀测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_7:
				GUI_DispStringInRect("液阀测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_8:
				GUI_DispStringInRect("建压测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_9:
				GUI_DispStringInRect("定量电极测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_10:
				GUI_DispStringInRect("进出仓运动",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_11:
				GUI_DispStringInRect("CAT数据测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_12:
				GUI_DispStringInRect("随机点击测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_13:
				GUI_DispStringInRect("常温老化",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			case ID_BUTTON_14:
				GUI_DispStringInRect("数据存储测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
			break;
			
			default :break;
		}
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



/*
* 设置控件回调函数，以及重绘控件
*/
static void AgingTestPage_Data_Updata(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;

    //打印老化数据
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//停止
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//返回
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//气嘴密闭性测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//流程老化
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//探针老化测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//电机测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//阀测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//建压测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//定量电极测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//进出仓运动
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//CAT数据测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//随机点击测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//流程老化
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//数据存储测试
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);  
    WM_SetCallback(hItem, AgingTestPage_Btn_Callback);
    WM_InvalidateWindow(hItem);
}



/***
*除停止按键外，其他按键全部屏蔽掉
***/
static void AgingTestPageDisableButtons(WM_MESSAGE * pMsg)
{ 
	StartTestFlag = 1;
	
	Disable_Motor_Task();
	
	//将其他按键（除停止按键外）全部禁止掉
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_9));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_10));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13));
}


// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void AgingTestPage_cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
    
  // USER START (Optionally insert additional variables)
	extern GUI_HMEM hMemBKBMP;						
	extern char* BKBmaDataBuf;
	extern uint32_t BKBMPBufLen;
	extern ServiceAgingTestUIInfo_s ServiceAgingTestUIInfo;
	extern osMessageQueueId_t xUIQueue;
	extern osMessageQueueId_t PrinterInfoQueueHandle;
	
	AgingTestUIToBackendInfo_s AgingTestUI2BInfo = {0};
	
	char StrBuf[256] = {0};
	
//	static uint8_t KeyBoardUseOnceFlag = 0;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'agingTestPage'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00F5E6C5));
  
	//设置显示字体
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem,&HZ_SONGTI_24);
	WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"服务");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
    //
    // Initialization of 'Count_e'
    //初始化老化次数编辑框
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	EDIT_SetTextAlign(hItem,GUI_TA_LEFT|GUI_TA_VCENTER);
    EDIT_SetText(hItem, "500");
	EDIT_EnableBlink(hItem,500,1);
  
	//配置多行编辑款
	hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
	MULTIEDIT_SetReadOnly(hItem,1);
	MULTIEDIT_SetBufferSize(hItem, 2048);
	MULTIEDIT_SetAutoScrollV(hItem, 1);
	MULTIEDIT_SetAutoScrollH(hItem, 1);
	MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, 0x00333333);
	MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
	MULTIEDIT_SetFont(hItem,&HZ_SONGTI_16);
	MULTIEDIT_ShowCursor(hItem,0);
	MULTIEDIT_SetInsertMode(hItem,0);
	MULTIEDIT_SetBkColor(hItem,MULTIEDIT_CI_READONLY,GUI_WHITE);
	
	//更新各控件
	AgingTestPage_Data_Updata(pMsg);
	
	//禁止掉桌面按键
	AbortPublishDestopButton();
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
	
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_11));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_14));
    
    break;
  case WM_PAINT:
  {
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
	  
	  //画线
	GUI_SetColor(0x009ea0a2);
	GUI_DrawHLine(54,8,790);
  }
  break;
  
  case WM_DELETE:
  break;
  
  //更新键盘事件
  case WM_KEYBOARD_UPDATE: 
	{
		uint8_t i = strlen(pMsg->Data.p);
		if(i == 1) //ASCII码
		{
			char c = *((char*)pMsg->Data.p);
			if(c >= '0' && c <= '9'){
				GUI_StoreKeyMsg(c, 1);
			}
		}
	}
   break;
	
	//键盘结束事件
   case WM_KEYBOARD_END: 
   {
//	   KeyBoardUseOnceFlag = 0;
	   
	   hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	   EDIT_GetText(hItem,StrBuf,20);
	   if(strlen(StrBuf) == 0){
			EDIT_SetText(hItem,"1");
	   }
	   
	   //恢复各按键
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_9));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_10));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13));
	  
		
   }
   
   //后端执行完毕消息
   case WM_SERVICE_AGING_TEST_BE_OVER:
		StartTestFlag = 0;
   
		Enable_Motor_Task(TRUE);
   
	   //恢复各按键
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_9));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_10));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13));
   
		//将编辑框使能
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetFocusable(hItem,1);
		WM_SetFocus(hItem);
		WM_EnableWindow(hItem);
   break;
  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'printer_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  {
		PrinterInfoData_s* PrinterInfoData = (PrinterInfoData_s*)SDRAM_ApplyCommonBuf(sizeof(PrinterInfoData_s));
		  
		//发送打印信息给打印机
		if((ServiceAgingTestUIInfo.startFlag != 0) || (ServiceAgingTestUIInfo.stopFlag != 0)){
			switch(ServiceAgingTestUIInfo.page){
				case TANZHEN_TEST_RESULT:
					PrinterInfoData->page = TAN_ZHEN_TEST_RESULT_PAGE;
					PrinterInfoData->pageUnion.tanZhenTestErrInfo = ServiceAgingTestUIInfo.unions.tanzhenTestInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				case AGING_TEST_RESULT:
					PrinterInfoData->page = AGING_TEST_RESULT_PAGE;
					PrinterInfoData->pageUnion.agingTestResultInfo = ServiceAgingTestUIInfo.unions.agingTestResultInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				case MOTOR_OUT_IN_RESULT:
					PrinterInfoData->page = MOTOR_OUT_IN_RESULT_PAGE;
					PrinterInfoData->pageUnion.outInTestResultInfo = ServiceAgingTestUIInfo.unions.outInTestResultInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				case QIZUI_TEST_RESULT:
					PrinterInfoData->page = QIZUI_TEST_RESULT_PAGE;
					PrinterInfoData->pageUnion.qizuiTestResultInfo = ServiceAgingTestUIInfo.unions.qizuiTestResultInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				case AIR_TEST_RESULT:
					PrinterInfoData->page = AIR_TEST_RESULT_PAGE;
					PrinterInfoData->pageUnion.airValveTestResultInfo = ServiceAgingTestUIInfo.unions.airValveTestResultInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				case YEFA_TEST_RESULT:
					PrinterInfoData->page = YEFA_TEST_RESULT_PAGE;
					PrinterInfoData->pageUnion.yeFaValveTestResultInfo = ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				case BUILD_PRESSURE_TEST_RESULT:
					PrinterInfoData->page = BUILD_PRESSURE_TEST_RESULT_PAGE;
					PrinterInfoData->pageUnion.buildPressureTestResultInfo = ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				case DL_ELEC_TEST_RESULT:
					PrinterInfoData->page = DL_ELEC_TEST_RESULT_PAGE;
					PrinterInfoData->pageUnion.dlElecTestResultInfo = ServiceAgingTestUIInfo.unions.dlElecTestResultInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				case SC_AGING_TEST_RESULT:
					PrinterInfoData->page = SC_AGING_TEST_RESULT_PAGE;
					PrinterInfoData->pageUnion.scAgingTestResultInfo = ServiceAgingTestUIInfo.unions.scAgingTestResultInfo;
					osMessageQueuePut(PrinterInfoQueueHandle,PrinterInfoData, 0, 0);
				break;
				default :break;
			}
		}
	  }
      break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'stop_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//提前停止老化测试
		ServiceAgingTestUIInfo.stopFlag = 1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//恢复桌面按键
		RecoverPublishDestopButton();
	  
		Disable_Motor_Task();
	  
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateservicePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'qizuiT_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送气嘴密闭性老化测试消息
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_QIZUI_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'agingT_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送流程老化测试消息
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_AGING_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
		//osMessageQueuePut(xUIQueue,&SendUIMSGBuf,0,osWaitForever);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'tanzhenT_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送探针老化测试消息
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);		
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_TANZHEN_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
		//osMessageQueuePut(xUIQueue,&SendUIMSGBuf,0,osWaitForever);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'motoT_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送气阀老化测试消息
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_AIR_VALVE_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'waveT_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送液阀老化测试消息
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_YEFA_VALVE_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'pressureT_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送建压老化测试消息
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_BUILD_PRESSURE_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'dlElecT_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送定量电极老化测试消息
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_DL_ELEC_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'otherT1_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送进出仓运动测试消息
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_OUTIN_MODULE_OUT_IN;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'CAT数据测试'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_CAT_DATA_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	 case ID_BUTTON_12: // Notifications sent by '随机点击测试'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	  
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		//将其他按键（除停止按键外）全部禁止掉
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_9));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_10));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13));
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_RAND_TOUCH_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_13: // Notifications sent by '生产老化'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_SHENGCHAN_AGING;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_14: // Notifications sent by '数据存储测试'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		AgingTestPageDisableButtons(pMsg);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		//将编辑框失能
		EDIT_SetFocusable(hItem,0);
		WM_DisableWindow(hItem);
	  
		AgingTestUI2BInfo.msgHead.usCmd = CMD_SERVER_DATA_SAVE_TEST;
		EDIT_GetText(hItem,StrBuf,20);
		AgingTestUI2BInfo.count = atoi(StrBuf);
        UI_Put_Msg((uint8_t*)&AgingTestUI2BInfo);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	  
    case ID_EDIT_0: // Notifications sent by 'Count_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//唤出输入法
//		if(KeyBoardUseOnceFlag == 0){
//			KeyBoardUseOnceFlag = 1;
			
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();

		
		//将其他按键（除停止按键外）全部禁止掉
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_9));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_10));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13));

//		}

        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_0: // Notifications sent by 'dispData_Me'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
	  // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	case SERVICE_AGING_USER_ID:
		//获取多行文本框句柄
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
		
		//清空显示多行文本框
		MULTIEDIT_SetText(hItem,"");
		
		switch(ServiceAgingTestUIInfo.page){
			//探针老化测试结果显示
			 case TANZHEN_TEST_RESULT:
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_HCENTER);
				 sprintf(StrBuf,"探针老化测试\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
				sprintf(StrBuf,"次数:%u/%u\n",ServiceAgingTestUIInfo.unions.tanzhenTestInfo.runCount,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.setCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"ST:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.year.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.month.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.day.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.min.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.startTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"ET:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.year.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.month.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.day.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.min.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.rtc.endTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"小孔电压:%u/%u:  %s\n",ServiceAgingTestUIInfo.unions.tanzhenTestInfo.xk.errCount,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.xk.maxValue,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.xk.errCount==0?"√":"×");
				 MULTIEDIT_AddText(hItem,StrBuf);
				 sprintf(StrBuf,"CV:%u/%.2lf:  %s\n",ServiceAgingTestUIInfo.unions.tanzhenTestInfo.cv.errCount,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.cv.maxCV,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.cv.errCount==0?"√":"×");
				 MULTIEDIT_AddText(hItem,StrBuf);
				 sprintf(StrBuf,"MEAN:%u/%.2lf:  %s\n",ServiceAgingTestUIInfo.unions.tanzhenTestInfo.mean.errCount,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.mean.maxMean,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.mean.errCount==0?"√":"×");
				 MULTIEDIT_AddText(hItem,StrBuf);
				 sprintf(StrBuf,"NUM:%u/%u:  %s\n",ServiceAgingTestUIInfo.unions.tanzhenTestInfo.num.errCount,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.num.maxNum,ServiceAgingTestUIInfo.unions.tanzhenTestInfo.num.errCount==0?"√":"×");
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 if(ServiceAgingTestUIInfo.stopFlag == 1){
					if(ServiceAgingTestUIInfo.unions.tanzhenTestInfo.xk.errCount != 0 || ServiceAgingTestUIInfo.unions.tanzhenTestInfo.cv.errCount != 0 || ServiceAgingTestUIInfo.unions.tanzhenTestInfo.mean.errCount != 0 || ServiceAgingTestUIInfo.unions.tanzhenTestInfo.num.errCount != 0 || ServiceAgingTestUIInfo.unions.tanzhenTestInfo.setCount != ServiceAgingTestUIInfo.unions.tanzhenTestInfo.runCount){
						MULTIEDIT_AddText(hItem,"老化结果：不通过\n");
					}else{
						MULTIEDIT_AddText(hItem,"老化结果：通过\n");
					}
				 }
			 break;
			 
			 //流程老化测试结果显示
			 case AGING_TEST_RESULT:
				 MULTIEDIT_SetTextAlign(hItem,GUI_TA_HCENTER);
				 sprintf(StrBuf,"***研发流程老化测试***\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				 sprintf(StrBuf,"格式:异常次数/最大偏移值\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				 MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
				 sprintf(StrBuf,"SN/RN:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.setCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.runCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"ST:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.year.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.month.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.day.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.min.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.startTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"ET:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.year.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.month.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.day.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.min.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.endTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				sprintf(StrBuf,"VCC_P12V:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.p12v.count,ServiceAgingTestUIInfo.unions.agingTestResultInfo.p12v.maxValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"VCC_N12V:%u/%d\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.n12v.count,ServiceAgingTestUIInfo.unions.agingTestResultInfo.n12v.maxValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"恒流源:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.hly.count,ServiceAgingTestUIInfo.unions.agingTestResultInfo.hly.maxValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"SDRAM:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.sdramCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"NAND:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.nandFlashCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"M_EEPROM:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.eepromCount1);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"S_EEPROM:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.eepromCount2);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"RTC偏差:%d\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.rtc.secondOffset);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"打印机:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.printerCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 sprintf(StrBuf,"CAT:OK:%u/ERR:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.cat.successCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.cat.failCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"=====进仓状态=====\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"进仓光耦:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.oc.inOCCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"出仓光耦:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.oc.outOCCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"导通光耦:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.oc.gdOCCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"断开光耦:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.oc.releaseOCCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"小孔电压:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.xk.count,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.xk.maxValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"建压:%u/%d\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.pressure.buildCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.pressure.maxBuildPressureValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"密闭性:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.pressure.airtightCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.pressure.maxairtightValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"放气残余:%u/%d\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.pressure.noPressureCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.pressure.maxnoPressureValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"HGB开:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.hgb.openCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.hgb.maxOpenValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"HGB关:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.hgb.closeCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.hgb.maxCloseValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 sprintf(StrBuf,"计数池检测上:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.JscDetectionCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"计数池检测下:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.JscTypeCheckCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"CV:%u/%.2lf\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.signal.cv.errCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.signal.cv.maxCV);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"MEAN:%u/%.2lf\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.signal.mean.errCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.signal.mean.maxMean);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"NUM:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.signal.num.errCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.inside.signal.num.maxNum);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"=====出仓状态=====\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"进仓光耦:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.oc.inOCCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"出仓光耦:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.oc.outOCCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"导通光耦:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.oc.gdOCCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"断开光耦:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.oc.releaseOCCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"小孔电压:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.xk.count,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.xk.maxValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"建压:%u/%d\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.pressure.buildCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.pressure.maxBuildPressureValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"密闭性:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.pressure.airtightCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.pressure.maxairtightValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"放气残余:%u/%d\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.pressure.noPressureCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.pressure.maxnoPressureValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"HGB开:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.hgb.openCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.hgb.maxOpenValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"HGB关:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.hgb.closeCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.hgb.maxCloseValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"计数池检测上:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.JscTypeCheckCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"计数池检测下:%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.JscDetectionCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"CV:%u/%.2lf\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.signal.cv.errCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.signal.cv.maxCV);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"MEAN:%u/%.2lf\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.signal.mean.errCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.signal.mean.maxMean);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"NUM:%u/%u\n",ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.signal.num.errCount,ServiceAgingTestUIInfo.unions.agingTestResultInfo.outside.signal.num.maxNum);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 break;
				 
			//进出仓老化测试
			case MOTOR_OUT_IN_RESULT:
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_HCENTER);
				 sprintf(StrBuf,"进出仓老化测试\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
				sprintf(StrBuf,"SN/RN:%u/%u\n",ServiceAgingTestUIInfo.unions.outInTestResultInfo.setCount,ServiceAgingTestUIInfo.unions.outInTestResultInfo.runCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"ST:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.year.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.month.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.day.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.min.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.startTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"ET:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.year.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.month.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.day.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.min.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.outInTestResultInfo.rtc.endTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"出仓异常：%u\n",ServiceAgingTestUIInfo.unions.outInTestResultInfo.outErrCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"进仓异常：%u\n",ServiceAgingTestUIInfo.unions.outInTestResultInfo.inErrCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"导通异常：%u\n",ServiceAgingTestUIInfo.unions.outInTestResultInfo.gdErrCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"断开异常：%u\n",ServiceAgingTestUIInfo.unions.outInTestResultInfo.sfErrCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			break;
			
			//气嘴密闭性测试结果显示
			case QIZUI_TEST_RESULT:
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_HCENTER);
				 sprintf(StrBuf,"气嘴密闭性测试\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
				sprintf(StrBuf,"SN/RN:%u/%u\n",ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.setCount,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.runCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"ST:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.year.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.month.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.day.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.min.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.startTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"ET:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.year.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.month.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.day.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.min.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.rtc.endTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"建压:%u/%d\n",ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.pressure.buildCount,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.pressure.maxBuildPressureValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"密闭性:%u/%u\n",ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.pressure.airtightCount,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.pressure.maxairtightValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"放气残余:%u/%d\n",ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.pressure.noPressureCount,ServiceAgingTestUIInfo.unions.qizuiTestResultInfo.pressure.maxnoPressureValue);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 break;
			 
			 //气阀老化测试结果显示
			case AIR_TEST_RESULT:
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_HCENTER);
				 sprintf(StrBuf,"气阀老化测试\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
				sprintf(StrBuf,"SN/RN:%u/%u\n",ServiceAgingTestUIInfo.unions.airValveTestResultInfo.setCount,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.runCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"ST:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.year.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.month.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.day.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.min.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.startTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"ET:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.year.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.month.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.day.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.min.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.airValveTestResultInfo.rtc.endTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 break;
			 
			 //液阀老化测试结果显示
			case YEFA_TEST_RESULT:
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_HCENTER);
				 sprintf(StrBuf,"液阀老化测试\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
				sprintf(StrBuf,"SN/RN:%u/%u\n",ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.setCount,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.runCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"ST:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.year.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.month.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.day.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.min.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.startTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"ET:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.year.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.month.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.day.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.min.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.yeFaValveTestResultInfo.rtc.endTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 break;
			 
			 //建压老化测试结果显示
			case BUILD_PRESSURE_TEST_RESULT:
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_HCENTER);
				 sprintf(StrBuf,"建压老化测试\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
				sprintf(StrBuf,"SN/RN:%u/%u\n",ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.setCount,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.runCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"ST:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.year.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.month.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.day.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.min.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.startTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"ET:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.year.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.month.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.day.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.min.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.rtc.endTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"建压到-10kPa:%u/%u ms\n",ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure10.buildCount,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure10.time);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"建压到-20kPa:%u/%u ms\n",ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure20.buildCount,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure20.time);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"建压到-30kPa:%u/%u ms\n",ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure30.buildCount,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure30.time);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"建压到-40kPa:%u/%u ms\n",ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure40.buildCount,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure40.time);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"建压到-50kPa:%u/%u ms\n",ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure50.buildCount,ServiceAgingTestUIInfo.unions.buildPressureTestResultInfo.pressure50.time);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 break;
			 
			 //定量电极老化测试
			case DL_ELEC_TEST_RESULT:
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_HCENTER);
				 sprintf(StrBuf,"定量电极老化测试\n");
				 MULTIEDIT_AddText(hItem,StrBuf);
				
				MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
				sprintf(StrBuf,"SN/RN:%u/%u\n",ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.setCount,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.runCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			 
				sprintf(StrBuf,"ST:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.year.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.month.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.day.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.min.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.startTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				sprintf(StrBuf,"ET:20%d%d-%d%d-%d%d %d%d:%d%d:%d%d\n",
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.year.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.year.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.month.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.month.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.day.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.day.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.hour.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.hour.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.min.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.min.bcd_l,
							ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.sec.bcd_h,ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.rtc.endTime.sec.bcd_l);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 
				 sprintf(StrBuf,"应触发态错误：%u\n",ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.activeStatusErrCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
				 sprintf(StrBuf,"非触发态错误：%u\n",ServiceAgingTestUIInfo.unions.dlElecTestResultInfo.idleStatusErrCount);
				 MULTIEDIT_AddText(hItem,StrBuf);
			break;
			 
			 default :break;
		 }
	break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateagingTestPage
*/
WM_HWIN CreateagingTestPage(void);
WM_HWIN CreateagingTestPage(void) {
	WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	Enable_Motor_Task(TRUE);
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), AgingTestPage_cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
