/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "file_operate.h"
#include "bsp_eeprom.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (DATA_MANAGE_PAGE_ID + 0x00)
#define ID_TEXT_0 (DATA_MANAGE_PAGE_ID + 0x01)
#define ID_TEXT_1 (DATA_MANAGE_PAGE_ID + 0x02)
#define ID_BUTTON_0 (DATA_MANAGE_PAGE_ID + 0x03)
#define ID_BUTTON_1 (DATA_MANAGE_PAGE_ID + 0x04)
#define ID_BUTTON_2 (DATA_MANAGE_PAGE_ID + 0x05)
#define ID_BUTTON_3 (DATA_MANAGE_PAGE_ID + 0x06)
#define ID_BUTTON_4 (DATA_MANAGE_PAGE_ID + 0x07)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "dataManagePage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SERV", ID_TEXT_0, 30, 15, 90, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> 数据管理", ID_TEXT_1, 122, 20, 140, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEL", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "重置仪器参数", ID_BUTTON_1, 320, 80, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "删除测试数据", ID_BUTTON_2, 320, 140, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "DEL USER DATA", ID_BUTTON_3, 320, 200, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "恢复出厂设置", ID_BUTTON_4, 320, 260, 160, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

static void _DataManagePageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	extern __IO MachRunPara_s	MachRunPara;
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("重置仪器参数",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("删除测试数据",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect(g_ucaLng_Serve_DEL_USERDATA[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("恢复出厂设置",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRectEx(&Rect,19);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("重置仪器参数",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("删除测试数据",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect(g_ucaLng_Serve_DEL_USERDATA[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("恢复出厂设置",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
* 设置控件回调函数，以及重绘控件
*/
static void _DataManagePageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //返回按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _DataManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//重置参数按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _DataManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//删除测试数据按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _DataManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//删除用户数据按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _DataManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//恢复出厂设置按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _DataManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  GUI_RECT Rect;
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreateSwitchDialogPage(void);
	extern WM_HWIN CreatedataManagePage(void);
	
	extern char* BKBmaDataBuf;
	extern  MachInfo_s	MachInfo;
    extern  __IO MachRunPara_s       MachRunPara;
	extern __IO DataManage_t  g_tDataManage;
	
	WM_HWIN hItem;
	
	CommonSwitchDialogPageData_s SwitchDialogData = {0};
  // USER END

  switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'service_t'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
			TEXT_SetFont(hItem,&HZ_SONGTI_24);
			WM_SetWindowPos(hItem,20, 13+63, 48, 30);
		}else{
			TEXT_SetFont(hItem,&GUI_Font24_ASCII);
			WM_SetWindowPos(hItem,20, 13+63, 84, 30);
		}
		TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
		TEXT_SetText(hItem,g_ucaLng_Serve_Serve[MachInfo.systemSet.eLanguage]);
		// USER START (Optionally insert additional code for further widget initialization)
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
			WM_SetWindowPos(hItem,68, 20+63, 140, 20);
		}else{
			WM_SetWindowPos(hItem,104, 20+63, 140, 20);
		}
		TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
		TEXT_SetText(hItem,g_ucaLng_Serve_DATAMENT[MachInfo.systemSet.eLanguage]);
	
		//重绘按钮样式
		_DataManagePageRedrawWidgetType(pMsg);
        
        //设置窗口颜色和背景颜色一致
        WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
	
		if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
			hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
			WM_HideWindow(hItem);
			hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2);
			WM_HideWindow(hItem);
			hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4);
			WM_HideWindow(hItem);
		}
    // USER END
    break;
	  
	  
	case WM_PAINT:
		//画背景BMP图
		//GUI_BMP_Draw(BKBmaDataBuf,1,0);
        //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
          WM_GetClientRect(&Rect); 
          GUI_SetColor(GUI_WHITE);
          GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
	break;
	  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateservicePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'resetRunPara_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹出选择对话框
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateSwitchDialogPage();
		
		//重置仪器参数
		SwitchDialogData.switchDialogItem = SERVICE_DATAMANAGE_RESET_PARA;
		SwitchDialogData.dialogData.bmpType = BMP_ALARM;
		SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
		SwitchDialogData.dialogData.fun = CreatedataManagePage;					//保存进入对话框前的界面创建函数
		strcpy(SwitchDialogData.dialogData.str,"确认重置仪器参数，完毕后将自动重启");
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &SwitchDialogData;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER ENDpsDebugInfo;
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '删除测试数据按钮'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹出选择对话框
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateSwitchDialogPage();
		
		//重置仪器参数
		SwitchDialogData.switchDialogItem = SERVICE_DATAMANAGE_DEL_TEST_DATA;
		SwitchDialogData.dialogData.bmpType = BMP_ALARM;
		SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
		SwitchDialogData.dialogData.fun = CreatedataManagePage;					//保存进入对话框前的界面创建函数
		strcpy(SwitchDialogData.dialogData.str,"确认删除测试数据，完毕后将自动重启");
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &SwitchDialogData;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '删除用户数据按钮'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹出选择对话框
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateSwitchDialogPage();
		
		//重置仪器参数
		SwitchDialogData.switchDialogItem = SERVICE_DATAMANAGE_DEL_USER_DATA;
		SwitchDialogData.dialogData.bmpType = BMP_ALARM;
		SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
		SwitchDialogData.dialogData.fun = CreatedataManagePage;					//保存进入对话框前的界面创建函数
		strcpy(SwitchDialogData.dialogData.str,g_ucaLng_Serve_CONFIM_DELUSERDATA[MachInfo.systemSet.eLanguage]);
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &SwitchDialogData;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
	  
	 case ID_BUTTON_4: // Notifications sent by 'resetFactory_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹出选择对话框
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateSwitchDialogPage();
		
		//重置仪器参数
		SwitchDialogData.switchDialogItem = SERVICE_DATAMANAGE_RECOVER_FACTORY;
		SwitchDialogData.dialogData.bmpType = BMP_ALARM;
		SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
		SwitchDialogData.dialogData.fun = CreatedataManagePage;					//保存进入对话框前的界面创建函数
		strcpy(SwitchDialogData.dialogData.str,"确认恢复出厂设置，将清除所有参数并重启仪器");
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &SwitchDialogData;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatedataManagePage
*/
WM_HWIN CreatedataManagePage(void);
WM_HWIN CreatedataManagePage(void) {
  WM_HWIN hWin;
	
	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
