/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "file_operate.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (DISK_PAGE_ID + 0x00)
#define ID_TEXT_0 (DISK_PAGE_ID + 0x01)
#define ID_TEXT_1 (DISK_PAGE_ID + 0x02)
#define ID_BUTTON_0 (DISK_PAGE_ID + 0x03)
#define ID_TEXT_2 (DISK_PAGE_ID + 0x04)
#define ID_TEXT_3 (DISK_PAGE_ID + 0x05)
#define ID_TEXT_4 (DISK_PAGE_ID + 0x06)
#define ID_TEXT_5 (DISK_PAGE_ID + 0x07)
#define ID_TEXT_6 (DISK_PAGE_ID + 0x08)
#define ID_TEXT_7 (DISK_PAGE_ID + 0x09)
#define ID_PROGBAR_0 (DISK_PAGE_ID + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "diskPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SERVE", ID_TEXT_0, 30, 15, 90, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> DISK", ID_TEXT_1, 120, 20, 150, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEL", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "USEDSPACE", ID_TEXT_2, 255, 160, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "FREESPACE", ID_TEXT_3, 410, 160, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "TOTALSPACE", ID_TEXT_4, 223, 219, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "totalPlaceNum_t", ID_TEXT_5, 478, 219, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "USEDSPACE", ID_TEXT_6, 223, 277, 110, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "usedPlaceNum_t", ID_TEXT_7, 478, 277, 100, 30, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 226, 125, 351, 16, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static int _Button_DrawSkin(const WIDGET_ITEM_DRAW_INFO* pDrawItemInfo)
{
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
	switch(pDrawItemInfo->Cmd){
		case WIDGET_ITEM_DRAW_BACKGROUND:
			if(BUTTON_IsPressed(pDrawItemInfo->hWin)){		//按钮按下时皮肤色
				switch(WM_GetId(pDrawItemInfo->hWin)){
					//返回
					case ID_BUTTON_0:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
				}
			}else{			//按钮没有按下时皮肤色
				switch(WM_GetId(pDrawItemInfo->hWin)){
					//返回
					case ID_BUTTON_0:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
				}
			}
		break;
		default:
			return BUTTON_SKIN_FLEX(pDrawItemInfo);
	}
	return 0;
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
  // USER START (Optionally insert additional variables)
	extern char* BKBmaDataBuf;
	
	//以页为单位
	uint32_t TotalNum = 0;
	uint32_t FreeNum = 0;
	PROGBAR_SKINFLEX_PROPS pProps;
	char StrTemp[20] = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	//获取NAND容量信息
	Nand_Volume_Info(&TotalNum,&FreeNum);
	
	//设置进度条
	hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
	PROGBAR_GetSkinFlexProps(&pProps,0);
	pProps.aColorLowerL[0] = MachInfo.companyInfo.skin.highlightKJNotSelect;
	pProps.aColorLowerL[1] = MachInfo.companyInfo.skin.highlightKJNotSelect;
	pProps.aColorUpperL[0] = MachInfo.companyInfo.skin.highlightKJNotSelect;
	pProps.aColorUpperL[1] = MachInfo.companyInfo.skin.highlightKJNotSelect;
	pProps.aColorLowerR[0] = 0x00f7f7f7;
	pProps.aColorLowerR[1] = 0x00f7f7f7;
	pProps.aColorUpperR[0] = 0x00f7f7f7;
	pProps.aColorUpperR[1] = 0x00f7f7f7;
	pProps.ColorFrame  = MachInfo.companyInfo.skin.buttBoard;
	PROGBAR_SetSkinFlexProps(&pProps,0);
	PROGBAR_SetMinMax(hItem,0,TotalNum/100);
	PROGBAR_SetValue(hItem,(TotalNum-FreeNum)/100);
	
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Serve_Serve[MachInfo.systemSet.eLanguage]); 

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Serve_DiskInfo[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	TEXT_SetText(hItem,g_ucaLng_Serve_UsedPlace[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	TEXT_SetText(hItem,g_ucaLng_Serve_CanPlace[MachInfo.systemSet.eLanguage]);
  
    //
    // Initialization of 'totalPlace_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_TotalPlace[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'totalPlaceNum_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	sprintf(StrTemp,"%.2f MB",TotalNum/2/1024.0);
	TEXT_SetText(hItem,StrTemp);
    //
    // Initialization of 'usedPlace_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_UsedPlace[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'usedPlaceNum_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	memset(StrTemp,0,20);
	sprintf(StrTemp,"%.2f MB",(TotalNum-FreeNum)/2/1024.0);
	TEXT_SetText(hItem,StrTemp);
	
	//设置按钮皮肤
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Return[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    break;
	
	case WM_PAINT:
          WM_GetClientRect(&Rect); 
          GUI_SetColor(GUI_WHITE);
          GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
	
		//画框
		GUI_SetColor(0x009ea0a2);
		GUI_AA_DrawRoundedRect(172,92,625,325,4);
	
		//画框内短线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(260,223,574);
	
		//画小矩形
		GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
		GUI_FillRect(226,160,238,172);
	
		GUI_SetColor(0x00f7f7f7);
		GUI_FillRect(384,160,396,172);
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateservicePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatediskPage
*/
WM_HWIN CreatediskPage(void);
WM_HWIN CreatediskPage(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
