/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bc.h"
#include "bsp_eeprom.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (JIAOHU_CHECK_PAGE_ID + 0x00)
#define ID_TEXT_0 (JIAOHU_CHECK_PAGE_ID + 0x01)
#define ID_TEXT_1 (JIAOHU_CHECK_PAGE_ID + 0x02)
#define ID_BUTTON_0 (JIAOHU_CHECK_PAGE_ID + 0x03)
#define ID_BUTTON_1 (JIAOHU_CHECK_PAGE_ID + 0x04)
#define ID_BUTTON_2 (JIAOHU_CHECK_PAGE_ID + 0x05)
#define ID_BUTTON_3 (JIAOHU_CHECK_PAGE_ID + 0x06)
#define ID_BUTTON_4 (JIAOHU_CHECK_PAGE_ID + 0x07)
#define ID_BUTTON_5 (JIAOHU_CHECK_PAGE_ID + 0x08)
#define ID_GRAPH_0 (JIAOHU_CHECK_PAGE_ID + 0x09)
#define ID_BUTTON_6 (JIAOHU_CHECK_PAGE_ID + 0x0a)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static uint8_t ShowVoiceButtFlag = 0;						//用于表示简易示波器按钮功能切换标志，即开/关简易示波器功能

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "jiaoHuCheckPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "服务", ID_TEXT_0, 30, 13, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> 交互自检", ID_TEXT_1, 90, 20, 104, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "返回", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "打印机测试", ID_BUTTON_1, 618, 80, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "电阻触摸校准", ID_BUTTON_2, 618, 140, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "边框显示测试", ID_BUTTON_3, 618, 200, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "屏幕显示测试", ID_BUTTON_4, 618, 260, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "简易示波器开", ID_BUTTON_5, 618, 320, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "性能检验", ID_BUTTON_6, 558, 11, 100, 40, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 20, 70, 550, 310, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _JiaohuCheckPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	extern __IO MachRunPara_s	MachRunPara;
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("打印机测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("电阻触摸校准",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("边框显示测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("屏幕显示测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					if(ShowVoiceButtFlag == 0){
						GUI_DispStringInRect("简易示波器开",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
					}else{
						GUI_DispStringInRect("简易示波器关",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
					}
				break;
					
				case ID_BUTTON_6:
					GUI_DispStringInRect("性能检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRectEx(&Rect,19);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("打印机测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("电阻触摸校准",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("边框显示测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("屏幕显示测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					if(ShowVoiceButtFlag == 0){
						GUI_DispStringInRect("简易示波器开",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
					}else{
						GUI_DispStringInRect("简易示波器关",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
					}
				break;
					
				case ID_BUTTON_6:
					GUI_DispStringInRect("性能检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
* 设置控件回调函数，以及重绘控件
*/
static void _JiaohuCheckPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //返回按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _JiaohuCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//打印机测试按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _JiaohuCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//电阻触摸校准按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _JiaohuCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//边框显示测试按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _JiaohuCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//屏幕显示测试按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _JiaohuCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//简易示波器按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, _JiaohuCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//性能检验按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, _JiaohuCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	extern char* BKBmaDataBuf;
	extern __IO BC_Data_t   g_stBC_Data[BC_END];
	extern WM_HWIN CreatescreenRGBTestPage(void);
	extern WM_HWIN CreatePCBA_Page(void);
	
	static GRAPH_SCALE_Handle GraphScaleHandleV = NULL;
	static GRAPH_DATA_Handle GraphDataHandle = NULL;
	static uint32_t PointNum = 0;
	static uint8_t ScareenBordFlag = 0;
	static uint16_t* ShiboqiDataStartAdr = NULL;
	
	Msg_Head_t BackendMsg = {0};
	uint32_t i = 0;
	GUI_RECT Rect;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  {
	ShiboqiDataStartAdr = (uint16_t*)SDRAM_ApplyCommonBuf(3*1024*1024);  
  
	//初始化标志位
	ShowVoiceButtFlag = 0;
	  
	
  
    //
    // Initialization of 'Graph'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 45, 5, 5, 5);
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem,&HZ_SONGTI_24);
	WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"服务");
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
  
    // USER START (Optionally insert additional code for further widget initialization)
	//设置曲线控件参数
	hItem = WM_GetDialogItem(pMsg->hWin,ID_GRAPH_0);
	GRAPH_SetGridVis(hItem,1);																				//设置网格可见
	GraphScaleHandleV = GRAPH_SCALE_Create(10,GUI_TA_VCENTER,GRAPH_SCALE_CF_VERTICAL,50);					//创建垂直刻度对象
	GRAPH_AttachScale(hItem, GraphScaleHandleV);
	GRAPH_SCALE_SetFactor(GraphScaleHandleV, 1.241);														//设置转换因子，这里是像素值 = AD/因子值
	
	//创建数据对象
	GraphDataHandle = GRAPH_DATA_YT_Create(GUI_WHITE, 500, 0, 0);
	GRAPH_AttachData(hItem, GraphDataHandle);
  
	//重绘按钮样式
	_JiaohuCheckPageRedrawWidgetType(pMsg);
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
  }
    // USER END
    break;
  
	case WM_PAINT:
		//画背景BMP图
		WM_GetClientRect(&Rect); 
		GUI_SetColor(GUI_WHITE);
		GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
	break;
		
	case WM_POST_PAINT:
		if(ScareenBordFlag == 1){
			GUI_GetClientRect(&Rect);
			
			//画被重绘的边框
			GUI_SetPenSize(5);
			GUI_SetColor(GUI_RED);
			GUI_DrawVLine(Rect.x0,Rect.y0,Rect.y1);
			GUI_DrawVLine(Rect.x1,Rect.y0,Rect.y1);
		}
	break;
		
	case WM_DELETE:
	{
	}break;

		
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateservicePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'printer_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_INTERACTION_PRINTER;
        UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'touch_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//重新进入校准界面进行校准
		MachInfo.touch.flag = TOUCH_FOCUS_FLAG;
		EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EEPROM_ADDR_MACHINFO_INIT_TOUCH,(uint8_t*)&MachInfo.touch,sizeof(MachInfo.touch));
	  
		//重启
		__set_PRIMASK(1);
		NVIC_SystemReset();
		// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'showBoard_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_INTERACTION_SCREEN_BOARD;
        UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'screenTest_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreatescreenRGBTestPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'showViose_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(ShowVoiceButtFlag == 0){
			//开启恒流源
			BC_CUR_SW_ON;
			HAL_Delay(500);
			
			//初始化用于存放示波器数据的SDRAM
			memset(ShiboqiDataStartAdr,0,3*1024*1024);
			
			PointNum = 0;
			
			//开启数据采集以及显示波形
			//关闭调度器
			osKernelLock();
			
			//使能血细胞信号采集
			BC_Enable(BC_WBC);
			
			while(1){
				if(PointNum >= 1024*1024){
					//关闭采集
					BC_Disable(BC_WBC);
					
					//恢复调度器
					osKernelUnlock();
					
					break;
				}
				
				if(BC_ADC_PART_1 == g_stBC_Data[BC_WBC].ucFlag){
					for(i=0;i<512;i++){
						*(ShiboqiDataStartAdr+PointNum) = g_stBC_Data[BC_WBC].ucBuf[i];
						PointNum++;
					}
					
					//复位标志
					g_stBC_Data[BC_WBC].ucFlag = BC_ADC_PART_NONE;
				}else if(BC_ADC_PART_2 == g_stBC_Data[BC_WBC].ucFlag){
					for(i=512;i<1024;i++){
						*(ShiboqiDataStartAdr+PointNum) = g_stBC_Data[BC_WBC].ucBuf[i];
						PointNum++;
					}
					
					//复位标志
					g_stBC_Data[BC_WBC].ucFlag = BC_ADC_PART_NONE;
				}
			}
			
			//关闭恒流源
			BC_CUR_SW_OFF;
			
			PointNum = 0;
			//创建窗口定时器,100ms触发一次
			WM_CreateTimer(pMsg->hWin,0,100,0);
		}
	  
		ShowVoiceButtFlag ^= 1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	
	case ID_BUTTON_6: // Notifications sent by '性能检验'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  {
		extern WM_HWIN CreateXNCheckPage(void);

		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateXNCheckPage();
	  }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	
	//窗口定时器消息
	case WM_TIMER:
		for(i=0;i<250;i++){
			GRAPH_DATA_YT_AddValue(GraphDataHandle,*(ShiboqiDataStartAdr+PointNum++));
		}
		
		if(PointNum < 1024*1024){
			//重启计时器
			if(ShowVoiceButtFlag == 1){
				WM_RestartTimer(pMsg->Data.v,100);
			}
		}else{
			ShowVoiceButtFlag ^= 1;
			WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
		}
	break;
	
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatejiaoHuCheckPage
*/
WM_HWIN CreatejiaoHuCheckPage(void);
WM_HWIN CreatejiaoHuCheckPage(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
