/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "file_operate.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (LOG_PAGE_ID + 0x00)
#define ID_TEXT_0 (LOG_PAGE_ID + 0x01)
#define ID_TEXT_1 (LOG_PAGE_ID + 0x02)
#define ID_BUTTON_0 (LOG_PAGE_ID + 0x03)
#define ID_LISTVIEW_0 (LOG_PAGE_ID + 0x04)
#define ID_BUTTON_1 (LOG_PAGE_ID + 0x05)
#define ID_BUTTON_2 (LOG_PAGE_ID + 0x06)
#define ID_BUTTON_3 (LOG_PAGE_ID + 0x07)
#define ID_BUTTON_4 (LOG_PAGE_ID + 0x08)
#define ID_MULTIEDIT_0 (LOG_PAGE_ID + 0x09)
#define ID_BUTTON_5 (LOG_PAGE_ID + 0x0a)
#define ID_BUTTON_6 (LOG_PAGE_ID + 0x0b)
#define ID_BUTTON_7 (LOG_PAGE_ID + 0x0c)
#define ID_BUTTON_8 (LOG_PAGE_ID + 0x0d)


// USER START (Optionally insert additional defines)
/***
*用于显示日志信息的相关结构体
***/
typedef struct _ShowLogInfo_s{
	uint32_t firstIndex;			//往以往记录方向的NAND数据序列号
	uint32_t lastIndex;				//往最新记录方向的NAND数据序列号
	
	uint32_t countUpNum;			//指示计数日志上翻还剩余的有效日志条数
	uint32_t countDownNum;			//指示计数日志下翻还剩余的有效日志条数
	
	AccountDataType_e curAccount;	//指示当前账户类型，内部账户还是外部账户
	
	uint8_t num;					//用于表示firstIndex和lastIndex之间间隔了多少个数据，正常情况下是间隔5个正常数据，最大值为5
	uint8_t logType;				//用于表示要显示的日志类型，为0表示要显示测试数据日志，为1表示要显示故障日志，为2表示要显示运行日志
	
	uint32_t upperSNNum;			//用于表示当前显示的上翻边界序列号，用于确定显示的序列号
	
	union{
		CountLog_s countLog[10];	//测试数据日志
		RunLog_s runLog[5];			//运行日志
	}un;
}ShowLogInfo_s;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
//用于保存从NAND中读取到的日志信息
static ShowLogInfo_s* ShowLogInfo = NULL;

//用于各上下翻按钮在遇到删除数据时，不能失能时使用，为1表示该按钮强制无效
static uint8_t UUpUnactiveFlag = 0;
static uint8_t UpUnactiveFlag = 0;
static uint8_t DDownUnactiveFlag = 0;
static uint8_t DownUnactiveFlag = 0;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "logPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SRV", ID_TEXT_0, 30, 15, 90, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "logType_t", ID_TEXT_1, 122, 20, 140, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEL", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 20, 58, 720, 187, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "uup_b", ID_BUTTON_1, 740, 58, 40, 48, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "up_b", ID_BUTTON_2, 740, 106, 40, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "down_b", ID_BUTTON_3, 740, 151, 40, 45, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ddown_b", ID_BUTTON_4, 740, 196, 40, 49, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 20, 257, 760, 130, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CONS ERR", ID_BUTTON_5, 568, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "OPER ERR", ID_BUTTON_6, 458, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "MACH ERR", ID_BUTTON_7, 348, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ZH ERR", ID_BUTTON_8, 238, 11, 100, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

static int _Button_DrawSkin(const WIDGET_ITEM_DRAW_INFO* pDrawItemInfo)
{
	extern  __IO MachRunPara_s       MachRunPara;
    extern  __IO DataManage_t    g_tDataManage;
	
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
	switch(pDrawItemInfo->Cmd){
		case WIDGET_ITEM_DRAW_BACKGROUND:
			if(BUTTON_IsPressed(pDrawItemInfo->hWin)){		//按钮按下时皮肤色
				switch(WM_GetId(pDrawItemInfo->hWin)){
					//返回
					case ID_BUTTON_0:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
					
					//耗材故障
					case ID_BUTTON_5:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
					
					//操作故障
					case ID_BUTTON_6:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
					
					//仪器故障
					case ID_BUTTON_7:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
					
					//综合故障
					case ID_BUTTON_8:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
					
					//上上按钮
					case ID_BUTTON_1:
						GUI_SetColor(MachInfo.companyInfo.skin.title);
						GUI_FillRectEx(&Rect);
						GUI_SetColor(0x00cccccc);
						GUI_DrawRectEx(&Rect);
						UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
					break;
					
					//上按钮
					case ID_BUTTON_2:
						GUI_SetColor(MachInfo.companyInfo.skin.title);
						GUI_FillRectEx(&Rect);
						GUI_SetColor(0x00cccccc);
						GUI_DrawRectEx(&Rect);
						UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
					break;
					
					//下按钮
					case ID_BUTTON_3:
						GUI_SetColor(MachInfo.companyInfo.skin.title);
						GUI_FillRectEx(&Rect);
						GUI_SetColor(0x00cccccc);
						GUI_DrawRectEx(&Rect);
						UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
					break;
					
					//下下按钮
					case ID_BUTTON_4:
						GUI_SetColor(MachInfo.companyInfo.skin.title);
						GUI_FillRectEx(&Rect);
						GUI_SetColor(0x00cccccc);
						GUI_DrawRectEx(&Rect);
						UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_WHITE);
					break;
				}
			}else{			//按钮没有按下时皮肤色
				switch(WM_GetId(pDrawItemInfo->hWin)){
					//返回
					case ID_BUTTON_0:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
					
					//耗材故障
					case ID_BUTTON_5:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
					
					//操作故障
					case ID_BUTTON_6:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
					
					//仪器故障
					case ID_BUTTON_7:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
					
					//综合故障
					case ID_BUTTON_8:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
					
					//上上按钮
					case ID_BUTTON_1:
						if(ShowLogInfo->num < 5 || UUpUnactiveFlag == 1){
							//淡色背景
							GUI_SetColor(0x00f3f1ec);
							GUI_FillRectEx(&Rect);
							GUI_SetColor(0x00cccccc);
							GUI_DrawRectEx(&Rect);
							
							UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
							WM_DisableWindow(pDrawItemInfo->hWin);
						}else{
							switch(ShowLogInfo->logType){
								//测试日志，故障日志
								case 0:
								case 1:
									if(ShowLogInfo->countUpNum >= 5){
										//还够5行数据
										//深色背景
										GUI_SetColor(MachInfo.companyInfo.skin.title);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
										WM_EnableWindow(pDrawItemInfo->hWin);
									}else{
										//不够5行数据
										//淡色背景
										GUI_SetColor(0x00f3f1ec);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
										WM_DisableWindow(pDrawItemInfo->hWin);
									}
								break;
								
								//运行日志
								case 2:
									if(ShowLogInfo->lastIndex > g_tDataManage.ulRunLog_Queue_TailIndex){
										if(ShowLogInfo->lastIndex+5 < RUN_LOG_MAX_NUM){
											//还够5行数据
											//深色背景
											GUI_SetColor(MachInfo.companyInfo.skin.title);
											GUI_FillRectEx(&Rect);
											GUI_SetColor(0x00cccccc);
											GUI_DrawRectEx(&Rect);
											
											UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
											
											WM_EnableWindow(pDrawItemInfo->hWin);
										}else{
											if((ShowLogInfo->lastIndex+5)%RUN_LOG_MAX_NUM > g_tDataManage.ulRunLog_Queue_TailIndex){
												//不够5行数据
												//淡色背景
												GUI_SetColor(0x00f3f1ec);
												GUI_FillRectEx(&Rect);
												GUI_SetColor(0x00cccccc);
												GUI_DrawRectEx(&Rect);
												
												UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
												
												WM_DisableWindow(pDrawItemInfo->hWin);
											}else{
												//还够5行数据
												//深色背景
												GUI_SetColor(MachInfo.companyInfo.skin.title);
												GUI_FillRectEx(&Rect);
												GUI_SetColor(0x00cccccc);
												GUI_DrawRectEx(&Rect);
												
												UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
												
												WM_EnableWindow(pDrawItemInfo->hWin);
											}
										}
									}else{
										if(ShowLogInfo->lastIndex+5 > g_tDataManage.ulRunLog_Queue_TailIndex){
											//不够5行数据
											//淡色背景
											GUI_SetColor(0x00f3f1ec);
											GUI_FillRectEx(&Rect);
											GUI_SetColor(0x00cccccc);
											GUI_DrawRectEx(&Rect);
											
											UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
											
											WM_DisableWindow(pDrawItemInfo->hWin);
										}else{
											//还够5行数据
											//深色背景
											GUI_SetColor(MachInfo.companyInfo.skin.title);
											GUI_FillRectEx(&Rect);
											GUI_SetColor(0x00cccccc);
											GUI_DrawRectEx(&Rect);
											
											UI_DrawSanJiao(UUP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
											
											WM_EnableWindow(pDrawItemInfo->hWin);
										}
									}
								break;
								default :break;
							}
						}
					break;
					
					//上按钮
					case ID_BUTTON_2:
						if(ShowLogInfo->num < 5 || UpUnactiveFlag == 1){
							//淡色背景
							GUI_SetColor(0x00f3f1ec);
							GUI_FillRectEx(&Rect);
							GUI_SetColor(0x00cccccc);
							GUI_DrawRectEx(&Rect);
							
							UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
							WM_DisableWindow(pDrawItemInfo->hWin);
						}else{
							switch(ShowLogInfo->logType){
								//测试日志，故障日志
								case 0:
								case 1:
									if(ShowLogInfo->countUpNum >= 1){
										//还够1行数据
										//深色背景
										GUI_SetColor(MachInfo.companyInfo.skin.title);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
										
										WM_EnableWindow(pDrawItemInfo->hWin);
									}else{
										//不够1行数据
										//淡色背景
										GUI_SetColor(0x00f3f1ec);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
										
										WM_DisableWindow(pDrawItemInfo->hWin);
									}
								break;
								
								//运行日志
								case 2:
									if(ShowLogInfo->lastIndex == g_tDataManage.ulRunLog_Queue_TailIndex){
										//不够1行数据
										//淡色背景
										GUI_SetColor(0x00f3f1ec);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
										
										WM_DisableWindow(pDrawItemInfo->hWin);
									}else{
										//还够1行数据
										//深色背景
										GUI_SetColor(MachInfo.companyInfo.skin.title);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(UP_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
										
										WM_EnableWindow(pDrawItemInfo->hWin);
									}
								break;
								default :break;
							}
						}
					break;
					
					//下按钮
					case ID_BUTTON_3:
						if(ShowLogInfo->num < 5 || DownUnactiveFlag == 1){
							//淡色背景
							GUI_SetColor(0x00f3f1ec);
							GUI_FillRectEx(&Rect);
							GUI_SetColor(0x00cccccc);
							GUI_DrawRectEx(&Rect);
							
							UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
							WM_DisableWindow(pDrawItemInfo->hWin);
						}else{
							switch(ShowLogInfo->logType){
								//测试日志，故障日志
								case 0:
								case 1:
									if(ShowLogInfo->countDownNum >= 1){
										//还够1行数据
										//深色背景
										GUI_SetColor(MachInfo.companyInfo.skin.title);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
										
										WM_EnableWindow(pDrawItemInfo->hWin);
									}else{
										//不够1行数据
										//淡色背景
										GUI_SetColor(0x00f3f1ec);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
										
										WM_DisableWindow(pDrawItemInfo->hWin);
									}
								break;
								
								//运行日志
								case 2:
									if(ShowLogInfo->firstIndex == g_tDataManage.ulRunLog_Queue_HeadIndex){
										//不够1行数据
										//淡色背景
										GUI_SetColor(0x00f3f1ec);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
										
										WM_DisableWindow(pDrawItemInfo->hWin);
									}else{
										//还够1行数据
										//深色背景
										GUI_SetColor(MachInfo.companyInfo.skin.title);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(DOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
										
										WM_EnableWindow(pDrawItemInfo->hWin);
									}
								break;
								default :break;
							}
						}
					break;
					
					//下下按钮
					case ID_BUTTON_4:
						if(ShowLogInfo->num < 5 || DDownUnactiveFlag == 1){
							//淡色背景
							GUI_SetColor(0x00f3f1ec);
							GUI_FillRectEx(&Rect);
							GUI_SetColor(0x00cccccc);
							GUI_DrawRectEx(&Rect);
							
							UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
							WM_DisableWindow(pDrawItemInfo->hWin);
						}else{
							switch(ShowLogInfo->logType){
								//测试日志，故障日志
								case 0:
								case 1:
									if(ShowLogInfo->countDownNum >= 5){
										//还够5行数据
										//深色背景
										GUI_SetColor(MachInfo.companyInfo.skin.title);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
										
										WM_EnableWindow(pDrawItemInfo->hWin);
									}else{
										//不够5行数据
										//淡色背景
										GUI_SetColor(0x00f3f1ec);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
										
										WM_DisableWindow(pDrawItemInfo->hWin);
									}
								break;
								
								//运行日志
								case 2:
									if(ShowLogInfo->firstIndex < g_tDataManage.ulRunLog_Queue_HeadIndex){
										//还够5行数据
										//深色背景
										GUI_SetColor(MachInfo.companyInfo.skin.title);
										GUI_FillRectEx(&Rect);
										GUI_SetColor(0x00cccccc);
										GUI_DrawRectEx(&Rect);
										
										UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
										
										WM_EnableWindow(pDrawItemInfo->hWin);
									}else{
										if(g_tDataManage.ulRunLog_Queue_HeadIndex+5 > ShowLogInfo->firstIndex){
											//不够5行数据
											//淡色背景
											GUI_SetColor(0x00f3f1ec);
											GUI_FillRectEx(&Rect);
											GUI_SetColor(0x00cccccc);
											GUI_DrawRectEx(&Rect);
											
											UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_LIGHTGRAY);
											
											WM_DisableWindow(pDrawItemInfo->hWin);
										}else{
											//还够5行数据
											//深色背景
											GUI_SetColor(MachInfo.companyInfo.skin.title);
											GUI_FillRectEx(&Rect);
											GUI_SetColor(0x00cccccc);
											GUI_DrawRectEx(&Rect);
											
											UI_DrawSanJiao(DDOWN_SAN_JIAO,Rect.x1>>1,Rect.y1>>1,GUI_BLACK);
											
											WM_EnableWindow(pDrawItemInfo->hWin);
										}
									}
								break;
								default :break;
							}
						}
					break;
				}
			}
		break;
		default:
			return BUTTON_SKIN_FLEX(pDrawItemInfo);
	}
	return 0;
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreateservicePage(void);
	
	extern char* BKBmaDataBuf;
	extern  __IO MachRunPara_s       MachRunPara;
    extern  __IO DataManage_t    g_tDataManage;
	extern  MachInfo_s	MachInfo;
	
	static ErrorType_e ShowErrType = ERROR_CODE_TYPE_NORMAL;		//用于故障日志显示中进行分类显示
	
	GUI_RECT Rect;
	HEADER_SKINFLEX_PROPS pProps;
	uint32_t i = 0;
	uint32_t Temp = 0;
	char Str[100] = {0};
	uint16_t TempLen = 0;
	uint16_t TempU16 = 0;

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:  
	//初始化用于保存日志信息的SDRAM空间
	ShowLogInfo = (ShowLogInfo_s*)SDRAM_ApplyCommonBuf(sizeof(ShowLogInfo_s));
  
	UUpUnactiveFlag = 0;
	UpUnactiveFlag = 0;
	DDownUnactiveFlag = 0;
	DownUnactiveFlag = 0;
  
	ShowErrType = ERROR_CODE_TYPE_NORMAL;
  
	//判断当前账户类型
	ShowLogInfo->curAccount = MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].dataType;
	
    //
    // Initialization of 'service_t'
    //
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Serve_Serve[MachInfo.systemSet.eLanguage]);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
    //
    // Initialization of 'Listview'列表相关
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
  
	//设置HEADER皮肤属性
	LISTVIEW_GetHeader(hItem);
	HEADER_GetSkinFlexProps(&pProps,0);
	pProps.aColorLower[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorLower[1] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[1] = MachInfo.companyInfo.skin.title;
	HEADER_SetSkinFlexProps(&pProps,0);
	
	LISTVIEW_SetFont(hItem,&HZ_SONGTI_16);
	LISTVIEW_AddColumn(hItem, 55, g_ucaLng_Serve_XuHao[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 170, g_ucaLng_Serve_Time[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 160, g_ucaLng_Serve_OutlineInfo[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_AddColumn(hItem, 220, g_ucaLng_Serve_Status[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 115, g_ucaLng_Serve_Operator[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_SetRowHeight(hItem, 29);
    LISTVIEW_SetHeaderHeight(hItem, 40);
	LISTVIEW_SetBkColor(hItem,LISTVIEW_CI_SELFOCUS,MachInfo.companyInfo.skin.highlightKJNotSelect);
	
	
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
	MULTIEDIT_SetReadOnly(hItem,1);
	MULTIEDIT_SetBufferSize(hItem, 4096);
	MULTIEDIT_SetAutoScrollV(hItem, 1);
	MULTIEDIT_SetAutoScrollH(hItem, 0);
	MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, 0x001a1a1a);
	MULTIEDIT_SetBkColor(hItem, MULTIEDIT_CI_READONLY,0x00ffffff);
	MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
	MULTIEDIT_SetFont(hItem,&HZ_SONGTI_16);
	MULTIEDIT_ShowCursor(hItem,0);
	MULTIEDIT_SetInsertMode(hItem,0);
	MULTIEDIT_SetWrapWord(hItem);
	
	//设置按钮皮肤
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Return[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Serve_HaocaiErr[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	WM_HideWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Serve_OperatorErr[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	WM_HideWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Serve_MachErr[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	WM_HideWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Serve_ZHErr[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	WM_HideWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetText(hItem,"");
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
	BUTTON_SetText(hItem,"");
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
	BUTTON_SetText(hItem,"");
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
	BUTTON_SetText(hItem,"");
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
    // USER START (Optionally insert additional code for further widget initialization)
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    // USER END
    break;
	
	case WM_PAINT:
      WM_GetClientRect(&Rect); 
      GUI_SetColor(GUI_WHITE);
      GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
	break;
	
	case WM_USER_DATA:		
		//保存要显示的日志类型
		ShowLogInfo->logType = pMsg->Data.v;
	
		//显示日志类型
		switch(ShowLogInfo->logType){
			//测试日志
			case 0:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				TEXT_SetText(hItem,g_ucaLng_Serve_Testlog[MachInfo.systemSet.eLanguage]);
			
				//初始化各参数值
				//计算上翻和下翻剩余值
				ShowLogInfo->countUpNum = 0;	
				ShowLogInfo->countDownNum = g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum>5?g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum-5:0;
				
				//确定当前是否有5条数据
				ShowLogInfo->num = g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum>5?5:g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum;
			
				//读取最新一条日志头信息
				if(ShowLogInfo->num >= 1){
					FatFs_Read_ConutHead(g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulQueue_TailIndex-1,&ShowLogInfo->un.countLog[0].logHead);
				}
			
				//读取日志头信息
				for(i=1;i<ShowLogInfo->num;i++){
					FatFs_Read_ConutHead(ShowLogInfo->un.countLog[i-1].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[i].logHead);
				}
				
				//初始化序号
				ShowLogInfo->upperSNNum = 1;
				
				//初始化显示的第一条序号
				TempU16 = ShowLogInfo->upperSNNum;
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者账户类型
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//故障日志
			case 1:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				TEXT_SetText(hItem,g_ucaLng_Serve_Errlog[MachInfo.systemSet.eLanguage]);
			
				//显示隐藏按钮
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
                WM_ShowWindow(hItem);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
                WM_ShowWindow(hItem);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
                WM_ShowWindow(hItem);
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
                WM_ShowWindow(hItem);
			
				TempLen = g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum;
			
				//读取最新一条日志头信息
				if(TempLen >= 1){
					FatFs_Read_ConutHead(g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulQueue_TailIndex-1,&ShowLogInfo->un.countLog[0].logHead);
					
					//判断是否故障日志
					if(ShowLogInfo->un.countLog[0].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen--;
						
						//查找最新一条故障日志头信息
						while(TempLen >= 1){
							FatFs_Read_ConutHead(ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[0].logHead);
							if(ShowLogInfo->un.countLog[0].logHead.eErrorCode != ERROR_CODE_SUCCESS){
								break;
							}
							
							TempLen--;
						}
					}
				}
				
				//判断是否没有一条故障数据，是，则直接break;
				if(TempLen == 0){
					ShowLogInfo->countUpNum = 0;	
					ShowLogInfo->countDownNum = 0;
					ShowLogInfo->num = 0;
					break;
				}
				
				Temp = ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex;
				TempU16 = 1;
				for(i=1;i<TempLen;i++){
					FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[TempU16].logHead);
					
					if(ShowLogInfo->un.countLog[TempU16].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
					}else{
						Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
						TempU16++;
					}
					
					if(TempU16 >= 5){
						break;
					}
				}
				
				//计算上翻和下翻剩余值
				ShowLogInfo->countUpNum = 0;	
				ShowLogInfo->countDownNum = TempLen-i-1;
				
				//确定当前是否有5条数据
				ShowLogInfo->num = TempU16;
			
				//初始化序号
				ShowLogInfo->upperSNNum = 1;
				
				//初始化显示的第一条序号
				TempU16 = ShowLogInfo->upperSNNum;
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//运行日志
			case 2:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
				TEXT_SetText(hItem,g_ucaLng_Serve_Runlog[MachInfo.systemSet.eLanguage]);
			
				ShowLogInfo->num = 0;
				ShowLogInfo->lastIndex = g_tDataManage.ulRunLog_Queue_TailIndex;
				if(ShowLogInfo->lastIndex >= 5){
					ShowLogInfo->firstIndex = ShowLogInfo->lastIndex - 5;
				}else{
					if(g_tDataManage.ulRunLog_Queue_TailIndex < g_tDataManage.ulRunLog_Queue_HeadIndex){
						//表示运行日志已经满了，尾指针从头开始写入了
						ShowLogInfo->firstIndex = RUN_LOG_MAX_NUM - (5-ShowLogInfo->lastIndex);
					}else{
						ShowLogInfo->firstIndex = g_tDataManage.ulRunLog_Queue_HeadIndex;
					}
				}
			
				//初始化序号
				ShowLogInfo->upperSNNum = 1;
				
				TempU16 = 4;
				//从NAND中读取数据，并填充到指定位置
				for(i=ShowLogInfo->firstIndex;i!=ShowLogInfo->lastIndex;){
					FatFs_Read_RunLog(i,&ShowLogInfo->un.runLog[TempU16--]);
					ShowLogInfo->num++;
					i = (i+1)%RUN_LOG_MAX_NUM;
				}
				
				//当初始数据不足5行时，需要重新规整读取到的日志头数据顺序
				if(ShowLogInfo->num < 5){
					for(i=0;i<ShowLogInfo->num;i++){
						TempU16++;
						ShowLogInfo->un.runLog[i] = ShowLogInfo->un.runLog[TempU16];
					}
				}
				
				//初始化显示的第一条序号
				TempU16 = ShowLogInfo->upperSNNum;
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					LISTVIEW_SetItemText(hItem,1,i,ShowLogInfo->un.runLog[i].logHead.dataTime);
					
					TempLen = sprintf(Str,"%u",ShowLogInfo->un.runLog[i].logHead.num);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,2,i,Str);
					
					LISTVIEW_SetItemText(hItem,3,i,ShowLogInfo->un.runLog[i].logHead.shortStr);
					
					switch(ShowLogInfo->un.runLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			default :break;
		}
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateservicePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_5: // Notifications sent by '耗材故障'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		ShowErrType = ERROR_CODE_TYPE_MATERIAL;
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,g_ucaLng_Serve_Conserr[MachInfo.systemSet.eLanguage]);
	  
		//清除掉多行编辑框中的数据
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
		MULTIEDIT_SetText(hItem,"");
	  
		//重置参数
		UUpUnactiveFlag = 0;
		UpUnactiveFlag = 0;
		DDownUnactiveFlag = 0;
		DownUnactiveFlag = 0;
	  
		//四个按键重绘
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
	  
		//确定当前是否有5条数据
		TempLen = g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum;
	
		//读取最新一条日志头信息
		if(TempLen >= 1){
			FatFs_Read_ConutHead(g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulQueue_TailIndex-1,&ShowLogInfo->un.countLog[0].logHead);
			
			//判断是否属于耗材故障
            if(ShowLogInfo->un.countLog[0].logHead.errType != ERROR_CODE_TYPE_MATERIAL){
				TempLen--;
			
				//查找最新一条故障日志头信息
				while(TempLen >= 1){
					FatFs_Read_ConutHead(ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[0].logHead);
                    if(ShowLogInfo->un.countLog[0].logHead.errType == ERROR_CODE_TYPE_MATERIAL){
						break;
					}
					
					TempLen--;
				}
			}
		}
		
		//清除原先列表值
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetNumRows(hItem);
		for(i=0;i<TempU16;i++){
			LISTVIEW_DeleteRow(hItem,0);
		}
		
		ShowLogInfo->countUpNum = 0;	
		ShowLogInfo->countDownNum = 0;
		ShowLogInfo->num = 0;
		
		//判断是否没有一条数据，是，则直接break;
		if(TempLen == 0){
			break;
		}
		
		Temp = ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex;
		TempU16 = 1;
		for(i=1;i<TempLen;i++){
			FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[TempU16].logHead);
			
            if(ShowLogInfo->un.countLog[TempU16].logHead.errType == ERROR_CODE_TYPE_MATERIAL){
				Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
				TempU16++;
			}else{
				Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
			}
			
			if(TempU16 >= 5){
				break;
			}
		}
		
		//计算上翻和下翻剩余值
		ShowLogInfo->countUpNum = 0;	
		ShowLogInfo->countDownNum = TempLen-i-1;
		
		//确定当前是否有5条数据
		ShowLogInfo->num = TempU16;
	
		//初始化序号
		ShowLogInfo->upperSNNum = 1;
		
		//初始化显示的第一条序号
		TempU16 = ShowLogInfo->upperSNNum;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		for(i=0;i<ShowLogInfo->num;i++){
			LISTVIEW_AddRow(hItem, NULL);
			
			//序号
			TempLen = sprintf(Str,"%u",TempU16);
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,0,i,Str);
			TempU16++;
			
			//时间
			LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
			
			//概要信息
			LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
			
			//结果
			if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
				TempLen = sprintf(Str,"Success");
			}else{
				TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
			}
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,3,i,Str);
			
			//操作者
			switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
				case ACCOUNT_TYPE_SUPER:
					TempLen = sprintf(Str,"Super");
				break;
				case ACCOUNT_TYPE_ADMIN:
					TempLen = sprintf(Str,"Admin");
				break;
				case ACCOUNT_TYPE_NORMAL:
					TempLen = sprintf(Str,"Normal");
				break;
				case ACCOUNT_TYPE_NEW:
					TempLen = sprintf(Str,"New User");
				break;
				default :break;
			}
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,4,i,Str);
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_6: // Notifications sent by '操作故障'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		ShowErrType = ERROR_CODE_TYPE_USER;
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,g_ucaLng_Serve_Operatorerr[MachInfo.systemSet.eLanguage]);
	  
		//清除掉多行编辑框中的数据
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
		MULTIEDIT_SetText(hItem,"");
	  
		//重置参数
		UUpUnactiveFlag = 0;
		UpUnactiveFlag = 0;
		DDownUnactiveFlag = 0;
		DownUnactiveFlag = 0;
	  
		//四个按键重绘
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
	  
		//确定当前是否有5条数据
		TempLen = g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum;
	
		//读取最新一条日志头信息
		if(TempLen >= 1){
			FatFs_Read_ConutHead(g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulQueue_TailIndex-1,&ShowLogInfo->un.countLog[0].logHead);
			
			//判断是否属于耗材故障
            if(ShowLogInfo->un.countLog[0].logHead.errType != ERROR_CODE_TYPE_USER){
				TempLen--;
			
				//查找最新一条故障日志头信息
				while(TempLen >= 1){
					FatFs_Read_ConutHead(ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[0].logHead);
                    if(ShowLogInfo->un.countLog[0].logHead.errType == ERROR_CODE_TYPE_USER){
						break;
					}
					
					TempLen--;
				}
			}
		}
		
		//清除原先列表值
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetNumRows(hItem);
		for(i=0;i<TempU16;i++){
			LISTVIEW_DeleteRow(hItem,0);
		}
		
		ShowLogInfo->countUpNum = 0;	
		ShowLogInfo->countDownNum = 0;
		ShowLogInfo->num = 0;
		
		//判断是否没有一条数据，是，则直接break;
		if(TempLen == 0){
			break;
		}
		
		Temp = ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex;
		TempU16 = 1;
		for(i=1;i<TempLen;i++){
			FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[TempU16].logHead);
			
            if(ShowLogInfo->un.countLog[TempU16].logHead.errType == ERROR_CODE_TYPE_USER){
				Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
				TempU16++;
			}else{
				Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
			}
			
			if(TempU16 >= 5){
				break;
			}
		}
		
		//计算上翻和下翻剩余值
		ShowLogInfo->countUpNum = 0;	
		ShowLogInfo->countDownNum = TempLen-i-1;
		
		//确定当前是否有5条数据
		ShowLogInfo->num = TempU16;
	
		//初始化序号
		ShowLogInfo->upperSNNum = 1;
		
		//初始化显示的第一条序号
		TempU16 = ShowLogInfo->upperSNNum;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		for(i=0;i<ShowLogInfo->num;i++){
			LISTVIEW_AddRow(hItem, NULL);
			
			//序号
			TempLen = sprintf(Str,"%u",TempU16);
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,0,i,Str);
			TempU16++;
			
			//时间
			LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
			
			//概要信息
			LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
			
			//结果
			if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
				TempLen = sprintf(Str,"Success");
			}else{
				TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
			}
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,3,i,Str);
			
			//操作者
			switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
				case ACCOUNT_TYPE_SUPER:
					TempLen = sprintf(Str,"Super");
				break;
				case ACCOUNT_TYPE_ADMIN:
					TempLen = sprintf(Str,"Admin");
				break;
				case ACCOUNT_TYPE_NORMAL:
					TempLen = sprintf(Str,"Normal");
				break;
				case ACCOUNT_TYPE_NEW:
					TempLen = sprintf(Str,"New User");
				break;
				default :break;
			}
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,4,i,Str);
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_7: // Notifications sent by '仪器故障'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		ShowErrType = ERROR_CODE_TYPE_MACHINE;
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,g_ucaLng_Serve_Macherr[MachInfo.systemSet.eLanguage]);
	  
		//清除掉多行编辑框中的数据
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
		MULTIEDIT_SetText(hItem,"");
	  
		//重置参数
		UUpUnactiveFlag = 0;
		UpUnactiveFlag = 0;
		DDownUnactiveFlag = 0;
		DownUnactiveFlag = 0;
	  
		//四个按键重绘
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
	  
		//确定当前是否有5条数据
		TempLen = g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum;
	
		//读取最新一条日志头信息
		if(TempLen >= 1){
			FatFs_Read_ConutHead(g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulQueue_TailIndex-1,&ShowLogInfo->un.countLog[0].logHead);
			
			//判断是否属于仪器故障
            if(ShowLogInfo->un.countLog[0].logHead.errType != ERROR_CODE_TYPE_MACHINE){
				TempLen--;
			
				//查找最新一条故障日志头信息
				while(TempLen >= 1){
					FatFs_Read_ConutHead(ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[0].logHead);
                    if(ShowLogInfo->un.countLog[0].logHead.errType == ERROR_CODE_TYPE_MACHINE){
						break;
					}
					
					TempLen--;
				}
			}
		}
		
		//清除原先列表值
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetNumRows(hItem);
		for(i=0;i<TempU16;i++){
			LISTVIEW_DeleteRow(hItem,0);
		}
		
		ShowLogInfo->countUpNum = 0;	
		ShowLogInfo->countDownNum = 0;
		ShowLogInfo->num = 0;
		
		//判断是否没有一条数据，是，则直接break;
		if(TempLen == 0){
			break;
		}
		
		Temp = ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex;
		TempU16 = 1;
		for(i=1;i<TempLen;i++){
			FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[TempU16].logHead);
			
            if(ShowLogInfo->un.countLog[TempU16].logHead.errType == ERROR_CODE_TYPE_MACHINE){
				Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
				TempU16++;
			}else{
				Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
			}
			
			if(TempU16 >= 5){
				break;
			}
		}
		
		//计算上翻和下翻剩余值
		ShowLogInfo->countUpNum = 0;	
		ShowLogInfo->countDownNum = TempLen-i-1;
		
		//确定当前是否有5条数据
		ShowLogInfo->num = TempU16;
	
		//初始化序号
		ShowLogInfo->upperSNNum = 1;
		
		//初始化显示的第一条序号
		TempU16 = ShowLogInfo->upperSNNum;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		for(i=0;i<ShowLogInfo->num;i++){
			LISTVIEW_AddRow(hItem, NULL);
			
			//序号
			TempLen = sprintf(Str,"%u",TempU16);
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,0,i,Str);
			TempU16++;
			
			//时间
			LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
			
			//概要信息
			LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
			
			//结果
			if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
				TempLen = sprintf(Str,"Success");
			}else{
				TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
			}
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,3,i,Str);
			
			//操作者
			switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
				case ACCOUNT_TYPE_SUPER:
					TempLen = sprintf(Str,"Super");
				break;
				case ACCOUNT_TYPE_ADMIN:
					TempLen = sprintf(Str,"Admin");
				break;
				case ACCOUNT_TYPE_NORMAL:
					TempLen = sprintf(Str,"Normal");
				break;
				case ACCOUNT_TYPE_NEW:
					TempLen = sprintf(Str,"New User");
				break;
				default :break;
			}
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,4,i,Str);
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_8: // Notifications sent by '综合故障'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		ShowErrType = ERROR_CODE_TYPE_MULTI;
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,g_ucaLng_Serve_ZHerr[MachInfo.systemSet.eLanguage]);
	  
		//清除掉多行编辑框中的数据
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
		MULTIEDIT_SetText(hItem,"");
	  
		//重置参数
		UUpUnactiveFlag = 0;
		UpUnactiveFlag = 0;
		DDownUnactiveFlag = 0;
		DownUnactiveFlag = 0;
	  
		//四个按键重绘
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
	  
		//确定当前是否有5条数据
		TempLen = g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulValidNum;
	
		//读取最新一条日志头信息
		if(TempLen >= 1){
			FatFs_Read_ConutHead(g_tDataManage.tDataManage_WBCHGB[ShowLogInfo->curAccount].ulQueue_TailIndex-1,&ShowLogInfo->un.countLog[0].logHead);
			
			//判断是否属于综合故障
            if(ShowLogInfo->un.countLog[0].logHead.errType != ERROR_CODE_TYPE_MULTI){
				TempLen--;
			
				//查找最新一条故障日志头信息
				while(TempLen >= 1){
					FatFs_Read_ConutHead(ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[0].logHead);
                    if(ShowLogInfo->un.countLog[0].logHead.errType == ERROR_CODE_TYPE_MULTI){
						break;
					}
					
					TempLen--;
				}
			}
		}
		
		//清除原先列表值
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetNumRows(hItem);
		for(i=0;i<TempU16;i++){
			LISTVIEW_DeleteRow(hItem,0);
		}
		
		ShowLogInfo->countUpNum = 0;	
		ShowLogInfo->countDownNum = 0;
		ShowLogInfo->num = 0;
		
		//判断是否没有一条数据，是，则直接break;
		if(TempLen == 0){
			break;
		}
		
		Temp = ShowLogInfo->un.countLog[0].logHead.ulLastValidIndex;
		TempU16 = 1;
		for(i=1;i<TempLen;i++){
			FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[TempU16].logHead);
			
            if(ShowLogInfo->un.countLog[TempU16].logHead.errType == ERROR_CODE_TYPE_MULTI){
				Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
				TempU16++;
			}else{
				Temp = ShowLogInfo->un.countLog[TempU16].logHead.ulLastValidIndex;
			}
			
			if(TempU16 >= 5){
				break;
			}
		}
		
		//计算上翻和下翻剩余值
		ShowLogInfo->countUpNum = 0;	
		ShowLogInfo->countDownNum = TempLen-i-1;
		
		//确定当前是否有5条数据
		ShowLogInfo->num = TempU16;
	
		//初始化序号
		ShowLogInfo->upperSNNum = 1;
		
		//初始化显示的第一条序号
		TempU16 = ShowLogInfo->upperSNNum;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		for(i=0;i<ShowLogInfo->num;i++){
			LISTVIEW_AddRow(hItem, NULL);
			
			//序号
			TempLen = sprintf(Str,"%u",TempU16);
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,0,i,Str);
			TempU16++;
			
			//时间
			LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
			
			//概要信息
			LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
			
			//结果
			if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
				TempLen = sprintf(Str,"Success");
			}else{
				TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
			}
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,3,i,Str);
			
			//操作者
			switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
				case ACCOUNT_TYPE_SUPER:
					TempLen = sprintf(Str,"Super");
				break;
				case ACCOUNT_TYPE_ADMIN:
					TempLen = sprintf(Str,"Admin");
				break;
				case ACCOUNT_TYPE_NORMAL:
					TempLen = sprintf(Str,"Normal");
				break;
				case ACCOUNT_TYPE_NEW:
					TempLen = sprintf(Str,"New User");
				break;
				default :break;
			}
			Str[TempLen] = '\0';
			LISTVIEW_SetItemText(hItem,4,i,Str);
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
	  //显示详细信息
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetSel(hItem);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
		
		switch(ShowLogInfo->logType){
			//测试日志，故障日志
			case 0:
			case 1:
				//从NAND中读取选中的日志字符串
//				FatFs_Read_ConutLog(ShowLogInfo->un.countLog[TempU16].logHead.ulCurIndex,ShowLogInfo->un.countLog[TempU16].Str,COUNT_LOG_DEFAULT_MAX_LEN);
//                MULTIEDIT_SetText(hItem,ShowLogInfo->un.countLog[TempU16].Str);
            	FatFs_Read_ConutLog(ShowLogInfo->un.countLog[TempU16].logHead.ulCurIndex,(__IO CountLog_t*)ShowLogInfo->un.countLog[TempU16].Str,COUNT_LOG_DEFAULT_MAX_LEN);
                MULTIEDIT_SetText(hItem, (char*)((CountLog_t*)(ShowLogInfo->un.countLog[TempU16].Str))->ucaLogBuffer);

			break;
			
			//运行日志
			case 2:
				MULTIEDIT_SetText(hItem,ShowLogInfo->un.runLog[TempU16].Str);
			break;
		}
		
		MULTIEDIT_SetCursorCharPos(hItem,0,0);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'uup_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//上翻一页数据
		switch(ShowLogInfo->logType){
			//数据日志
			case 0:
				//重置标志
				DownUnactiveFlag = 0;
				DDownUnactiveFlag = 0;
			
				//更新上下翻剩余值
				ShowLogInfo->countUpNum -= 5;
				ShowLogInfo->countDownNum += 5;
			
				//读取日志头信息
				FatFs_Read_ConutHead(ShowLogInfo->un.countLog[0].logHead.ulNextValidIndex,&ShowLogInfo->un.countLog[4].logHead);
				
				for(i=4;i>=1;i--){
					FatFs_Read_ConutHead(ShowLogInfo->un.countLog[i].logHead.ulNextValidIndex,&ShowLogInfo->un.countLog[i-1].logHead);
				}
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递减显示的第一条序号
				ShowLogInfo->upperSNNum -= 5;
				TempU16 = ShowLogInfo->upperSNNum;
				
				//填充值
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//故障日志
			case 1:
				//重置标志
				DownUnactiveFlag = 0;
				DDownUnactiveFlag = 0;
			
				Temp = ShowLogInfo->un.countLog[0].logHead.ulNextValidIndex;
				i = 9;
				while(1){
					//查找故障日志数据，并且数据先暂存在临时缓存中
					FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[i].logHead);
					
					Temp = ShowLogInfo->un.countLog[i].logHead.ulNextValidIndex;
					
					if(ShowErrType == ERROR_CODE_TYPE_USER){
                        if(ShowLogInfo->un.countLog[i].logHead.errType == ERROR_CODE_TYPE_USER){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							i--;
							
							if(i==4){
								break;
							}
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MACHINE){
                        if(ShowLogInfo->un.countLog[i].logHead.errType == ERROR_CODE_TYPE_MACHINE){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							i--;
							
							if(i==4){
								break;
							}
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MATERIAL){
                        if(ShowLogInfo->un.countLog[i].logHead.errType == ERROR_CODE_TYPE_MATERIAL){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							i--;
							
							if(i==4){
								break;
							}
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MULTI){
                        if(ShowLogInfo->un.countLog[i].logHead.errType == ERROR_CODE_TYPE_MULTI){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							i--;
							
							if(i==4){
								break;
							}
						}
					}else{
						if(ShowLogInfo->un.countLog[i].logHead.eErrorCode != ERROR_CODE_SUCCESS){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							i--;
							
							if(i==4){
								break;
							}
						}
					}
					
					if(Temp == 0xFFFFFFFF){
						ShowLogInfo->countUpNum = 0;
						break;
					}
				}
			
				//判断是否已经没有有效数据了
				if(ShowLogInfo->countUpNum == 0){
					UUpUnactiveFlag = 1;
					UpUnactiveFlag = 1;
				}
				
				//规整数据顺序
				if(i!=9){
					TempU16 = 9-i;
					
					if(TempU16 == 5){
						ShowLogInfo->un.countLog[0].logHead = ShowLogInfo->un.countLog[5].logHead;
						ShowLogInfo->un.countLog[1].logHead = ShowLogInfo->un.countLog[6].logHead;
						ShowLogInfo->un.countLog[2].logHead = ShowLogInfo->un.countLog[7].logHead;
						ShowLogInfo->un.countLog[3].logHead = ShowLogInfo->un.countLog[8].logHead;
						ShowLogInfo->un.countLog[4].logHead = ShowLogInfo->un.countLog[9].logHead;
					}else{
						for(i=0;i<TempU16;i++){
							ShowLogInfo->un.countLog[i+5].logHead = ShowLogInfo->un.countLog[i+5+TempU16-1].logHead;
						}
						
						for(;i<5;i++){
							ShowLogInfo->un.countLog[i+5].logHead = ShowLogInfo->un.countLog[i-TempU16].logHead;
						}
						
						ShowLogInfo->un.countLog[0].logHead = ShowLogInfo->un.countLog[5].logHead;
						ShowLogInfo->un.countLog[1].logHead = ShowLogInfo->un.countLog[6].logHead;
						ShowLogInfo->un.countLog[2].logHead = ShowLogInfo->un.countLog[7].logHead;
						ShowLogInfo->un.countLog[3].logHead = ShowLogInfo->un.countLog[8].logHead;
						ShowLogInfo->un.countLog[4].logHead = ShowLogInfo->un.countLog[9].logHead;
					}
				}else{
					//没有数据更新，直接退出即可
					break;
				}
				
				//递减显示的第一条序号
				ShowLogInfo->upperSNNum -= TempU16;
				TempU16 = ShowLogInfo->upperSNNum;
			
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				Temp = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<Temp;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//填充值
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//运行日志
			case 2:
				DDownUnactiveFlag = 0;
				DownUnactiveFlag = 0;
			
				//还够5行数据
				ShowLogInfo->lastIndex = (ShowLogInfo->lastIndex+5)%RUN_LOG_MAX_NUM;
				ShowLogInfo->firstIndex = (ShowLogInfo->firstIndex+5)%RUN_LOG_MAX_NUM;
				
				TempU16 = 4;
				//从NAND中读取数据，并填充到指定位置
				for(i=ShowLogInfo->firstIndex;i!=ShowLogInfo->lastIndex;){
					FatFs_Read_RunLog(i,&ShowLogInfo->un.runLog[TempU16--]);
					i = (i+1)%RUN_LOG_MAX_NUM;
				}
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递减显示的第一条序号
				ShowLogInfo->upperSNNum -= 5;
				TempU16 = ShowLogInfo->upperSNNum;
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					LISTVIEW_SetItemText(hItem,1,i,ShowLogInfo->un.runLog[i].logHead.dataTime);
					
					TempLen = sprintf(Str,"%u",ShowLogInfo->un.runLog[i].logHead.num);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,2,i,Str);
					
					LISTVIEW_SetItemText(hItem,3,i,ShowLogInfo->un.runLog[i].logHead.shortStr);
					
					switch(ShowLogInfo->un.runLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			default :break;
		}
		
		//四个按键重绘
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'up_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//上翻一条数据
		switch(ShowLogInfo->logType){
			//数据日志
			case 0:
				//重置标志
				DownUnactiveFlag = 0;
				DDownUnactiveFlag = 0;
			
				//更新上下翻剩余值
				ShowLogInfo->countUpNum -= 1;
				ShowLogInfo->countDownNum += 1;
			
				//先将原先4行列表值往下挪，减少读取数据的次数
				for(i=4;i>=1;i--){
					ShowLogInfo->un.countLog[i] = ShowLogInfo->un.countLog[i-1];
				}
			
				//读取日志头信息
				FatFs_Read_ConutHead(ShowLogInfo->un.countLog[1].logHead.ulNextValidIndex,&ShowLogInfo->un.countLog[0].logHead);
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递减显示的第一条序号
				ShowLogInfo->upperSNNum -= 1;
				TempU16 = ShowLogInfo->upperSNNum;
				
				//填充值
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//故障日志
			case 1:
				//重置标志
				DownUnactiveFlag = 0;
				DDownUnactiveFlag = 0;
			
				Temp = ShowLogInfo->un.countLog[0].logHead.ulNextValidIndex;
				TempU16 = 0;
				while(1){
					//查找故障日志数据，并且数据先暂存在临时缓存中
					FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[5].logHead);
					
					Temp = ShowLogInfo->un.countLog[5].logHead.ulNextValidIndex;
					
					if(ShowErrType == ERROR_CODE_TYPE_USER){
                        if(ShowLogInfo->un.countLog[5].logHead.errType == ERROR_CODE_TYPE_USER){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							TempU16++;
							break;
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MACHINE){
                        if(ShowLogInfo->un.countLog[5].logHead.errType == ERROR_CODE_TYPE_MACHINE){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							TempU16++;
							break;
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MATERIAL){
                        if(ShowLogInfo->un.countLog[5].logHead.errType == ERROR_CODE_TYPE_MATERIAL){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							TempU16++;
							break;
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MULTI){
                        if(ShowLogInfo->un.countLog[5].logHead.errType == ERROR_CODE_TYPE_MULTI){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							TempU16++;
							break;
						}
					}else{
						if(ShowLogInfo->un.countLog[5].logHead.eErrorCode != ERROR_CODE_SUCCESS){
							ShowLogInfo->countUpNum--;
							ShowLogInfo->countDownNum++;
							TempU16++;
							break;
						}
					}
					
					if(Temp == 0xFFFFFFFF){
						ShowLogInfo->countUpNum = 0;
						break;
					}
				}
			
				//判断是否已经没有有效数据了
				if(ShowLogInfo->countUpNum == 0){
					UUpUnactiveFlag = 1;
					UpUnactiveFlag = 1;
				}
				
				//规整数据顺序
				if(TempU16 != 0){
					ShowLogInfo->un.countLog[4].logHead = ShowLogInfo->un.countLog[3].logHead;
					ShowLogInfo->un.countLog[3].logHead = ShowLogInfo->un.countLog[2].logHead;
					ShowLogInfo->un.countLog[2].logHead = ShowLogInfo->un.countLog[1].logHead;
					ShowLogInfo->un.countLog[1].logHead = ShowLogInfo->un.countLog[0].logHead;
					ShowLogInfo->un.countLog[0].logHead = ShowLogInfo->un.countLog[5].logHead;
				}else{
					//没有数据更新，直接退出即可
					break;
				}
			
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递减显示的第一条序号
				ShowLogInfo->upperSNNum -= 1;
				TempU16 = ShowLogInfo->upperSNNum;
				
				//填充值
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//运行日志
			case 2:
				DDownUnactiveFlag = 0;
				DownUnactiveFlag = 0;
			
				//还够1行数据
				ShowLogInfo->lastIndex = (ShowLogInfo->lastIndex+1)%RUN_LOG_MAX_NUM;
				ShowLogInfo->firstIndex = (ShowLogInfo->firstIndex+1)%RUN_LOG_MAX_NUM;
				
				ShowLogInfo->un.runLog[4] = ShowLogInfo->un.runLog[3];
				ShowLogInfo->un.runLog[3] = ShowLogInfo->un.runLog[2];
				ShowLogInfo->un.runLog[2] = ShowLogInfo->un.runLog[1];
				ShowLogInfo->un.runLog[1] = ShowLogInfo->un.runLog[0];
			
				FatFs_Read_RunLog(ShowLogInfo->lastIndex-1,&ShowLogInfo->un.runLog[0]);
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
			
				//递减显示的第一条序号
				ShowLogInfo->upperSNNum -= 1;
				TempU16 = ShowLogInfo->upperSNNum;
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					LISTVIEW_SetItemText(hItem,1,i,ShowLogInfo->un.runLog[i].logHead.dataTime);
					
					TempLen = sprintf(Str,"%u",ShowLogInfo->un.runLog[i].logHead.num);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,2,i,Str);
					
					LISTVIEW_SetItemText(hItem,3,i,ShowLogInfo->un.runLog[i].logHead.shortStr);
					
					switch(ShowLogInfo->un.runLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			default :break;
		}
	  
		//四个按键重绘
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'down_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//下翻一条数据
		switch(ShowLogInfo->logType){
			//数据日志
			case 0:
				//重置标志
				DownUnactiveFlag = 0;
				DDownUnactiveFlag = 0;
			
				//更新上下翻剩余值
				ShowLogInfo->countUpNum += 1;
				ShowLogInfo->countDownNum -= 1;
			
				//先将原先4行列表值往上挪，减少读取数据的次数
				for(i=0;i<4;i++){
					ShowLogInfo->un.countLog[i] = ShowLogInfo->un.countLog[i+1];
				}
			
				//读取日志头信息
				FatFs_Read_ConutHead(ShowLogInfo->un.countLog[3].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[4].logHead);
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递增显示的第一条序号
				ShowLogInfo->upperSNNum += 1;
				TempU16 = ShowLogInfo->upperSNNum;
				
				//填充值
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//故障日志
			case 1:
				//重置标志
				UUpUnactiveFlag = 0;
				UpUnactiveFlag = 0;
			
				Temp = ShowLogInfo->un.countLog[4].logHead.ulLastValidIndex;
				TempU16 = 0;
				while(1){
					//查找故障日志数据，并且数据先暂存在临时缓存中
					FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[5].logHead);
					
					Temp = ShowLogInfo->un.countLog[5].logHead.ulLastValidIndex;
					
					if(ShowErrType == ERROR_CODE_TYPE_USER){
                        if(ShowLogInfo->un.countLog[5].logHead.errType == ERROR_CODE_TYPE_USER){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							TempU16++;
							break;
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MACHINE){
                        if(ShowLogInfo->un.countLog[5].logHead.errType == ERROR_CODE_TYPE_MACHINE){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							TempU16++;
							break;
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MATERIAL){
                        if(ShowLogInfo->un.countLog[5].logHead.errType == ERROR_CODE_TYPE_MATERIAL){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							TempU16++;
							break;
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MULTI){
                        if(ShowLogInfo->un.countLog[5].logHead.errType == ERROR_CODE_TYPE_MULTI){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							TempU16++;
							break;
						}
					}else{
						if(ShowLogInfo->un.countLog[5].logHead.eErrorCode != ERROR_CODE_SUCCESS){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							TempU16++;
							break;
						}
					}
					
					if(Temp == 0xFFFFFFFF){
						ShowLogInfo->countDownNum = 0;
						break;
					}
				}
			
				//判断是否已经没有有效数据了
				if(ShowLogInfo->countDownNum == 0){
					DownUnactiveFlag = 1;
					DDownUnactiveFlag = 1;
				}
				
				//规整数据顺序
				if(TempU16 != 0){
					ShowLogInfo->un.countLog[0].logHead = ShowLogInfo->un.countLog[1].logHead;
					ShowLogInfo->un.countLog[1].logHead = ShowLogInfo->un.countLog[2].logHead;
					ShowLogInfo->un.countLog[2].logHead = ShowLogInfo->un.countLog[3].logHead;
					ShowLogInfo->un.countLog[3].logHead = ShowLogInfo->un.countLog[4].logHead;
					ShowLogInfo->un.countLog[4].logHead = ShowLogInfo->un.countLog[5].logHead;
				}else{
					//没有数据更新，直接退出即可
					break;
				}
			
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递增显示的第一条序号
				ShowLogInfo->upperSNNum += 1;
				TempU16 = ShowLogInfo->upperSNNum;
				
				//填充值
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//运行日志
			case 2:
				UUpUnactiveFlag = 0;
				UpUnactiveFlag = 0;
			
				//还够1行数据
				if(ShowLogInfo->lastIndex == 0){
					ShowLogInfo->lastIndex = RUN_LOG_MAX_NUM - 1;
				}else{
					ShowLogInfo->lastIndex -= 1;
				}
				
				if(ShowLogInfo->firstIndex == 0){
					ShowLogInfo->firstIndex = RUN_LOG_MAX_NUM - 1;
				}else{
					ShowLogInfo->firstIndex -= 1;
				}
				
				ShowLogInfo->un.runLog[0] = ShowLogInfo->un.runLog[1];
				ShowLogInfo->un.runLog[1] = ShowLogInfo->un.runLog[2];
				ShowLogInfo->un.runLog[2] = ShowLogInfo->un.runLog[3];
				ShowLogInfo->un.runLog[3] = ShowLogInfo->un.runLog[4];
			
				FatFs_Read_RunLog(ShowLogInfo->firstIndex,&ShowLogInfo->un.runLog[4]);
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递增显示的第一条序号
				ShowLogInfo->upperSNNum += 1;
				TempU16 = ShowLogInfo->upperSNNum;
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					LISTVIEW_SetItemText(hItem,1,i,ShowLogInfo->un.runLog[i].logHead.dataTime);
					
					TempLen = sprintf(Str,"%u",ShowLogInfo->un.runLog[i].logHead.num);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,2,i,Str);
					
					LISTVIEW_SetItemText(hItem,3,i,ShowLogInfo->un.runLog[i].logHead.shortStr);
					
					switch(ShowLogInfo->un.runLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			default :break;
		}
		
		//四个按键重绘
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'ddown_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//下翻一页数据
		switch(ShowLogInfo->logType){
			//数据日志
			case 0:
				//重置标志
				DownUnactiveFlag = 0;
				DDownUnactiveFlag = 0;
			
				//更新上下翻剩余值
				ShowLogInfo->countUpNum += 5;
				ShowLogInfo->countDownNum -= 5;
			
				//读取日志头信息
				FatFs_Read_ConutHead(ShowLogInfo->un.countLog[4].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[0].logHead);
				
				for(i=1;i<5;i++){
					FatFs_Read_ConutHead(ShowLogInfo->un.countLog[i-1].logHead.ulLastValidIndex,&ShowLogInfo->un.countLog[i].logHead);
				}
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递减显示的第一条序号
				ShowLogInfo->upperSNNum += 5;
				TempU16 = ShowLogInfo->upperSNNum;
				
				//填充值
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//故障日志
			case 1:
				//重置标志
				UUpUnactiveFlag = 0;
				UpUnactiveFlag = 0;
			
				Temp = ShowLogInfo->un.countLog[4].logHead.ulLastValidIndex;
				i = 5;
				while(1){
					//查找故障日志数据，并且数据先暂存在临时缓存中
					FatFs_Read_ConutHead(Temp,&ShowLogInfo->un.countLog[i].logHead);
					
					Temp = ShowLogInfo->un.countLog[i].logHead.ulLastValidIndex;
					
					if(ShowErrType == ERROR_CODE_TYPE_USER){
                        if(ShowLogInfo->un.countLog[i].logHead.errType == ERROR_CODE_TYPE_USER){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							i++;
							
							if(i==10){
								break;
							}
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MACHINE){
                        if(ShowLogInfo->un.countLog[i].logHead.errType == ERROR_CODE_TYPE_MACHINE){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							i++;
							
							if(i==10){
								break;
							}
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MATERIAL){
                        if(ShowLogInfo->un.countLog[i].logHead.errType == ERROR_CODE_TYPE_MATERIAL){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							i++;
							
							if(i==10){
								break;
							}
						}
					}else if(ShowErrType == ERROR_CODE_TYPE_MULTI){
                        if(ShowLogInfo->un.countLog[i].logHead.errType == ERROR_CODE_TYPE_MULTI){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							i++;
							
							if(i==10){
								break;
							}
						}
					}else{
						if(ShowLogInfo->un.countLog[i].logHead.eErrorCode != ERROR_CODE_SUCCESS){
							ShowLogInfo->countDownNum--;
							ShowLogInfo->countUpNum++;
							i++;
							
							if(i==10){
								break;
							}
						}
					}
					
					if(Temp == 0xFFFFFFFF){
						ShowLogInfo->countDownNum = 0;
						break;
					}
				}
			
				//判断是否已经没有有效数据了
				if(ShowLogInfo->countDownNum == 0){
					DownUnactiveFlag = 1;
					DDownUnactiveFlag = 1;
				}
				
				//规整数据顺序
				if(i != 5){
					TempU16 = i-5;
					
					for(i=0;i<5;i++){
						ShowLogInfo->un.countLog[i].logHead = ShowLogInfo->un.countLog[i+TempU16].logHead;
					}
				}else{
					//没有数据更新，直接退出即可
					break;
				}
				
				//递增显示的第一条序号
				ShowLogInfo->upperSNNum += TempU16;
				TempU16 = ShowLogInfo->upperSNNum;
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				Temp = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<Temp;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//填充值
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					//序号
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					//时间
					LISTVIEW_SetItemText(hItem,1,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaDateTime);
					
					//概要信息
					LISTVIEW_SetItemText(hItem,2,i,(char*)ShowLogInfo->un.countLog[i].logHead.ucaSampleSN);
					
					//结果
					if(ShowLogInfo->un.countLog[i].logHead.eErrorCode == ERROR_CODE_SUCCESS){
						TempLen = sprintf(Str,"Success");
					}else{
						TempLen = sprintf(Str,"Fail-E%u",ShowLogInfo->un.countLog[i].logHead.eErrorCode);
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,3,i,Str);
					
					//操作者
					switch(ShowLogInfo->un.countLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			
			//运行日志
			case 2:
				UUpUnactiveFlag = 0;
				UpUnactiveFlag = 0;
			
				//还够5行数据
				if(ShowLogInfo->lastIndex < 5){
					ShowLogInfo->lastIndex = RUN_LOG_MAX_NUM - (5-ShowLogInfo->lastIndex);
				}else{
					ShowLogInfo->lastIndex -= 5;
				}
				
				if(ShowLogInfo->firstIndex < 5){
					ShowLogInfo->firstIndex = RUN_LOG_MAX_NUM - (5-ShowLogInfo->firstIndex);
				}else{
					ShowLogInfo->firstIndex -= 5;
				}
			
				TempU16 = 4;
				//从NAND中读取数据，并填充到指定位置
				for(i=ShowLogInfo->firstIndex;i!=ShowLogInfo->lastIndex;){
					FatFs_Read_RunLog(i,&ShowLogInfo->un.runLog[TempU16--]);
					i = (i+1)%RUN_LOG_MAX_NUM;
				}
				
				//清除原先列表值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				TempU16 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<TempU16;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				//递增显示的第一条序号
				ShowLogInfo->upperSNNum += 5;
				TempU16 = ShowLogInfo->upperSNNum;
				
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				for(i=0;i<ShowLogInfo->num;i++){
					LISTVIEW_AddRow(hItem, NULL);
					
					TempLen = sprintf(Str,"%u",TempU16);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,0,i,Str);
					TempU16++;
					
					LISTVIEW_SetItemText(hItem,1,i,ShowLogInfo->un.runLog[i].logHead.dataTime);
					
					TempLen = sprintf(Str,"%u",ShowLogInfo->un.runLog[i].logHead.num);
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,2,i,Str);
					
					LISTVIEW_SetItemText(hItem,3,i,ShowLogInfo->un.runLog[i].logHead.shortStr);
					
					switch(ShowLogInfo->un.runLog[i].logHead.eAccountType){
						case ACCOUNT_TYPE_SUPER:
							TempLen = sprintf(Str,"Super");
						break;
						case ACCOUNT_TYPE_ADMIN:
							TempLen = sprintf(Str,"Admin");
						break;
						case ACCOUNT_TYPE_NORMAL:
							TempLen = sprintf(Str,"Normal");
						break;
						case ACCOUNT_TYPE_NEW:
							TempLen = sprintf(Str,"New User");
						break;
						default :break;
					}
					Str[TempLen] = '\0';
					LISTVIEW_SetItemText(hItem,4,i,Str);
				}
			break;
			default :break;
		}
		
		//四个按键重绘
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
		WM_InvalidateWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatelogPage
*/
WM_HWIN CreatelogPage(void);
WM_HWIN CreatelogPage(void) {
  WM_HWIN hWin;
	
	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
