/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "pcba.h"
#include "CAT_iot.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_WINDOW_PCBA_PAGE_ID + 0x00)
#define ID_TEXT_0 (GUI_WINDOW_PCBA_PAGE_ID + 0x01)
#define ID_TEXT_1 (GUI_WINDOW_PCBA_PAGE_ID + 0x02)
#define ID_BUTTON_0 (GUI_WINDOW_PCBA_PAGE_ID + 0x03)
#define ID_BUTTON_1 (GUI_WINDOW_PCBA_PAGE_ID + 0x04)
#define ID_BUTTON_2 (GUI_WINDOW_PCBA_PAGE_ID + 0x05)
#define ID_BUTTON_3 (GUI_WINDOW_PCBA_PAGE_ID + 0x06)
#define ID_BUTTON_4 (GUI_WINDOW_PCBA_PAGE_ID + 0x07)
#define ID_BUTTON_5 (GUI_WINDOW_PCBA_PAGE_ID + 0x08)
#define ID_BUTTON_6 (GUI_WINDOW_PCBA_PAGE_ID + 0x09)
#define ID_MULTIEDIT_0 (GUI_WINDOW_PCBA_PAGE_ID + 0x0A)
#define ID_TEXT_2 (GUI_WINDOW_PCBA_PAGE_ID + 0x0B)
#define ID_EDIT_0 (GUI_WINDOW_PCBA_PAGE_ID + 0x0C)
#define ID_BUTTON_7 (GUI_WINDOW_PCBA_PAGE_ID + 0x0D)
#define ID_BUTTON_8 (GUI_WINDOW_PCBA_PAGE_ID + 0x0E)
#define ID_BUTTON_9 (GUI_WINDOW_PCBA_PAGE_ID + 0x0F)
#define ID_TEXT_3 (GUI_WINDOW_PCBA_PAGE_ID + 0x10)
#define ID_TEXT_4 (GUI_WINDOW_PCBA_PAGE_ID + 0x11)
#define ID_BUTTON_10 (GUI_WINDOW_PCBA_PAGE_ID + 0x12)
#define ID_BUTTON_11 (GUI_WINDOW_PCBA_PAGE_ID + 0x13)
#define ID_BUTTON_12 (GUI_WINDOW_PCBA_PAGE_ID + 0x14)
#define ID_BUTTON_13 (GUI_WINDOW_PCBA_PAGE_ID + 0x15)
#define ID_BUTTON_14 (GUI_WINDOW_PCBA_PAGE_ID + 0x16)
#define ID_BUTTON_15 (GUI_WINDOW_PCBA_PAGE_ID + 0x17)
#define ID_BUTTON_16 (GUI_WINDOW_PCBA_PAGE_ID + 0x18)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "PCBA_Page", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "服务", ID_TEXT_0, 30, 13, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> PCBA检验", ID_TEXT_1, 90, 20, 360, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "返回", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "主控板检验", ID_BUTTON_1, 678, 80, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "转接板检验", ID_BUTTON_2, 678, 130, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CAT来料检", ID_BUTTON_3, 678, 180, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "触摸屏来料检", ID_BUTTON_4, 678, 230, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "电机来料检", ID_BUTTON_5, 678, 280, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "预留", ID_BUTTON_6, 678, 330, 100, 40, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 30, 75, 300, 295, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "editTip_t", ID_TEXT_2, 350, 130, 96, 40, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "edit_e", ID_EDIT_0, 450, 130, 115, 40, 0, 0xa, 0 },
  { BUTTON_CreateIndirect, "确认", ID_BUTTON_7, 570, 130, 90, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "电机推力", ID_BUTTON_8, 450, 180, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "电机跳动", ID_BUTTON_9, 560, 180, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "电机控制", ID_TEXT_3, 350, 180, 96, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "执行反馈", ID_TEXT_4, 350, 80, 96, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "NO", ID_BUTTON_10, 450, 80, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "YES", ID_BUTTON_11, 560, 80, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "阀检测", ID_BUTTON_12, 450, 330, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "泵检测", ID_BUTTON_13, 560, 330, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HONE检测", ID_BUTTON_14, 450, 280, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "IT110检测", ID_BUTTON_15, 560, 280, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "压力校准", ID_BUTTON_16, 560, 11, 100, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _PCBAPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	extern __IO MachRunPara_s	MachRunPara;
	
    switch (pMsg->MsgId)
    {
	case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("主控板检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("转接板检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("CAT1检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("触摸屏检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect("电机检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect("预留",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
					
				case ID_BUTTON_7:
					GUI_DispStringInRect("确认",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_8:
					GUI_DispStringInRect("电机推力",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_9:
					GUI_DispStringInRect("电机跳动",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_10:
					GUI_DispStringInRect("NO",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_11:
					GUI_DispStringInRect("YES",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_12:
					GUI_DispStringInRect("阀检测",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_13:
					GUI_DispStringInRect("泵检测",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_14:
					GUI_DispStringInRect("HONE检测",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_15:
					GUI_DispStringInRect("IT110检测",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_16:
					GUI_DispStringInRect("压力校准",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{	
			//控件失能时，则置灰
			if(WM_IsEnabled(pMsg->hWin) == 1){
				//填充
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
				GUI_AA_FillRoundedRectEx(&Rect,20);
				
				//设置字符前景和背景色
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			}else{
				//填充
				GUI_SetColor(GUI_LIGHTGRAY);
				GUI_AA_FillRoundedRectEx(&Rect,20);
				
				//设置字符前景和背景色
				GUI_SetColor(0x00ffffff);
				GUI_SetBkColor(GUI_LIGHTGRAY);
			}
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("主控板检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("转接板检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("CAT1检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("触摸屏检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect("电机检验",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect("预留",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
					
				case ID_BUTTON_7:
					GUI_DispStringInRect("确认",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_8:
					GUI_DispStringInRect("电机推力",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_9:
					GUI_DispStringInRect("电机跳动",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_10:
					GUI_DispStringInRect("NO",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_11:
					GUI_DispStringInRect("YES",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_12:
					GUI_DispStringInRect("阀检测",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_13:
					GUI_DispStringInRect("泵检测",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_14:
					GUI_DispStringInRect("HONE检测",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_15:
					GUI_DispStringInRect("IT110检测",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_16:
					GUI_DispStringInRect("压力校准",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
* 设置控件回调函数，以及重绘控件
*/
static void _PCBAPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //返回按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//主控板检验按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//转接板检验按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//CAT1模块检验按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//触摸屏检验按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//电机检验按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//压力模块检验按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//输入确认按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//电机推力按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//电机跳动按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//NO按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//YES按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//阀检测
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//泵检测
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//HONE检测
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//IT110检测
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//压力校准
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);  
    WM_SetCallback(hItem, _PCBAPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreatejiaoHuCheckPage(void);
	extern osEventFlagsId_t PCBAEventGroupHandle;
	extern  MachInfo_s MachInfo;
	extern CATGlobalStatus_s CATGlobalStatus;
	
	static uint8_t CurrentFlag = 0;							//用来表示当前执行的检验，为0表示没有执行，为1表示主控板，为2表示转接板，为3表示CAT检验，为4表示触摸屏，为5表示电机，为6表示压力传感器，为7表示阀检测，为8表示泵检测，为9表示检测HONEYWELL压力传感器，为10表示检测IT110压力传感器
	Msg_Head_t BackendMsg = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  {
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    MULTIEDIT_SetReadOnly(hItem,1);
	MULTIEDIT_SetBufferSize(hItem, 4096);
	MULTIEDIT_SetAutoScrollV(hItem, 1);
	MULTIEDIT_SetAutoScrollH(hItem, 0);
	MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, 0x001a1a1a);
	MULTIEDIT_SetBkColor(hItem, MULTIEDIT_CI_READONLY,0x00ffffff);
	MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
	MULTIEDIT_SetFont(hItem,&HZ_SONGTI_16);
	MULTIEDIT_ShowCursor(hItem,0);
	MULTIEDIT_SetInsertMode(hItem,0);
	MULTIEDIT_SetWrapWord(hItem);
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem,&HZ_SONGTI_24);
	TEXT_SetText(hItem,"服务");
  
    //
    // Initialization of 'editTip_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"输入");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"执行反馈");
    //
    // Initialization of 'edit_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetFont(hItem,&HZ_SONGTI_16); //TEXT_SetFont(hItem,&SIF_HZ16_SONGTI); //
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    //
    // Initialization of 'motoCTRlTip_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem,&HZ_SONGTI_16); //
	TEXT_SetText(hItem,"电机控制");
	
    // USER START (Optionally insert additional code for further widget initialization)
	
	//重绘按钮样式
	_PCBAPageRedrawWidgetType(pMsg);
	
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
	
	//临时创建事件组
	if(PCBAEventGroupHandle == NULL){
		PCBAEventGroupHandle = osEventFlagsNew(NULL);
	}
	
	//禁止掉桌面按键
	AbortPublishDestopButton();
	
	//将版本号临时提升到最大，防止程序被网络自动升级
	CATGlobalStatus.localVersion.mainVersion = 999;
	CATGlobalStatus.localVersion.bootloadVersion = 999;
	CATGlobalStatus.localVersion.uiVersion = 999;
	
	#if PCBA_CHECK_MAIN_BOARD
		//失能部分控件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		WM_DisableWindow(hItem);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetMaxLen(hItem,4);								//设置编辑框可输入的最大的字符数
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetFont(hItem,&HZ_SONGTI_16);
		TEXT_SetText(hItem,"> CX-2200主控板PCBA检验_V1.0.1");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetFont(hItem,&HZ_SONGTI_16);
		TEXT_SetText(hItem,"硬件版本号");
	#elif PCBA_CHECK_ZJ_BOARD
		//失能部分控件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		WM_DisableWindow(hItem);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetMaxLen(hItem,4);								//设置编辑框可输入的最大的字符数
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,"> CX-2200显示转接板PCBA检验_V1.0.0");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem,"硬件版本号");
	#elif PCBA_CHECK_CAT
		//失能部分控件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		WM_DisableWindow(hItem);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		WM_DisableWindow(hItem);							
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,"> CX-2200联网模块PCBA检验_V1.0.0");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem,"输入");
		
		//临时测试使用的SN
		strcpy((char*)MachInfo.labInfo.ucaMachineSN,"CAT1_TEST123");
		
	#elif PCBA_CHECK_TOUCH_SCREEN
		//失能部分控件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		WM_DisableWindow(hItem);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		WM_DisableWindow(hItem);							
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,"> 触摸显示模组检验_V1.0.0");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem,"输入");
	#elif PCBA_CHECK_MOTO
		//失能部分控件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		WM_DisableWindow(hItem);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		WM_DisableWindow(hItem);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,"> 直线步进电机检验_V1.0.0");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem,"输入");
	#elif PCBA_CHECK_PRESSURE_MONITOR
		//失能部分控件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_DisableWindow(hItem);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		WM_DisableWindow(hItem);							
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,"> 压力传感器模块检验_V1.0.0");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem,"输入压力");
	#elif PCBA_CHECK_VALVE_PUMP
		//失能部分控件
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_DisableWindow(hItem);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_DisableWindow(hItem);
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		WM_DisableWindow(hItem);							
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem,"> 旋转泵液阀检验_V1.0.1");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem,"输入压力");
		WM_DisableWindow(hItem);
	#endif

    }
    break;
	
  case WM_DELETE:
	  //退出界面时需要删除创建的事件组
		if(PCBAEventGroupHandle != NULL){
			osEventFlagsDelete(PCBAEventGroupHandle);
		}
  break;
	
	case WM_PAINT:
    {
		//画背景BMP图
		//GUI_BMP_Draw(BKBmaDataBuf,1,0);
        //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
    
        GUI_RECT Rect;
		WM_GetClientRect(&Rect); 
		GUI_SetColor(GUI_WHITE);
		GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
    }
	break;
	
	case WM_POST_PAINT:
		//画框
		GUI_DrawRect(345,75,665,125);
		GUI_DrawRect(345,125,665,175);
		GUI_DrawRect(345,175,665,225);
	break;
	
	//更新键盘事件
	case WM_KEYBOARD_UPDATE: 
	{
		uint8_t i = strlen(pMsg->Data.p);
		if(i == 1) //ASCII码
		{
			char c = *((char*)pMsg->Data.p);
			if(CurrentFlag == 7 || CurrentFlag == 8 || CurrentFlag == 9 || CurrentFlag == 10 || CurrentFlag == 11){
				if((c >= '0' && c <= '9') || (c == '-')){
					GUI_StoreKeyMsg(c, 1);
				}
			}else{
				if((c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c == '.')){
					GUI_StoreKeyMsg(c, 1);
				}
			}
		}
	}
	break;
	
	//键盘结束事件
   case WM_KEYBOARD_END: 
   {
//	   KeyBoardUseOnceFlag = 0;
   }
   break;
   
  //后端通知界面执行完毕事件
   case WM_PCBA_TEST_BE_OVER:
   {
		CurrentFlag = 0;
   }
   break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreatejiaoHuCheckPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'mainBoard_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 1;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_MAIN;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'zjBoard_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 2;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_ZJ;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'CAT_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 3;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_CAT;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'touch_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 4;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_TOUCH;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'moto_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 5;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_MOTO;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'pressure_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 6;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_PRESURE;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'edit_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//唤出输入法
//		if(KeyBoardUseOnceFlag == 0){
//			KeyBoardUseOnceFlag = 1;
			
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
//		}
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'editConfim_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		osEventFlagsSet(PCBAEventGroupHandle,PCBA_EVENT_CONFIM_BUTTON_FLAG);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	case ID_BUTTON_8: // Notifications sent by '电机推力'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		osEventFlagsSet(PCBAEventGroupHandle,PCBA_EVENT_MOTO_TUILI_BUTTON_FLAG);
        // USER END
        break;
	  case WM_NOTIFICATION_MOVED_OUT:
		break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	case ID_BUTTON_9: // Notifications sent by '电机跳动'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		osEventFlagsSet(PCBAEventGroupHandle,PCBA_EVENT_MOTO_TIAODONG_BUTTON_FLAG);
        // USER END
        break;
	  case WM_NOTIFICATION_MOVED_OUT:
		break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_10: // Notifications sent by '执行反馈NO按钮'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		osEventFlagsSet(PCBAEventGroupHandle,PCBA_EVENT_NO_BUTTON_FLAG);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_11: // Notifications sent by '执行反馈YES按钮'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		osEventFlagsSet(PCBAEventGroupHandle,PCBA_EVENT_YES_BUTTON_FLAG);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_12: // Notifications sent by '阀检测'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 7;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_VALVE;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_13: // Notifications sent by '泵检测'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 8;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_PUMP;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_14: // Notifications sent by 'HONE检测'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 9;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_HONE;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_15: // Notifications sent by 'IT110检测'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 10;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_CHECK_IT110;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_16: // Notifications sent by '压力校准'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//防止多次点击，重复执行
		if(CurrentFlag != 0){
			break;
		}
		CurrentFlag = 11;
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PCBA_PRESSURE_ADJUST;
		UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	  
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePCBA_Page
*/
WM_HWIN CreatePCBA_Page(void);
WM_HWIN CreatePCBA_Page(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
