/*********************************************************************
*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   服务界面 
*
*/
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "GUI_Type.h"
#include "WM.h"
#include "ui_files.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (SERVICE_ITEM_PAGE_ID + 0x00)
#define ID_BUTTON_0 (SERVICE_ITEM_PAGE_ID + 0x01)
#define ID_BUTTON_1 (SERVICE_ITEM_PAGE_ID + 0x02)
#define ID_BUTTON_2 (SERVICE_ITEM_PAGE_ID + 0x03)
#define ID_BUTTON_3 (SERVICE_ITEM_PAGE_ID + 0x04)
#define ID_BUTTON_4 (SERVICE_ITEM_PAGE_ID + 0x05)
#define ID_BUTTON_5 (SERVICE_ITEM_PAGE_ID + 0x06)
#define ID_BUTTON_6 (SERVICE_ITEM_PAGE_ID + 0x07)
#define ID_BUTTON_7 (SERVICE_ITEM_PAGE_ID + 0x08)
#define ID_BUTTON_8 (SERVICE_ITEM_PAGE_ID + 0x09)
#define ID_BUTTON_9 (SERVICE_ITEM_PAGE_ID + 0x0A)
#define ID_BUTTON_10 (SERVICE_ITEM_PAGE_ID + 0x0B)
#define ID_BUTTON_11 (SERVICE_ITEM_PAGE_ID + 0x0C)
#define ID_BUTTON_12 (SERVICE_ITEM_PAGE_ID + 0x0D)
#define ID_TEXT_13 (SERVICE_ITEM_PAGE_ID + 0x0E)
#define ID_TEXT_14 (SERVICE_ITEM_PAGE_ID + 0x0F)
#define ID_TEXT_15 (SERVICE_ITEM_PAGE_ID + 0x10)
#define ID_TEXT_16 (SERVICE_ITEM_PAGE_ID + 0x11)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
//用于服务图标背景的BMP图相关变量
//GUI_HMEM hMemICONBMP;						
//char* ICONBmaDataBuf;
//uint32_t ICONBMPBufLen;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "servicePage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "pres_but", ID_BUTTON_0, 20, 100, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "airLig_but", ID_BUTTON_1, 130, 100, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "moto_but", ID_BUTTON_2, 240, 100, 100, 100, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "HGB", ID_BUTTON_2, 240, 100, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "stat_but", ID_BUTTON_3, 350, 100, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "interaction_but", ID_BUTTON_4, 460, 100, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "other_but", ID_BUTTON_5, 570, 100, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "aging_but", ID_BUTTON_6, 680, 100, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "testLog_but", ID_BUTTON_7, 20, 270, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "errLog_but", ID_BUTTON_8, 130, 270, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "allLog_but", ID_BUTTON_9, 240, 270, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "version_but", ID_BUTTON_10, 460, 270, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "disk_but", ID_BUTTON_11, 570, 270, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "dataMent_but", ID_BUTTON_12, 680, 270, 100, 100, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SERVE", ID_TEXT_13, 30, 13, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SELF-CHECK", ID_TEXT_14, 30, 67, 80, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LOG", ID_TEXT_15, 30, 237, 50, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "STATUS", ID_TEXT_16, 470, 237, 120, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
//自定义此窗口所有控件的回调函数
static void Service_Btn_Callback(WM_MESSAGE* pMsg)
{
	extern  MachInfo_s	MachInfo;
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//画ICON的BMP背景图
            Show_BK_BMP(BK_SDRAM, BK_PICTURE_OTHERS_IconBkSmall, Rect.x0+1,Rect.y0+1);

			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Pressure, Rect.x0+25,Rect.y0+15);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_BuildCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_1:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_AirLight, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_Check[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_2:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Moto, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
                    //GUI_DispStringHCenterAt(g_ucaLng_Serve_HGB[MachInfo.systemSet.eLanguage], Rect.x0+50,Rect.y0+65);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_MotoCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_3:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_StatusActive, Rect.x0+25,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_StatusUnactive, Rect.x0+25,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_StatusCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_4:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_InterActionActive, Rect.x0+25,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_InterActionUnactive, Rect.x0+25,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_InteractionCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_5:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Others, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_OtherCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_6:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_AgingTestActive, Rect.x0+25,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_AgingTestUnactive, Rect.x0+25,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_AgingCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_7:
					//画图标
					Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_ParaLog, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_TestLog[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_8:
					//画图标
					Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_ErrLog, Rect.x0+25,Rect.y0+15);
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_ErrLog[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_9:
					//画图标
					Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_AllLog, Rect.x0+25,Rect.y0+15);
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_RunLog[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_10:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Version, Rect.x0+25,Rect.y0+15);
                
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_Version[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_11:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Disk, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_Disk[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_12:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER || MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_ADMIN){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_DataActive, Rect.x0+25,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_DataUnActive, Rect.x0+25,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_DataManage[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				default :break;
			}
        }
        else {
			//画ICON的BMP背景图
            Show_BK_BMP(BK_SDRAM, BK_PICTURE_OTHERS_IconBkSmall, Rect.x0+1,Rect.y0+1);

			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Pressure, Rect.x0+25,Rect.y0+15);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_BuildCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_1:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_AirLight, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_Check[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_2:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Moto, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
                    //GUI_DispStringHCenterAt(g_ucaLng_Serve_HGB[MachInfo.systemSet.eLanguage], Rect.x0+50,Rect.y0+65);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_MotoCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_3:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_StatusActive, Rect.x0+25,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_StatusUnactive, Rect.x0+25,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_StatusCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_4:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_InterActionActive, Rect.x0+25,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_InterActionUnactive, Rect.x0+25,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_InteractionCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_5:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Others, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_OtherCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_6:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_AgingTestActive, Rect.x0+25,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_AgingTestUnactive, Rect.x0+25,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_AgingCheck[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_7:
					//画图标
                   Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_ParaLog, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_TestLog[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_8:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_ErrLog, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_ErrLog[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_9:
					//画图标
                   Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_AllLog, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_RunLog[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_10:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Version, Rect.x0+25,Rect.y0+15);
                
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_Version[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_11:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Disk, Rect.x0+25,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_Disk[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				case ID_BUTTON_12:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER || MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_ADMIN){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_DataActive, Rect.x0+25,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_DataUnActive, Rect.x0+25,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_Serve_DataManage[MachInfo.systemSet.eLanguage],Rect.x0+50,Rect.y0+65);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}





/*
* 设置控件回调函数，以及重绘控件
*/
static void Service_Data_Updata(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;

    //负压自检
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//气密性自检
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//电机自检
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//状态自检
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//交互自检
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//其他自检
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//组件老化
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//测试日志
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//故障日志
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//运行日志
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//版本信息
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//磁盘信息
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//数据管理
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);  
    WM_SetCallback(hItem, Service_Btn_Callback);
    WM_InvalidateWindow(hItem);
}






// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void ServicePage_cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
	
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreateagingTestPage(void);
	extern WM_HWIN CreateStatusCheckPage(void);
	extern WM_HWIN CreatedataManagePage(void);
	extern WM_HWIN CreatejiaoHuCheckPage(void);
	extern WM_HWIN CreateDialogPage(void);
	extern WM_HWIN CreatelogPage(void);
	extern WM_HWIN CreatediskPage(void);
	extern WM_HWIN CreateversionPage(void);
	extern WM_HWIN CreateotherCheckPage(void);
	
	extern  MachInfo_s	MachInfo;
	extern GUI_HMEM hMemBKBMP;						
	extern char* BKBmaDataBuf;
	extern uint32_t BKBMPBufLen;
	extern GUI_HMEM hMemICONBMP;
	extern __IO MachRunPara_s	MachRunPara;
	
	Msg_Head_t BackendMsg = {0};
	CommonDialogPageData_s DialogPageData = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	//设置显示字体
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Serve_Serve[MachInfo.systemSet.eLanguage]);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_Selfcheck[MachInfo.systemSet.eLanguage]);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_Log[MachInfo.systemSet.eLanguage]);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_Info[MachInfo.systemSet.eLanguage]);  
  
      
    //
    // Initialization of 'servicePage'
    // 
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00F5E6C5));
  
	//根据不同的用户权限，开放按键
	if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
		hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3);
		WM_DisableWindow(hItem);
		
		hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4);
		WM_DisableWindow(hItem);
		
		hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6);
		WM_DisableWindow(hItem);
	}
	
	if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority){
		hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12);
		WM_DisableWindow(hItem);
	}
	
   
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_PAINT:
		//画背景BMP图
        //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
        //GUI_RECT Rect;
        WM_GetClientRect(&Rect); 
        GUI_SetColor(GUI_WHITE);
        GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
  
		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
  
		Service_Data_Updata(pMsg);
        
  break;
  
  case WM_DELETE:
  {
	//释放内存
	//GUI_ALLOC_Free(hMemICONBMP);
  }
  break;
  case WM_MOTOR_ERROR_PROMPT:
  {
      Motor_Error_Prompt(pMsg, CreateservicePage);
  }
  break;
  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'pres_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateDialogPage();
	  
		//保存对话框内容
		DialogPageData.bmpType = BMP_SELF_CHECK;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = CreateservicePage;
		strcpy(DialogPageData.str,g_ucaLng_Serve_Building[MachInfo.systemSet.eLanguage]);
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &DialogPageData;
		WM_SendMessage(g_hActiveWin,pMsg);
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_PRESS;
        UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'airLig_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateDialogPage();
	  
		//保存对话框内容
		DialogPageData.bmpType = BMP_SELF_CHECK;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = CreateservicePage;
		strcpy(DialogPageData.str,g_ucaLng_Serve_AirTighting[MachInfo.systemSet.eLanguage]);
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &DialogPageData;
		WM_SendMessage(g_hActiveWin,pMsg);
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_AIR_LIGHT;
        UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
      case ID_BUTTON_2: // Notifications sent by 'moto_but' 
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
      
//        GUI_EndDialog(pMsg->hWin, 0);
//        g_hActiveWin = HGB_Debug_CreateWindow();
      
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateDialogPage();
	  
		//保存对话框内容
		DialogPageData.bmpType = BMP_SELF_CHECK;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = CreateservicePage;
		strcpy(DialogPageData.str,g_ucaLng_Serve_MotoChecking[MachInfo.systemSet.eLanguage]);
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &DialogPageData;
		WM_SendMessage(g_hActiveWin,pMsg);
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SERVER_MOTOR;
        UI_Put_Msg((uint8_t*)&BackendMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'stat_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateStatusCheckPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'interaction_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatejiaoHuCheckPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'other_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateotherCheckPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'aging_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateagingTestPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'testLog_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatelogPage();
	  
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.v = 0;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'errLog_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatelogPage();
	  
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.v = 1;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by '运行日志'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatelogPage();
	  
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.v = 2;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'version_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateversionPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'disk_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatediskPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by 'dataMent_but'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatedataManagePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateservicePage
*/
WM_HWIN CreateservicePage(void);
WM_HWIN CreateservicePage(void) {
	WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
    Set_Cur_MenuID(GUI_WINDOW_LIST_REVIEW_ID);
    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), ServicePage_cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
