/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_outin.h"
#include "bsp_press.h"
#include "monitorV.h"
#include "CAT_iot.h"
#include "time.h"
#include "bsp_pump.h"
#include "bsp_motor.h"
#include "bsp_light.h"
#include "bc.h"
#include "bsp_eeprom.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (STATUS_CHECK_PAGE_ID + 0x00)
#define ID_TEXT_0 (STATUS_CHECK_PAGE_ID + 0x01)
#define ID_TEXT_1 (STATUS_CHECK_PAGE_ID + 0x02)
//#define ID_BUTTON_0 (STATUS_CHECK_PAGE_ID + 0x03)
#define ID_BUTTON_1 (STATUS_CHECK_PAGE_ID + 0x04)
#define ID_TEXT_2 (STATUS_CHECK_PAGE_ID + 0x05)
#define ID_TEXT_3 (STATUS_CHECK_PAGE_ID + 0x06)
#define ID_TEXT_4 (STATUS_CHECK_PAGE_ID + 0x07)
#define ID_TEXT_5 (STATUS_CHECK_PAGE_ID + 0x08)
#define ID_TEXT_6 (STATUS_CHECK_PAGE_ID + 0x09)
#define ID_TEXT_7 (STATUS_CHECK_PAGE_ID + 0x0A)
#define ID_TEXT_8 (STATUS_CHECK_PAGE_ID + 0x0B)
#define ID_TEXT_9 (STATUS_CHECK_PAGE_ID + 0x0C)
#define ID_TEXT_10 (STATUS_CHECK_PAGE_ID + 0x0D)
#define ID_TEXT_11 (STATUS_CHECK_PAGE_ID + 0x0E)
#define ID_TEXT_12 (STATUS_CHECK_PAGE_ID + 0x0F)
#define ID_TEXT_13 (STATUS_CHECK_PAGE_ID + 0x10)
//#define ID_TEXT_14 (STATUS_CHECK_PAGE_ID + 0x11)
//#define ID_TEXT_15 (STATUS_CHECK_PAGE_ID + 0x12)
#define ID_TEXT_16 (STATUS_CHECK_PAGE_ID + 0x13)
#define ID_TEXT_17 (STATUS_CHECK_PAGE_ID + 0x14)
#define ID_TEXT_18 (STATUS_CHECK_PAGE_ID + 0x15)
#define ID_TEXT_19 (STATUS_CHECK_PAGE_ID + 0x16)
#define ID_TEXT_20 (STATUS_CHECK_PAGE_ID + 0x17)
#define ID_TEXT_21 (STATUS_CHECK_PAGE_ID + 0x18)
#define ID_TEXT_22 (STATUS_CHECK_PAGE_ID + 0x19)
#define ID_TEXT_23 (STATUS_CHECK_PAGE_ID + 0x1A)
#define ID_TEXT_24 (STATUS_CHECK_PAGE_ID + 0x1B)
#define ID_TEXT_25 (STATUS_CHECK_PAGE_ID + 0x1C)
#define ID_TEXT_26 (STATUS_CHECK_PAGE_ID + 0x1D)
#define ID_TEXT_27 (STATUS_CHECK_PAGE_ID + 0x1E)
#define ID_TEXT_28 (STATUS_CHECK_PAGE_ID + 0x1F)
#define ID_TEXT_29 (STATUS_CHECK_PAGE_ID + 0x20)
#define ID_TEXT_30 (STATUS_CHECK_PAGE_ID + 0x21)
#define ID_TEXT_31 (STATUS_CHECK_PAGE_ID + 0x22)
#define ID_TEXT_32 (STATUS_CHECK_PAGE_ID + 0x23)
#define ID_TEXT_33 (STATUS_CHECK_PAGE_ID + 0x24)
#define ID_TEXT_34 (STATUS_CHECK_PAGE_ID + 0x25)
#define ID_TEXT_35 (STATUS_CHECK_PAGE_ID + 0x26)
#define ID_TEXT_36 (STATUS_CHECK_PAGE_ID + 0x27)
#define ID_TEXT_37 (STATUS_CHECK_PAGE_ID + 0x28)
#define ID_TEXT_38 (STATUS_CHECK_PAGE_ID + 0x29)
#define ID_TEXT_39 (STATUS_CHECK_PAGE_ID + 0x2A)
#define ID_TEXT_40 (STATUS_CHECK_PAGE_ID + 0x2B)
#define ID_TEXT_41 (STATUS_CHECK_PAGE_ID + 0x2C)
#define ID_TEXT_42 (STATUS_CHECK_PAGE_ID + 0x2D)
#define ID_TEXT_43 (STATUS_CHECK_PAGE_ID + 0x2E)
#define ID_TEXT_44 (STATUS_CHECK_PAGE_ID + 0x2F)
#define ID_TEXT_45 (STATUS_CHECK_PAGE_ID + 0x30)
#define ID_BUTTON_2 (STATUS_CHECK_PAGE_ID + 0x31)
#define ID_BUTTON_3 (STATUS_CHECK_PAGE_ID + 0x32)
#define ID_BUTTON_4 (STATUS_CHECK_PAGE_ID + 0x33)
#define ID_BUTTON_5 (STATUS_CHECK_PAGE_ID + 0x34)
#define ID_BUTTON_6 (STATUS_CHECK_PAGE_ID + 0x35)
#define ID_BUTTON_7 (STATUS_CHECK_PAGE_ID + 0x36)
#define ID_BUTTON_8 (STATUS_CHECK_PAGE_ID + 0x37)
#define ID_BUTTON_9 (STATUS_CHECK_PAGE_ID + 0x38)
#define ID_TEXT_46 (STATUS_CHECK_PAGE_ID + 0x39)
#define ID_TEXT_47 (STATUS_CHECK_PAGE_ID + 0x3A)
#define ID_TEXT_48 (STATUS_CHECK_PAGE_ID + 0x3B)
#define ID_TEXT_49 (STATUS_CHECK_PAGE_ID + 0x3C)
#define ID_BUTTON_10 (STATUS_CHECK_PAGE_ID + 0x3D)
#define ID_BUTTON_11 (STATUS_CHECK_PAGE_ID + 0x3E)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "StatusCheckPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "服务", ID_TEXT_0, 30, 13, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> 运行状态", ID_TEXT_1, 90, 20, 104, 20, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "刷新", ID_BUTTON_0, 558, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "返回", ID_BUTTON_1, 678, 11, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t1", ID_TEXT_2, 80, 96, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t1_1", ID_TEXT_3, 170, 96, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t2", ID_TEXT_4, 80, 120, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t2_2", ID_TEXT_5, 170, 120, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t3", ID_TEXT_6, 80, 140, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t3_3", ID_TEXT_7, 170, 140, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t4", ID_TEXT_8, 80, 160, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t4_4", ID_TEXT_9, 170, 160, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t5", ID_TEXT_10, 80, 180, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t5_5", ID_TEXT_11, 170, 180, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t6", ID_TEXT_12, 80, 200, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t6_6", ID_TEXT_13, 170, 200, 80, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "t7", ID_TEXT_14, 45, 220, 115, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "t7_7", ID_TEXT_15, 170, 220, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t8", ID_TEXT_16, 45, 220, 115, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t8_8", ID_TEXT_17, 170, 220, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t9", ID_TEXT_18, 80, 240, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t9_9", ID_TEXT_19, 170, 240, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t10", ID_TEXT_20, 60, 260, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t10_10", ID_TEXT_21, 170, 260, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t21", ID_TEXT_42, 40, 280, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t21_21", ID_TEXT_43, 170, 280, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t23", ID_TEXT_46, 40, 300, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t23_23", ID_TEXT_47, 170, 300, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t11", ID_TEXT_22, 355, 96, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t11_11", ID_TEXT_23, 445, 96, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t12", ID_TEXT_24, 355, 120, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t12_12", ID_TEXT_25, 445, 120, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t13", ID_TEXT_26, 355, 160, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t13_13", ID_TEXT_27, 445, 160, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t14", ID_TEXT_28, 355, 180, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t14_14", ID_TEXT_29, 445, 180, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t15", ID_TEXT_30, 355, 140, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t15_15", ID_TEXT_31, 445, 140, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t16", ID_TEXT_32, 335, 200, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t16_16", ID_TEXT_33, 445, 200, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t17", ID_TEXT_34, 355, 220, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t17_17", ID_TEXT_35, 445, 220, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t18", ID_TEXT_36, 355, 240, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t18_18", ID_TEXT_37, 445, 240, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t19", ID_TEXT_38, 355, 260, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t19_19", ID_TEXT_39, 445, 260, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t20", ID_TEXT_40, 315, 280, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t20_20", ID_TEXT_41, 445, 280, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t22", ID_TEXT_44, 315, 300, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t22_22", ID_TEXT_45, 445, 300, 200, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t24", ID_TEXT_48, 315, 320, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "t24_24", ID_TEXT_49, 445, 320, 200, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "建压", ID_BUTTON_2, 678, 80, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "开气阀", ID_BUTTON_3, 678, 130, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "开液阀", ID_BUTTON_4, 678, 180, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "进仓", ID_BUTTON_5, 678, 230, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "出仓", ID_BUTTON_6, 678, 280, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "开535灯", ID_BUTTON_7, 678, 330, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "固定", ID_BUTTON_8, 568, 80, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "释放", ID_BUTTON_9, 568, 130, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "重置用户开机时间", ID_BUTTON_10, 530, 11, 140, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "开415灯", ID_BUTTON_11, 568, 330, 100, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _StatusCheckPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	extern __IO MachRunPara_s	MachRunPara;
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				//返回按钮
				case ID_BUTTON_1:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("建压",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("开气阀",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("开液阀",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect("进仓",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect("出仓",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_7:
					GUI_DispStringInRect("开535灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_8:
					GUI_DispStringInRect("固定",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_9:
					GUI_DispStringInRect("释放",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_10:
					GUI_DispStringInRect("重置用户开机时间",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_11:
					GUI_DispStringInRect("开415灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRectEx(&Rect,19);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_1:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("建压",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("开气阀",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("开液阀",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect("进仓",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect("出仓",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_7:
					GUI_DispStringInRect("开535灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_8:
					GUI_DispStringInRect("固定",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_9:
					GUI_DispStringInRect("释放",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_10:
					GUI_DispStringInRect("重置用户开机时间",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_11:
					GUI_DispStringInRect("开415灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
* 设置控件回调函数，以及重绘控件
*/
static void _StatusCheckPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
//    //刷新按钮
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
//    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
//    WM_InvalidateWindow(hItem);
	
	//返回按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//建压按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//开气阀按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//开液阀按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//进仓按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//出仓按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//开535灯按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//探针电机固定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//探针电机释放按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//重置用户开机时间按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//开415灯
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);  
    WM_SetCallback(hItem, _StatusCheckPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
  // USER START (Optionally insert additional variables)
	extern char* BKBmaDataBuf;
	extern CATGlobalStatus_s CATGlobalStatus;
	extern MachInfo_s MachInfo;
	extern __IO BC_Data_t   g_stBC_Data[BC_END];
	
	char StrBuf[60];
	uint32_t Temp = 0;
	struct tm FactoryTime;
	struct tm UserFirstOpenTime;
	
	static uint16_t MaxWBCADCValue = 0;
	long LocalTimestamp = 0;
	
	extern osMessageQueueId_t CATQueueHandle;
	CATQueueInfoBuf_s CATQueueInfoBuf = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	BC_CUR_SW_ON;  
  
	//开启WBC采集
	BC_Enable(BC_WBC);
  
    //
    // Initialization of 'service_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem,&HZ_SONGTI_24);
	WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"服务");
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
    //
    // Initialization of 't1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"出仓光耦：");
    //
    // Initialization of 't1_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(OC_Status(OC_INDEX_OUTIN_OUT) == SET){
		TEXT_SetText(hItem,"激活");
	}else{
		TEXT_SetText(hItem,"空闲");
	}
    //
    // Initialization of 't2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"进仓光耦：");
    //
    // Initialization of 't2_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(OC_Status(OC_INDEX_OUTIN_IN) == SET){
		TEXT_SetText(hItem,"激活");
	}else{
		TEXT_SetText(hItem,"空闲");
	}
    //
    // Initialization of 't3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"导通光耦：");
    //
    // Initialization of 't3_3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(OC_Status(OC_INDEX_CLAMP_OUT) == SET){
		TEXT_SetText(hItem,"激活");
	}else{
		TEXT_SetText(hItem,"空闲");
	}
    //
    // Initialization of 't4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"断开光耦：");
    //
    // Initialization of 't4_4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(OC_Status(OC_INDEX_CLAMP_IN) == SET){
		TEXT_SetText(hItem,"激活");
	}else{
		TEXT_SetText(hItem,"空闲");
	}
    //
    // Initialization of 't5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"定量电极：");
    //
    // Initialization of 't5_5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(ELEC_STATUS == SET){
		TEXT_SetText(hItem,"激活");
	}else{
		TEXT_SetText(hItem,"空闲");
	}
    //
    // Initialization of 't6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"负压：");
    //
    // Initialization of 't6_6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	Temp = sprintf(StrBuf,"%d Pa",Press_Value());
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
    //
    // Initialization of 't7'
    //
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
//    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
//	TEXT_SetText(hItem,"/");
//    //
//    // Initialization of 't7_7'
//    //
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
//    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
//	TEXT_SetText(hItem,"/");
    //
    // Initialization of 't8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"计数池检测：");
    //
    // Initialization of 't8_8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	COUNT_CELL_SW_ON;
	HAL_Delay(10);
	if(CHECK_JSC_EXIST_STATUS != JSC_EXIST_STATUS_ACTIVE){
		TEXT_SetText(hItem,"空闲");
	}else{
		TEXT_SetText(hItem,"激活");
	}
	COUNT_CELL_SW_OFF;
    //
    // Initialization of 't9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"小孔电压：");
    //
    // Initialization of 't9_9'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	Temp = sprintf(StrBuf,"%u mV",XK_V());
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
	
    //
    // Initialization of 't10'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"恒流源电压：");
    //
    // Initialization of 't10_10'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	Temp = sprintf(StrBuf,"%u mV",BC_Current_V());
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
	//
    // Initialization of 't21'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_42);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"HGB值：");
    //
    // Initialization of 't21_21'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_43);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	Temp = sprintf(StrBuf,"%u mV, %u",HGB_V(), HGB_ADC());
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
	//
    // Initialization of 't23'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_46);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"NTC温度：");
    //
    // Initialization of 't23_23'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_47);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
//	Temp = sprintf(StrBuf,"%u mV",HGB_V());
//	StrBuf[Temp] = '\0';
//	TEXT_SetText(hItem,StrBuf);
	
    //
    // Initialization of 't11'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_22);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"+12V电压：");
    //
    // Initialization of 't11_11'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_23);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	Temp = sprintf(StrBuf,"%u mV",Power_12VP_V());
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
    //
    // Initialization of 't12'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_24);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"-12V电压：");
    //
    // Initialization of 't12_12'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_25);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	Temp = sprintf(StrBuf,"%d mV",Power_12VN_V());
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
    //
    // Initialization of 't13'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_26);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"IMEI：");
    //
    // Initialization of 't13_13'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_27);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(strlen(CATGlobalStatus.imei) < 10){
		TEXT_SetText(hItem,"/");
	}else{
		TEXT_SetText(hItem,CATGlobalStatus.imei);
	}
    //
    // Initialization of 't14'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_28);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"ICCID：");
    //
    // Initialization of 't14_14'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_29);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(strlen(CATGlobalStatus.iccid) < 10){
		TEXT_SetText(hItem,"/");
	}else{
		TEXT_SetText(hItem,CATGlobalStatus.iccid);
	}
    //
    // Initialization of 't15'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_30);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"运营商：");
    //
    // Initialization of 't15_15'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_31);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(CATGlobalStatus.operatorNum == 0){
		TEXT_SetText(hItem,"中国电信");
	}else if(CATGlobalStatus.operatorNum == 1){
		TEXT_SetText(hItem,"中国移动");
	}else{
		TEXT_SetText(hItem,"/");
	}
    //
    // Initialization of 't16'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_32);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"CAT.1状态：");
    //
    // Initialization of 't16_16'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_33);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(CATGlobalStatus.flag.powOn == 0){
		TEXT_SetText(hItem,"尚未开机");
	}else{
		if(CATGlobalStatus.flag.conn == 0){
			TEXT_SetText(hItem,"串口尚未连接");
		}else{
			if(CATGlobalStatus.flag.sim == 0){
				TEXT_SetText(hItem,"未识别到SIM卡");
			}else{
				if(CATGlobalStatus.signalStrength < 15){
					TEXT_SetText(hItem,"信号强度弱");
				}else{
					if(CATGlobalStatus.registerNet == CAT_REGISTNET_UNKNOW){
						TEXT_SetText(hItem,"网络未知");
					}else{
						if(CATGlobalStatus.registerNet == CAT_REGISTNET_CHECKING){
							TEXT_SetText(hItem,"搜网中...");
						}else{
							if(CATGlobalStatus.registerNet == CAT_REGISTNET_SIM_OVERDUE){
								TEXT_SetText(hItem,"SIM卡过期");
							}else{
								if(CATGlobalStatus.flag.connServerErr == 1){
									TEXT_SetText(hItem,"注网成功/连接服务端异常");
								}else{
									TEXT_SetText(hItem,"正常");
								}
							}
						}
					}
				}
			}
		}
	}
    //
    // Initialization of 't17'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_34);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"网络强度：");
    //
    // Initialization of 't17_17'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_35);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(CATGlobalStatus.signalStrength <= 10){
		Temp = sprintf(StrBuf,"%u 差",CATGlobalStatus.signalStrength);
	}else if(CATGlobalStatus.signalStrength <= 20){
		Temp = sprintf(StrBuf,"%u 一般",CATGlobalStatus.signalStrength);
	}else if(CATGlobalStatus.signalStrength <= 25){
		Temp = sprintf(StrBuf,"%u 良好",CATGlobalStatus.signalStrength);
	}else if(CATGlobalStatus.signalStrength == 99){
		Temp = sprintf(StrBuf,"%u 无网络",CATGlobalStatus.signalStrength);
	}else{
		Temp = sprintf(StrBuf,"%u 优",CATGlobalStatus.signalStrength);
	}
	
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
    //
    // Initialization of 't18'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_36);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"位置信息：");
    //
    // Initialization of 't18_18'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_37);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	if(strlen(CATGlobalStatus.position) < 10){
		TEXT_SetText(hItem,"/");
	}else{
		TEXT_SetText(hItem,CATGlobalStatus.position);
	}
    //
    // Initialization of 't19'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_38);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"出厂时间：");
    //
    // Initialization of 't19_19'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_39);
	LocalTimestamp = MachInfo.other.factoryTimestamp + 8*3600;			//转换成本地东八时间戳
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	FactoryTime = *(localtime((time_t*)&LocalTimestamp));
	Temp = sprintf(StrBuf,"%u-%u-%u %u:%u:%u",FactoryTime.tm_year+1900,FactoryTime.tm_mon+1,FactoryTime.tm_mday,FactoryTime.tm_hour,FactoryTime.tm_min,FactoryTime.tm_sec);
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
    //
    // Initialization of 't20'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_40);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"用户开机时间：");
    //
    // Initialization of 't20_20'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_41);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	LocalTimestamp = MachInfo.other.userTimestamp + 8*3600;			//转换成本地东八时间戳
	UserFirstOpenTime = *(localtime((time_t*)&LocalTimestamp));
	Temp = sprintf(StrBuf,"%u-%u-%u %u:%u:%u",UserFirstOpenTime.tm_year+1900,UserFirstOpenTime.tm_mon+1,UserFirstOpenTime.tm_mday,UserFirstOpenTime.tm_hour,UserFirstOpenTime.tm_min,UserFirstOpenTime.tm_sec);
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
	//
    // Initialization of 't22'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_44);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"开机总次数：");
    //
    // Initialization of 't22_22'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_45);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	Temp = sprintf(StrBuf,"%u",MachInfo.other.totalOpenCount);
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
	//
    // Initialization of 't24'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_48);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"空白WBC噪声：");
	
    //
    // Initialization of 't24_24'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_49);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	for(Temp=0;Temp<500;Temp++){
		if(MaxWBCADCValue < g_stBC_Data[BC_WBC].ucBuf[Temp]){
			MaxWBCADCValue = g_stBC_Data[BC_WBC].ucBuf[Temp];
		}
	}
	Temp = sprintf(StrBuf,"%u mV",(MaxWBCADCValue*3300)>>12);
	StrBuf[Temp] = '\0';
	TEXT_SetText(hItem,StrBuf);
    // USER START (Optionally insert additional code for further widget initialization)
	
	//重绘按钮样式
	_StatusCheckPageRedrawWidgetType(pMsg);
    
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    // USER END
    break;
	
	case WM_PAINT:
		//画背景BMP图
        WM_GetClientRect(&Rect); 
        GUI_SetColor(GUI_WHITE);
        GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
	break;
	
	//删除窗口
	case WM_DELETE:
		//关闭恒流源
		BC_CUR_SW_OFF;
	
		//关闭WBC采集
		BC_Disable(BC_WBC);
		g_stBC_Data[BC_WBC].ucFlag = BC_ADC_PART_NONE;
		
		//退出窗口时重置
		MaxWBCADCValue = 0;
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
//    case ID_BUTTON_0: // Notifications sent by 'refresh_b'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      // USER START (Optionally insert additional code for further notification handling)
//      // USER END
//      }
//      break;
    case ID_BUTTON_1: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateservicePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
	case ID_BUTTON_2: // Notifications sent by '建压按钮'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				//建压
				AIR_WAVE_OPEN;
				LIQUID_WAVE_CLOSE;
				Pump_Start();
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				//结束建压
				AIR_WAVE_CLOSE;
				LIQUID_WAVE_CLOSE;
				Pump_Stop();
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				//结束建压
				AIR_WAVE_CLOSE;
				LIQUID_WAVE_CLOSE;
				Pump_Stop();
			break;
			// USER END
		}
	break;
	case ID_BUTTON_3: // Notifications sent by '开气阀'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				AIR_WAVE_OPEN;
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				AIR_WAVE_CLOSE;
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				AIR_WAVE_CLOSE;
			break;
			// USER END
		}
	break;
	case ID_BUTTON_4: // Notifications sent by '开液阀'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				LIQUID_WAVE_OPEN;
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				LIQUID_WAVE_CLOSE;
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				LIQUID_WAVE_CLOSE;
			break;
			// USER END
		}
	break;
	case ID_BUTTON_5: // Notifications sent by '进仓'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				MV_InitPara(MOTOR_OUTIN, 1920, 10000, 100, 10);
				MV_Move(MOTOR_OUTIN, 0xffffffff, MOTOR_DIR_IN); 
				MTx_IoMinitor_Disnable(MOTOR_OUTIN);
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				MV_Stop(MOTOR_OUTIN);
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				MV_Stop(MOTOR_OUTIN);
			break;
			// USER END
		}
	break;
	case ID_BUTTON_6: // Notifications sent by '出仓'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				MV_InitPara(MOTOR_OUTIN, 1920, 10000, 100, 10);
				MV_Move(MOTOR_OUTIN, 0xffffffff, MOTOR_DIR_OUT); 
				MTx_IoMinitor_Disnable(MOTOR_OUTIN);
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				MV_Stop(MOTOR_OUTIN);
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				MV_Stop(MOTOR_OUTIN);
			break;
			// USER END
		}
	break;
	case ID_BUTTON_7: // Notifications sent by '开535灯'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				Light_Start(HGBLED_535,MachInfo.paramSet.current535);
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				Light_Stop();
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				Light_Stop();
			break;
			// USER END
		}
	break;
	case ID_BUTTON_8: // Notifications sent by '探针电机固定按钮'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				MV_InitPara(MOTOR_CLAMP, 1920, 10000, 100, 10);
				MV_Move(MOTOR_CLAMP, 0xffffffff, MOTOR_DIR_OUT); 
				MTx_IoMinitor_Disnable(MOTOR_CLAMP);
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				MV_Stop(MOTOR_CLAMP);
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				MV_Stop(MOTOR_CLAMP);
			break;
			// USER END
		}
	break;
	case ID_BUTTON_9: // Notifications sent by '探针电机释放按钮'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				MV_InitPara(MOTOR_CLAMP, 1920, 10000, 100, 10);
				MV_Move(MOTOR_CLAMP, 0xffffffff, MOTOR_DIR_IN); 
				MTx_IoMinitor_Disnable(MOTOR_CLAMP);
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				MV_Stop(MOTOR_CLAMP);
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				MV_Stop(MOTOR_CLAMP);
			break;
			// USER END
		}
	break;
		
	case ID_BUTTON_10: // Notifications sent by '重置用户开机时间按钮'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				if(MachInfo.catMastSynServEvent.bit.resetUserOpenTimestamp == 0){
					MachInfo.flag.bit.userTimestampInit = 0;
					MachInfo.other.userTimestamp = 0;
				
					//CAT必发项
					MachInfo.catMastSynServEvent.bit.resetUserOpenTimestamp = 1;
					
					//通知后台修改了用户开机时间事件
					CATQueueInfoBuf.msgType = CHANGE_MACHINE_INFO_CAT_MSG_TYPGE;
					CATQueueInfoBuf.para.changeMachineInfo.changeType = 4;					//4表示通知服务端重置了用户开机时间
					osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
				
					//写入EEPROM
					EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_FLAG,(uint8_t*)&MachInfo.flag,sizeof(MachInfo.flag));
					EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_OTHER,(uint8_t*)&MachInfo.other,sizeof(MachInfo.other));
					EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_CAT_SYNC_SER_EVENT,(uint8_t*)&MachInfo.catMastSynServEvent,sizeof(MachInfo.catMastSynServEvent));
				}
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
	break;
		
	case ID_BUTTON_11: // Notifications sent by '开415灯'
		switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
				Light_Start(HGBLED_415,MachInfo.paramSet.current415);
			// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
				Light_Stop();
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			case WM_NOTIFICATION_MOVED_OUT:
				Light_Stop();
			break;
			// USER END
		}
	break;
		
		
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	//窗口定时器消息
	case WM_TIMER:
		//
		// Initialization of 't1_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		if(OC_Status(OC_INDEX_OUTIN_OUT) == SET){
			TEXT_SetText(hItem,"激活");
		}else{
			TEXT_SetText(hItem,"空闲");
		}
		//
		// Initialization of 't2_2'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		if(OC_Status(OC_INDEX_OUTIN_IN) == SET){
			TEXT_SetText(hItem,"激活");
		}else{
			TEXT_SetText(hItem,"空闲");
		}
		//
		// Initialization of 't3_3'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
		if(OC_Status(OC_INDEX_CLAMP_OUT) == SET){
			TEXT_SetText(hItem,"激活");
		}else{
			TEXT_SetText(hItem,"空闲");
		}
		//
		// Initialization of 't4_4'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
		if(OC_Status(OC_INDEX_CLAMP_IN) == SET){
			TEXT_SetText(hItem,"激活");
		}else{
			TEXT_SetText(hItem,"空闲");
		}
		//
		// Initialization of 't5_5'
		//
        memset(StrBuf, 0, sizeof(StrBuf));
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
		if(ELEC_STATUS == SET){
            sprintf(StrBuf, "%s,%dmv", "激活", Elec_V());
		}else{
            sprintf(StrBuf, "%s,%dmv", "空闲", Elec_V());
		}
        TEXT_SetText(hItem, StrBuf);
		//
		// Initialization of 't6_6'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
		Temp = sprintf(StrBuf,"%d Pa",Press_Value());
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't7_7'
		//
//		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
//		TEXT_SetText(hItem,"/");
		//
		// Initialization of 't8_8'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
		COUNT_CELL_SW_ON;
		HAL_Delay(10);
		if(CHECK_JSC_EXIST_STATUS != JSC_EXIST_STATUS_ACTIVE){
			TEXT_SetText(hItem,"空闲");
		}else{
			TEXT_SetText(hItem,"激活");
		}
		COUNT_CELL_SW_OFF;
		//
		// Initialization of 't9_9'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
		Temp = sprintf(StrBuf,"%u mV",XK_V());
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't10_10'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
		Temp = sprintf(StrBuf,"%u mV",BC_Current_V());
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't21_21'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_43);
		Temp = sprintf(StrBuf,"%u mV, %u",HGB_V(), HGB_ADC());
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't23_23'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_47);
		Temp = sprintf(StrBuf,"%d ℃",NTC_Temperature());
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't11_11'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_23);
		Temp = sprintf(StrBuf,"%u mV",Power_12VP_V());
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't12_12'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_25);
		Temp = sprintf(StrBuf,"%d mV",Power_12VN_V());
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't13_13'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_27);
		if(strlen(CATGlobalStatus.imei) < 10){
			TEXT_SetText(hItem,"/");
		}else{
			TEXT_SetText(hItem,CATGlobalStatus.imei);
		}
		//
		// Initialization of 't14_14'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_29);
		if(strlen(CATGlobalStatus.iccid) < 10){
			TEXT_SetText(hItem,"/");
		}else{
			TEXT_SetText(hItem,CATGlobalStatus.iccid);
		}
		//
		// Initialization of 't15_15'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_31);
		if(CATGlobalStatus.operatorNum == 0){
			TEXT_SetText(hItem,"中国电信");
		}else if(CATGlobalStatus.operatorNum == 1){
			TEXT_SetText(hItem,"中国移动");
		}else{
			TEXT_SetText(hItem,"/");
		}
		//
		// Initialization of 't16_16'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_33);
		if(CATGlobalStatus.flag.powOn == 0){
			TEXT_SetText(hItem,"尚未开机");
		}else{
			if(CATGlobalStatus.flag.conn == 0){
				TEXT_SetText(hItem,"串口尚未连接");
			}else{
				if(CATGlobalStatus.flag.sim == 0){
					TEXT_SetText(hItem,"未识别到SIM卡");
				}else{
					if(CATGlobalStatus.signalStrength < 15){
						TEXT_SetText(hItem,"信号强度弱");
					}else{
						if(CATGlobalStatus.registerNet == CAT_REGISTNET_UNKNOW){
							TEXT_SetText(hItem,"网络未知");
						}else{
							if(CATGlobalStatus.registerNet == CAT_REGISTNET_CHECKING){
								TEXT_SetText(hItem,"搜网中...");
							}else{
								if(CATGlobalStatus.registerNet == CAT_REGISTNET_SIM_OVERDUE){
									TEXT_SetText(hItem,"SIM卡过期");
								}else{
									if(CATGlobalStatus.flag.connServerErr == 1){
										TEXT_SetText(hItem,"注网成功/连接服务端异常");
									}else{
										TEXT_SetText(hItem,"正常");
									}
								}
							}
						}
					}
				}
			}
		}
		//
		// Initialization of 't17_17'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_35);
		if(CATGlobalStatus.signalStrength <= 10){
			Temp = sprintf(StrBuf,"%u 差",CATGlobalStatus.signalStrength);
		}else if(CATGlobalStatus.signalStrength <= 20){
			Temp = sprintf(StrBuf,"%u 一般",CATGlobalStatus.signalStrength);
		}else if(CATGlobalStatus.signalStrength <= 25){
			Temp = sprintf(StrBuf,"%u 良好",CATGlobalStatus.signalStrength);
		}else if(CATGlobalStatus.signalStrength == 99){
			Temp = sprintf(StrBuf,"%u 无网络",CATGlobalStatus.signalStrength);
		}else{
			Temp = sprintf(StrBuf,"%u 优",CATGlobalStatus.signalStrength);
		}
		
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't18_18'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_37);
		if(strlen(CATGlobalStatus.position) < 10){
			TEXT_SetText(hItem,"/");
		}else{
			TEXT_SetText(hItem,CATGlobalStatus.position);
		}
		//
		// Initialization of 't19_19'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_39);
		LocalTimestamp = MachInfo.other.factoryTimestamp + 8*3600;			//转换成本地东八时间戳
		FactoryTime = *(localtime((time_t*)&LocalTimestamp));
		Temp = sprintf(StrBuf,"%u-%u-%u %u:%u:%u",FactoryTime.tm_year+1900,FactoryTime.tm_mon+1,FactoryTime.tm_mday,FactoryTime.tm_hour,FactoryTime.tm_min,FactoryTime.tm_sec);
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't20_20'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_41);
		LocalTimestamp = MachInfo.other.userTimestamp + 8*3600;			//转换成本地东八时间戳
		UserFirstOpenTime = *(localtime((time_t*)&LocalTimestamp));
		Temp = sprintf(StrBuf,"%u-%u-%u %u:%u:%u",UserFirstOpenTime.tm_year+1900,UserFirstOpenTime.tm_mon+1,UserFirstOpenTime.tm_mday,UserFirstOpenTime.tm_hour,UserFirstOpenTime.tm_min,UserFirstOpenTime.tm_sec);
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't22_22'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_45);
		Temp = sprintf(StrBuf,"%u",MachInfo.other.totalOpenCount);
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
		//
		// Initialization of 't24_24'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_49);
		for(Temp=0;Temp<500;Temp++){
			if(MaxWBCADCValue < g_stBC_Data[BC_WBC].ucBuf[Temp]){
				MaxWBCADCValue = g_stBC_Data[BC_WBC].ucBuf[Temp];
			}
		}
		Temp = sprintf(StrBuf,"%u mV",(MaxWBCADCValue*3300)>>12);
		StrBuf[Temp] = '\0';
		TEXT_SetText(hItem,StrBuf);
	
		//重启计时器
		WM_RestartTimer(pMsg->Data.v,500);
	break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateStatusCheckPage
*/
WM_HWIN CreateStatusCheckPage(void);
WM_HWIN CreateStatusCheckPage(void) {
	WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	//创建窗口定时器,500ms触发一次
	WM_CreateTimer(hWin,0,500,0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
