/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "main.h"
#include "algdata.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (VERSION_PAGE_ID + 0x00)
#define ID_TEXT_0 (VERSION_PAGE_ID + 0x01)
#define ID_TEXT_1 (VERSION_PAGE_ID + 0x02)
#define ID_BUTTON_0 (VERSION_PAGE_ID + 0x03)
#define ID_TEXT_2 (VERSION_PAGE_ID + 0x04)
#define ID_TEXT_3 (VERSION_PAGE_ID + 0x05)
#define ID_TEXT_4 (VERSION_PAGE_ID + 0x06)
#define ID_TEXT_5 (VERSION_PAGE_ID + 0x07)
#define ID_TEXT_6 (VERSION_PAGE_ID + 0x08)
#define ID_TEXT_7 (VERSION_PAGE_ID + 0x09)
#define ID_TEXT_8 (VERSION_PAGE_ID + 0x0A)
#define ID_TEXT_9 (VERSION_PAGE_ID + 0x0B)
#define ID_TEXT_10 (VERSION_PAGE_ID + 0x0C)
#define ID_TEXT_11 (VERSION_PAGE_ID + 0x0D)
#define ID_TEXT_12 (VERSION_PAGE_ID + 0x0E)
#define ID_TEXT_13 (VERSION_PAGE_ID + 0x0F)
#define ID_TEXT_14 (VERSION_PAGE_ID + 0x10)
#define ID_TEXT_15 (VERSION_PAGE_ID + 0x11)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "versionPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SERV", ID_TEXT_0, 30, 15, 90, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> VERSION", ID_TEXT_1, 120, 20, 140, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEL", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Pub VER", ID_TEXT_14, 223, 110, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PubValue_t", ID_TEXT_15, 470, 110, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "FULL VER", ID_TEXT_2, 223, 150, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "softFullValue_t", ID_TEXT_3, 470, 150, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ALGO VER", ID_TEXT_4, 223, 190, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "algoValue_t", ID_TEXT_5, 470, 190, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "MAIN VER", ID_TEXT_6, 223, 230, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "mainValue_t", ID_TEXT_7, 470, 230, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "BOOTL VER", ID_TEXT_8, 223, 270, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "bootValue_t", ID_TEXT_9, 470, 270, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HARD VER", ID_TEXT_10, 223, 310, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "hardValue_t", ID_TEXT_11, 430, 310, 150, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "UI VER", ID_TEXT_12, 223, 350, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "uiValue_t", ID_TEXT_13, 470, 350, 110, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static int _Button_DrawSkin(const WIDGET_ITEM_DRAW_INFO* pDrawItemInfo)
{
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
	switch(pDrawItemInfo->Cmd){
		case WIDGET_ITEM_DRAW_BACKGROUND:
			if(BUTTON_IsPressed(pDrawItemInfo->hWin)){		//按钮按下时皮肤色
				switch(WM_GetId(pDrawItemInfo->hWin)){
					//返回
					case ID_BUTTON_0:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
				}
			}else{			//按钮没有按下时皮肤色
				switch(WM_GetId(pDrawItemInfo->hWin)){
					//返回
					case ID_BUTTON_0:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
				}
			}
		break;
		default:
			return BUTTON_SKIN_FLEX(pDrawItemInfo);
	}
	return 0;
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
    
  // USER START (Optionally insert additional variables)
	extern char* BKBmaDataBuf;
	extern MachInfo_s MachInfo;
	
	char StrTemp[20] = {0};
	uint16_t Temp = 0;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Serve_Serve[MachInfo.systemSet.eLanguage]); 
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Serve_VersionInfo[MachInfo.systemSet.eLanguage]);
	
	//发布版本号
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_PubVer[MachInfo.systemSet.eLanguage]);
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	Temp = sprintf(StrTemp,"%s",RELEASE_VERSION);
	StrTemp[Temp] = '\0';
	TEXT_SetText(hItem,StrTemp);
	
    //
    // Initialization of 'softFull_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_FullVer[MachInfo.systemSet.eLanguage]);
	
    //
    // Initialization of 'softFullValue_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	Temp = sprintf(StrTemp,"V%u.%u.%u",FULL_VERSION/100,(FULL_VERSION%100)/10,(FULL_VERSION%100)%10);
	StrTemp[Temp] = '\0';
	TEXT_SetText(hItem,StrTemp);
    //
    // Initialization of 'algo_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_AlgoVer[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'algoValue_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	Temp = sprintf(StrTemp,"%s",version());
	StrTemp[Temp] = '\0';
	TEXT_SetText(hItem,StrTemp);
    //
    // Initialization of 'main_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_MainVer[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'mainValue_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	Temp = sprintf(StrTemp,"V%u.%u.%u",MAIN_VERSION/100,(MAIN_VERSION%100)/10,(MAIN_VERSION%100)%10);
	StrTemp[Temp] = '\0';
	TEXT_SetText(hItem,StrTemp);
    //
    // Initialization of 'boot_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&SIF_HZ16_SONGTI);
	TEXT_SetText(hItem,g_ucaLng_Serve_BootloadVer[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'bootValue_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	Temp = sprintf(StrTemp,"V%u.%u.%u",*((uint16_t*)BOOTLOAD_VERSION_ADR)/100,(*((uint16_t*)BOOTLOAD_VERSION_ADR)%100)/10,(*((uint16_t*)BOOTLOAD_VERSION_ADR)%100)%10);
	StrTemp[Temp] = '\0';
	TEXT_SetText(hItem,StrTemp);
    //
    // Initialization of 'hard_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_HardVer[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'hardValue_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	Temp = sprintf(StrTemp,"%s/%s",MachRunPara.hardVer.main,MachRunPara.hardVer.zjb);
	StrTemp[Temp] = '\0';
	TEXT_SetText(hItem,StrTemp);
    //
    // Initialization of 'ui_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_Serve_UIVer[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'uiValue_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	Temp = sprintf(StrTemp,"V%u.%u.%u",MachInfo.other.uiVersion/100,(MachInfo.other.uiVersion%100)/10,(MachInfo.other.uiVersion%100)%10);
	StrTemp[Temp] = '\0';
	TEXT_SetText(hItem,StrTemp);
	
    //判断是否需要隐藏项
	if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_4));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_5));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_7));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_8));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_9));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_10));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_11));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_12));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_TEXT_13));
	}
	
	//设置按钮皮肤
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Return[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
    // USER START (Optionally insert additional code for further widget initialization)
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    // USER END
    break;
	
	case WM_PAINT:
		//画背景BMP图
		//GUI_BMP_Draw(BKBmaDataBuf,1,0);
        //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);          
          WM_GetClientRect(&Rect); 
          GUI_SetColor(GUI_WHITE);
          GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
	
		//判断是否需要隐藏项
		if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
			//画框
			GUI_SetColor(0x009ea0a2);
			GUI_AA_DrawRoundedRect(172,92,625,182,4);
		
			//画框内短线
			GUI_SetColor(0x009ea0a2);
			GUI_DrawHLine(140,223,578);
		}else{
			//画框
			GUI_SetColor(0x009ea0a2);
			GUI_AA_DrawRoundedRect(172,92,625,382,4);
		
			//画框内短线
			GUI_SetColor(0x009ea0a2);
			GUI_DrawHLine(140,223,578);
			GUI_DrawHLine(180,223,578);
			GUI_DrawHLine(220,223,578);
			GUI_DrawHLine(260,223,578);
			GUI_DrawHLine(300,223,578);
			GUI_DrawHLine(340,223,578);
		}
		
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateservicePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateversionPage
*/
WM_HWIN CreateversionPage(void);
WM_HWIN CreateversionPage(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
