/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "process.h"
#include "bsp_eeprom.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (SERVICE_XNCHECK_PAGE_ID + 0x00)
#define ID_TEXT_0    (SERVICE_XNCHECK_PAGE_ID + 0x01)
#define ID_TEXT_1    (SERVICE_XNCHECK_PAGE_ID + 0x02)
#define ID_BUTTON_0    (SERVICE_XNCHECK_PAGE_ID + 0x03)
#define ID_BUTTON_1    (SERVICE_XNCHECK_PAGE_ID + 0x04)
#define ID_BUTTON_2    (SERVICE_XNCHECK_PAGE_ID + 0x05)
#define ID_BUTTON_3    (SERVICE_XNCHECK_PAGE_ID + 0x06)
#define ID_BUTTON_4    (SERVICE_XNCHECK_PAGE_ID + 0x07)
#define ID_EDIT_0    (SERVICE_XNCHECK_PAGE_ID + 0x08)
#define ID_EDIT_1    (SERVICE_XNCHECK_PAGE_ID + 0x09)
#define ID_EDIT_2    (SERVICE_XNCHECK_PAGE_ID + 0x0A)
#define ID_BUTTON_5    (SERVICE_XNCHECK_PAGE_ID + 0x0B)
#define ID_BUTTON_6    (SERVICE_XNCHECK_PAGE_ID + 0x0C)
#define ID_BUTTON_7    (SERVICE_XNCHECK_PAGE_ID + 0x0D)
#define ID_TEXT_2    (SERVICE_XNCHECK_PAGE_ID + 0x0E)
#define ID_TEXT_3    (SERVICE_XNCHECK_PAGE_ID + 0x0F)
#define ID_TEXT_4    (SERVICE_XNCHECK_PAGE_ID + 0x10)
#define ID_BUTTON_8    (SERVICE_XNCHECK_PAGE_ID + 0x11)
#define ID_TEXT_5    (SERVICE_XNCHECK_PAGE_ID + 0x12)
#define ID_EDIT_3    (SERVICE_XNCHECK_PAGE_ID + 0x13)
#define ID_EDIT_4    (SERVICE_XNCHECK_PAGE_ID + 0x14)
#define ID_EDIT_5    (SERVICE_XNCHECK_PAGE_ID + 0x15)
#define ID_EDIT_6    (SERVICE_XNCHECK_PAGE_ID + 0x16)
#define ID_EDIT_7    (SERVICE_XNCHECK_PAGE_ID + 0x17)
#define ID_EDIT_8    (SERVICE_XNCHECK_PAGE_ID + 0x18)
#define ID_BUTTON_9    (SERVICE_XNCHECK_PAGE_ID + 0x19)
#define ID_BUTTON_10    (SERVICE_XNCHECK_PAGE_ID + 0x1A)
#define ID_BUTTON_11    (SERVICE_XNCHECK_PAGE_ID + 0x1B)
#define ID_TEXT_6    (SERVICE_XNCHECK_PAGE_ID + 0x1C)
#define ID_TEXT_7    (SERVICE_XNCHECK_PAGE_ID + 0x1D)
#define ID_TEXT_8    (SERVICE_XNCHECK_PAGE_ID + 0x1E)
#define ID_TEXT_9    (SERVICE_XNCHECK_PAGE_ID + 0x1F)
#define ID_TEXT_10    (SERVICE_XNCHECK_PAGE_ID + 0x20)
#define ID_TEXT_11    (SERVICE_XNCHECK_PAGE_ID + 0x21)
#define ID_BUTTON_12    (SERVICE_XNCHECK_PAGE_ID + 0x22)
#define ID_BUTTON_13    (SERVICE_XNCHECK_PAGE_ID + 0x23)
#define ID_BUTTON_14    (SERVICE_XNCHECK_PAGE_ID + 0x24)
#define ID_BUTTON_15    (SERVICE_XNCHECK_PAGE_ID + 0x25)
#define ID_BUTTON_16    (SERVICE_XNCHECK_PAGE_ID + 0x26)
#define ID_TEXT_12    (SERVICE_XNCHECK_PAGE_ID + 0x27)
#define ID_TEXT_13    (SERVICE_XNCHECK_PAGE_ID + 0x28)
#define ID_TEXT_14    (SERVICE_XNCHECK_PAGE_ID + 0x29)
#define ID_TEXT_15    (SERVICE_XNCHECK_PAGE_ID + 0x2A)
#define ID_TEXT_16    (SERVICE_XNCHECK_PAGE_ID + 0x2B)
#define ID_MULTIEDIT_0    (SERVICE_XNCHECK_PAGE_ID + 0x2C)

#define ID_BUTTON_17    (SERVICE_XNCHECK_PAGE_ID + 0x2D)
#define ID_TEXT_17    (SERVICE_XNCHECK_PAGE_ID + 0x2E)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "XNCheckPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Service_t", ID_TEXT_0, 30, 13, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "XNCheck_t", ID_TEXT_1, 90, 20, 104, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Return_b", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBJMD_b", ID_BUTTON_1, 568, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBKB_b", ID_BUTTON_2, 458, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "WBC_b", ID_BUTTON_3, 348, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Upload_b", ID_BUTTON_4, 238, 11, 100, 40, 0, 0x0, 0 },
  
  { EDIT_CreateIndirect, "HGBBZ1_e", ID_EDIT_0, 57, 122, 66, 29, 0, 0x6, 0 },
  { EDIT_CreateIndirect, "HGBBZ2_e", ID_EDIT_1, 57, 154, 66, 29, 0, 0x6, 0 },
  { EDIT_CreateIndirect, "HGBBZ3_e", ID_EDIT_2, 57, 186, 66, 29, 0, 0x6, 0 },
  { BUTTON_CreateIndirect, "HGBBZ1_b", ID_BUTTON_5, 130, 122, 60, 29, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBBZ2_b", ID_BUTTON_6, 130, 154, 60, 29, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBBZ3_b", ID_BUTTON_7, 130, 186, 60, 29, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBBZ1_t", ID_TEXT_2, 200, 121, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBBZ2_t", ID_TEXT_3, 200, 154, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBBZ3_t", ID_TEXT_4, 200, 187, 60, 30, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "WBCXS_b", ID_BUTTON_17, 286, 90, 90, 29, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WBCXS_t", ID_TEXT_17, 286, 122, 90, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBXS_b", ID_BUTTON_8, 286, 154, 90, 29, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBXS_t", ID_TEXT_5, 286, 187, 90, 30, 0, 0x0, 0 },
  
  { EDIT_CreateIndirect, "WBCZQ1_e", ID_EDIT_3, 57, 281, 66, 29, 0, 0x6, 0 },
  { EDIT_CreateIndirect, "WBCZQ2_e", ID_EDIT_4, 57, 313, 66, 29, 0, 0x6, 0 },
  { EDIT_CreateIndirect, "WBCZQ3_e", ID_EDIT_5, 57, 345, 66, 29, 0, 0x6, 0 },
  { EDIT_CreateIndirect, "HGBZQ1_e", ID_EDIT_6, 127, 281, 66, 29, 0, 0x6, 0 },
  { EDIT_CreateIndirect, "HGBZQ2_e", ID_EDIT_7, 127, 313, 66, 29, 0, 0x6, 0 },
  { EDIT_CreateIndirect, "HGBZQ3_e", ID_EDIT_8, 127, 345, 66, 29, 0, 0x6, 0 },
  { BUTTON_CreateIndirect, "ZQFX1_b", ID_BUTTON_9, 200, 281, 60, 29, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ZQFX2_b", ID_BUTTON_10, 200, 313, 60, 29, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "ZQFX3_b", ID_BUTTON_11, 200, 345, 60, 29, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WBCZQ1_t", ID_TEXT_6, 267, 281, 59, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WBCZQ2_t", ID_TEXT_7, 267, 314, 59, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "WBCZQ3_t", ID_TEXT_8, 267, 347, 59, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBZQ1_t", ID_TEXT_9, 327, 281, 59, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBZQ2_t", ID_TEXT_10, 327, 314, 59, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBZQ3_t", ID_TEXT_11, 327, 347, 59, 30, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "HGBXX1_b", ID_BUTTON_12, 440, 121, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBXX2_b", ID_BUTTON_13, 440, 153, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBXX3_b", ID_BUTTON_14, 440, 185, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBXX4_b", ID_BUTTON_15, 440, 217, 60, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBXX5_b", ID_BUTTON_16, 440, 249, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBXX1_t", ID_TEXT_12, 510, 121, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBXX2_t", ID_TEXT_13, 510, 153, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBXX3_t", ID_TEXT_14, 510, 185, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBXX4_t", ID_TEXT_15, 510, 217, 60, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGBXX5_t", ID_TEXT_16, 510, 249, 60, 30, 0, 0x0, 0 },
  
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 595, 90, 185, 280, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

static void _ButtonRedrawWidgetType_Callback2(WM_MESSAGE* pMsg)
{
	extern __IO MachRunPara_s	MachRunPara;
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,5);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_5:
					GUI_DispStringInRect("HGB60#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect("HGB120#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_7:
					GUI_DispStringInRect("HGB180#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_8:
					GUI_DispStringInRect("HGB校准系数",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_9:
					GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_10:
					GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
					
				case ID_BUTTON_11:
					GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_12:
					GUI_DispStringInRect("HGB20#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_13:
					GUI_DispStringInRect("HGB60#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_14:
					GUI_DispStringInRect("HGB120#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_15:
					GUI_DispStringInRect("HGB180#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_16:
					GUI_DispStringInRect("HGB240#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_17:
					GUI_DispStringInRect("WBC校准系数",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				default :break;
			}
        }
        else{
			if(WM_IsEnabled(pMsg->hWin)){
				//填充
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
				GUI_AA_FillRoundedRectEx(&Rect,5);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRectEx(&Rect,4);
				
				//设置字符前景和背景色
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			}else{
				//填充
				GUI_SetColor(GUI_WHITE);
				GUI_AA_FillRoundedRectEx(&Rect,5);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRectEx(&Rect,4);
				
				//设置字符前景和背景色
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(GUI_WHITE);
			}
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_5:
					GUI_DispStringInRect("HGB60#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect("HGB120#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_7:
					GUI_DispStringInRect("HGB180#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_8:
					GUI_DispStringInRect("HGB校准系数",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_9:
					GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_10:
					GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
					
				case ID_BUTTON_11:
					GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_12:
					GUI_DispStringInRect("HGB20#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_13:
					GUI_DispStringInRect("HGB60#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_14:
					GUI_DispStringInRect("HGB120#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_15:
					GUI_DispStringInRect("HGB180#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_16:
					GUI_DispStringInRect("HGB240#",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_17:
					GUI_DispStringInRect("WBC校准系数",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




static void _ButtonRedrawWidgetType_Callback1(WM_MESSAGE* pMsg)
{
	extern __IO MachRunPara_s	MachRunPara;
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("HGB精密度",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("HGB空白",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("WBC",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("数据上传",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				
				default :break;
			}
        }
        else{
			if(WM_IsEnabled(pMsg->hWin)){
				//填充
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
				GUI_AA_FillRoundedRectEx(&Rect,20);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRectEx(&Rect,19);
				
				//设置字符前景和背景色
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			}else{
				//填充
				GUI_SetColor(GUI_WHITE);
				GUI_AA_FillRoundedRectEx(&Rect,20);
				
				GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
				GUI_AA_DrawRoundedRectEx(&Rect,19);
				
				//设置字符前景和背景色
				GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
				GUI_SetBkColor(GUI_WHITE);
			}
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("HGB精密度",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("HGB空白",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("WBC",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("数据上传",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}




/*
* 设置控件回调函数，以及重绘控件
*/
static void _ButtonRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //返回按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback1);
    WM_InvalidateWindow(hItem);
	
	//HGB精密度按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback1);
    WM_InvalidateWindow(hItem);
	
	//HGB空白按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback1);
    WM_InvalidateWindow(hItem);
	
	//WBC按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback1);
    WM_InvalidateWindow(hItem);
	
	//数据上传按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback1);
    WM_InvalidateWindow(hItem);
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback2);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	static uint8_t MoveWindowFlag = 0;							//是否移动了窗口标志
	static uint8_t MoveWindowYValue = 0;						//移动窗口的Y轴偏移量
	
	GUI_RECT Rect;
	char Str[50];
	uint16_t U16Temp = 0;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
  {
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem,&HZ_SONGTI_24);
	WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"服务");
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);  
	TEXT_SetText(hItem,"> 性能检验");
    //
    // Initialization of 'HGBBZ1_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'HGBBZ2_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'HGBBZ3_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'HGBBZ1_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBBZ2_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBBZ3_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBXS_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	memset(Str,0,10);
	sprintf(Str,"%.2f",MachInfo.calibration.fHGB);
	TEXT_SetText(hItem,Str);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	memset(Str,0,10);
	sprintf(Str,"%.2f",MachInfo.calibration.fWBC);
	TEXT_SetText(hItem,Str);
    //
    // Initialization of 'WBCZQ1_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'WBCZQ2_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'WBCZQ3_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'HGBZQ1_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'HGBZQ2_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'HGBZQ3_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
    //
    // Initialization of 'WBCZQ1_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'WBCZQ2_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'WBCZQ3_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBZQ1_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBZQ2_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBZQ3_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBXX1_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBXX2_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBXX3_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBXX4_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'HGBXX5_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"0");
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
	MULTIEDIT_SetReadOnly(hItem,1);
	MULTIEDIT_SetBufferSize(hItem, 1024);
	MULTIEDIT_SetAutoScrollV(hItem, 1);
	MULTIEDIT_SetAutoScrollH(hItem, 0);
	MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, 0x001a1a1a);
	MULTIEDIT_SetBkColor(hItem, MULTIEDIT_CI_READONLY,0x00ffffff);
	MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
	MULTIEDIT_SetFont(hItem,&HZ_SONGTI_16);
	MULTIEDIT_ShowCursor(hItem,0);
	MULTIEDIT_SetInsertMode(hItem,0);
	MULTIEDIT_SetWrapWord(hItem);
	MULTIEDIT_AddText(hItem, "性能检验\r\n");
	U16Temp = sprintf(Str,"序列号：%s\r\n",MachInfo.labInfo.ucaMachineSN);
	Str[U16Temp] = '\0';
	MULTIEDIT_AddText(hItem,Str);
	
	//重绘按钮样式
	_ButtonRedrawWidgetType(pMsg);
	
	//设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
	
	//禁止掉桌面按键
	AbortPublishDestopButton();
	
	//按钮状态初始化
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_9));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_10));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_11));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_14));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_15));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_16));
	WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_17));
  }break;
	
	case WM_PAINT:
	{
		//画背景BMP图
		WM_GetClientRect(&Rect); 
		GUI_SetColor(GUI_WHITE);
		GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
	
		//===画HGB校准相关===
		GUI_SetColor(GUI_BLACK);
		GUI_SetBkColor(GUI_WHITE);
		GUI_SetFont(&HZ_SONGTI_16);
		Rect.x0 = 20;
		Rect.y0 = 65;
		Rect.x1 = 90;
		Rect.y1 = 85;
		GUI_DispStringInRect("HGB校准",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		//背景色填充
		GUI_SetColor(MachInfo.companyInfo.skin.title);
		GUI_AA_FillRoundedRect(20,90,265,216,4);
		GUI_SetColor(GUI_WHITE);
		GUI_FillRect(20,120,265,216);
		
		//外框线
		GUI_SetColor(GUI_BLACK);
		GUI_AA_DrawRoundedRect(20,90,265,216,4);
		
		//内框线
		GUI_DrawLine(20,120,265,120);
		GUI_DrawLine(20,152,265,152);
		GUI_DrawLine(20,184,265,184);
		GUI_DrawLine(55,90,55,216);
		GUI_DrawLine(125,90,125,216);
		GUI_DrawLine(195,90,195,216);
		
		GUI_SetColor(GUI_BLACK);
		GUI_SetBkColor(MachInfo.companyInfo.skin.title);
		GUI_SetFont(&HZ_SONGTI_16);
		Rect.x0 = 20;
		Rect.y0 = 90;
		Rect.x1 = 55;
		Rect.y1 = 120;
		GUI_DispStringInRect("序号",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 55;
		Rect.y0 = 90;
		Rect.x1 = 125;
		Rect.y1 = 120;
		GUI_DispStringInRect("HGB靶值",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 125;
		Rect.y0 = 90;
		Rect.x1 = 195;
		Rect.y1 = 120;
		GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 195;
		Rect.y0 = 90;
		Rect.x1 = 265;
		Rect.y1 = 120;
		GUI_DispStringInRect("HGB数据",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		GUI_SetBkColor(GUI_WHITE);
		Rect.x0 = 20;
		Rect.y0 = 120;
		Rect.x1 = 55;
		Rect.y1 = 152;
		GUI_DispStringInRect("1",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 20;
		Rect.y0 = 152;
		Rect.x1 = 55;
		Rect.y1 = 184;
		GUI_DispStringInRect("2",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 20;
		Rect.y0 = 184;
		Rect.x1 = 55;
		Rect.y1 = 216;
		GUI_DispStringInRect("3",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		//===HGB校准系数画框===
		GUI_SetColor(GUI_BLACK);
		GUI_AA_DrawRoundedRect(275,88,387,216,4);
		GUI_DrawLine(275,120,387,120);
		GUI_DrawLine(275,152,387,152);
		GUI_DrawLine(275,184,387,184);
		
		//===准确度===
		GUI_SetColor(GUI_BLACK);
		GUI_SetBkColor(GUI_WHITE);
		GUI_SetFont(&HZ_SONGTI_16);
		Rect.x0 = 20;
		Rect.y0 = 224;
		Rect.x1 = 90;
		Rect.y1 = 244;
		GUI_DispStringInRect("准确度",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		//背景色填充
		GUI_SetColor(MachInfo.companyInfo.skin.title);
		GUI_AA_FillRoundedRect(20,249,387,375,4);
		GUI_SetColor(GUI_WHITE);
		GUI_FillRect(20,279,387,375);
		
		//外框线
		GUI_SetColor(GUI_BLACK);
		GUI_AA_DrawRoundedRect(20,249,387,375,4);
		
		//内框线
		GUI_DrawLine(20,279,387,279);
		GUI_DrawLine(20,311,387,311);
		GUI_DrawLine(20,343,387,343);
		
		GUI_DrawLine(55,249,55,375);
		GUI_DrawLine(125,249,125,375);
		GUI_DrawLine(195,249,195,375);
		GUI_DrawLine(265,249,265,375);
		GUI_DrawLine(326,249,326,375);
		
		GUI_SetColor(GUI_BLACK);
		GUI_SetBkColor(MachInfo.companyInfo.skin.title);
		GUI_SetFont(&HZ_SONGTI_16);
		Rect.x0 = 20;
		Rect.y0 = 249;
		Rect.x1 = 55;
		Rect.y1 = 279;
		GUI_DispStringInRect("序号",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 55;
		Rect.y0 = 249;
		Rect.x1 = 125;
		Rect.y1 = 279;
		GUI_DispStringInRect("WBC靶值",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 125;
		Rect.y0 = 249;
		Rect.x1 = 195;
		Rect.y1 = 279;
		GUI_DispStringInRect("HGB靶值",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 195;
		Rect.y0 = 249;
		Rect.x1 = 265;
		Rect.y1 = 279;
		GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 265;
		Rect.y0 = 249;
		Rect.x1 = 326;
		Rect.y1 = 279;
		GUI_DispStringInRect("WBC数据",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 326;
		Rect.y0 = 249;
		Rect.x1 = 387;
		Rect.y1 = 279;
		GUI_DispStringInRect("HGB数据",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		GUI_SetBkColor(GUI_WHITE);
		Rect.x0 = 20;
		Rect.y0 = 279;
		Rect.x1 = 55;
		Rect.y1 = 311;
		GUI_DispStringInRect("1",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 20;
		Rect.y0 = 311;
		Rect.x1 = 55;
		Rect.y1 = 343;
		GUI_DispStringInRect("2",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 20;
		Rect.y0 = 343;
		Rect.x1 = 55;
		Rect.y1 = 387;
		GUI_DispStringInRect("3",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		//===HGB线性===
		GUI_SetColor(GUI_BLACK);
		GUI_SetBkColor(GUI_WHITE);
		GUI_SetFont(&HZ_SONGTI_16);
		Rect.x0 = 400;
		Rect.y0 = 65;
		Rect.x1 = 470;
		Rect.y1 = 85;
		GUI_DispStringInRect("HGB线性",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		//背景色填充
		GUI_SetColor(MachInfo.companyInfo.skin.title);
		GUI_AA_FillRoundedRect(400,90,575,280,4);
		GUI_SetColor(GUI_WHITE);
		GUI_FillRect(400,120,575,280);
		
		//外框线
		GUI_SetColor(GUI_BLACK);
		GUI_AA_DrawRoundedRect(400,90,575,280,4);
		
		//内框线
		GUI_DrawLine(400,120,575,120);
		GUI_DrawLine(400,152,575,152);
		GUI_DrawLine(400,184,575,184);
		GUI_DrawLine(400,216,575,216);
		GUI_DrawLine(400,248,575,248);
		
		GUI_DrawLine(435,90,435,280);
		GUI_DrawLine(505,90,505,280);
		
		GUI_SetColor(GUI_BLACK);
		GUI_SetBkColor(MachInfo.companyInfo.skin.title);
		GUI_SetFont(&HZ_SONGTI_16);
		Rect.x0 = 400;
		Rect.y0 = 90;
		Rect.x1 = 435;
		Rect.y1 = 120;
		GUI_DispStringInRect("序号",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 435;
		Rect.y0 = 90;
		Rect.x1 = 505;
		Rect.y1 = 120;
		GUI_DispStringInRect("分析",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 505;
		Rect.y0 = 90;
		Rect.x1 = 575;
		Rect.y1 = 120;
		GUI_DispStringInRect("HGB数据",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		GUI_SetBkColor(GUI_WHITE);
		Rect.x0 = 400;
		Rect.y0 = 120;
		Rect.x1 = 435;
		Rect.y1 = 152;
		GUI_DispStringInRect("1",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 400;
		Rect.y0 = 152;
		Rect.x1 = 435;
		Rect.y1 = 184;
		GUI_DispStringInRect("2",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 400;
		Rect.y0 = 184;
		Rect.x1 = 435;
		Rect.y1 = 216;
		GUI_DispStringInRect("3",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 400;
		Rect.y0 = 216;
		Rect.x1 = 435;
		Rect.y1 = 248;
		GUI_DispStringInRect("4",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		Rect.x0 = 400;
		Rect.y0 = 248;
		Rect.x1 = 435;
		Rect.y1 = 280;
		GUI_DispStringInRect("5",&Rect,GUI_TA_HCENTER | GUI_TA_VCENTER);
		
	}break;
	
	case WM_DELETE:
	{
		Disable_Motor_Task();
	}break;
	
	//键盘更新事件
	case WM_KEYBOARD_UPDATE:
	{
		char c;
		U16Temp = strlen(pMsg->Data.p);
		c = *((char*)pMsg->Data.p);

		//ASCII码
		if(U16Temp == 1){
			if((c>='0'&&c<='9') || c == '.'){
				GUI_StoreKeyMsg(c,1);
			}
		}
	}break;
  
	//键盘结束事件
	case WM_KEYBOARD_END:
		//判断是否移动了窗口，是，则还原
		if(MoveWindowFlag == 1){
			MoveWindowFlag = 0;
			WM_MoveWindow(pMsg->hWin,0,MoveWindowYValue);
		}
	break;
		
	//相关测试完毕后通知页面消息处理
	case WM_ZJ_TEST_OVER:
	{
		extern WM_HWIN DialogWin;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		DialogPageData.bmpType = BMP_OK;
		DialogPageData.confimButt = HAS_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"测试完毕");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
	}break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  {
		extern WM_HWIN CreatejiaoHuCheckPage(void);
		  
		//恢复桌面按键
		RecoverPublishDestopButton();
		  
		GUI_EndDialog(pMsg->hWin, 0);
		GUI_Exec();
		g_hActiveWin = CreatejiaoHuCheckPage();
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'HGBJMD_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB精密度测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_JMD);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'HGBKB_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB空白测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_KB);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'WBC_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入数字工装计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行WBC质检模式中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_WBC_TEST);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Upload_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'HGBBZ1_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
	  {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.hgb.jz[0].dest = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'HGBBZ2_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_1);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.hgb.jz[1].dest = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'HGBBZ3_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//移动窗口
			MoveWindowYValue = 30;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_2);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.hgb.jz[2].dest = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'HGBBZ1_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB校准1测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_JZ_1);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'HGBBZ2_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB校准2测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_JZ_2);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'HGBBZ3_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB校准3测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_JZ_3);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'HGBXS_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		float Tempf = 0.0f;
		uint16_t Temp1,Temp2;
		  
		hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_5);
		memset(Str,0,10);
		TEXT_GetText(hItem,Str,10);
		Tempf = atof(Str);
		Temp1 = Tempf*100;
		Temp2 = MachInfo.calibration.fHGB*100;
		if(Temp1 != Temp2){
			MachInfo.calibration.fHGB = Tempf;
			strncpy((char*)MachInfo.calibration.ucaHGB_CalibrationDate, (char*)MachRunPara.ucaLastestDateTime, DATE_TIME_LEN);
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_CALIBRATION,(uint8_t*)&MachInfo.calibration,sizeof(MachInfo.calibration));
		}
		
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12));
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'WBCZQ1_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//移动窗口
			MoveWindowYValue = 130;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);

			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_3);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.zqd[0].wbcDest.wbc = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'WBCZQ2_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//移动窗口
			MoveWindowYValue = 150;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);

			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_4);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.zqd[1].wbcDest.wbc = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_5: // Notifications sent by 'WBCZQ3_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//移动窗口
			MoveWindowYValue = 200;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);

			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_5);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.zqd[2].wbcDest.wbc = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_6: // Notifications sent by 'HGBZQ1_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//移动窗口
			MoveWindowYValue = 130;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);

			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_6);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.zqd[0].hgbDest = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_7: // Notifications sent by 'HGBZQ2_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//移动窗口
			MoveWindowYValue = 150;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);

			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_7);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.zqd[1].hgbDest = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_8: // Notifications sent by 'HGBZQ3_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;

			//移动窗口
			MoveWindowYValue = 200;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);

			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
		}
	  }break;
      case WM_NOTIFICATION_VALUE_CHANGED:
      {
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_8);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		MachRunPara.zj.zqd[2].hgbDest = atof(Str);
	  }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'ZQFX1_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'ZQFX2_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_11: // Notifications sent by 'ZQFX3_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_12: // Notifications sent by 'HGBXX1_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB线性1测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_XX_1);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_13: // Notifications sent by 'HGBXX2_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB线性2测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_XX_2);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_14: // Notifications sent by 'HGBXX3_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB线性3测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_XX_3);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_15: // Notifications sent by 'HGBXX4_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB线性4测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_XX_4);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_16: // Notifications sent by 'HGBXX5_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		extern WM_HWIN CreateDialogPage(void);
		extern WM_HWIN DialogWin;
		extern __IO osSemaphoreId_t xSema_Count_Key;
		CommonDialogPageData_s DialogPageData = {0};
		WM_MESSAGE pMsg;
		
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断是否放入了数字工装计数池
		if(ConutCell_Is_Exist() == RESET){
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			
			strcpy(DialogPageData.str,"请放入指定浓度的HGB计数池");

			pMsg.MsgId = WM_USER_DATA;
			pMsg.Data.p = &DialogPageData;
			WM_SendMessage(DialogWin,&pMsg);
			
			break;
		}
		
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = NULL;
		
		strcpy(DialogPageData.str,"正在执行HGB线性5测试中，请等待...");

		pMsg.MsgId = WM_USER_DATA;
		pMsg.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsg);
		
		//启动算法任务
		Enable_Algo_Task(TRUE);
		Set_CountMode(COUNT_MODE_ZJ_HGB_XX_5);
		osSemaphoreRelease(xSema_Count_Key);
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_17: // Notifications sent by 'WBC校准系数按钮'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
		float Tempf = 0.0f;
		uint16_t Temp1,Temp2;
		  
		hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_17);
		memset(Str,0,10);
		TEXT_GetText(hItem,Str,10);
		Tempf = atof(Str);
		Temp1 = Tempf*100;
		Temp2 = MachInfo.calibration.fWBC*100;
		if(Temp1 != Temp2){
			MachInfo.calibration.fWBC = Tempf;
			strncpy((char*)MachInfo.calibration.ucaWBC_CalibrationDate, (char*)MachRunPara.ucaLastestDateTime, DATE_TIME_LEN);
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_CALIBRATION,(uint8_t*)&MachInfo.calibration,sizeof(MachInfo.calibration));
		}
		
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
	  }break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateXNCheckPage
*/
WM_HWIN CreateXNCheckPage(void);
WM_HWIN CreateXNCheckPage(void) {
  WM_HWIN hWin;
	
	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Enable_Motor_Task(TRUE);
	Disable_Algo_Task();

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
