/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_DATE_TIME_SET_PAGE_ID + 0x00)
#define ID_BUTTON_0 (CONFIG_DATE_TIME_SET_PAGE_ID + 0x01)
#define ID_BUTTON_1 (CONFIG_DATE_TIME_SET_PAGE_ID + 0x02)
#define ID_LISTWHEEL_0 (CONFIG_DATE_TIME_SET_PAGE_ID + 0x04)
#define ID_LISTWHEEL_1 (CONFIG_DATE_TIME_SET_PAGE_ID + 0x05)
#define ID_LISTWHEEL_2 (CONFIG_DATE_TIME_SET_PAGE_ID + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

#define AGE_MAX_VALUE   149
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "dataTimeSetPage", ID_WINDOW_0, 180, 96, 440, 230, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "取消", ID_BUTTON_0, 0, 190, 220, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "确定", ID_BUTTON_1, 220, 190, 220, 40, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel1", ID_LISTWHEEL_0, 30, 60, 120, 90, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel2", ID_LISTWHEEL_1, 155, 60, 120, 90, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel3", ID_LISTWHEEL_2, 280, 60, 120, 90, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _DateTimeSetPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			switch(WM_GetId(pMsg->hWin)){
				//取消按钮
				case ID_BUTTON_0:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//确认按钮
				case ID_BUTTON_1:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			switch(WM_GetId(pMsg->hWin)){
				//取消按钮
				case ID_BUTTON_0:
					//画框
					GUI_SetColor(GUI_LIGHTGRAY);
					GUI_FillRect(Rect.x0,Rect.y0,Rect.x1,Rect.y1);
				
					//设置字符前景和背景色
					GUI_SetColor(BTN_CHAR_COLOR);
					GUI_SetBkColor(GUI_LIGHTGRAY);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				
					
				break;
				
				//确认按钮
				case ID_BUTTON_1:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



static void _DateTimeSetPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
	//取消按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _DateTimeSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
    //确定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _DateTimeSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}



static int _ListWheelOwnerDraw(const WIDGET_ITEM_DRAW_INFO * pDrawItemInfo)
{
    GUI_RECT aRect;
    
    switch (pDrawItemInfo->Cmd) {
    case WIDGET_ITEM_DRAW_OVERLAY:
        /* 获取控件坐标 ,注意这里x0，y0是控件左上角的相对坐标，即都为0，x1，y1是控件左下角的相对坐标*/
        aRect.x0 = pDrawItemInfo->x0;
        aRect.x1 = pDrawItemInfo->x1;
        aRect.y1 = pDrawItemInfo->y1;
        /* 画分割线 */
        GUI_SetColor(GUI_GRAY);
        GUI_DrawLine(aRect.x0, (aRect.y1) / 2-15, aRect.x1, (aRect.y1) / 2-15);
        GUI_DrawLine(aRect.x0, (aRect.y1) / 2+15, aRect.x1, (aRect.y1) / 2+15);
        break;
    default:
        return LISTWHEEL_OwnerDraw(pDrawItemInfo);
    }
    return 0;
        
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreatesysConfigPage(void);
	extern  __IO MachRunPara_s       MachRunPara;
	
	//当前设置日期时间的标志
	static uint8_t SetDateTimeFlag = 0;
	
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	uint8_t ListWheelIndex = 0;
	
	RTC_HYM8563Info_s RTCInfo = {0};
	
	uint16_t Year = 0;
	uint16_t Month = 0;
	uint16_t Day = 0;
	
	uint16_t Hour = 0;
	uint16_t Min = 0;
	uint16_t Sec = 0;
	
	uint16_t i = 0;
	char Str[6] = {0};
	
	uint8_t RunNianFlag = 0;				//为0表示选中的年份不是闰年，为1表示选中的是闰年
	static uint8_t MonthFlag = 0;				//为0表示选中的月份为28天，为1表示29天，为2表示30天，为3表示31天
  // USER END

  switch (pMsg->MsgId) {
	  
	case WM_INIT_DIALOG:
		//配置列表轮属性
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
		LISTWHEEL_SetLineHeight(hItem, 30);                                     //设置每项行高
		LISTWHEEL_SetSnapPosition(hItem, 30);                                   //设置吸入位置，像素为单位
		LISTWHEEL_SetFont(hItem, &GUI_Font24_ASCII);                            //设置字体
		LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);         //设置文本对齐方式
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, GUI_GRAY);            //设置未选中的文本颜色
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, MachInfo.companyInfo.skin.highlightKJNotSelect);              //设置选中的文本颜色
		LISTWHEEL_SetOwnerDraw(hItem, _ListWheelOwnerDraw);                     //设置外观回调函数 
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
		LISTWHEEL_SetLineHeight(hItem, 30);                                     
		LISTWHEEL_SetSnapPosition(hItem, 30);                                   
		LISTWHEEL_SetFont(hItem, &GUI_Font24_ASCII);                            
		LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);         
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, GUI_GRAY);            
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, MachInfo.companyInfo.skin.highlightKJNotSelect);              
		LISTWHEEL_SetOwnerDraw(hItem, _ListWheelOwnerDraw);  

		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
		LISTWHEEL_SetLineHeight(hItem, 30);                                     
		LISTWHEEL_SetSnapPosition(hItem, 30);                                   
		LISTWHEEL_SetFont(hItem, &GUI_Font24_ASCII);                            
		LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);         
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, GUI_GRAY);            
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, MachInfo.companyInfo.skin.highlightKJNotSelect);              
		LISTWHEEL_SetOwnerDraw(hItem, _ListWheelOwnerDraw);
	
		//重绘按钮样式
		_DateTimeSetPageRedrawWidgetType(pMsg);
	break;
	  
	case WM_PAINT:
		//先设置弹窗和背景为相同的透明度
		GUI_SetAlpha(30);
		GUI_SetColor(0x00525a4e);
		GUI_FillRectEx(&Rect);
		GUI_SetAlpha(0);

		//重绘弹窗为圆角矩形
		GUI_SetColor(0x00ffffff);
		GUI_AA_FillRoundedRectEx(&Rect,6);
	break;
	
	case WM_USER_DATA:
		//读取当前时间
		RTC_HYM8563GetTime(&RTCInfo);
		Year = 2000 + RTCInfo.year.bcd_h*10 + RTCInfo.year.bcd_l;
		Month = RTCInfo.month.bcd_h*10 + RTCInfo.month.bcd_l;
		Day = RTCInfo.day.bcd_h*10 + RTCInfo.day.bcd_l;
	
		Hour = RTCInfo.hour.bcd_h*10 + RTCInfo.hour.bcd_l;
		Min = RTCInfo.min.bcd_h*10 + RTCInfo.min.bcd_l;
		Sec = RTCInfo.sec.bcd_h*10 + RTCInfo.sec.bcd_l;
	
		//判断当前设置的年份是否为闰年
		if(((Year%4)!=0) || (((Year%4)==0) && ((Year%100)==0) && ((Year%400)!=0))){
			//非闰年
			RunNianFlag = 0;
		}else{
			//闰年
			RunNianFlag = 1;
		}
		
		//判断月份
		switch(Month){
			case 1:
			case 3:
			case 5:
			case 7:
			case 8:
			case 10:
			case 12:
				MonthFlag = 3;
			break;
			
			case 4:
			case 6:
			case 9:
			case 11:
				MonthFlag = 2;
			break;
			
			case 2:
				if(RunNianFlag == 1){
					MonthFlag = 1;
				}else{
					MonthFlag = 0;
				}
			break;
		}
	
		//根据调用此界面的按钮，给列表轮初始化不同数据源
		SetDateTimeFlag = pMsg->Data.v;
		switch(SetDateTimeFlag){
			
			case 0://设置界面，初始化日期
            case 3: //质控设定界面，有效期
                
				//初始化年份
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
				for(i = 0;i<100;i++){
					memset(Str,0,6);
					sprintf(Str,"%u",Year);
					LISTWHEEL_AddString(hItem,Str);
					Year = (Year+1)%2100;
					if(Year == 0){
						Year = 2000;
					}
				}
				
				//初始化月份
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
				for(i = 0;i<12;i++){
					memset(Str,0,6);
					sprintf(Str,"%02u",Month);
					LISTWHEEL_AddString(hItem,Str);
					Month = (Month+1)%13;
					if(Month == 0){
						Month = 1;
					}
				}
				
				//初始化天数
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
				for(i=0;i<31;i++){
					memset(Str,0,6);
					sprintf(Str,"%u",Day);
					LISTWHEEL_AddString(hItem,Str);
					Day = (Day+1)%32;
					if(Day == 0){
						Day = 1;
					}
				}
			break;
			
			//设置界面，初始化时间
			case 1:
				//初始化时
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
				for(i = 0;i<24;i++){
					memset(Str,0,6);
					sprintf(Str,"%02u",Hour);
					LISTWHEEL_AddString(hItem,Str);
					Hour = (Hour+1)%24;
				}
				
				//初始化分
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
				for(i = 0;i<60;i++){
					memset(Str,0,6);
					sprintf(Str,"%02u",Min);
					LISTWHEEL_AddString(hItem,Str);
					Min = (Min+1)%60;
				}
				
				//初始化秒
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
				for(i = 0;i<60;i++){
					memset(Str,0,6);
					sprintf(Str,"%u",Sec);
					LISTWHEEL_AddString(hItem,Str);
					Sec = (Sec+1)%60;
				}
			break;
                        
            case 2: //下一样本测试界面，出生年月 
            case 4: //病人信息，出生年月 
            {
                uint16_t usTempYear = 0;
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
                usTempYear = Year - AGE_MAX_VALUE; 
				for(i = 0;i<150;i++){
					memset(Str,0,6);
					sprintf(Str,"%u",usTempYear);
					LISTWHEEL_AddString(hItem,Str);
					usTempYear++;//Year = (Year+1)%2100;
//					if(usTempYear == 0){
//						usTempYear = 2000;
//					}
				}
                
                //
                uint16_t usDiff = 0;
                if(2 == SetDateTimeFlag)
                {
                    //下一样本
                    if(AGE_UNIT_YEAR == MachRunPara.tNextSample.eAgeUnit)
                    {
                        usDiff = AGE_MAX_VALUE - MachRunPara.tNextSample.ucAge;
                    }else{
                        usDiff = 0;
                    }
                }else if(4 == SetDateTimeFlag){
                    //病人信息 
                    extern __IO Patient_Info_t g_tPatinet_Info;
                    if(AGE_UNIT_YEAR == g_tPatinet_Info.eAgeUnit)
                    {
                        usDiff = AGE_MAX_VALUE - g_tPatinet_Info.ucAge;
                    }else{
                        usDiff = 0;
                    }
                }
                LISTWHEEL_SetSel(hItem, usDiff);
                LISTWHEEL_SetPos(hItem, usDiff); 
               
				
				//初始化月份
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
				for(i = 0;i<12;i++){
					memset(Str,0,6);
					sprintf(Str,"%02u",Month);
					LISTWHEEL_AddString(hItem,Str);
					Month = (Month+1)%13;
					if(Month == 0){
						Month = 1;
					}
				}
				
				//初始化天数
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
				for(i = 0;i<31;i++){
					memset(Str,0,6);
					sprintf(Str,"%u",Day);
					LISTWHEEL_AddString(hItem,Str);
					Day = (Day+1)%32;
					if(Day == 0){
						Day = 1;
					}
				}
            }
			break;
                
			default :break;
		}
	break;
	  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'cel_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        if(CONFIG_SYS_PAGE_ID == Get_Cur_MenuID())
        {   //系统设置界面
            g_hActiveWin = CreatesysConfigPage();
        }else if(GUI_WINDOW_NEXT_SAMPLE_ID == Get_Cur_MenuID()){
            //下一样测试界面
            g_hActiveWin = CreateNextSample_Window();
            //更新
            WM_SendMessageNoPara(g_hActiveWin, WM_NEXT_SAMPLE_UPDATE);
        }else if(GUI_WINDOW_QC_SET_ID == Get_Cur_MenuID()){
            //质控设定界面
            g_hActiveWin = QC_Set_CreateWindow();
        }else if(GUI_WINDOW_ANALYSIS_ID == Get_Cur_MenuID() || GUI_WINDOW_LIST_REVIEW_ID == Get_Cur_MenuID() || GUI_WINDOW_RESULT_INFO_ID == Get_Cur_MenuID()){
             //病人信息
             g_hActiveWin = CreatePatient_Info_Window();
         }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'confim_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//读取当前时间
		RTC_HYM8563GetTime(&RTCInfo);
	  
		switch(SetDateTimeFlag){
			//设置界面，设置日期
			case 0:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Year = atoi(Str);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Month = atoi(Str);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Day = atoi(Str);
				
				RTCInfo.month.c = 0;
				RTCInfo.year.bcd_h = (Year-2000)/10;
				RTCInfo.year.bcd_l = (Year-2000)%10;
				
				RTCInfo.month.bcd_h = Month/10;
				RTCInfo.month.bcd_l = Month%10;
				
				RTCInfo.day.bcd_h = Day/10;
				RTCInfo.day.bcd_l = Day%10;
				
				RTC_HYM8563SetTime(&RTCInfo);
			break;
			
			//设置界面，设置时间
			case 1:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Hour = atoi(Str);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Min = atoi(Str);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Sec = atoi(Str);
				
				RTCInfo.hour.bcd_h = Hour/10;
				RTCInfo.hour.bcd_l = Hour%10;
				
				RTCInfo.min.bcd_h = Min/10;
				RTCInfo.min.bcd_l = Min%10;
				
				RTCInfo.sec.bcd_h = Sec/10;
				RTCInfo.sec.bcd_l = Sec%10;
				
				RTC_HYM8563SetTime(&RTCInfo);
			break;
            case 2: //下一样本测试界面，出生年月 
            case 3: //质控设定界面，有效期
            case 4: //病人信息界面，出生年月
            {
                 //
                uint16_t usYear = 0, usCurYear = 0, usCurMonth = 0, usCurDay = 0;
                char buffer[10] = {0}, Flag = 0;
                
                hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Year = atoi(Str);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Month = atoi(Str);
			
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
				ListWheelIndex = LISTWHEEL_GetSel(hItem);
				memset(Str,0,6);
				LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
				Day = atoi(Str);
                
                //判断选择日期是否超过当前时间, 超过了不做处理            
                usCurYear = 2000 + RTCInfo.year.bcd_h*10 + RTCInfo.year.bcd_l;
                usCurMonth = RTCInfo.month.bcd_h*10 + RTCInfo.month.bcd_l;
                usCurDay = RTCInfo.day.bcd_h*10 + RTCInfo.day.bcd_l;
                if(usCurYear > Year)
                {
                   Flag = 1;
                }else{
                    if((usCurYear == Year) && (usCurMonth >= Month))
                    {
                        Flag = 1;
                    }else{
                        if(((usCurYear == Year) && (usCurMonth == Month) && (usCurDay >= Day)))
                        {
                            Flag = 1;
                        }
                    }
                }
                    
                //
                if(Get_Cur_MenuID() == GUI_WINDOW_NEXT_SAMPLE_ID)
                {
                    //
                    if(1 == Flag)
                    {
                        //下一样本测试界面，出生年月 
                        memset((void*)MachRunPara.tNextSample.ucaBirthDay, 0, sizeof(MachRunPara.tNextSample.ucaBirthDay));
                        sprintf((char*)MachRunPara.tNextSample.ucaBirthDay, "%d/%d/%d", Year, Month, Day);
                        //根据出生年，更新年龄
                        memmove(buffer, (const char*)MachRunPara.tNextSample.ucaBirthDay, 4);
                        usYear = atoi(buffer);
                        MachRunPara.tNextSample.ucAge = usCurYear-usYear;
                        //从出生年月--》倒推年龄（只限于年文单位）
                        MachRunPara.tNextSample.eAgeUnit = AGE_UNIT_YEAR;
                    
                    }
                }else if(Get_Cur_MenuID() == GUI_WINDOW_QC_SET_ID){
                    //质控设定界面，有效期
                    extern __IO uint8_t gs_ucFileNum_ListVew_Index;
                    if(1 == Flag)
                    {
                        memset((void*)MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].ucaValidDate, 0, sizeof(MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].ucaValidDate));
                        sprintf((char*)MachRunPara.taQC_SetInfo[gs_ucFileNum_ListVew_Index].ucaValidDate, "%d/%d/%d", Year, Month, Day);
                    }
                
                }else if(GUI_WINDOW_ANALYSIS_ID == Get_Cur_MenuID() || GUI_WINDOW_LIST_REVIEW_ID == Get_Cur_MenuID() || GUI_WINDOW_RESULT_INFO_ID == Get_Cur_MenuID()){
                    //病人信息，出生年月
                    extern __IO Patient_Info_t g_tPatinet_Info;
                    if(1 == Flag)
                    {
                        //下一样本测试界面，出生年月 
                        memset((void*)g_tPatinet_Info.ucaBirthDay, 0, sizeof(g_tPatinet_Info.ucaBirthDay));
                        sprintf((char*)g_tPatinet_Info.ucaBirthDay, "%d/%d/%d", Year, Month, Day);
                        //根据出生年，更新年龄
                        memmove(buffer, (const char*)g_tPatinet_Info.ucaBirthDay, 4);
                        usYear = atoi(buffer);
                        g_tPatinet_Info.ucAge = usCurYear-usYear;
                        g_tPatinet_Info.eAgeUnit = AGE_UNIT_YEAR;
                    }
                }
            }
            break;
			default:break;
		}
        
        //
        GUI_EndDialog(pMsg->hWin, 0);
        if(CONFIG_SYS_PAGE_ID == Get_Cur_MenuID())
        {   //系统设置界面
            RTC_Read((uint8_t*)MachRunPara.ucaLastestDateTime, DATE_TIME_LEN);
            WM_SendMessageNoPara(WM_HBKWIN, WM_PUBLIC_UPDATE);
            g_hActiveWin = CreatesysConfigPage();
        }else if(GUI_WINDOW_NEXT_SAMPLE_ID == Get_Cur_MenuID()){
            //下一样本
            g_hActiveWin = CreateNextSample_Window();
            //更新
            WM_SendMessageNoPara(g_hActiveWin, WM_NEXT_SAMPLE_UPDATE);
        }else if(GUI_WINDOW_QC_SET_ID == Get_Cur_MenuID()){
            //质控设定界面
            g_hActiveWin = QC_Set_CreateWindow();
            WM_SendMessageNoPara(g_hActiveWin, WM_PAINT);
         }else if(GUI_WINDOW_ANALYSIS_ID == Get_Cur_MenuID() || GUI_WINDOW_LIST_REVIEW_ID == Get_Cur_MenuID() || GUI_WINDOW_RESULT_INFO_ID == Get_Cur_MenuID()){
             //病人信息
             g_hActiveWin = CreatePatient_Info_Window();
             WM_SendMessageNoPara(g_hActiveWin, WM_PATIENT_INFO_UPDATE);
         }
		
//		//实时更新日期时间显示
//		RTC_Read((uint8_t*)MachRunPara.ucaLastestDateTime, DATE_TIME_LEN);
//		WM_SendMessageNoPara(WM_HBKWIN, WM_PUBLIC_UPDATE);
//		
//		GUI_EndDialog(pMsg->hWin, 0);
//		g_hActiveWin = CreatesysConfigPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_0: // Notifications sent by 'Listwheel1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
		ListWheelIndex = LISTWHEEL_GetPos(hItem);				//获取吸入项的位置的索引
		LISTWHEEL_SetSel(hItem, ListWheelIndex);				//设置当前选择的项
	  
		//列表轮为设置日期
		if(SetDateTimeFlag != 1){
			uint8_t ListWheelIndexTemp = 0;
			
			memset(Str,0,6);
			LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
			Year = atoi(Str);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
			ListWheelIndex = LISTWHEEL_GetPos(hItem);	
			memset(Str,0,6);
			LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
			Month = atoi(Str);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
			ListWheelIndex = LISTWHEEL_GetPos(hItem);	
			memset(Str,0,6);
			LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
			Day = atoi(Str);
			
			//判断当前设置的年份是否为闰年
			if(((Year%4)!=0) || (((Year%4)==0) && ((Year%100)==0) && ((Year%400)!=0))){
				//非闰年
				RunNianFlag = 0;
			}else{
				//闰年
				RunNianFlag = 1;
			}
			
			//判断月份
			switch(Month){
				case 1:
				case 3:
				case 5:
				case 7:
				case 8:
				case 10:
				case 12:
					MonthFlag = 3;
				break;
				
				case 4:
				case 6:
				case 9:
				case 11:
					MonthFlag = 2;
				break;
				
				case 2:
					if(RunNianFlag == 1){
						MonthFlag = 1;
					}else{
						MonthFlag = 0;
					}
				break;
			}
			
			ListWheelIndexTemp = ListWheelIndex;
			
			switch(MonthFlag){
				//28
				case 0:
				{
					switch(Day){
						case 29:ListWheelIndexTemp = (ListWheelIndexTemp+3)%31;break;
						case 30:ListWheelIndexTemp = (ListWheelIndexTemp+2)%31;break;
						case 31:ListWheelIndexTemp = (ListWheelIndexTemp+1)%31;break;
						default :break;
					}
				}
				break;
				
				//29
				case 1:
				{
					switch(Day){
						case 30:ListWheelIndexTemp = (ListWheelIndexTemp+2)%31;break;
						case 31:ListWheelIndexTemp = (ListWheelIndexTemp+1)%31;break;
						default :break;
					}
				}
				break;
				
				//30
				case 2:
				{
					switch(Day){
						case 31:ListWheelIndexTemp = (ListWheelIndexTemp+1)%31;break;
						default :break;
					}
				}
				break;
				default :break;
			}
			
			if(ListWheelIndexTemp != ListWheelIndex){
				LISTWHEEL_MoveToPos(hItem, ListWheelIndexTemp);
				LISTWHEEL_SetSel(hItem, ListWheelIndexTemp);				
			}
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_1: // Notifications sent by 'Listwheel2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_1);
		ListWheelIndex = LISTWHEEL_GetPos(hItem);				//获取吸入项的位置的索引
		LISTWHEEL_SetSel(hItem, ListWheelIndex);				//设置当前选择的项
	  
		//列表轮为设置日期
		if(SetDateTimeFlag != 1){
			uint8_t ListWheelIndexTemp = 0;
			
			memset(Str,0,6);
			LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
			Month = atoi(Str);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_0);
			ListWheelIndex = LISTWHEEL_GetPos(hItem);	
			memset(Str,0,6);
			LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
			Year = atoi(Str);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
			ListWheelIndex = LISTWHEEL_GetPos(hItem);	
			memset(Str,0,6);
			LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
			Day = atoi(Str);
			
			//判断当前设置的年份是否为闰年
			if(((Year%4)!=0) || (((Year%4)==0) && ((Year%100)==0) && ((Year%400)!=0))){
				//非闰年
				RunNianFlag = 0;
			}else{
				//闰年
				RunNianFlag = 1;
			}
			
			//判断月份
			switch(Month){
				case 1:
				case 3:
				case 5:
				case 7:
				case 8:
				case 10:
				case 12:
					MonthFlag = 3;
				break;
				
				case 4:
				case 6:
				case 9:
				case 11:
					MonthFlag = 2;
				break;
				
				case 2:
					if(RunNianFlag == 1){
						MonthFlag = 1;
					}else{
						MonthFlag = 0;
					}
				break;
			}
			
			ListWheelIndexTemp = ListWheelIndex;
			
			switch(MonthFlag){
				//28
				case 0:
				{
					switch(Day){
						case 29:ListWheelIndexTemp = (ListWheelIndexTemp+3)%31;break;
						case 30:ListWheelIndexTemp = (ListWheelIndexTemp+2)%31;break;
						case 31:ListWheelIndexTemp = (ListWheelIndexTemp+1)%31;break;
						default :break;
					}
				}
				break;
				
				//29
				case 1:
				{
					switch(Day){
						case 30:ListWheelIndexTemp = (ListWheelIndexTemp+2)%31;break;
						case 31:ListWheelIndexTemp = (ListWheelIndexTemp+1)%31;break;
						default :break;
					}
				}
				break;
				
				//30
				case 2:
				{
					switch(Day){
						case 31:ListWheelIndexTemp = (ListWheelIndexTemp+1)%31;break;
						default :break;
					}
				}
				break;
				default :break;
			}
			
			if(ListWheelIndexTemp != ListWheelIndex){
				LISTWHEEL_MoveToPos(hItem, ListWheelIndexTemp);
				LISTWHEEL_SetSel(hItem, ListWheelIndexTemp);				
			}
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_2: // Notifications sent by 'Listwheel3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTWHEEL_2);
		ListWheelIndex = LISTWHEEL_GetPos(hItem);				//获取吸入项的位置的索引
		
		//列表轮为设置日期
		if(SetDateTimeFlag != 1){
			memset(Str,0,6);
			LISTWHEEL_GetItemText(hItem,ListWheelIndex,Str,6);
			Day = atoi(Str);
			
			switch(MonthFlag){
				//28
				case 0:
				{
					switch(Day){
						case 29:ListWheelIndex = (ListWheelIndex+3)%31;break;
						case 30:ListWheelIndex = (ListWheelIndex+2)%31;break;
						case 31:ListWheelIndex = (ListWheelIndex+1)%31;break;
						default :break;
					}
				}
				break;
				
				//29
				case 1:
				{
					switch(Day){
						case 30:ListWheelIndex = (ListWheelIndex+2)%31;break;
						case 31:ListWheelIndex = (ListWheelIndex+1)%31;break;
						default :break;
					}
				}
				break;
				
				//30
				case 2:
				{
					switch(Day){
						case 31:ListWheelIndex = (ListWheelIndex+1)%31;break;
						default :break;
					}
				}
				break;
				default :break;
			}
		}
	  
		LISTWHEEL_MoveToPos(hItem, ListWheelIndex);
		LISTWHEEL_SetSel(hItem, ListWheelIndex);				//设置当前选择的项
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatedataTimeSetPage
*/
WM_HWIN CreatedataTimeSetPage(void);
WM_HWIN CreatedataTimeSetPage(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin);
	Public_Hide_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
