/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_Debug_PAGE_ID + 0x00)
#define ID_TEXT_0 (CONFIG_Debug_PAGE_ID + 0x01)
#define ID_TEXT_1 (CONFIG_Debug_PAGE_ID + 0x02)
#define ID_TEXT_2 (CONFIG_Debug_PAGE_ID + 0x03)
#define ID_TEXT_3 (CONFIG_Debug_PAGE_ID + 0x04)
#define ID_TEXT_4 (CONFIG_Debug_PAGE_ID + 0x05)
#define ID_TEXT_5 (CONFIG_Debug_PAGE_ID + 0x06)
#define ID_TEXT_6 (CONFIG_Debug_PAGE_ID + 0x08)
#define ID_EDIT_0 (CONFIG_Debug_PAGE_ID + 0x09)
#define ID_BUTTON_0 (CONFIG_Debug_PAGE_ID + 0x0A)
#define ID_BUTTON_1 (CONFIG_Debug_PAGE_ID + 0x0B)
#define ID_EDIT_1 (CONFIG_Debug_PAGE_ID + 0x0C)
#define ID_BUTTON_2 (CONFIG_Debug_PAGE_ID + 0x0D)
#define ID_BUTTON_3 (CONFIG_Debug_PAGE_ID + 0x0E)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "debugPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET", ID_TEXT_0, 30, 15, 95, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> Debug", ID_TEXT_1, 125, 20, 140, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CountDelay", ID_TEXT_2, 300, 105, 120, 22, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CountReuse", ID_TEXT_3, 290, 152, 126, 22, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "DebugWBC", ID_TEXT_4, 220, 217, 200, 22, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Count", ID_TEXT_5, 349, 260, 70, 22, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "min_t", ID_TEXT_6, 525, 105, 35, 22, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "delayTime_e", ID_EDIT_0, 428, 97, 94, 32, 0, 0x8, 0 },
  { BUTTON_CreateIndirect, "reuse_b", ID_BUTTON_0, 428, 148, 58, 32, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "gzTest_b", ID_BUTTON_1, 428, 210, 58, 32, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "runCount_e", ID_EDIT_1, 428, 253, 94, 32, 0, 0x8, 0 },
  { BUTTON_CreateIndirect, "Cel", ID_BUTTON_2, 265, 330, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Confim", ID_BUTTON_3, 415, 330, 120, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _DebugPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	
	extern __IO MachRunPara_s	MachRunPara;
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			switch(WM_GetId(pMsg->hWin)){
				//计数池重复使用按钮
				case ID_BUTTON_0:
					
				break;
				
				//工装计数池测试WBC
				case ID_BUTTON_1:
					
				break;
				
				case ID_BUTTON_2:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_AA_FillRoundedRectEx(&Rect,20);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_AA_FillRoundedRectEx(&Rect,20);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			switch(WM_GetId(pMsg->hWin)){
				//计数池重复使用按钮
				case ID_BUTTON_0:
					if(MachRunPara.psDebugInfo.jscReuseFlag == 0){
                        Show_BK_BMP(BK_FILE, BK_PICTURE_SET_SwitchClose, Rect.x0,Rect.y0);
                        
					}else{
                        Show_BK_BMP(BK_FILE, BK_PICTURE_SET_SwitchOpen, Rect.x0,Rect.y0);
					}
				break;
				
				//工装计数池测试WBC
				case ID_BUTTON_1:
					if(MachRunPara.psDebugInfo.gzTestWBCFlag == 0){
                        Show_BK_BMP(BK_FILE, BK_PICTURE_SET_SwitchClose, Rect.x0,Rect.y0);
					}else{
                        Show_BK_BMP(BK_FILE, BK_PICTURE_SET_SwitchOpen, Rect.x0,Rect.y0);
					}
				break;
				
				case ID_BUTTON_2:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRectEx(&Rect,20);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,19);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRectEx(&Rect,20);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,19);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}			
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



/*
*   调试界面，发送信息给后端接口
*/
static ErrorCode_e DebugPage_Send_Msg(void)
{
    extern __IO MachRunPara_s MachRunPara;
    //uint8_t ucaSendBuffer[UI_TO_BACKEND_MSG_BUFFER_LEN] = {0};
    ParaSetDebugInfo_Msg_t tParaSetDebugInfo_Msg = {0};
    ParaSetDebugInfo_Msg_t *pMsg = &tParaSetDebugInfo_Msg;//(ParaSetDebugInfo_Msg_t*)ucaSendBuffer;
    //head
    pMsg->tMsgHead.usCmd = CMD_SET_DEBUG;
    pMsg->tMsgHead.eErrorCode = ERROR_CODE_SUCCESS;
    //body
    pMsg->sParaSetDebugInfo.countDelayTime    = MachRunPara.psDebugInfo.countDelayTime;
    pMsg->sParaSetDebugInfo.gzTestCount       = MachRunPara.psDebugInfo.gzTestCount;
    pMsg->sParaSetDebugInfo.gzTestWBCFlag     = MachRunPara.psDebugInfo.gzTestWBCFlag;
    pMsg->sParaSetDebugInfo.jscReuseFlag      = MachRunPara.psDebugInfo.jscReuseFlag;

    //发送消息给后端
    if(osOK != UI_Put_Msg((uint8_t*)&tParaSetDebugInfo_Msg))//ucaSendBuffer)) //osOk != ...
    {
        LOG_Error("Send Msg Fail");
        return ERROR_CODE_FAILURE;
    }
    
    return ERROR_CODE_SUCCESS;
}

/*
* 设置控件回调函数，以及重绘控件
*/
static void _DebugPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
	//计数池重复使用按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _DebugPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//工装计数池测试wbc按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _DebugPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
    //取消按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _DebugPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//确定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _DebugPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
    
  // USER START (Optionally insert additional variables)
	extern char* BKBmaDataBuf;
	extern __IO MachRunPara_s	MachRunPara;
	
	extern GUI_HMEM hMemSwitchOpenBmp;
	extern GUI_HMEM hMemSwitchCloseBmp;
	
//	static uint8_t KeyBoardUseOnceFlag = 0;						//是否已经唤出键盘标志
	static uint8_t MoveWindowFlag = 0;							//是否移动了窗口标志
	static uint8_t MoveWindowYValue = 0;						//移动窗口的Y轴偏移量
	
	char Buf[10] = {0};
	uint32_t U32Temp = 0;
	char c;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Set[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_Debug[MachInfo.systemSet.eLanguage]);
  
    //
    // Initialization of 'delayTime_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00333333));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_CountDelay[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'reuse_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00333333));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_CountReuse[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'gzTest_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00333333));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_DebugWBC[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'runCount_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00333333));
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_Count[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'min_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    //TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00B3B3B3));
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00333333));
    TEXT_SetText(hItem, "S");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16_ASCII);
    //
    // Initialization of 'delayTime_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    EDIT_SetMaxLen(hItem, 5);
	EDIT_EnableBlink(hItem,500,1);
	U32Temp = sprintf(Buf,"%u",MachRunPara.psDebugInfo.countDelayTime);
	Buf[U32Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    WM_DisableWindow(hItem);
    //
    // Initialization of 'runCount_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
	EDIT_EnableBlink(hItem,500,1);
	U32Temp = sprintf(Buf,"%u",MachRunPara.psDebugInfo.gzTestCount);
	Buf[U32Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    WM_DisableWindow(hItem);
//	if(MachRunPara.psDebugInfo.gzTestWBCFlag == 0){
//		WM_DisableWindow(hItem);
//	}else{
//		WM_EnableWindow(hItem);
//	}
	
	//重绘按钮样式
	_DebugPageRedrawWidgetType(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    // USER END
    break;
	
  case WM_PAINT:
	//画背景BMP图
	//GUI_BMP_Draw(BKBmaDataBuf,1,0);
    //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
    
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
  
//  GUI_RECT Rect;

	//画线
	GUI_SetColor(0x009ea0a2);
	GUI_DrawHLine(54,8,790);
  
	//画工装计数池测试边框
	GUI_SetColor(0x00cbcbcb);
	GUI_DrawRoundedRect(219,188,579,304,4);
  break;
  
  //键盘更新事件
  case WM_KEYBOARD_UPDATE:
	
	hItem = WM_GetFocusedWindow();
	U32Temp = strlen(pMsg->Data.p);
	c = *((char*)pMsg->Data.p);
	
	//ASCII码
	if(U32Temp == 1){
		//只能输入数字
		if((c>='0'&&c<='9')){
			GUI_StoreKeyMsg(c,1);
		}
	}
  break;
  
  //键盘结束事件
  case WM_KEYBOARD_END:
//	  if(KeyBoardUseOnceFlag == 1){
//		KeyBoardUseOnceFlag = 0;
//	  }
	  
	  //判断是否移动了窗口，是，则还原
	  if(MoveWindowFlag == 1){
		MoveWindowFlag = 0;
		WM_MoveWindow(pMsg->hWin,0,MoveWindowYValue);
	  }
	  
//	WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
//	WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
//	WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
//	WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));
//	WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
//	WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));
  break;
	  
	case WM_DELETE:
		//释放图标内存
//		GUI_ALLOC_Free(hMemSwitchOpenBmp);
//		GUI_ALLOC_Free(hMemSwitchCloseBmp);
	break;

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'delayTime_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
//		if(KeyBoardUseOnceFlag == 0){
//			KeyBoardUseOnceFlag = 1;
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
			
			//失能其他编辑框
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));
//		}
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'reuse_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {         
//          hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);    //gz
//          if(WM_IsEnabled(hItem))
//          {
//            MachRunPara.psDebugInfo.jscReuseFlag ^= 1;
//          }
//          //disable gz btn
//          WM_DisableWindow(hItem);
//          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);    //gz
//          WM_DisableWindow(hItem);
          

          if(MachRunPara.psDebugInfo.gzTestWBCFlag == 0)
          {
              MachRunPara.psDebugInfo.jscReuseFlag ^= 1;  
              //
              if(MachRunPara.psDebugInfo.jscReuseFlag == 1)
              {
                 hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);    //gz
                 WM_DisableWindow(hItem);
                  
                 //delay time
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);    //reuse
                WM_EnableWindow(hItem);
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0); //edit delay time
                U32Temp = sprintf(Buf,"%u", MachRunPara.psDebugInfo.countDelayTime);
                Buf[U32Temp] = '\0';
                EDIT_SetText(hItem, Buf);  
              
              }else{
                 hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);    //gz
                 WM_EnableWindow(hItem);
              }
          }
          
//        //发送消息给后台，更新计数模式
//        DebugPage_Send_Msg();

      }
      break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'gzTest_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
            
           
          if(MachRunPara.psDebugInfo.jscReuseFlag == 0)
          {
              MachRunPara.psDebugInfo.gzTestWBCFlag ^= 1;  
              if(MachRunPara.psDebugInfo.gzTestWBCFlag == 1)
              {
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);    //edit re count
                WM_DisableWindow(hItem);
                //
                WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));
                MachRunPara.psDebugInfo.gzTestCount = 1;
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
                U32Temp = sprintf(Buf,"%u",MachRunPara.psDebugInfo.gzTestCount);
                Buf[U32Temp] = '\0';
                EDIT_SetText(hItem, Buf);  
              }else{
                hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);    //edit re count
                WM_EnableWindow(hItem);
              }                 
          }

//        //发送消息给后台，更新计数模式
//        DebugPage_Send_Msg();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'runCount_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
//		if(KeyBoardUseOnceFlag == 0){
//			KeyBoardUseOnceFlag = 1;
        
        if(0 == MoveWindowFlag)
        {
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 90;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
			
			//失能其他
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));
        }
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
//		}
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'cel_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'confim_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//保存参数
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U32Temp = atoi(Buf);
		MachRunPara.psDebugInfo.countDelayTime = U32Temp;
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U32Temp = atoi(Buf);
		MachRunPara.psDebugInfo.gzTestCount = U32Temp;
	  
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
      
        //发送消息给后台，更新计数模式
        DebugPage_Send_Msg();
        //
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatedebugPage
*/
WM_HWIN CreatedebugPage(void);
WM_HWIN CreatedebugPage(void) {
  WM_HWIN hWin;
	
	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
