/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "CAT_iot.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_FUZHU_PAGE_ID + 0x00)
#define ID_TEXT_0 (CONFIG_FUZHU_PAGE_ID + 0x01)
#define ID_TEXT_1 (CONFIG_FUZHU_PAGE_ID + 0x02)
#define ID_BUTTON_0 (CONFIG_FUZHU_PAGE_ID + 0x03)
#define ID_BUTTON_1 (CONFIG_FUZHU_PAGE_ID + 0x04)
#define ID_BUTTON_2 (CONFIG_FUZHU_PAGE_ID + 0x05)
#define ID_BUTTON_3 (CONFIG_FUZHU_PAGE_ID + 0x06)
#define ID_BUTTON_4 (CONFIG_FUZHU_PAGE_ID + 0x07)
#define ID_BUTTON_5 (CONFIG_FUZHU_PAGE_ID + 0x08)
#define ID_BUTTON_6 (CONFIG_FUZHU_PAGE_ID + 0x09)
#define ID_BUTTON_7 (CONFIG_FUZHU_PAGE_ID + 0x0a)
#define ID_BUTTON_8 (CONFIG_FUZHU_PAGE_ID + 0x0b)
#define ID_BUTTON_9 (CONFIG_FUZHU_PAGE_ID + 0x0c)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "FuzhuConfigPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET", ID_TEXT_0, 30, 15, 95, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> ASSIST", ID_TEXT_1, 125, 20, 150, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "EXIT", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LOGO", ID_BUTTON_1, 60, 140, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "U_UPDATE", ID_BUTTON_2, 60, 200, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SET_SKIN", ID_BUTTON_3, 60, 260, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "UPDATE P_MAIN", ID_BUTTON_4, 315, 140, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "UPDATE P_BOOT", ID_BUTTON_5, 315, 200, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "UPDATE P_UI", ID_BUTTON_6, 315, 260, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "UPDATE T_MAIN", ID_BUTTON_7, 580, 140, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "UPDATE T_BOOT", ID_BUTTON_8, 580, 200, 160, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "RES3", ID_BUTTON_9, 580, 260, 160, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _FuzhuSetPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect(g_ucaLng_SET_CompanySwitch[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect(g_ucaLng_SET_UUpdate[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect(g_ucaLng_SET_SetSkin[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateMain[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateBoot[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateUI[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_7:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateMain[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_8:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateBoot[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_9:
					GUI_DispStringInRect(g_ucaLng_SET_RES3[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//画框
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRectEx(&Rect,19);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect(g_ucaLng_SET_CompanySwitch[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect(g_ucaLng_SET_UUpdate[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect(g_ucaLng_SET_SetSkin[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateMain[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateBoot[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateUI[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_7:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateMain[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_8:
					GUI_DispStringInRect(g_ucaLng_SET_UpdateBoot[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_9:
					GUI_DispStringInRect(g_ucaLng_SET_RES3[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
    break;
    }
}




/*
* 设置控件回调函数，以及重绘控件
*/
static void _FuzhuSetPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //返回按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//切换LOGO按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);  
    WM_SetCallback(hItem, _FuzhuSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int NCode;
  int Id;
  GUI_RECT Rect;
    
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreatelogoSwitchPage(void);
	extern WM_HWIN CreateSetPage(void);
	extern WM_HWIN CreateDialogPage(void);
	extern WM_HWIN DialogWin;
	extern char* BKBmaDataBuf;
	extern CATGlobalStatus_s CATGlobalStatus;
	
	CommonDialogPageData_s DialogPageData = {0};
    WM_MESSAGE pMsgTemp;
	CATQueueInfoBuf_s CATQueueInfoBuf = {0};
	extern osMessageQueueId_t CATQueueHandle;
  // USER END

  switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
			TEXT_SetFont(hItem,&HZ_SONGTI_24);
			WM_SetWindowPos(hItem,20, 13+63, 48, 30);
		}else{
			TEXT_SetFont(hItem,&GUI_Font24_ASCII);
			WM_SetWindowPos(hItem,20, 13+63, 84, 30);
		}
		TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
		TEXT_SetText(hItem,g_ucaLng_Set[MachInfo.systemSet.eLanguage]);
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
			WM_SetWindowPos(hItem,68, 20+63, 140, 20);
		}else{
			WM_SetWindowPos(hItem,104, 20+63, 140, 20);
		}
		TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
		TEXT_SetText(hItem,g_ucaLng_SET_ASSIST[MachInfo.systemSet.eLanguage]);
		
		//重绘按钮样式
		_FuzhuSetPageRedrawWidgetType(pMsg);
        //设置窗口颜色和背景颜色一致
        WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
		
		//不同权限显示不同的按钮内容
		if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_ADMIN){
			WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
			WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
			WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
			WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
			WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
			WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8));
			WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_9));
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
			WM_SetWindowPos(hItem,315, 200, 160, 40);
			
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
			WM_SetWindowPos(hItem,315, 260, 160, 40);
		}
	break;

	case WM_PAINT:
	//画背景BMP图
	//GUI_BMP_Draw(BKBmaDataBuf,1,0);
    //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);   
      WM_GetClientRect(&Rect); 
      GUI_SetColor(GUI_WHITE);
      GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

	//画线
	GUI_SetColor(0x009ea0a2);
	GUI_DrawHLine(54,8,790);
	
	//不同权限显示不同的按钮内容
	if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
		//画框
		GUI_AA_DrawRoundedRect(50,90,230,330,5);
		GUI_AA_DrawRoundedRect(305,90,485,330,5);
		GUI_AA_DrawRoundedRect(570,90,750,330,5);
		
		//写字
		GUI_SetColor(0x009ea0a2);
		GUI_SetBkColor(GUI_WHITE);
		GUI_SetFont(&GUI_Font24_ASCII);
		GUI_DispStringHCenterAt("Release",395,105);
		GUI_DispStringHCenterAt("Test",650,105);
	}
	
  break;
	  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '公司切换'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatelogoSwitchPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_2: // Notifications sent by 'U盘升级'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		{
			extern WM_HWIN CreateFuzhuConfigPage(void);
			CommonSwitchDialogPageData_s SwitchDialogData;
			
			//弹出选择对话框
			GUI_EndDialog(pMsg->hWin, 0);
			g_hActiveWin = CreateSwitchDialogPage();
			
			//重置仪器参数
			SwitchDialogData.switchDialogItem = CONFIG_U_UPDATE;
			SwitchDialogData.dialogData.bmpType = BMP_ALARM;
			SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
			SwitchDialogData.dialogData.fun = CreateFuzhuConfigPage;					
			strcpy(SwitchDialogData.dialogData.str,g_ucaLng_SET_ConfirmUUpdate[MachInfo.systemSet.eLanguage]);
			
			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &SwitchDialogData;
			WM_SendMessage(g_hActiveWin,pMsg);
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_3: // Notifications sent by '设置皮肤'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  {
		extern WM_HWIN CreateSetSkinWindow(void);
		  
		  GUI_EndDialog(pMsg->hWin, 0);
		  g_hActiveWin = CreateSetSkinWindow();
	  }
		
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_4: // Notifications sent by '主程序升级到发布版'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹窗提示
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断下和服务端连接是否正常
		if(CATGlobalStatus.registerNet != CAT_REGISTNET_SUCCESS || CATGlobalStatus.flag.connServerErr == 1){
			//弹窗提示
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,"服务端通讯异常，请稍后重试");
		}else{
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = NO_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,g_ucaLng_SET_Configing[MachInfo.systemSet.eLanguage]);
			
			//这里需要向服务端发送指令
			CATQueueInfoBuf.msgType = ACTIVE_UPDATE_CAT_MSG_TYPE;
			CATQueueInfoBuf.para.forceUpdate.versionType = 0;									//1表示请求服务端发送测试版
			CATQueueInfoBuf.para.forceUpdate.updateType = 0;									//0表示请求服务端发送主程序信息
			osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
		}

		pMsgTemp.MsgId = WM_USER_DATA;
		pMsgTemp.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsgTemp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_5: // Notifications sent by '引导程序升级到发布版'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹窗提示
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断下和服务端连接是否正常
		if(CATGlobalStatus.registerNet != CAT_REGISTNET_SUCCESS || CATGlobalStatus.flag.connServerErr == 1){
			//弹窗提示
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,"服务端通讯异常，请稍后重试");
		}else{
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = NO_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,g_ucaLng_SET_Configing[MachInfo.systemSet.eLanguage]);
			
			//这里需要向服务端发送指令
			CATQueueInfoBuf.msgType = ACTIVE_UPDATE_CAT_MSG_TYPE;
			CATQueueInfoBuf.para.forceUpdate.versionType = 0;									//1表示请求服务端发送测试版
			CATQueueInfoBuf.para.forceUpdate.updateType = 1;									//0表示请求服务端发送主程序信息
			osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
		}

		pMsgTemp.MsgId = WM_USER_DATA;
		pMsgTemp.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsgTemp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_6: // Notifications sent by 'UI升级到发布版'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹窗提示
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断下和服务端连接是否正常
		if(CATGlobalStatus.registerNet != CAT_REGISTNET_SUCCESS || CATGlobalStatus.flag.connServerErr == 1){
			//弹窗提示
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,"服务端通讯异常，请稍后重试");
		}else{
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = NO_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,g_ucaLng_SET_Configing[MachInfo.systemSet.eLanguage]);
			
			//这里需要向服务端发送指令
			CATQueueInfoBuf.msgType = ACTIVE_UPDATE_CAT_MSG_TYPE;
			CATQueueInfoBuf.para.forceUpdate.versionType = 0;									//1表示请求服务端发送测试版
			CATQueueInfoBuf.para.forceUpdate.updateType = 2;									//0表示请求服务端发送主程序信息
			osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
		}

		pMsgTemp.MsgId = WM_USER_DATA;
		pMsgTemp.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsgTemp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_7: // Notifications sent by '主程序升级到测试版'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹窗提示
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断下和服务端连接是否正常
		if(CATGlobalStatus.registerNet != CAT_REGISTNET_SUCCESS || CATGlobalStatus.flag.connServerErr == 1){
			//弹窗提示
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,"服务端通讯异常，请稍后重试");
		}else{
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = NO_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,g_ucaLng_SET_Configing[MachInfo.systemSet.eLanguage]);
			
			//这里需要向服务端发送指令
			CATQueueInfoBuf.msgType = ACTIVE_UPDATE_CAT_MSG_TYPE;
			CATQueueInfoBuf.para.forceUpdate.versionType = 1;									//1表示请求服务端发送测试版
			CATQueueInfoBuf.para.forceUpdate.updateType = 0;									//0表示请求服务端发送主程序信息
			osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
		}

		pMsgTemp.MsgId = WM_USER_DATA;
		pMsgTemp.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsgTemp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_8: // Notifications sent by '引导程序升级到测试版'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//弹窗提示
		WM_HideWindow(g_hActiveWin);
		DialogWin = CreateDialogPage();
		
		//先判断下和服务端连接是否正常
		if(CATGlobalStatus.registerNet != CAT_REGISTNET_SUCCESS || CATGlobalStatus.flag.connServerErr == 1){
			//弹窗提示
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,"服务端通讯异常，请稍后重试");
		}else{
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = NO_CONFIM_BUTTON;
			DialogPageData.fun = NULL;
			strcpy(DialogPageData.str,g_ucaLng_SET_Configing[MachInfo.systemSet.eLanguage]);
			
			//这里需要向服务端发送指令
			CATQueueInfoBuf.msgType = ACTIVE_UPDATE_CAT_MSG_TYPE;
			CATQueueInfoBuf.para.forceUpdate.versionType = 1;									//1表示请求服务端发送测试版
			CATQueueInfoBuf.para.forceUpdate.updateType = 1;									//0表示请求服务端发送主程序信息
			osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
		}

		pMsgTemp.MsgId = WM_USER_DATA;
		pMsgTemp.Data.p = &DialogPageData;
		WM_SendMessage(DialogWin,&pMsgTemp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_9: // Notifications sent by 'RES3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFuzhuConfigPage
*/
WM_HWIN CreateFuzhuConfigPage(void);
WM_HWIN CreateFuzhuConfigPage(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
