/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_eeprom.h"
#include "Common.h"
#include "bsp_resistance.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (HGB_SELF_CHECK_WINDOW_ID + 0x00)
#define ID_TEXT_0 (HGB_SELF_CHECK_WINDOW_ID + 0x01)
#define ID_TEXT_1 (HGB_SELF_CHECK_WINDOW_ID + 0x02)
#define ID_TEXT_2 (HGB_SELF_CHECK_WINDOW_ID + 0x03)
#define ID_TEXT_3 (HGB_SELF_CHECK_WINDOW_ID + 0x04)
#define ID_TEXT_4 (HGB_SELF_CHECK_WINDOW_ID + 0x05)
#define ID_TEXT_5 (HGB_SELF_CHECK_WINDOW_ID + 0x06)
#define ID_EDIT_0 (HGB_SELF_CHECK_WINDOW_ID + 0x07)
#define ID_EDIT_1 (HGB_SELF_CHECK_WINDOW_ID + 0x08)
#define ID_EDIT_2 (HGB_SELF_CHECK_WINDOW_ID + 0x09)
#define ID_EDIT_3 (HGB_SELF_CHECK_WINDOW_ID + 0x0A)
#define ID_BUTTON_0 (HGB_SELF_CHECK_WINDOW_ID + 0x0B)
#define ID_BUTTON_1 (HGB_SELF_CHECK_WINDOW_ID + 0x0C)
#define ID_TEXT_6 (HGB_SELF_CHECK_WINDOW_ID + 0x0D)
#define ID_TEXT_7 (HGB_SELF_CHECK_WINDOW_ID + 0x0E)
#define ID_EDIT_4 (HGB_SELF_CHECK_WINDOW_ID + 0x0F)
#define ID_EDIT_5 (HGB_SELF_CHECK_WINDOW_ID + 0x10)
#define ID_EDIT_6 (HGB_SELF_CHECK_WINDOW_ID + 0x11)
#define ID_EDIT_7 (HGB_SELF_CHECK_WINDOW_ID + 0x12)
#define ID_BUTTON_2 (HGB_SELF_CHECK_WINDOW_ID + 0x13)
#define ID_MULTIEDIT_0 (HGB_SELF_CHECK_WINDOW_ID + 0x14)
#define ID_BUTTON_3 (HGB_SELF_CHECK_WINDOW_ID + 0x15)
#define ID_BUTTON_4 (HGB_SELF_CHECK_WINDOW_ID + 0x16)
#define ID_BUTTON_5 (HGB_SELF_CHECK_WINDOW_ID + 0x17)
#define ID_BUTTON_6 (HGB_SELF_CHECK_WINDOW_ID + 0x18)
#define ID_TEXT_8 (HGB_SELF_CHECK_WINDOW_ID + 0x19)
#define ID_TEXT_9 (HGB_SELF_CHECK_WINDOW_ID + 0x1A)
#define ID_EDIT_8 (HGB_SELF_CHECK_WINDOW_ID + 0x1B)
#define ID_EDIT_9 (HGB_SELF_CHECK_WINDOW_ID + 0x1C)
#define ID_EDIT_10 (HGB_SELF_CHECK_WINDOW_ID + 0x1D)
#define ID_EDIT_11 (HGB_SELF_CHECK_WINDOW_ID + 0x1E)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "HGBDebugPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET_t", ID_TEXT_0, 30, 15, 95, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "HGB_Debug_t", ID_TEXT_1, 125, 20, 140, 20, 0, 0x0, 0 },
  
  { TEXT_CreateIndirect, "415nm_t", ID_TEXT_2, 150, 60, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "535nm_t", ID_TEXT_3, 250, 60, 80, 20, 0, 0x0, 0 },
  
  { TEXT_CreateIndirect, "Point1", ID_TEXT_8, 30, 100, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Point2", ID_TEXT_9, 30, 140, 100, 30, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Point1_415_e", ID_EDIT_8, 150, 100, 80, 30, 0, 0x4, 0 },
  { EDIT_CreateIndirect, "Point1_535_e", ID_EDIT_9, 250, 100, 80, 30, 0, 0x4, 0 },
  { EDIT_CreateIndirect, "Point2_415_e", ID_EDIT_10, 150, 140, 80, 30, 0, 0x4, 0 },
  { EDIT_CreateIndirect, "Point2_535_e", ID_EDIT_11, 250, 140, 80, 30, 0, 0x4, 0 },
  
  { TEXT_CreateIndirect, "Air_ADC_T", ID_TEXT_4, 30, 180, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "KB_ADC_t", ID_TEXT_5, 30, 220, 100, 30, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "AirADC415_e", ID_EDIT_0, 150, 180, 80, 30, 0, 0x4, 0 },
  { EDIT_CreateIndirect, "AirADC535_e", ID_EDIT_1, 250, 180, 80, 30, 0, 0x4, 0 },
  { EDIT_CreateIndirect, "KBADC415_e", ID_EDIT_2, 150, 220, 80, 30, 0, 0x4, 0 },
  { EDIT_CreateIndirect, "KBADC535_e", ID_EDIT_3, 250, 220, 80, 30, 0, 0x4, 0 },
  
  { TEXT_CreateIndirect, "Current_t", ID_TEXT_6, 30, 260, 100, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ZY_t", ID_TEXT_7, 30, 300, 100, 30, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Curr415_e", ID_EDIT_4, 150, 260, 80, 30, 0, 0x4, 0 },
  { EDIT_CreateIndirect, "Curr535_e", ID_EDIT_5, 250, 260, 80, 30, 0, 0x4, 0 },
  { EDIT_CreateIndirect, "ZY_e", ID_EDIT_6, 150, 300, 180, 30, 0, 0x3, 0 },
  
  { BUTTON_CreateIndirect, "AirAuto_b", ID_BUTTON_0, 20, 340, 150, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "KBAuto_b", ID_BUTTON_1, 180, 340, 150, 40, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "Return_b", ID_BUTTON_2, 678, 11, 100, 40, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 400, 80, 350, 190, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGBTest_b", ID_BUTTON_3, 400, 280, 350, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Open415_b", ID_BUTTON_4, 400, 330, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Open535_b", ID_BUTTON_5, 520, 330, 100, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Close_b", ID_BUTTON_6, 640, 330, 110, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _RedrawButtonType_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("空气校准",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("空白校准",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("HGB测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("开415灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect("开535灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect("关灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRectEx(&Rect,19);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("空气校准",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("空白校准",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					GUI_DispStringInRect("返回",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect("HGB测试",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect("开415灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect("开535灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect("关灯",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



/*
* 设置控件回调函数，以及重绘控件
*/
static void _RedrawButtonType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _RedrawButtonType_Callback);
    WM_InvalidateWindow(hItem);
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _RedrawButtonType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _RedrawButtonType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _RedrawButtonType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _RedrawButtonType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, _RedrawButtonType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, _RedrawButtonType_Callback);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	GUI_RECT Rect;
	uint16_t U16Temp = 0;
	char Str[30] = {0};
	static uint8_t MoveWindowFlag = 0;							//是否移动了窗口标志
	static uint8_t MoveWindowYValue = 0;						//移动窗口的Y轴偏移量
	
	//记录原始参数值，以便当参数有修改时，需要上传到服务端去
	static uint16_t Current415 = 0;
	static uint16_t Current535 = 0;
	static uint16_t HGBZY = 0;
	
	
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	Current415 = MachInfo.paramSet.current415;  
	Current535 = MachInfo.paramSet.current535;
	HGBZY = MachInfo.paramSet.ucHGB_Gain; 
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem,&HZ_SONGTI_24);
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	TEXT_SetText(hItem,"设置");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	TEXT_SetText(hItem,"> HGB调校");  
  
    //
    // Initialization of '415nm_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"415nm"); 
    //
    // Initialization of '535nm_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetText(hItem,"535nm"); 
	
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"点1电流"); 
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"点2电流"); 
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.point1Curr415);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.point1Curr535);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.point2Curr415);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.point2Curr535);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
	
    //
    // Initialization of 'Air_ADC_T'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"空气校准ADC"); 
    //
    // Initialization of 'KB_ADC_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"空白校准ADC");
    //
    // Initialization of 'AirADC415_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.KQADC415);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
    //
    // Initialization of 'AirADC535_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.KQADC535);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
    //
    // Initialization of 'KBADC415_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.KBADC415);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
    //
    // Initialization of 'KBADC535_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.KBADC535);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
    //
    // Initialization of 'Current_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"驱动电流");
    //
    // Initialization of 'ZY_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"HGB增益");
    //
    // Initialization of 'Curr415_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.current415);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
	
    //
    // Initialization of 'Curr535_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.current535);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
    //
    // Initialization of 'ZY_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Str,"%u",MachInfo.paramSet.ucHGB_Gain);
	Str[U16Temp] = '\0';
    EDIT_SetText(hItem, Str);
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    MULTIEDIT_SetText(hItem, "");
	MULTIEDIT_SetReadOnly(hItem,1);
	MULTIEDIT_SetBufferSize(hItem, 2048);
	MULTIEDIT_SetAutoScrollV(hItem, 1);
	MULTIEDIT_SetAutoScrollH(hItem, 1);
	MULTIEDIT_SetTextAlign(hItem,GUI_TA_LEFT);
	MULTIEDIT_SetFont(hItem,&HZ_SONGTI_16);
	MULTIEDIT_ShowCursor(hItem,0);
	MULTIEDIT_SetInsertMode(hItem,0);
	MULTIEDIT_SetBkColor(hItem,MULTIEDIT_CI_READONLY,GUI_WHITE);
	MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, GUI_BLACK);
	
	//重绘按钮样式
	_RedrawButtonType(pMsg);
	
	//禁止掉桌面按键
	AbortPublishDestopButton();
	
	//设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
	
	//恒流源关
	BC_CUR_SW_OFF;
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	
	case WM_PAINT:
		//画背景BMP图
		WM_GetClientRect(&Rect); 
		GUI_SetColor(GUI_WHITE);
		GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
	break;
	
	case WM_DELETE:
	{
		Disable_Motor_Task();
	}break;
	
	//键盘更新事件
	case WM_KEYBOARD_UPDATE:
	{
		char c;
		U16Temp = strlen(pMsg->Data.p);
		c = *((char*)pMsg->Data.p);

		//ASCII码
		if(U16Temp == 1){
			if((c>='0'&&c<='9')){
				GUI_StoreKeyMsg(c,1);
			}
		}
	}break;
  
	//键盘结束事件
	case WM_KEYBOARD_END:
		//判断是否移动了窗口，是，则还原
		if(MoveWindowFlag == 1){
			MoveWindowFlag = 0;
			WM_MoveWindow(pMsg->hWin,0,MoveWindowYValue);
		}
	break;

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
	case ID_EDIT_8: // Notifications sent by '点1的415电流值_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        //唤出键盘
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_NUM;
		CreateKeyboard_Window();
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_8);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.point1Curr415){
			MachInfo.paramSet.point1Curr415 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.point1Curr415-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.point1Curr415,sizeof(MachInfo.paramSet.point1Curr415));
		}
        break;
      }
      break;
	  
	case ID_EDIT_9: // Notifications sent by '点1的535电流值_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        //唤出键盘
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_NUM;
		CreateKeyboard_Window();
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_9);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.point1Curr535){
			MachInfo.paramSet.point1Curr535 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.point1Curr535-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.point1Curr535,sizeof(MachInfo.paramSet.point1Curr535));
		}
        break;
      }
      break;
	  
	case ID_EDIT_10: // Notifications sent by '点2的415电流值_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        //唤出键盘
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_NUM;
		CreateKeyboard_Window();
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_10);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.point2Curr415){
			MachInfo.paramSet.point2Curr415 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.point2Curr415-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.point2Curr415,sizeof(MachInfo.paramSet.point2Curr415));
		}
        break;
      }
      break;
		
	case ID_EDIT_11: // Notifications sent by '点2的535电流值_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        //唤出键盘
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_NUM;
		CreateKeyboard_Window();
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_11);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.point2Curr535){
			MachInfo.paramSet.point2Curr535 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.point2Curr535-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.point2Curr535,sizeof(MachInfo.paramSet.point2Curr535));
		}
        break;
      }
      break;
		
    case ID_EDIT_0: // Notifications sent by 'AirADC415_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 30;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
         }
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.KQADC415){
			MachInfo.paramSet.KQADC415 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.KQADC415-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.KQADC415,sizeof(MachInfo.paramSet.KQADC415));
		}
        break;
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'AirADC535_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 30;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
         }
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_1);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.KQADC535){
			MachInfo.paramSet.KQADC535 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.KQADC535-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.KQADC535,sizeof(MachInfo.paramSet.KQADC535));
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'KBADC415_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 100;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
         }
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_2);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.KBADC415){
			MachInfo.paramSet.KBADC415 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.KBADC415-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.KBADC415,sizeof(MachInfo.paramSet.KBADC415));
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'KBADC535_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 100;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
         }
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_3);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.KBADC535){
			MachInfo.paramSet.KBADC535 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.KBADC535-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.KBADC535,sizeof(MachInfo.paramSet.KBADC535));
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'AirAuto_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        {
			Msg_Head_t BackendMsg = {0};
			
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
			
			//往后台发送消息
			BackendMsg.usCmd = CMD_SET_HGB_ADJUST_KQ_AUTO;
			UI_Put_Msg((uint8_t*)&BackendMsg);
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'KBAuto_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        {
			Msg_Head_t BackendMsg = {0};
			
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
			
			//往后台发送消息
			BackendMsg.usCmd = CMD_SET_HGB_ADJUST_KB_AUTO;
			UI_Put_Msg((uint8_t*)&BackendMsg);
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Curr415_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 130;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_4);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.current415){
			MachInfo.paramSet.current415 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.current415-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.current415,sizeof(MachInfo.paramSet.current415));
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_5: // Notifications sent by 'Curr535_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 130;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
          }
	  
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_5);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.current535){
			MachInfo.paramSet.current535 = U16Temp;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.current535-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.current535,sizeof(MachInfo.paramSet.current535));
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_6: // Notifications sent by 'ZY415_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 160;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_6);
		memset(Str,0,10);
		EDIT_GetText(hItem,Str,10);
		U16Temp = atoi(Str);
		if(U16Temp != MachInfo.paramSet.ucHGB_Gain){
			MachInfo.paramSet.ucHGB_Gain = U16Temp;
			HGB_Gran_Set(HGB_DR_CHANNEL,MachInfo.paramSet.ucHGB_Gain);
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET+((uint8_t*)&MachInfo.paramSet.ucHGB_Gain-(uint8_t*)&MachInfo.paramSet),(uint8_t*)&MachInfo.paramSet.ucHGB_Gain,sizeof(MachInfo.paramSet.ucHGB_Gain));
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
//    case ID_EDIT_7: // Notifications sent by 'ZY535_e'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_VALUE_CHANGED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      // USER START (Optionally insert additional code for further notification handling)
//      // USER END
//      }
//      break;
    case ID_BUTTON_2: // Notifications sent by 'Return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  {
		extern WM_HWIN CreateParaSetPage(void);
		  
		  //恢复桌面按键
		RecoverPublishDestopButton();
		  
		GUI_EndDialog(pMsg->hWin, 0);
		GUI_Exec();
		g_hActiveWin = CreateParaSetPage();
		  
		  //判断参数是否有更改，是，则上传到服务端
		  if(Current415 != MachInfo.paramSet.current415 || Current535 != MachInfo.paramSet.current535 || HGBZY != MachInfo.paramSet.ucHGB_Gain){
			  extern osMessageQueueId_t CATQueueHandle;
			  CATQueueInfoBuf_s CATQueueInfoBuf;
			  
			//通过CAT模块发送参数修改信息到后台
			//标记CAT必发事件标记
			MachInfo.catMastSynServEvent.bit.paraSet = 1;
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_CAT_SYNC_SER_EVENT,(uint8_t*)&MachInfo.catMastSynServEvent,sizeof(MachInfo.catMastSynServEvent));
			CATQueueInfoBuf.msgType = SET_PARA_OVER_CAT_MSG_TYPE;
            osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
		  }
	  }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'HGBTest_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		{
			Msg_Head_t BackendMsg = {0};
			
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6));
			
			//往后台发送消息
			BackendMsg.usCmd = CMD_SET_HGB_ADJUST_TEST;
			UI_Put_Msg((uint8_t*)&BackendMsg);
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Open415_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        {
			extern osEventFlagsId_t GlobalEventOtherGroupHandle;
			Msg_Head_t BackendMsg = {0};
			
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));

			osEventFlagsClear(GlobalEventOtherGroupHandle,GLOBAL_EVENT_OTHER_HGB_ADJUST_CLOSE);
			
			//往后台发送消息
			BackendMsg.usCmd = CMD_SET_HGB_ADJUST_OPEN415;
			UI_Put_Msg((uint8_t*)&BackendMsg);
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Open535_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        {
			extern osEventFlagsId_t GlobalEventOtherGroupHandle;
			Msg_Head_t BackendMsg = {0};
			
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4));
			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5));
			
			osEventFlagsClear(GlobalEventOtherGroupHandle,GLOBAL_EVENT_OTHER_HGB_ADJUST_CLOSE);

			//往后台发送消息
			BackendMsg.usCmd = CMD_SET_HGB_ADJUST_OPEN535;
			UI_Put_Msg((uint8_t*)&BackendMsg);
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Close_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        {
			extern osEventFlagsId_t GlobalEventOtherGroupHandle;
			
			osEventFlagsSet(GlobalEventOtherGroupHandle,GLOBAL_EVENT_OTHER_HGB_ADJUST_CLOSE);
		}
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateHGBDebugPage
*/
WM_HWIN CreateHGBDebugPage(void);
WM_HWIN CreateHGBDebugPage(void) {
  WM_HWIN hWin;

	Enable_Motor_Task(TRUE);
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
