/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_eeprom.h"
#include "Common.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_SWITCH_LOGO_PAGE_ID + 0x00)
#define ID_BUTTON_0 (CONFIG_SWITCH_LOGO_PAGE_ID + 0x01)
#define ID_BUTTON_1 (CONFIG_SWITCH_LOGO_PAGE_ID + 0x02)
#define ID_RADIO_0 (CONFIG_SWITCH_LOGO_PAGE_ID + 0x03)
#define ID_RADIO_1 (CONFIG_SWITCH_LOGO_PAGE_ID + 0x04)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "logoSwitchPage", ID_WINDOW_0, 80, 50, 640, 380, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "cel", ID_BUTTON_0, 0, 340, 320, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "confim", ID_BUTTON_1, 320, 340, 320, 40, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio1", ID_RADIO_0, 66, 90, 250, 200, 0, 0x3204, 0 },
  { RADIO_CreateIndirect, "Radio2", ID_RADIO_1, 320, 89, 250, 200, 0, 0x3204, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _SwitchLogoPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			switch(WM_GetId(pMsg->hWin)){
				//取消按钮
				case ID_BUTTON_0:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//确认按钮
				case ID_BUTTON_1:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			switch(WM_GetId(pMsg->hWin)){
				//取消按钮
				case ID_BUTTON_0:
					GUI_SetColor(GUI_LIGHTGRAY);
					GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
					GUI_SetColor(BTN_CHAR_COLOR);
					GUI_SetBkColor(GUI_LIGHTGRAY);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//确认按钮
				case ID_BUTTON_1:
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
					GUI_FillRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1);
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



static void _SwitchLogoPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
	//取消按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _SwitchLogoPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
    //确定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _SwitchLogoPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
//  WM_HWIN hItem;
	WM_HWIN hItem1;
	WM_HWIN hItem2;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreateFuzhuConfigPage(void);
	extern  MachInfo_s	MachInfo;
	
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
	uint8_t RadioValue1 = 0;
	uint8_t RadioValue2 = 0;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Radio1'
    //
    hItem1 = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
	RADIO_SetFont(hItem1,&HZ_SONGTI_16);
	RADIO_SetFocusColor(hItem1,GUI_WHITE);
    RADIO_SetText(hItem1, g_ucaLng_SET_CH[MachInfo.systemSet.eLanguage], 0);
    RADIO_SetText(hItem1, g_ucaLng_SET_Reserve1[MachInfo.systemSet.eLanguage], 1);
    RADIO_SetText(hItem1, g_ucaLng_SET_Reserve2[MachInfo.systemSet.eLanguage], 2);
    RADIO_SetText(hItem1, g_ucaLng_SET_Reserve3[MachInfo.systemSet.eLanguage], 3);
    //
    // Initialization of 'Radio2'
    //
    hItem2 = WM_GetDialogItem(pMsg->hWin, ID_RADIO_1);
	RADIO_SetFont(hItem2,&HZ_SONGTI_16);
	RADIO_SetFocusColor(hItem2,GUI_WHITE);
    RADIO_SetText(hItem2, g_ucaLng_SET_Reserve4[MachInfo.systemSet.eLanguage], 0);
    RADIO_SetText(hItem2, g_ucaLng_SET_Reserve5[MachInfo.systemSet.eLanguage], 1);
    RADIO_SetText(hItem2, g_ucaLng_SET_Reserve6[MachInfo.systemSet.eLanguage], 2);
    RADIO_SetText(hItem2, g_ucaLng_SET_Reserve7[MachInfo.systemSet.eLanguage], 3);
	
	//合并成一组
	RADIO_SetGroupId(hItem1,1);
	RADIO_SetGroupId(hItem2,1);
	
    
	if(MachInfo.companyInfo.company <= 3){
		RADIO_SetValue(hItem1,MachInfo.companyInfo.company);
		RADIO_SetValue(hItem2,0xff);
	}else if(MachInfo.companyInfo.company <= 7){
		RADIO_SetValue(hItem1,0xff);
		RADIO_SetValue(hItem2,MachInfo.companyInfo.company-4);
	}else{
		MachInfo.companyInfo.company = 0;
		RADIO_SetValue(hItem1,MachInfo.companyInfo.company);
		RADIO_SetValue(hItem2,0xff);
		EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_COMPANY+((uint8_t*)&MachInfo.companyInfo.company-(uint8_t*)&MachInfo.companyInfo),(uint8_t*)&MachInfo.companyInfo.company,sizeof(MachInfo.companyInfo.company));
	}
	
	//重绘按钮样式
	_SwitchLogoPageRedrawWidgetType(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  
  case WM_PAINT:
	//先设置弹窗和背景为相同的透明度
	GUI_SetAlpha(30);
	GUI_SetColor(0x00525a4e);
	GUI_FillRectEx(&Rect);
	GUI_SetAlpha(0);
  
	//重绘弹窗为圆角矩形
	GUI_SetColor(0x00ffffff);
	GUI_AA_FillRoundedRectEx(&Rect,6);
  
	//重绘顶部标题栏，采用重叠法
	GUI_SetColor(MachInfo.companyInfo.skin.title);
	GUI_AA_FillRoundedRect(Rect.x0,Rect.y0,Rect.x1,Rect.y0+15,6);
	GUI_FillRect(Rect.x0,Rect.y0+10,Rect.x1,Rect.y0+38);
	
	//标题
	GUI_SetFont(&HZ_SONGTI_16);
	GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
	GUI_SetBkColor(MachInfo.companyInfo.skin.title);
	GUI_DispStringHCenterAt(g_ucaLng_SET_LogoSwitch[MachInfo.systemSet.eLanguage],320,10);
  break;
  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'cel_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateFuzhuConfigPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'confim_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
            hItem1 = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
            hItem2 = WM_GetDialogItem(pMsg->hWin, ID_RADIO_1);
            RadioValue1 = RADIO_GetValue(hItem1);
            RadioValue2 = RADIO_GetValue(hItem2);
            
            //这里要偏移radio2的值
            if(RadioValue2 != 0xff){
                RadioValue2 += 4;
            }

            if(RadioValue1 != 0xFF && MachInfo.companyInfo.company != RadioValue1){
                MachInfo.companyInfo.company = RadioValue1;
                EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_COMPANY+((uint8_t*)&MachInfo.companyInfo.company-(uint8_t*)&MachInfo.companyInfo),(uint8_t*)&MachInfo.companyInfo.company,sizeof(MachInfo.companyInfo.company));
				
				//更新公司信息
				Company_ConfigInfo(MachInfo.companyInfo.company);
				
				//标记CAT必发事件标记
				MachInfo.catMastSynServEvent.bit.paraSet = 1;
				EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_CAT_SYNC_SER_EVENT,(uint8_t*)&MachInfo.catMastSynServEvent,sizeof(MachInfo.catMastSynServEvent));
				
                osDelay(500);
				
				//重新登录
				__set_PRIMASK(1);
				NVIC_SystemReset();
            }else if(RadioValue2 != 0xFF && MachInfo.companyInfo.company != RadioValue2){
                MachInfo.companyInfo.company = RadioValue2;				
                EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_COMPANY+((uint8_t*)&MachInfo.companyInfo.company-(uint8_t*)&MachInfo.companyInfo),(uint8_t*)&MachInfo.companyInfo.company,sizeof(MachInfo.companyInfo.company));
                
				//更新公司信息
				Company_ConfigInfo(MachInfo.companyInfo.company);
				
				//标记CAT必发事件标记
				MachInfo.catMastSynServEvent.bit.paraSet = 1;
				EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_CAT_SYNC_SER_EVENT,(uint8_t*)&MachInfo.catMastSynServEvent,sizeof(MachInfo.catMastSynServEvent));
				
                osDelay(500);
				
				//重新登录
				__set_PRIMASK(1);
				NVIC_SystemReset();
            }
            
            //
            GUI_EndDialog(pMsg->hWin, 0);
            g_hActiveWin = CreateFuzhuConfigPage();
        }
    }
    break;
    case ID_RADIO_0: // Notifications sent by 'Radio1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_1: // Notifications sent by 'Radio2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatelogoSwitchPage
*/
WM_HWIN CreatelogoSwitchPage(void);
WM_HWIN CreatelogoSwitchPage(void) {
  WM_HWIN hWin;
	
	WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin);
	Public_Hide_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
