/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_eeprom.h"
#include "bsp_resistance.h"
#include "bsp_pump.h"
#include "file_operate.h"
#include "bsp_press.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_ParaSet_PAGE_ID + 0x00)
#define ID_TEXT_0 (CONFIG_ParaSet_PAGE_ID + 0x01)
#define ID_TEXT_1 (CONFIG_ParaSet_PAGE_ID + 0x02)
#define ID_TEXT_2 (CONFIG_ParaSet_PAGE_ID + 0x03)
#define ID_TEXT_3 (CONFIG_ParaSet_PAGE_ID + 0x04)
#define ID_TEXT_4 (CONFIG_ParaSet_PAGE_ID + 0x05)
#define ID_TEXT_5 (CONFIG_ParaSet_PAGE_ID + 0x06)
#define ID_TEXT_6 (CONFIG_ParaSet_PAGE_ID + 0x07)
#define ID_TEXT_7 (CONFIG_ParaSet_PAGE_ID + 0x08)
#define ID_TEXT_8 (CONFIG_ParaSet_PAGE_ID + 0x09)
#define ID_TEXT_9 (CONFIG_ParaSet_PAGE_ID + 0x0A)
#define ID_TEXT_10 (CONFIG_ParaSet_PAGE_ID + 0x0B)
#define ID_TEXT_11 (CONFIG_ParaSet_PAGE_ID + 0x0C)
#define ID_TEXT_12 (CONFIG_ParaSet_PAGE_ID + 0x0D)
#define ID_TEXT_13 (CONFIG_ParaSet_PAGE_ID + 0x0E)
#define ID_TEXT_14 (CONFIG_ParaSet_PAGE_ID + 0x0F)
#define ID_TEXT_15 (CONFIG_ParaSet_PAGE_ID + 0x10)
#define ID_TEXT_16 (CONFIG_ParaSet_PAGE_ID + 0x11)
#define ID_TEXT_17 (CONFIG_ParaSet_PAGE_ID + 0x12)
#define ID_TEXT_18 (CONFIG_ParaSet_PAGE_ID + 0x13)
#define ID_TEXT_19 (CONFIG_ParaSet_PAGE_ID + 0x14)
#define ID_TEXT_20 (CONFIG_ParaSet_PAGE_ID + 0x15)
#define ID_TEXT_21 (CONFIG_ParaSet_PAGE_ID + 0x16)

#define ID_EDIT_0 (CONFIG_ParaSet_PAGE_ID + 0x17)
#define ID_EDIT_1 (CONFIG_ParaSet_PAGE_ID + 0x18)
#define ID_EDIT_2 (CONFIG_ParaSet_PAGE_ID + 0x19)
#define ID_EDIT_3 (CONFIG_ParaSet_PAGE_ID + 0x1A)
#define ID_EDIT_4 (CONFIG_ParaSet_PAGE_ID + 0x1B)
#define ID_EDIT_5 (CONFIG_ParaSet_PAGE_ID + 0x1C)
#define ID_EDIT_6 (CONFIG_ParaSet_PAGE_ID + 0x1D)
#define ID_EDIT_7 (CONFIG_ParaSet_PAGE_ID + 0x1E)
#define ID_EDIT_8 (CONFIG_ParaSet_PAGE_ID + 0x1F)
#define ID_EDIT_9 (CONFIG_ParaSet_PAGE_ID + 0x20)

#define ID_BUTTON_0 (CONFIG_ParaSet_PAGE_ID + 0x21)
#define ID_BUTTON_1 (CONFIG_ParaSet_PAGE_ID + 0x22)
#define ID_BUTTON_2 (CONFIG_ParaSet_PAGE_ID + 0x23)
#define ID_BUTTON_3 (CONFIG_ParaSet_PAGE_ID + 0x24)
#define ID_BUTTON_4 (CONFIG_ParaSet_PAGE_ID + 0x25)

#define ID_RADIO_0 (CONFIG_PRINTER_PAGE_ID + 0x26)





// USER START (Optionally insert additional defines)
/***
*定义参数被修改的标志位结构体
***/
typedef struct _ParaSetFlag_s{
	uint32_t wbcZY:							1;
	uint32_t hgbZY:							1;
	uint32_t pump:							1;
	uint32_t current535:					1;
	uint32_t current415:					1;
	uint32_t pressure:						1;
	uint32_t ocIn:							1;
	uint32_t ocOut:							1;
	uint32_t ocGD:							1;
	uint32_t ocRelease:						1;
	uint32_t pressSensor:					1;
}ParaSetFlag_s;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ParaSetPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET", ID_TEXT_0, 30, 15, 95, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> PARA SET", ID_TEXT_1, 125, 20, 140, 20, 0, 0x0, 0 },
  
  { TEXT_CreateIndirect, "WBC", ID_TEXT_2, 80, 80, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "wbcZY_e", ID_EDIT_0, 190, 75, 100, 30, 0, 0x5, 0 },
  { TEXT_CreateIndirect, "t1", ID_TEXT_3, 300, 80, 100, 20, 0, 15, 0 },
  
  { TEXT_CreateIndirect, "HGB", ID_TEXT_4, 80, 120, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "hgbZY_e", ID_EDIT_1, 190, 115, 100, 30, 0, 0x5, 0 },
  { TEXT_CreateIndirect, "t2", ID_TEXT_5, 300, 120, 100, 20, 0, 15, 0 },
  
  { TEXT_CreateIndirect, "PUMP", ID_TEXT_6, 80, 160, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "pump_e", ID_EDIT_2, 190, 155, 100, 30, 0, 0x5, 0 },
  { TEXT_CreateIndirect, "t3", ID_TEXT_7, 300, 160, 100, 20, 0, 15, 0 },
  
  { TEXT_CreateIndirect, "535CURRENT", ID_TEXT_8, 80, 200, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "HGB_Cur_e", ID_EDIT_3, 190, 195, 100, 30, 0, 0x6, 0 },
  { TEXT_CreateIndirect, "t4", ID_TEXT_9, 300, 200, 100, 20, 0, 15, 0 },
  
  { TEXT_CreateIndirect, "415CURRENT", ID_TEXT_10, 80, 240, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "HGB_Cur_e", ID_EDIT_4, 190, 235, 100, 30, 0, 0x6, 0 },
  { TEXT_CreateIndirect, "t4", ID_TEXT_11, 300, 240, 100, 20, 0, 15, 0 },
  
  { BUTTON_CreateIndirect, "PRESSURE", ID_BUTTON_4, 80, 275, 100, 30, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "pressure_e", ID_EDIT_5, 190, 275, 100, 30, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "t5", ID_TEXT_12, 300, 280, 100, 20, 0, 15, 0 },
  
  
  { TEXT_CreateIndirect, "OC_IN", ID_TEXT_13, 450, 80, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "OC_In_e", ID_EDIT_6, 560, 75, 100, 30, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "t6", ID_TEXT_14, 670, 80, 110, 20, 0, 15, 0 },
  
  { TEXT_CreateIndirect, "OC_OUT", ID_TEXT_15, 450, 120, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "OC_Out_e", ID_EDIT_7, 560, 115, 100, 30, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "t7", ID_TEXT_16, 670, 120, 110, 20, 0, 15, 0 },
  
  { TEXT_CreateIndirect, "OC_ON", ID_TEXT_17, 450, 160, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "OC_GD_e", ID_EDIT_8, 560, 155, 100, 30, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "t8", ID_TEXT_18, 670, 160, 110, 20, 0, 15, 0 },
  
  { TEXT_CreateIndirect, "OC_OFF", ID_TEXT_19, 450, 200, 100, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "OC_Release_e", ID_EDIT_9, 560, 195, 100, 30, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "t9", ID_TEXT_20, 670, 200, 110, 20, 0, 15, 0 },
  
  { TEXT_CreateIndirect, "Radio_t", ID_TEXT_21, 450, 250, 100, 20, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 570, 245, 80, 50, 0, 0x1e02, 0 },
  
  { BUTTON_CreateIndirect, "CEL", ID_BUTTON_0, 265, 330, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CONFIM", ID_BUTTON_1, 415, 330, 120, 40, 0, 0x0, 0 },
  
  { BUTTON_CreateIndirect, "AUTO", ID_BUTTON_2, 370, 155, 80, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "HGB_Debug", ID_BUTTON_3, 370, 115, 80, 30, 0, 0x0, 0 },
  
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _ParaSetPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_AA_FillRoundedRectEx(&Rect,20);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_AA_FillRoundedRectEx(&Rect,20);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_AA_FillRoundedRectEx(&Rect,15);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
				
					GUI_DispStringInRect(g_ucaLng_SET_AUTOAdjust[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_AA_FillRoundedRectEx(&Rect,15);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
				
					GUI_DispStringInRect(g_ucaLng_SET_HGB_Debug[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_AA_FillRoundedRectEx(&Rect,15);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
				
					GUI_DispStringInRect(g_ucaLng_SET_Pressure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRectEx(&Rect,20);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,19);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRectEx(&Rect,20);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,19);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_2:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRectEx(&Rect,15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,14);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
					GUI_DispStringInRect(g_ucaLng_SET_AUTOAdjust[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRectEx(&Rect,15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,14);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
					GUI_DispStringInRect(g_ucaLng_SET_HGB_Debug[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
					GUI_AA_FillRoundedRectEx(&Rect,15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
					GUI_AA_DrawRoundedRectEx(&Rect,14);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
				
					GUI_DispStringInRect(g_ucaLng_SET_Pressure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}





/*
* 设置控件回调函数，以及重绘控件
*/
static void _ParaSetPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //取消按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _ParaSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//确定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _ParaSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, _ParaSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _ParaSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _ParaSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
  // USER START (Optionally insert additional variables)
	extern char* BKBmaDataBuf;
	extern MachInfo_s MachInfo;
	extern  __IO MachRunPara_s       MachRunPara;
	extern osMessageQueueId_t CATQueueHandle;
	extern WM_HWIN CreateParaSetPage(void);
	extern WM_HWIN CreateDialogPage(void);
	extern WM_HWIN DialogWin;
	
//	static uint8_t KeyBoardUseOnceFlag = 0;						//是否已经唤出键盘标志
	static uint8_t MoveWindowFlag = 0;							//是否移动了窗口标志
	static uint8_t MoveWindowYValue = 0;						//移动窗口的Y轴偏移量
	
	char Buf[10] = {0};
	uint16_t U16Temp = 0;
	float FTemp = 0.0;
	ParaSetFlag_s ParaSetFlag = {0};
	char c;
	uint8_t PumpResult = 0;
	CATQueueInfoBuf_s CATQueueInfoBuf;
	uint16_t Len = 0;
	
	CommonDialogPageData_s DialogPageData = {0};
	RTC_HYM8563Info_s RTCInfo = {0};
	
	//运行日志缓存区
	static RunLog_s RunLog = {0};
	
	WM_MESSAGE pMsgTemp;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Set[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_ParaSet[MachInfo.systemSet.eLanguage]);
  
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_WBC_Gain[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[0-255]");
  
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_HGB_Gain[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[0-255]");
  
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_Pump[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[10-100]");
  
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
	TEXT_SetFont(hItem,&SIF_HZ16_SONGTI);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_535Current[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[0-4095]");
	
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
	TEXT_SetFont(hItem,&SIF_HZ16_SONGTI);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_415Current[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[0-4095]");
	
  
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[-10.0~10.0]");
	
	
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
	TEXT_SetFont(hItem,&SIF_HZ16_SONGTI);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_OCIN[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[0-20000]");
	
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
	TEXT_SetFont(hItem,&SIF_HZ16_SONGTI);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_OCOUT[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_16);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[0-20000]");
	
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_17);
	TEXT_SetFont(hItem,&SIF_HZ16_SONGTI);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_OCDAOTONG[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_18);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[0-20000]");
	
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_19);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_OCDUANKAI[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_20);
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"[0-20000]");
	
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_21);
	TEXT_SetFont(hItem,&SIF_HZ16_SONGTI);
	TEXT_SetTextAlign(hItem,TEXT_CF_RIGHT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_PRESSURESensor[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
	RADIO_SetFont(hItem,&SIF_HZ16_SONGTI);
    RADIO_SetText(hItem, "IT110", 0);
	RADIO_SetText(hItem, "HONEYWELL", 1);
	if(MachInfo.paramSet.pressSensor == 0){
		RADIO_SetValue(hItem,0);
	}else{
		RADIO_SetValue(hItem,1);
	}
    //
    // Initialization of 'wbcZY_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,3);
	U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.ucWBC_Gain);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    //
    // Initialization of 'hgbZY_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,3);
    U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.ucHGB_Gain);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    //
    // Initialization of 'pump_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,3);
    U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.ucPump_Scale);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    //
    // Initialization of '535灯电流_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,4);
    U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.current535);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	//
    // Initialization of '415灯电流_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,4);
    U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.current415);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    //
    // Initialization of 'pressure_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,5);
    U16Temp = sprintf(Buf,"%.1f",MachInfo.paramSet.fPress_Adjust);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    //
    // Initialization of 'OC_In_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,5);
    U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.ulOutIn_In_AddStep);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    //
    // Initialization of 'OC_Out_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,5);
    U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.ulOutIn_Out_AddStep);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    //
    // Initialization of 'OC_GD_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,5);
    U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.ulClamp_Out_AddStep);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
    //
    // Initialization of 'OC_Release_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
	EDIT_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,5);
    U16Temp = sprintf(Buf,"%u",MachInfo.paramSet.ulClamp_In_AddStep);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	
	//重绘按钮样式
	_ParaSetPageRedrawWidgetType(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
	
	//初始化运行日志参数
	RunLog.logHead.logLen = 0;
	RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"Parameter Setting:\r\n");

	//禁止掉桌面按键
	AbortPublishDestopButton();
    // USER END
    break;
	
  case WM_PAINT:
	//画背景BMP图
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

	//画线
	GUI_SetColor(0x009ea0a2);
	GUI_DrawHLine(54,8,790);

	//画框
	GUI_SetColor(GUI_BLACK);
	GUI_DrawRect(560,235,660,295);
  break;
  
  case WM_DELETE:
  {
	Disable_Motor_Task();
  }break;
  
  //键盘更新事件
  case WM_KEYBOARD_UPDATE:
	
	hItem = WM_GetFocusedWindow();
	U16Temp = strlen(pMsg->Data.p);
	c = *((char*)pMsg->Data.p);
	
	//ASCII码
	if(U16Temp == 1){
		if(hItem == WM_GetDialogItem(pMsg->hWin,ID_EDIT_5)){			//输入正负浮点值
			if((c>='0'&&c<='9') || (c=='.') || (c=='-')){
				GUI_StoreKeyMsg(c,1);
			}
		}else{		//只能输入数字
			if((c>='0'&&c<='9')){
				GUI_StoreKeyMsg(c,1);
			}
		}
	}
  break;
  
  //键盘结束事件
  case WM_KEYBOARD_END:
	  
	  //判断是否移动了窗口，是，则还原
	  if(MoveWindowFlag == 1){
		MoveWindowFlag = 0;
		WM_MoveWindow(pMsg->hWin,0,MoveWindowYValue);
	  }
	  
  break;

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'wbcZY_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'hgbZY_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
			
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'pump_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
          if(1 != MoveWindowFlag)
          {
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 20;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by '535灯电流设置'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if(1 != MoveWindowFlag)
        {
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 60;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
        }
			
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_EDIT_4: // Notifications sent by '415灯电流设置'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if(1 != MoveWindowFlag)
        {
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 100;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
        }
			
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
    case ID_EDIT_5: // Notifications sent by 'pressure_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
      
         if(1 != MoveWindowFlag)
        {
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 140;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
        }
			
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_6: // Notifications sent by 'OC_In_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
			
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_7: // Notifications sent by 'OC_Out_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
			
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_8: // Notifications sent by 'OC_GD_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
      
        if(1 != MoveWindowFlag)
        {
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 20;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
        }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_9: // Notifications sent by 'OC_Release_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if(1 != MoveWindowFlag)
        {
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 60;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_NUM;
			CreateKeyboard_Window();
        }
			
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
    case ID_BUTTON_2: // Notifications sent by 'pumpAuto_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//失能其他控件
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_3));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_4));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_5));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_6));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_7));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_8));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_9));
	  
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));
		WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4));
	  
		//自适应调节泵占空比
		if(ParaSet_AutoPumpAdjust(&PumpResult) == HAL_OK){
			GUI_EndDialog(pMsg->hWin, 0);
			g_hActiveWin = CreateDialogPage();
			
			//保存对话框内容
			DialogPageData.bmpType = BMP_OK;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = CreateParaSetPage;					//保存进入对话框前的界面创建函数
			strcpy(DialogPageData.str,g_ucaLng_SET_PumpAutoSuccess[MachInfo.systemSet.eLanguage]);
			
			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &DialogPageData;
			WM_SendMessage(g_hActiveWin,pMsg);
		}else{
			GUI_EndDialog(pMsg->hWin, 0);
			g_hActiveWin = CreateDialogPage();
			
			//保存对话框内容
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = CreateParaSetPage;					//保存进入对话框前的界面创建函数
			strcpy(DialogPageData.str,g_ucaLng_SET_PumpAutoFail[MachInfo.systemSet.eLanguage]);
			
			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &DialogPageData;
			WM_SendMessage(g_hActiveWin,pMsg);
		}
		
		//使能其他控件
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_3));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_4));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_5));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_6));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_7));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_8));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_9));
	  
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3));
		WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4));
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'cel_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//恢复桌面按键
		RecoverPublishDestopButton();
	  
		//判断下是否需要释放压力
		if(Press_Value() < -10000){
			extern uint8_t g_OutIn_Module_Status;
			uint16_t Count = 0;
			
			//开液阀,放气
			LIQUID_WAVE_OPEN;
			osDelay(1500);
			LIQUID_WAVE_CLOSE;
			
			//当进出电机，还未执行完成时，等待其完成
			while(1 == g_OutIn_Module_Status)
			{
				//未执行完成
				osDelay(50);
				if(0 == g_OutIn_Module_Status || ++Count > 220) //进出仓模块执行完成，或超过11s
				{
					break;
				}
			}
			g_OutIn_Module_Status = 0;
			
			//进仓位置
			OutIn_Module_In(MOTOR_MODE_NORMAL);
		}
	  
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'confirm_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//恢复桌面按键
		RecoverPublishDestopButton();
			  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.ucWBC_Gain != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 255){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"WBC增益超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			//保存日志信息
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"WBC Gain:%u-->%u\r\n",MachInfo.paramSet.ucWBC_Gain,U16Temp>255?255:U16Temp);
			
			ParaSetFlag.wbcZY = 1;
			MachInfo.paramSet.ucWBC_Gain = U16Temp>255?255:U16Temp;
            WBC_Gran_Set(WBC_DR_CHANNEL, MachInfo.paramSet.ucWBC_Gain);
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.ucHGB_Gain != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 255){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"HGB增益超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"HGB Gain:%u-->%u\r\n",MachInfo.paramSet.ucHGB_Gain,U16Temp>255?255:U16Temp);
			
			ParaSetFlag.hgbZY = 1;
			MachInfo.paramSet.ucHGB_Gain = U16Temp>255?255:U16Temp;
			//写入HGB增益
			HGB_Gran_Set(HGB_DR_CHANNEL, MachInfo.paramSet.ucHGB_Gain);
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.ucPump_Scale != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 100 || U16Temp < 10){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"泵占空比超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"Pump:%u-->%u\r\n",MachInfo.paramSet.ucPump_Scale,U16Temp>100?100:U16Temp);
			
			ParaSetFlag.pump = 1;
			MachInfo.paramSet.ucPump_Scale = U16Temp>100?100:U16Temp;
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.current535 != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 4095){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"535灯电流超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"535Current:%u-->%u\r\n",MachInfo.paramSet.current535,U16Temp>4095?4095:U16Temp);
			
			ParaSetFlag.current535 = 1;
			MachInfo.paramSet.current535 = U16Temp>4095?4095:U16Temp;
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.current415 != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 4095){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"415灯电流超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"415Current:%u-->%u\r\n",MachInfo.paramSet.current415,U16Temp>4095?4095:U16Temp);
			
			ParaSetFlag.current415 = 1;
			MachInfo.paramSet.current415 = U16Temp>4095?4095:U16Temp;
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		FTemp = atof(Buf);
		if(MachInfo.paramSet.fPress_Adjust != FTemp){
			//判断参数值是否超限
			if(FTemp<-10.0f || FTemp>10.0f){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"压力补偿超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			ParaSetFlag.pressure = 1;
			if(FTemp<-10.0f){
				FTemp = -10.0f;
			}else if(FTemp > 10.0f){
				FTemp = 10.0f;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"Pressure Adjust:%.1f-->%.1f\r\n",MachInfo.paramSet.fPress_Adjust,FTemp);
			
			MachInfo.paramSet.fPress_Adjust = FTemp;
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.ulOutIn_In_AddStep != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 20000){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"进仓光耦补偿超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"OC_IN:%u-->%u\r\n",MachInfo.paramSet.ulOutIn_In_AddStep,U16Temp>20000?20000:U16Temp);
			
			ParaSetFlag.ocIn = 1;
			MachInfo.paramSet.ulOutIn_In_AddStep = U16Temp>20000?20000:U16Temp;
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.ulOutIn_Out_AddStep != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 20000){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"出仓光耦补偿超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"OC_Out:%u-->%u\r\n",MachInfo.paramSet.ulOutIn_Out_AddStep,U16Temp>20000?20000:U16Temp);
			
			ParaSetFlag.ocOut = 1;
			MachInfo.paramSet.ulOutIn_Out_AddStep = U16Temp>20000?20000:U16Temp;
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.ulClamp_Out_AddStep != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 20000){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"导通光耦补偿超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"OC_On:%u-->%u\r\n",MachInfo.paramSet.ulClamp_Out_AddStep,U16Temp>20000?20000:U16Temp);
			
			ParaSetFlag.ocGD = 1;
			MachInfo.paramSet.ulClamp_Out_AddStep = U16Temp>20000?20000:U16Temp;
		}
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,10);
		U16Temp = atoi(Buf);
		if(MachInfo.paramSet.ulClamp_In_AddStep != U16Temp){
			//判断参数值是否超限
			if(U16Temp > 20000){
				WM_HideWindow(g_hActiveWin);
				DialogWin = CreateDialogPage();
				
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = NULL;
				strcpy(DialogPageData.str,"断开光耦补偿超限");
				
				pMsgTemp.MsgId = WM_USER_DATA;
				pMsgTemp.Data.p = &DialogPageData;
				WM_SendMessage(DialogWin,&pMsgTemp);
				
				break;
			}
			
			RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"OC_Off:%u-->%u\r\n",MachInfo.paramSet.ulClamp_In_AddStep,U16Temp>20000?20000:U16Temp);
			
			ParaSetFlag.ocRelease = 1;
			MachInfo.paramSet.ulClamp_In_AddStep = U16Temp>20000?20000:U16Temp;
		}
		
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		if(MachInfo.paramSet.pressSensor != RADIO_GetValue(hItem)){
			MachInfo.paramSet.pressSensor = RADIO_GetValue(hItem);
			ParaSetFlag.pressSensor = 1;
			
			if(MachInfo.paramSet.pressSensor == 0){
				RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"Pressure Sensor:HONEYWEL-->IT110\r\n");
			}else{
				RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"Pressure Sensor:IT110-->HONEYWEL\r\n");
			}
		}
		
		
		//判断参数是否有发生更改
		if(*((uint32_t*)(&ParaSetFlag)) != 0){
			//保存运行日志
            uint32_t ulIndex = 0;
			RunLog.Str[RunLog.logHead.logLen] = '\0';
			RunLog.logHead.num = g_tDataManage.ulRunLog_SN;//g_tDataManage.lastRunLogNum;
			RunLog.logHead.eAccountType = MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type;
			RTC_HYM8563GetTime(&RTCInfo);
			sprintf(RunLog.logHead.dataTime,"20%d%d-%d%d-%d%d %d%d:%d%d:%d%d",
							RTCInfo.year.bcd_h,RTCInfo.year.bcd_l,
							RTCInfo.month.bcd_h,RTCInfo.month.bcd_l,
							RTCInfo.day.bcd_h,RTCInfo.day.bcd_l,
							RTCInfo.hour.bcd_h,RTCInfo.hour.bcd_l,
							RTCInfo.min.bcd_h,RTCInfo.min.bcd_l,
							RTCInfo.sec.bcd_h,RTCInfo.sec.bcd_l);
			Len = sprintf(RunLog.logHead.shortStr,"Parameters Change");
			RunLog.logHead.shortStr[Len] = '\0';
			RunLog.logHead.timestamp = GetCurrentTimestamp(RTCInfo);
            RunLog.usCrc = CRC16((uint8_t*)&RunLog, sizeof(RunLog_s)-2);
            
            ulIndex = Update_RunLog_Tail();
			Fatfs_Write_RunLog(ulIndex, &RunLog);
			
			g_tDataManage.ulRunLog_SN++;//g_tDataManage.lastRunLogNum++;
            Add_RunLog_Tail();
			Save_DataMange_Info(&g_tDataManage);
				
			
			//通过CAT模块发送参数修改信息到后台
			//标记CAT必发事件标记
			MachInfo.catMastSynServEvent.bit.paraSet = 1;
			MachInfo.catMastSynServEvent.bit.sendRunLog = 1;
			
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PARAMSET,(uint8_t*)&MachInfo.paramSet,sizeof(MachInfo.paramSet));
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_CAT_SYNC_SER_EVENT,(uint8_t*)&MachInfo.catMastSynServEvent,sizeof(MachInfo.catMastSynServEvent));
        
						
			CATQueueInfoBuf.msgType = SET_PARA_OVER_CAT_MSG_TYPE;
            osMessageQueuePut(CATQueueHandle,&CATQueueInfoBuf,0,0);
		}
		
		//判断下是否需要释放压力
		if(Press_Value() < -10000){
			//开液阀,放气
			LIQUID_WAVE_OPEN;
			osDelay(1500);
			LIQUID_WAVE_CLOSE;
			
			//进仓位置
			OutIn_Module_In(MOTOR_MODE_NORMAL);
		}
	  
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
        // USER END
        break;  
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
      case ID_BUTTON_3: // Notifications sent by 'HGB Debug'
      switch(NCode) {
         case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
         break;
         case WM_NOTIFICATION_RELEASED:
         {
           // USER START (Optionally insert code for reacting on notification message)
			 extern WM_HWIN CreateHGBDebugPage(void);
			 
           GUI_EndDialog(pMsg->hWin, 0);
			GUI_Exec();
           g_hActiveWin = CreateHGBDebugPage();
            // USER END
         }
         break;
      }
      break; 
	
	case ID_BUTTON_4: // Notifications sent by '压力校准'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  {
		 Msg_Head_t BackendMsg = {0};
		  
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateDialogPage();
		
		//保存对话框内容
		DialogPageData.bmpType = BMP_ALARM;
		DialogPageData.confimButt = NO_CONFIM_BUTTON;
		DialogPageData.fun = CreateParaSetPage;					
		strcpy(DialogPageData.str,g_ucaLng_SET_BuildPressing[MachInfo.systemSet.eLanguage]);
		
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.p = &DialogPageData;
		WM_SendMessage(g_hActiveWin,pMsg);
	  
		//往后台发送消息
		BackendMsg.usCmd = CMD_SET_BUILD_PRESSURE;
		UI_Put_Msg((uint8_t*)&BackendMsg);
	  }
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateParaSetPage
*/
WM_HWIN CreateParaSetPage(void);
WM_HWIN CreateParaSetPage(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
	//使能电机任务
    Enable_Motor_Task(TRUE);
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
