/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_eeprom.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_PRINTER_PAGE_ID + 0x00)
#define ID_TEXT_0 (CONFIG_PRINTER_PAGE_ID + 0x01)
#define ID_TEXT_1 (CONFIG_PRINTER_PAGE_ID + 0x02)
#define ID_TEXT_2 (CONFIG_PRINTER_PAGE_ID + 0x03)
#define ID_TEXT_3 (CONFIG_PRINTER_PAGE_ID + 0x04)
#define ID_EDIT_0 (CONFIG_PRINTER_PAGE_ID + 0x05)
#define ID_RADIO_0 (CONFIG_PRINTER_PAGE_ID + 0x06)
#define ID_BUTTON_0 (CONFIG_PRINTER_PAGE_ID + 0x07)
#define ID_BUTTON_1 (CONFIG_PRINTER_PAGE_ID + 0x08)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "PrinterSetPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET", ID_TEXT_0, 30, 15, 95, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> PRINTER", ID_TEXT_1, 125, 20, 140, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "TITLE", ID_TEXT_2, 245, 131, 100, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "MODE", ID_TEXT_3, 255, 192, 85, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Title_e", ID_EDIT_0, 351, 120, 260, 32, 0, 0x32, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 351, 182, 400, 60, 0, 0x1e02, 0 },
  { BUTTON_CreateIndirect, "CEL", ID_BUTTON_0, 265, 330, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CONFIM", ID_BUTTON_1, 415, 330, 120, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _PrinterSetPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRectEx(&Rect,19);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
    break;
    }
}




/*
* 设置控件回调函数，以及重绘控件
*/
static void _PrinterSetPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //取消按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _PrinterSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//确定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _PrinterSetPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  
    
  // USER START (Optionally insert additional variables)
	extern char* BKBmaDataBuf;
	extern MachInfo_s MachInfo;
	extern  __IO MachRunPara_s       MachRunPara;
	
	char StrTemp[60];
	uint8_t ParaChangeFlag = 0;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Set[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_Printer[MachInfo.systemSet.eLanguage]);
	
    //
    // Initialization of 'Title_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_Title[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'PrintMode_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_PrinterMode[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'Title_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
	RADIO_SetFont(hItem,&HZ_SONGTI_16);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,PRINTSET_TITILE_MAX_LEN-1);
	if(strlen(MachInfo.printSet.ucaPrintTitle) == 0){
		EDIT_SetText(hItem, g_ucaLng_SET_TitleInfo[MachInfo.systemSet.eLanguage]);
	}else{
		EDIT_SetText(hItem, MachInfo.printSet.ucaPrintTitle);
	}
	EDIT_SetInsertMode(hItem,1);
	
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
	RADIO_SetFont(hItem,&HZ_SONGTI_16);
    RADIO_SetText(hItem, g_ucaLng_SET_AutoPrinter[MachInfo.systemSet.eLanguage], 0);
    RADIO_SetText(hItem, g_ucaLng_SET_ManualPrinter[MachInfo.systemSet.eLanguage], 1);
	if(MachInfo.printSet.ePrintWay > 1){
		RADIO_SetValue(hItem,0);
	}else{
		RADIO_SetValue(hItem,MachInfo.printSet.ePrintWay);
	}
	//重绘按钮样式
	_PrinterSetPageRedrawWidgetType(pMsg);
    
    //设置窗口颜色
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	
  case WM_PAINT:
  {
	//画背景BMP图
	//GUI_BMP_Draw(BKBmaDataBuf,1,0);
    //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);   
     GUI_RECT Rect;
      WM_GetClientRect(&Rect); 
      GUI_SetColor(GUI_WHITE);
      GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

	//画线
	GUI_SetColor(0x009ea0a2);
	GUI_DrawHLine(54,8,790);
  
	//画打印方式边框
	GUI_SetColor(0x00cbcbcb);
	GUI_DrawRoundedRect(345,170,610,240,4);
  }
  break;
	
	//更新键盘事件
	case WM_KEYBOARD_UPDATE: 
	{
		char c;
		char ReportTitle[50];
		uint8_t i = strlen(pMsg->Data.p);
		hItem = WM_GetFocusedWindow();
		
		if(i == 1){								//输入ASCII码
			c = *((char*)pMsg->Data.p);
			GUI_StoreKeyMsg(c, 1);
		}else if(i == 3){						//输入汉字
			memset(ReportTitle,0,50);
			EDIT_GetText(hItem, ReportTitle, 50);
			strcat(ReportTitle, pMsg->Data.p);
			EDIT_SetText(hItem, ReportTitle);
			
		}
	}
	break;
	
	//键盘结束事件
	case WM_KEYBOARD_END:
		
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Title_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//唤出键盘
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_HZ;
		CreateKeyboard_Window();
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Cel_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'confim_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//保存参数
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		memset(StrTemp,0,sizeof(StrTemp));
		EDIT_GetText(hItem,StrTemp,50);
		if(strcmp(StrTemp,MachInfo.printSet.ucaPrintTitle) != 0){
			memset(MachInfo.printSet.ucaPrintTitle,0,sizeof(MachInfo.printSet.ucaPrintTitle));
			strcpy(MachInfo.printSet.ucaPrintTitle,StrTemp);
			ParaChangeFlag = 1;
		}
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		if(MachInfo.printSet.ePrintWay != RADIO_GetValue(hItem)){
			MachInfo.printSet.ePrintWay = RADIO_GetValue(hItem);
			ParaChangeFlag = 1;
		}
	  
		if(ParaChangeFlag == 1){
			//写入EEPROM
			EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PRINT_SET,(uint8_t*)&MachInfo.printSet,sizeof(MachInfo.printSet));
		}
	  
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatePrinterSetPage
*/
WM_HWIN CreatePrinterSetPage(void);
WM_HWIN CreatePrinterSetPage(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
