/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_eeprom.h"
#include "file_operate.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_RESET_PSW_PAGE_ID + 0x00)
#define ID_TEXT_0 (CONFIG_RESET_PSW_PAGE_ID + 0x01)
#define ID_TEXT_1 (CONFIG_RESET_PSW_PAGE_ID + 0x02)
#define ID_TEXT_2 (CONFIG_RESET_PSW_PAGE_ID + 0x03)
#define ID_EDIT_0 (CONFIG_RESET_PSW_PAGE_ID + 0x04)
#define ID_EDIT_1 (CONFIG_RESET_PSW_PAGE_ID + 0x05)
#define ID_EDIT_2 (CONFIG_RESET_PSW_PAGE_ID + 0x06)
#define ID_TEXT_3 (CONFIG_RESET_PSW_PAGE_ID + 0x07)
#define ID_TEXT_4 (CONFIG_RESET_PSW_PAGE_ID + 0x08)
#define ID_BUTTON_0 (CONFIG_RESET_PSW_PAGE_ID + 0x09)
#define ID_BUTTON_1 (CONFIG_RESET_PSW_PAGE_ID + 0x0A)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ResetPswPage", ID_WINDOW_0, 80, 65, 640, 380, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "OldPW", ID_TEXT_0, 98, 85, 150, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "NewPW", ID_TEXT_1, 98, 182, 150, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ConfimPW", ID_TEXT_2, 98, 240, 150, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "oldPsw_e", ID_EDIT_0, 268, 75, 184, 40, 0, 0xa, 0 },
  { EDIT_CreateIndirect, "newPsw_e", ID_EDIT_1, 268, 168, 184, 40, 0, 0xa, 0 },
  { EDIT_CreateIndirect, "confimPsw_e", ID_EDIT_2, 268, 226, 184, 40, 0, 0xa, 0 },
  { TEXT_CreateIndirect, "oldPswTip_t", ID_TEXT_3, 268, 125, 190, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "confimPswTip_t", ID_TEXT_4, 268, 270, 300, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEl", ID_BUTTON_0, 0, 340, 320, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Confim", ID_BUTTON_1, 320, 340, 320, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _ResetPswPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			switch(WM_GetId(pMsg->hWin)){
				//取消按钮
				case ID_BUTTON_0:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//确认按钮
				case ID_BUTTON_1:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			switch(WM_GetId(pMsg->hWin)){
				//取消按钮
				case ID_BUTTON_0:
					//画框
					GUI_SetColor(GUI_LIGHTGRAY);
					GUI_FillRect(Rect.x0,Rect.y0,Rect.x1,Rect.y1);
				
					//设置字符前景和背景色
					GUI_SetColor(GUI_WHITE);
					GUI_SetBkColor(GUI_LIGHTGRAY);
					GUI_DispStringInRect(g_ucaLng_Cancel[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				//确认按钮
				case ID_BUTTON_1:
					//填充
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
					GUI_FillRectEx(&Rect);
					
					//设置字符前景和背景色
					GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
					GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
				
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



static void _ResetPswPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
	//取消按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _ResetPswPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
    //确定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _ResetPswPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreateUserManagePage(void);
	extern  MachInfo_s	MachInfo;
	extern  __IO MachRunPara_s       MachRunPara;
	
//	static uint8_t KeyBoardUseOnceFlag = 0;						//是否已经唤出键盘标志
	static uint8_t MoveWindowFlag = 0;							//是否移动了窗口标志
	static uint8_t MoveWindowYValue = 0;						//移动窗口的Y轴偏移量
	static uint8_t CurrentUser = 0;								//用于表示当前要修改那个账户的索引值
	
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	char Str[30];
	char Str2[30];
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'oldPsw_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_OldPW[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'newPsw_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_NewPW[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'confimPsw_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_ConfimPW[MachInfo.systemSet.eLanguage]);
    //
    // Initialization of 'oldPsw_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,ACCOUNT_PSW_MAX_LEN-1);
    //
    // Initialization of 'newPsw_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,ACCOUNT_PSW_MAX_LEN-1);
    //
    // Initialization of 'confimPsw_e'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	EDIT_SetMaxLen(hItem,ACCOUNT_PSW_MAX_LEN-1);
    //
    // Initialization of 'oldPswTip_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
	TEXT_SetText(hItem,"");
    //
    // Initialization of 'confimPswTip_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
	TEXT_SetText(hItem,"");
	
	//重绘按钮样式
	_ResetPswPageRedrawWidgetType(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	
  case WM_PAINT:
	//先设置弹窗和背景为相同的透明度
	GUI_SetAlpha(30);
	GUI_SetColor(0x00525a4e);
	GUI_FillRectEx(&Rect);
	GUI_SetAlpha(0);
  
	//重绘弹窗为圆角矩形
	GUI_SetColor(0x00ffffff);
	GUI_AA_FillRoundedRectEx(&Rect,6);
  
	//重绘顶部标题栏，采用重叠法
	GUI_SetColor(MachInfo.companyInfo.skin.title);
	GUI_AA_FillRoundedRect(Rect.x0,Rect.y0,Rect.x1,Rect.y0+15,6);
	GUI_FillRect(Rect.x0,Rect.y0+10,Rect.x1,Rect.y0+38);
	
	//标题
	GUI_SetFont(&HZ_SONGTI_16);
	GUI_SetColor(MachInfo.companyInfo.skin.titleFont);
	GUI_SetBkColor(MachInfo.companyInfo.skin.title);
	GUI_DispStringHCenterAt(g_ucaLng_SET_ChangePW[MachInfo.systemSet.eLanguage],320,10);
  break;
  
  //键盘更新事件
  case WM_KEYBOARD_UPDATE:
  {
		hItem = WM_GetFocusedWindow();
		Id = WM_GetId(hItem);

		//ASCII码
		if(strlen(pMsg->Data.p) == 1){
			if(Id == ID_EDIT_0 || Id == ID_EDIT_1 || Id == ID_EDIT_2){
				if(*((char*)pMsg->Data.p) != ' '){
					GUI_StoreKeyMsg(*((char*)pMsg->Data.p),1);
				}
			}else{
				GUI_StoreKeyMsg(*((char*)pMsg->Data.p),1);
			}
		}
  }break;
  
  //键盘结束事件
  case WM_KEYBOARD_END:
//	  if(KeyBoardUseOnceFlag == 1){
//		KeyBoardUseOnceFlag = 0;
//	  }
	  
	  //判断是否移动了窗口，是，则还原
	  if(MoveWindowFlag == 1){
		MoveWindowFlag = 0;
		WM_MoveWindow(pMsg->hWin,0,MoveWindowYValue);
	  }
	  
//	  WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_EDIT_0));
//	  WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_EDIT_1));
//	  WM_EnableWindow(WM_GetDialogItem(pMsg->hWin,ID_EDIT_2));
  break;
	  
  case WM_USER_DATA:
	  CurrentUser = pMsg->Data.v;
  break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'oldPsw_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
//		if(KeyBoardUseOnceFlag == 0){
//			KeyBoardUseOnceFlag = 1;
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
			
			//失能其他编辑框
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2));
//		}
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'newPsw_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
//		if(KeyBoardUseOnceFlag == 0){
//			KeyBoardUseOnceFlag = 1;
      
            if(0 == MoveWindowFlag)
            {
                MoveWindowFlag = 1;
                
                //移动窗口
                MoveWindowYValue = 20;
                WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
                
                //唤出键盘
                WM_SetFocus(pMsg->hWinSrc);
				MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
                CreateKeyboard_Window();
            }
			
			//失能其他编辑框
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2));
//		}
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'confimPsw_e'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
//		if(KeyBoardUseOnceFlag == 0){
//			KeyBoardUseOnceFlag = 1;
      
            if(0 == MoveWindowFlag)
            {
                MoveWindowFlag = 1;
                
                //移动窗口
                MoveWindowYValue = 80;
                WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
                
                //唤出键盘
                WM_SetFocus(pMsg->hWinSrc);
				MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
                CreateKeyboard_Window();
            }
			
			//失能其他编辑框
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0));
//			WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1));
//		}
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'cel_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateUserManagePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'confim_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		memset(Str,0,30);
		hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
		EDIT_GetText(hItem,Str,30);
	  
		//先判断
		if(strcmp(Str,MachInfo.accountMM.accountInfo[CurrentUser].psw) != 0){
			hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_3);
			TEXT_SetText(hItem,g_ucaLng_SET_OldPWErr[MachInfo.systemSet.eLanguage]);
		}else{
			hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_3);
			TEXT_SetText(hItem,"");
			
			memset(Str,0,30);
			memset(Str2,0,30);
			
			hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_1);
			EDIT_GetText(hItem,Str,30);
			hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_2);
			EDIT_GetText(hItem,Str2,30);
			
			if(strlen(Str2) == 0 || strlen(Str) == 0){
				hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_4);
				TEXT_SetText(hItem,g_ucaLng_SET_EnterNewPW[MachInfo.systemSet.eLanguage]);
			}else if(strcmp(Str,Str2) != 0){
				hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_4);
				TEXT_SetText(hItem,g_ucaLng_SET_PWNotMatch[MachInfo.systemSet.eLanguage]);
			}else{
				//运行日志缓存区
				RunLog_s RunLog = {0};
				RTC_HYM8563Info_s RTCInfo = {0};
                uint32_t ulIndex = 0;
				
				//保存运行日志
				RunLog.logHead.num = g_tDataManage.ulRunLog_SN;//g_tDataManage.lastRunLogNum;
				RunLog.logHead.eAccountType = MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type;
				RTC_HYM8563GetTime(&RTCInfo);
				sprintf(RunLog.logHead.dataTime,"20%d%d-%d%d-%d%d %d%d:%d%d:%d%d",
								RTCInfo.year.bcd_h,RTCInfo.year.bcd_l,
								RTCInfo.month.bcd_h,RTCInfo.month.bcd_l,
								RTCInfo.day.bcd_h,RTCInfo.day.bcd_l,
								RTCInfo.hour.bcd_h,RTCInfo.hour.bcd_l,
								RTCInfo.min.bcd_h,RTCInfo.min.bcd_l,
								RTCInfo.sec.bcd_h,RTCInfo.sec.bcd_l);
				sprintf(RunLog.logHead.shortStr,"Change Password");
				RunLog.logHead.logLen += sprintf(RunLog.Str+RunLog.logHead.logLen,"Password of user %s was changed",MachInfo.accountMM.accountInfo[CurrentUser].user);
				RunLog.Str[RunLog.logHead.logLen] = '\0';
				RunLog.logHead.timestamp = GetCurrentTimestamp(RTCInfo);
                RunLog.usCrc = CRC16((uint8_t*)&RunLog, sizeof(RunLog_s)-2);
                
                ulIndex = Update_RunLog_Tail();
				Fatfs_Write_RunLog(ulIndex, &RunLog);
				
				g_tDataManage.ulRunLog_SN++;//g_tDataManage.lastRunLogNum++;
                Add_RunLog_Tail();
				Save_DataMange_Info(&g_tDataManage);
				
				hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_4);
				TEXT_SetText(hItem,"");
				
				//保存更新密码
				strcpy(MachInfo.accountMM.accountInfo[CurrentUser].psw,Str);
				EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_ACCOUNT_MM,(uint8_t*)&MachInfo.accountMM,sizeof(MachInfo.accountMM));
				
				//标记CAT必发项
				if(MachInfo.catMastSynServEvent.bit.sendRunLog != 1){
					MachInfo.catMastSynServEvent.bit.sendRunLog = 1;
					EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_CAT_SYNC_SER_EVENT,(uint8_t*)&MachInfo.catMastSynServEvent,sizeof(MachInfo.catMastSynServEvent));
				}
				
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateUserManagePage();
			}
		}
	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateResetPswPage
*/
WM_HWIN CreateResetPswPage(void);
WM_HWIN CreateResetPswPage(void) {
  WM_HWIN hWin;
	
	WM_SetCallback(WM_HBKWIN, NotAlphaBk_cbBkWin);
	Public_Hide_Widget();
	
	Disable_Algo_Task();

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
