/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
/*
*
*   设置界面
*
*/
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (CONFIG_MAIN_PAGE_ID + 0x00)
#define ID_TEXT_0  (CONFIG_MAIN_PAGE_ID + 0x01)
#define ID_BUTTON_0  (CONFIG_MAIN_PAGE_ID + 0x02)
#define ID_BUTTON_1  (CONFIG_MAIN_PAGE_ID + 0x03)
#define ID_BUTTON_2  (CONFIG_MAIN_PAGE_ID + 0x04)
#define ID_BUTTON_3  (CONFIG_MAIN_PAGE_ID + 0x05)
#define ID_BUTTON_4  (CONFIG_MAIN_PAGE_ID + 0x06)
#define ID_BUTTON_5  (CONFIG_MAIN_PAGE_ID + 0x07)
#define ID_BUTTON_6  (CONFIG_MAIN_PAGE_ID + 0x08)
#define ID_BUTTON_7  (CONFIG_MAIN_PAGE_ID + 0x09)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)

//用于设置主界面图标背景的BMP图相关变量
GUI_HMEM hMemICONBMP_Conf;
char* ICONBmaDataBuf_Conf;
uint32_t ICONBMPBufLen_Conf;

// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "configPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET", ID_TEXT_0, 30, 15, 90, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "sys_b", ID_BUTTON_0, 154, 99, 116, 116, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "user_b", ID_BUTTON_1, 285, 99, 116, 116, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "fuzhu_b", ID_BUTTON_2, 416, 99, 116, 116, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "printer_b", ID_BUTTON_3, 547, 99, 116, 116, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "lab_b", ID_BUTTON_4, 154, 225, 116, 116, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "jiaozhun_b", ID_BUTTON_5, 285, 225, 116, 116, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "para_b", ID_BUTTON_6, 416, 225, 116, 116, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "test_b", ID_BUTTON_7, 547, 225, 116, 116, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
// USER START (Optionally insert additional static code)
//自定义此窗口所有控件的回调函数
static void Config_M_Btn_Callback(WM_MESSAGE* pMsg)
{
	extern GUI_HMEM hMemICONBMP_Conf;
	extern char* ICONBmaDataBuf_Conf;
	extern uint32_t ICONBMPBufLen_Conf;
	extern __IO MachRunPara_s	MachRunPara;
	extern  MachInfo_s	MachInfo;
	
//	GUI_HMEM hMemICONFrontBMP;						
//	char* ICONBmaDataFrontBuf;
//	uint32_t ICONFrontBMPBufLen;
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//画ICON的BMP背景图
            Show_BK_BMP(BK_SDRAM, BK_PICTURE_OTHERS_IconBkBig, Rect.x0+1,Rect.y0+1); 

			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_Sys, Rect.x0+35,Rect.y0+15);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_XiTong[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_1:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_User, Rect.x0+35,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_YongHu[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_2:
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_FuZhuUnactive, Rect.x0+35,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_FuZhu, Rect.x0+35,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_FuZhu[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_3:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_Printer, Rect.x0+35,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_DaYing[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_4:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_LabInfo, Rect.x0+35,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_ShiYanShi[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_5:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority){
						Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_JiaoZhunGray, Rect.x0+35,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_JiaoZhun, Rect.x0+35,Rect.y0+15);
					}
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_JiaoZhun[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_6:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_Para, Rect.x0+35,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_ParaGray, Rect.x0+35,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_Canshu[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_7:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_Test, Rect.x0+35,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_TestGray, Rect.x0+35,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_TiaoShi[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				default :break;
			}
        }
        else {
			//画ICON的BMP背景图
            Show_BK_BMP(BK_SDRAM, BK_PICTURE_OTHERS_IconBkBig, Rect.x0+1,Rect.y0+1); 


			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_Sys, Rect.x0+35,Rect.y0+15);
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_XiTong[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_1:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_User, Rect.x0+35,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_YongHu[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_2:
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_FuZhuUnactive, Rect.x0+35,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_FuZhu, Rect.x0+35,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_FuZhu[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_3:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_Printer, Rect.x0+35,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_DaYing[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_4:
					//画图标
                    Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_LabInfo, Rect.x0+35,Rect.y0+15);
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_ShiYanShi[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_5:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority){
						Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_JiaoZhunGray, Rect.x0+35,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_JiaoZhun, Rect.x0+35,Rect.y0+15);
					}
					
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_JiaoZhun[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_6:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_Para, Rect.x0+35,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_ParaGray, Rect.x0+35,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_Canshu[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				
				case ID_BUTTON_7:
					//画图标
					//根据不同用户权限，读取不同图标
					if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_Test, Rect.x0+35,Rect.y0+15);
					}else{
                        Show_BK_BMP(BK_SDRAM, BK_PICTURE_SET_TestGray, Rect.x0+35,Rect.y0+15);
					}
				
					GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
					GUI_SetBkColor(GUI_WHITE);
					GUI_DispStringHCenterAt(g_ucaLng_SET_TiaoShi[MachInfo.systemSet.eLanguage],Rect.x0+58,Rect.y0+78);
				break;
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}






/*
* 设置控件回调函数，以及重绘控件
*/
static void config_Data_Updata(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;

    //系统设置
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, Config_M_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//用户管理
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, Config_M_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//辅助设置
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);  
    WM_SetCallback(hItem, Config_M_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//打印设置
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, Config_M_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//实验室信息
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, Config_M_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//校准
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, Config_M_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//参数设置
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, Config_M_Btn_Callback);
    WM_InvalidateWindow(hItem);
	
	//调试功能
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);  
    WM_SetCallback(hItem, Config_M_Btn_Callback);
    WM_InvalidateWindow(hItem);
}





// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
    
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreatesysConfigPage(void);
	extern WM_HWIN Createlab_infoPage(void);
	extern WM_HWIN CreateParaSetPage(void);
	extern WM_HWIN CreatedebugPage(void);
	extern WM_HWIN CreatePrinterSetPage(void);
	extern WM_HWIN CreateFuzhuConfigPage(void);
	extern WM_HWIN CreateUserManagePage(void);
	
	extern GUI_HMEM hMemICONBMP_Conf;
	extern char* ICONBmaDataBuf_Conf;
	extern uint32_t ICONBMPBufLen_Conf;
	extern char* BKBmaDataBuf;
	extern __IO MachRunPara_s	MachRunPara;
	extern MachInfo_s MachInfo;
	
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'configPage'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00F5E6C5));
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Set[MachInfo.systemSet.eLanguage]);
  
	//根据不同的用户权限，开放按键
	if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
		hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6);
		WM_DisableWindow(hItem);
		
		hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7);
		WM_DisableWindow(hItem);
	}
	
	if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority){
		hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2);
		WM_DisableWindow(hItem);
		
		hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5);
		WM_DisableWindow(hItem);
	}
	
	
    // USER START (Optionally insert additional code for further widget initialization)
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    
    // USER END
    break;
  case WM_DELETE:
	  //释放内存
	//GUI_ALLOC_Free(hMemICONBMP_Conf);
  break;
  
  case WM_PAINT:
	  //画背景BMP图
    //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
    
      WM_GetClientRect(&Rect); 
      GUI_SetColor(GUI_WHITE);
      GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);	

	//画线
	GUI_SetColor(0x009ea0a2);
	GUI_DrawHLine(54,8,790);
  
	config_Data_Updata(pMsg);
  break;
  case WM_MOTOR_ERROR_PROMPT:
  {
      Motor_Error_Prompt(pMsg, CreateSetPage);   
  }
  break;  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'sys_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatesysConfigPage();
	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'user_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateUserManagePage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'fuzhu_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateFuzhuConfigPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'printer_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatePrinterSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'lab_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = Createlab_infoPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'jiaozhun_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = Calibration_CreateWindow();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'para_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateParaSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'test_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatedebugPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSetPage
*/
WM_HWIN CreateSetPage(void);
WM_HWIN CreateSetPage(void) {
	
    WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
