/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_eeprom.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_SET_SKIN_PAGE_ID + 0x00)
#define ID_TEXT_0 (CONFIG_SET_SKIN_PAGE_ID + 0x01)
#define ID_TEXT_1 (CONFIG_SET_SKIN_PAGE_ID + 0x02)
#define ID_TEXT_1 (CONFIG_SET_SKIN_PAGE_ID + 0x02)
#define ID_BUTTON_0 (CONFIG_SET_SKIN_PAGE_ID + 0x03)
#define ID_BUTTON_1 (CONFIG_SET_SKIN_PAGE_ID + 0x04)
#define ID_TEXT_2 (CONFIG_SET_SKIN_PAGE_ID + 0x05)
#define ID_TEXT_3 (CONFIG_SET_SKIN_PAGE_ID + 0x06)
#define ID_TEXT_4 (CONFIG_SET_SKIN_PAGE_ID + 0x07)
#define ID_TEXT_5 (CONFIG_SET_SKIN_PAGE_ID + 0x08)
#define ID_TEXT_6 (CONFIG_SET_SKIN_PAGE_ID + 0x09)
#define ID_TEXT_7 (CONFIG_SET_SKIN_PAGE_ID + 0x0A)
#define ID_TEXT_8 (CONFIG_SET_SKIN_PAGE_ID + 0x0B)
#define ID_TEXT_9 (CONFIG_SET_SKIN_PAGE_ID + 0x0C)
#define ID_TEXT_10 (CONFIG_SET_SKIN_PAGE_ID + 0x0D)
#define ID_TEXT_11 (CONFIG_SET_SKIN_PAGE_ID + 0x0E)
#define ID_TEXT_12 (CONFIG_SET_SKIN_PAGE_ID + 0x0F)
#define ID_TEXT_13 (CONFIG_SET_SKIN_PAGE_ID + 0x10)

#define ID_EDIT_0 (CONFIG_SET_SKIN_PAGE_ID + 0x11)
#define ID_EDIT_1 (CONFIG_SET_SKIN_PAGE_ID + 0x12)
#define ID_EDIT_2 (CONFIG_SET_SKIN_PAGE_ID + 0x13)
#define ID_EDIT_3 (CONFIG_SET_SKIN_PAGE_ID + 0x14)
#define ID_EDIT_4 (CONFIG_SET_SKIN_PAGE_ID + 0x15)
#define ID_EDIT_5 (CONFIG_SET_SKIN_PAGE_ID + 0x16)
#define ID_EDIT_6 (CONFIG_SET_SKIN_PAGE_ID + 0x17)
#define ID_EDIT_7 (CONFIG_SET_SKIN_PAGE_ID + 0x18)
#define ID_EDIT_8 (CONFIG_SET_SKIN_PAGE_ID + 0x19)
#define ID_EDIT_9 (CONFIG_SET_SKIN_PAGE_ID + 0x1A)
#define ID_EDIT_10 (CONFIG_SET_SKIN_PAGE_ID + 0x1B)
#define ID_EDIT_11 (CONFIG_SET_SKIN_PAGE_ID + 0x1C)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET_t", ID_TEXT_0, 30, 15, 95, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> SetSkin_t", ID_TEXT_1, 125, 20, 140, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEL_b", ID_BUTTON_0, 265, 330, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CONFIRM_b", ID_BUTTON_1, 415, 330, 120, 40, 0, 0x0, 0 },
  
  { TEXT_CreateIndirect, "背景_t", ID_TEXT_2, 60, 85, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "背景_e", ID_EDIT_0, 270, 85, 110, 25, 0, 0x8, 0 },
  
  { TEXT_CreateIndirect, "标题栏_t", ID_TEXT_3, 60, 120, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "标题栏_e", ID_EDIT_1, 270, 120, 110, 25, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "标题栏字符_t", ID_TEXT_9, 400, 120, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "标题栏字符_e", ID_EDIT_7, 610, 120, 110, 25, 0, 0x8, 0 },
  
  { TEXT_CreateIndirect, "按钮未点击色_t", ID_TEXT_4, 60, 155, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "按钮未点击色_e", ID_EDIT_2, 270, 155, 110, 25, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "按钮未点击字符色_t", ID_TEXT_10, 400, 155, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "按钮未点击字符色_e", ID_EDIT_8, 610, 155, 110, 25, 0, 0x8, 0 },
  
  { TEXT_CreateIndirect, "按钮点击色_t", ID_TEXT_5, 60, 190, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "按钮点击色_e", ID_EDIT_3, 270, 190, 110, 25, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "按钮点击色字符_t", ID_TEXT_11, 400, 190, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "按钮点击色字符_e", ID_EDIT_9, 610, 190, 110, 25, 0, 0x8, 0 },
  
  { TEXT_CreateIndirect, "按钮边框色_t", ID_TEXT_6, 60, 225, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "按钮边框色_e", ID_EDIT_4, 270, 225, 110, 25, 0, 0x8, 0 },
  
  { TEXT_CreateIndirect, "突出控件未选中色_t", ID_TEXT_7, 60, 260, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "突出控件未选中色_e", ID_EDIT_5, 270, 260, 110, 25, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "突出控件未选中字符色_t", ID_TEXT_12, 400, 260, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "突出控件未选中字符色_e", ID_EDIT_10, 610, 260, 110, 25, 0, 0x8, 0 },
  
  { TEXT_CreateIndirect, "突出控件选中色_t", ID_TEXT_8, 60, 295, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "突出控件选中色_e", ID_EDIT_6, 270, 295, 110, 25, 0, 0x8, 0 },
  { TEXT_CreateIndirect, "突出控件选中字符色_t", ID_TEXT_13, 400, 295, 200, 25, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "突出控件选中字符色_e", ID_EDIT_11, 610, 295, 110, 25, 0, 0x8, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _ButtonRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("取消",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("确定",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRectEx(&Rect,19);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect("取消",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect("确定",&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
    break;
    }
}


/*
* 设置控件回调函数，以及重绘控件
*/
static void _ButtonRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //返回按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//确认按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _ButtonRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}


/***
*将16进制字符串转化成数值
***/
static uint32_t _Convert16StrToInt(char* Str)
{
	uint32_t U32Temp = 0;
	uint16_t i = 0;
	uint16_t Len = strlen(Str);
	
	if(Str == NULL || Len == 0){
		return 0;
	}
	
	for(i=0;i<Len;i++){
		if(*(Str+i) == '\0'){
			return U32Temp;
		}
		
		if(*(Str+i) >= 'a' && *(Str+i) <= 'f'){
			U32Temp = U32Temp*16+(*(Str+i) - 'a' + 10);
		}
		
		if(*(Str+i) >= 'A' && *(Str+i) <= 'F'){
			U32Temp = U32Temp*16+(*(Str+i) - 'A' + 10);
		}
		
		if(*(Str+i) >= '0' && *(Str+i) <= '9'){
			U32Temp = U32Temp*16+(*(Str+i) - '0');
		}
	}
	
	return U32Temp;
}


// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	extern MachInfo_s MachInfo;
	uint16_t U16Temp = 0;
	uint32_t U32Temp = 0;
	char c;
	static uint8_t MoveWindowFlag = 0;							//是否移动了窗口标志
	static uint8_t MoveWindowYValue = 0;						//移动窗口的Y轴偏移量
	char Buf[15] = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	TEXT_SetFont(hItem,&HZ_SONGTI_24);
	WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"设置");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,"> 皮肤(GBR)");
	
	//重绘按钮样式
	_ButtonRedrawWidgetType(pMsg);
	//设置窗口颜色和背景颜色一致
	WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);  
	
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"背景色(0x)");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"标题栏(0x)");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"按钮未点击色(0x)");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"按钮点击色(0x)");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"按钮边框色(0x)");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"突出控件未选中色(0x)");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"突出控件选中色(0x)");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"标题栏字符色(0x)");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"按钮未点击字符色(0x)");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"按钮点击字符色(0x)");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"突出控件未选中字符色(0x)");
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,"突出控件选中字符色(0x)");

	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.bg);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.bg);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.title);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.title);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.buttNotPress);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.buttNotPress);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.buttPress);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.buttPress);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.buttBoard);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.buttBoard);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.highlightKJNotSelect);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.highlightKJNotSelect);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.highlightKJSelect);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.highlightKJSelect);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.titleFont);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.titleFont);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.buttNotPressFont);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.buttNotPressFont);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.buttPressFont);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.buttPressFont);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.highlightKHNotSelectFont);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.highlightKHNotSelectFont);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
    EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	EDIT_EnableBlink(hItem,500,1);
	U16Temp = sprintf(Buf,"%06x",MachInfo.companyInfo.skin.highlightKJSelectFont);
	Buf[U16Temp] = '\0';
    EDIT_SetText(hItem, Buf);
	EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,MachInfo.companyInfo.skin.highlightKJSelectFont);
	
	
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
	
  case WM_PAINT:
  {
	  GUI_RECT Rect;
	  
	//画背景BMP图
    WM_GetClientRect(&Rect); 
    GUI_SetColor(GUI_WHITE);
    GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

	//画线
	GUI_SetColor(0x009ea0a2);
	GUI_DrawHLine(54,8,790);
  }break;
  
  //键盘更新事件
  case WM_KEYBOARD_UPDATE:
  {
	U16Temp = strlen(pMsg->Data.p);
	c = *((char*)pMsg->Data.p);
	
	//ASCII码
	if(U16Temp == 1){
		//只能输入数字和a~f
		if((c>='0'&&c<='9') || (c>='a'&&c<='f') || (c>='A'&&c<='F')){
			GUI_StoreKeyMsg(c,1);
		}
	}
  }break;
  
  //键盘结束事件
  case WM_KEYBOARD_END:
	  //判断是否移动了窗口，是，则还原
	  if(MoveWindowFlag == 1){
		MoveWindowFlag = 0;
		WM_MoveWindow(pMsg->hWin,0,MoveWindowYValue);
	  }
  break;

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'CEL_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  {
		extern WM_HWIN CreateSetPage(void);
		
		  GUI_EndDialog(pMsg->hWin, 0);
		  g_hActiveWin = CreateSetPage();
	  }
		
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'CONFIRM_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.bg = U32Temp;
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.title = U32Temp;
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.buttNotPress = U32Temp;
	  
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.buttPress = U32Temp;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.buttBoard = U32Temp;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.highlightKJNotSelect = U32Temp;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.highlightKJSelect = U32Temp;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.titleFont = U32Temp;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.buttNotPressFont = U32Temp;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.buttPressFont = U32Temp;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.highlightKHNotSelectFont = U32Temp;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		MachInfo.companyInfo.skin.highlightKJSelectFont = U32Temp;
		
		EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_COMPANY+((uint8_t*)&MachInfo.companyInfo.skin-(uint8_t*)&MachInfo.companyInfo),(uint8_t*)&MachInfo.companyInfo.skin,sizeof(MachInfo.companyInfo.skin));
	  
		GUI_EndDialog(pMsg->hWin, 0);
		g_hActiveWin = CreateSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by '背景色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		//唤出键盘
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
		CreateKeyboard_Window();
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by '标题栏'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
		CreateKeyboard_Window();
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by '按钮未点击色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
		CreateKeyboard_Window();
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by '按钮点击色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 20;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	
	case ID_EDIT_4: // Notifications sent by '按钮边框色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 70;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	
    case ID_EDIT_5: // Notifications sent by '突出控件未选中色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 100;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_6: // Notifications sent by '突出控件选中色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 130;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_EDIT_7: // Notifications sent by '标题栏字符'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
		CreateKeyboard_Window();
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_EDIT_8: // Notifications sent by '按钮未点击字符色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		WM_SetFocus(pMsg->hWinSrc);
		MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
		CreateKeyboard_Window();
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_8);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_EDIT_9: // Notifications sent by '按钮点击字符色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 20;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_9);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_EDIT_10: // Notifications sent by '突出控件未选中字符色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 100;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_10);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_EDIT_11: // Notifications sent by '突出控件选中字符色'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MoveWindowFlag != 1){
			MoveWindowFlag = 1;
			
			//移动窗口
			MoveWindowYValue = 130;
			WM_MoveWindow(pMsg->hWin,0,-MoveWindowYValue);
			
			//唤出键盘
			WM_SetFocus(pMsg->hWinSrc);
			MachRunPara.keyboardInitJM = KEYBOARD_CHAR;
			CreateKeyboard_Window();
          }
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_11);
		memset(Buf,0,sizeof(Buf));
		EDIT_GetText(hItem,Buf,sizeof(Buf));
		U32Temp = _Convert16StrToInt(Buf);
		EDIT_SetBkColor(hItem,EDIT_CI_ENABLED,U32Temp);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break; 
	 
	
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateSetSkinWindow(void);
WM_HWIN CreateSetSkinWindow(void) {
  WM_HWIN hWin;

	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();
	
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
