/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_rtc.h"
#include "bsp_eeprom.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_SYS_PAGE_ID + 0x00)
#define ID_TEXT_0 (CONFIG_SYS_PAGE_ID + 0x01)
#define ID_TEXT_1 (CONFIG_SYS_PAGE_ID + 0x02)
#define ID_TEXT_2 (CONFIG_SYS_PAGE_ID + 0x03)
#define ID_TEXT_3 (CONFIG_SYS_PAGE_ID + 0x04)
#define ID_TEXT_4 (CONFIG_SYS_PAGE_ID + 0x05)
#define ID_BUTTON_0 (CONFIG_SYS_PAGE_ID + 0x06)
#define ID_BUTTON_1 (CONFIG_SYS_PAGE_ID + 0x07)
#define ID_DROPDOWN_0 (CONFIG_SYS_PAGE_ID + 0x08)
#define ID_BUTTON_2 (CONFIG_SYS_PAGE_ID + 0x09)
#define ID_BUTTON_3 (CONFIG_SYS_PAGE_ID + 0x0A)
#define ID_TEXT_5 (CONFIG_SYS_PAGE_ID + 0x0B)
#define ID_DROPDOWN_1 (CONFIG_SYS_PAGE_ID + 0x0C)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "sysConfigPage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET", ID_TEXT_0, 30, 15, 95, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> SYSTEM", ID_TEXT_1, 125, 20, 150, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "DATE", ID_TEXT_2, 99, 131, 40, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "TIME", ID_TEXT_3, 99, 190, 40, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "LANGUAGE", ID_TEXT_4, 439, 131, 72, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "date_b", ID_BUTTON_0, 146, 119, 200, 42, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "time_b", ID_BUTTON_1, 146, 181, 200, 42, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "langu_d", ID_DROPDOWN_0, 523, 123, 180, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEL", ID_BUTTON_2, 265, 330, 120, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CONFIM", ID_BUTTON_3, 415, 330, 120, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "dataNum_t", ID_TEXT_5, 392, 190, 120, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "dataNum_d", ID_DROPDOWN_1, 523, 182, 180, 60, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static int _Button_DrawSkin(const WIDGET_ITEM_DRAW_INFO* pDrawItemInfo)
{
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
	switch(pDrawItemInfo->Cmd){
		case WIDGET_ITEM_DRAW_BACKGROUND:
			if(BUTTON_IsPressed(pDrawItemInfo->hWin)){
				switch(WM_GetId(pDrawItemInfo->hWin)){
					case ID_BUTTON_0:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,4);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,4);
					
						GUI_SetPenSize(3);
						GUI_AA_DrawLine(167,18,174,24);
						GUI_AA_DrawLine(174,24,180,18);
					break;
					
					case ID_BUTTON_1:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,4);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,4);
						GUI_SetPenSize(3);
						GUI_AA_DrawLine(167,18,174,24);
						GUI_AA_DrawLine(174,24,180,18);
					break;
					
					case ID_BUTTON_2:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
					
					case ID_BUTTON_3:
						GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					break;
				}
			}else{
				switch(WM_GetId(pDrawItemInfo->hWin)){
					case ID_BUTTON_0:
						GUI_SetColor(0x00a2a09e);
						GUI_AA_DrawRoundedRectEx(&Rect,4);
					
						GUI_SetPenSize(3);
						GUI_AA_DrawLine(167,18,174,24);
						GUI_AA_DrawLine(174,24,180,18);
					break;
					
					case ID_BUTTON_1:
						GUI_SetColor(0x00a2a09e);
						GUI_AA_DrawRoundedRectEx(&Rect,4);
					
						GUI_SetPenSize(3);
						GUI_AA_DrawLine(167,18,174,24);
						GUI_AA_DrawLine(174,24,180,18);
					break;
					
					case ID_BUTTON_2:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
					
					case ID_BUTTON_3:
						GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
						GUI_AA_FillRoundedRectEx(&Rect,20);
					
						GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
						GUI_AA_DrawRoundedRectEx(&Rect,19);
					break;
				}
			}
		break;
		default:
			return BUTTON_SKIN_FLEX(pDrawItemInfo);
	}
	return 0;
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  GUI_RECT Rect;
    
  // USER START (Optionally insert additional variables)
	extern char* BKBmaDataBuf;
	extern MachInfo_s MachInfo;
	extern  __IO MachRunPara_s       MachRunPara;
	extern WM_HWIN CreatedataTimeSetPage(void);
	extern OutSideDataNum_s OutSideDataNum;
	
	DROPDOWN_SKINFLEX_PROPS pProps;
	RTC_HYM8563Info_s RTCInfo = {0};
	char Str[30] = {0};
	uint16_t i = 0;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Set[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_Sys[MachInfo.systemSet.eLanguage]);
  
    //
    // Initialization of 'date_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_Date[MachInfo.systemSet.eLanguage]); 
    //
    // Initialization of 'time_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_Time[MachInfo.systemSet.eLanguage]); 
    //
    // Initialization of 'langu_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_Language[MachInfo.systemSet.eLanguage]); 
    //
    // Initialization of 'langu_d'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_SetListHeight(hItem, 55);							//下拉框要足够高，否则会导致项被隐藏
	DROPDOWN_SetTextAlign(hItem,GUI_TA_LEFT|GUI_TA_VCENTER);
	DROPDOWN_SetTextHeight(hItem,30);
	DROPDOWN_SetFont(hItem,&HZ_SONGTI_16);
	DROPDOWN_SetItemSpacing(hItem,10);
	DROPDOWN_AddString(hItem,g_ucaLng_SET_Chinese[MachInfo.systemSet.eLanguage]);
	DROPDOWN_AddString(hItem,g_ucaLng_SET_English[MachInfo.systemSet.eLanguage]);
	DROPDOWN_SetSel(hItem,MachInfo.systemSet.eLanguage);
	DROPDOWN_SetBkColor(hItem,DROPDOWN_CI_SEL,MachInfo.companyInfo.skin.highlightKJNotSelect);
	DROPDOWN_SetBkColor(hItem,DROPDOWN_CI_SELFOCUS,MachInfo.companyInfo.skin.highlightKJNotSelect);
	//
    // Initialization of 'dataNum_t'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetText(hItem,g_ucaLng_SET_DataNum[MachInfo.systemSet.eLanguage]); 
    //
    // Initialization of 'dataNum_d'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
    DROPDOWN_SetListHeight(hItem, 55);							//下拉框要足够高，否则会导致项被隐藏
	DROPDOWN_SetTextAlign(hItem,GUI_TA_LEFT|GUI_TA_VCENTER);
	DROPDOWN_SetTextHeight(hItem,30);
	DROPDOWN_SetFont(hItem,&HZ_SONGTI_16);
	DROPDOWN_SetItemSpacing(hItem,10);
	DROPDOWN_SetBkColor(hItem,DROPDOWN_CI_SEL,MachInfo.companyInfo.skin.highlightKJNotSelect);
	DROPDOWN_SetBkColor(hItem,DROPDOWN_CI_SELFOCUS,MachInfo.companyInfo.skin.highlightKJNotSelect);
	for(i=0;i<OUTSIDE_DATA_NUM_MODE_NUM;i++){
		memset(Str,0,10);
		sprintf(Str,"%u",OutSideDataNum.dataNum[i]);
		DROPDOWN_AddString(hItem,Str);
	}
	DROPDOWN_SetSel(hItem,OutSideDataNum.index);
	
	//语言切换功能和数据容量选择功能只能在超级管理员账号下才能看到
	if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_TEXT_4));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1));
		WM_HideWindow(WM_GetDialogItem(pMsg->hWin,ID_TEXT_5));
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		WM_SetWindowPos(hItem,99+180, 131+63, 40, 20);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		WM_SetWindowPos(hItem,99+180, 190+63, 40, 20);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		WM_SetWindowPos(hItem,146+180, 119+63, 200, 42);
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		WM_SetWindowPos(hItem,146+180, 181+63, 200, 42);
	}
	
	//修改下拉框皮肤属性
	DROPDOWN_GetSkinFlexProps(&pProps,DROPDOWN_SKINFLEX_PI_ENABLED);
	pProps.aColorFrame[0] = 0x00a2a09e;
	pProps.aColorFrame[1] = 0x00ffffff;
	pProps.aColorFrame[2] = 0x00ffffff;
	
	pProps.aColorLower[0] = 0x00ffffff;
	pProps.aColorLower[1] = 0x00ffffff;
	
	pProps.aColorUpper[0] = 0x00ffffff;
	pProps.aColorUpper[1] = 0x00ffffff;
	
	pProps.Radius = 4;
	
	DROPDOWN_SetSkinFlexProps(&pProps,DROPDOWN_SKINFLEX_PI_ENABLED);
	DROPDOWN_SetSkinFlexProps(&pProps,DROPDOWN_SKINFLEX_PI_EXPANDED);
	DROPDOWN_SetSkinFlexProps(&pProps,DROPDOWN_SKINFLEX_PI_FOCUSED);
	
	
	//读取当前时间
	RTC_HYM8563GetTime(&RTCInfo);
	
	//设置按钮属性
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
	BUTTON_SetTextAlign(hItem,GUI_TA_LEFT|GUI_TA_VCENTER);
	BUTTON_SetFont(hItem,&GUI_Font24_ASCII);
	memset(Str,0,sizeof(Str));
	sprintf(Str,"20%d%d/%d%d/%d%d",
							RTCInfo.year.bcd_h,RTCInfo.year.bcd_l,
							RTCInfo.month.bcd_h,RTCInfo.month.bcd_l,
							RTCInfo.day.bcd_h,RTCInfo.day.bcd_l);
	BUTTON_SetText(hItem,Str);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetTextAlign(hItem,GUI_TA_LEFT|GUI_TA_VCENTER);
	BUTTON_SetFont(hItem,&GUI_Font24_ASCII);
	memset(Str,0,sizeof(Str));
	sprintf(Str,"%d%d:%d%d:%d%d",
							RTCInfo.hour.bcd_h,RTCInfo.hour.bcd_l,
							RTCInfo.min.bcd_h,RTCInfo.min.bcd_l,
							RTCInfo.sec.bcd_h,RTCInfo.sec.bcd_l);
	BUTTON_SetText(hItem,Str);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Cancel[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
	BUTTON_SetFont(hItem,&HZ_SONGTI_16);
	BUTTON_SetTextAlign(hItem,GUI_TA_HCENTER|GUI_TA_VCENTER);
	BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_GRAY);
	BUTTON_SetTextColor(hItem,BUTTON_CI_PRESSED,MachInfo.companyInfo.skin.buttPressFont);
	BUTTON_SetTextColor(hItem,BUTTON_CI_UNPRESSED,MachInfo.companyInfo.skin.buttNotPressFont);
	BUTTON_SetText(hItem,g_ucaLng_Sure[MachInfo.systemSet.eLanguage]);
	BUTTON_SetSkin(hItem,_Button_DrawSkin);									//设置皮肤回调函数
	
    // USER START (Optionally insert additional code for further widget initialization)
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    // USER END
    break;

  case WM_PAINT:
      //画背景BMP图
      //GUI_BMP_Draw(BKBmaDataBuf, 1, 0);
      //Show_SDRAM_BMP(SDRAM_BMP_Frame, 1, 0);
    
      WM_GetClientRect(&Rect); 
      GUI_SetColor(GUI_WHITE);
      GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);
  
      //画线
      GUI_SetColor(0x009ea0a2);
      GUI_DrawHLine(54, 8, 790);
  break;

  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'date_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatedataTimeSetPage();
	  
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.v = 0;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'time_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreatedataTimeSetPage();
	  
		pMsg->MsgId = WM_USER_DATA;
		pMsg->Data.v = 1;
		WM_SendMessage(g_hActiveWin,pMsg);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'langu_d'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'cel_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'confim_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
            // USER START (Optionally insert code for reacting on notification message)
            Msg_Head_t tMsgHead = {0};
            hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
            memset(Str,0,30);
            DROPDOWN_GetItemText(hItem,DROPDOWN_GetSel(hItem),Str,30);
            
            if(strcmp(Str,g_ucaLng_SET_Chinese[0]) == 0){
                if(MachInfo.systemSet.eLanguage != LANGUAGE_CHINESE){
                    MachInfo.systemSet.eLanguage = LANGUAGE_CHINESE;
                    EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_SYS_SET,(uint8_t*)&MachInfo.systemSet,sizeof(MachInfo.systemSet));
                    
					//切换语言后，切换打印报告单上标题
					memset((char*)MachInfo.printSet.ucaPrintTitle,0,sizeof(MachInfo.printSet.ucaPrintTitle));
					strcpy((char*)MachInfo.printSet.ucaPrintTitle,"血细胞检验报告单");
					EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PRINT_SET,(uint8_t*)&MachInfo.printSet,sizeof(MachInfo.printSet));
					
					//切换语言后，更新对应的登录图片
                    tMsgHead.usCmd = CMD_SET_UPDATE_LOGIN_PICTURE;
                    UI_Put_Msg((uint8_t*)&tMsgHead);
                }
            }else{
                if(MachInfo.systemSet.eLanguage != LANGUAGE_ENGLISH){
                    MachInfo.systemSet.eLanguage = LANGUAGE_ENGLISH;
                    EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_SYS_SET,(uint8_t*)&MachInfo.systemSet,sizeof(MachInfo.systemSet));
                    
					//切换语言后，切换打印报告单上标题
					memset((char*)MachInfo.printSet.ucaPrintTitle,0,sizeof(MachInfo.printSet.ucaPrintTitle));
					strcpy((char*)MachInfo.printSet.ucaPrintTitle,"Blood Cell Test Report");
					EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_PRINT_SET,(uint8_t*)&MachInfo.printSet,sizeof(MachInfo.printSet));
					
					//切换语言后，更新对应的登录图片
                    tMsgHead.usCmd = CMD_SET_UPDATE_LOGIN_PICTURE;
                    UI_Put_Msg((uint8_t*)&tMsgHead);
                }
            }
			
			//外部账号样本分析数据容量
			hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
            if(OutSideDataNum.index != DROPDOWN_GetSel(hItem)){
				extern WM_HWIN CreatesysConfigPage(void);
				CommonSwitchDialogPageData_s SwitchDialogData = {0};
				
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateSwitchDialogPage();
				
				//删除用户
				SwitchDialogData.switchDialogItem = CONFIG_CHANGE_DATA_NUM;
				SwitchDialogData.u32 = DROPDOWN_GetSel(hItem);							//传递要切换的数据容量索引值
				SwitchDialogData.dialogData.bmpType = BMP_ALARM;
				SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
				SwitchDialogData.dialogData.fun = CreatesysConfigPage;					//保存进入对话框前的界面创建函数
				strcpy(SwitchDialogData.dialogData.str,g_ucaLng_SET_ConfirmDataNum[MachInfo.systemSet.eLanguage]);
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.p = &SwitchDialogData;
				WM_SendMessage(g_hActiveWin,pMsg);
			}else{
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateSetPage();
			}
        // USER END
        }
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatesysConfigPage
*/
WM_HWIN CreatesysConfigPage(void);
WM_HWIN CreatesysConfigPage(void) {
  WM_HWIN hWin;

  WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
  Public_Show_Widget();
  Set_Cur_MenuID(CONFIG_SYS_PAGE_ID);
	
	Disable_Algo_Task();

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
