/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
#include "bsp_eeprom.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (CONFIG_USER_MANAGE_PAGE_ID + 0x00)
#define ID_TEXT_0 (CONFIG_USER_MANAGE_PAGE_ID + 0x01)
#define ID_TEXT_1 (CONFIG_USER_MANAGE_PAGE_ID + 0x02)
#define ID_BUTTON_0 (CONFIG_USER_MANAGE_PAGE_ID + 0x03)
#define ID_BUTTON_1 (CONFIG_USER_MANAGE_PAGE_ID + 0x04)
#define ID_BUTTON_3 (CONFIG_USER_MANAGE_PAGE_ID + 0x06)
#define ID_LISTVIEW_0 (CONFIG_USER_MANAGE_PAGE_ID + 0x07)
#define ID_BUTTON_4 (CONFIG_USER_MANAGE_PAGE_ID + 0x08)
#define ID_BUTTON_5 (CONFIG_USER_MANAGE_PAGE_ID + 0x09)
#define ID_BUTTON_6 (CONFIG_USER_MANAGE_PAGE_ID + 0x0a)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "UserManagePage", ID_WINDOW_0, 0, 63, 800, 395, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SET", ID_TEXT_0, 30, 15, 95, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "> USER", ID_TEXT_1, 125, 20, 150, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CEL", ID_BUTTON_0, 678, 11, 100, 40, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 220, 70, 480, 242, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "NEW USER", ID_BUTTON_4, 40, 70, 150, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "DEL USER", ID_BUTTON_5, 40, 120, 150, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SET DEFAULT", ID_BUTTON_6, 40, 170, 150, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "PASSWD", ID_BUTTON_1, 40, 220, 150, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "FACT RESET", ID_BUTTON_3, 40, 270, 150, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _UserManagePageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect(g_ucaLng_SET_ChangePsw[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect(g_ucaLng_SET_FactoryReset[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect(g_ucaLng_SET_NewUser[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect(g_ucaLng_SET_DelUser[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect(g_ucaLng_SET_SetDefault[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPress);
			GUI_AA_FillRoundedRectEx(&Rect,20);
			
			GUI_SetColor(MachInfo.companyInfo.skin.buttBoard);
			GUI_AA_DrawRoundedRectEx(&Rect,19);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.buttNotPressFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.buttNotPress);
			
			switch(WM_GetId(pMsg->hWin)){
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Return[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_1:
					GUI_DispStringInRect(g_ucaLng_SET_ChangePsw[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_3:
					GUI_DispStringInRect(g_ucaLng_SET_FactoryReset[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_4:
					GUI_DispStringInRect(g_ucaLng_SET_NewUser[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_5:
					GUI_DispStringInRect(g_ucaLng_SET_DelUser[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				case ID_BUTTON_6:
					GUI_DispStringInRect(g_ucaLng_SET_SetDefault[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
    break;
    }
}




/*
* 设置控件回调函数，以及重绘控件
*/
static void _UserManagePageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //返回按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _UserManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//修改密码按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);  
    WM_SetCallback(hItem, _UserManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//恢复出厂设置按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);  
    WM_SetCallback(hItem, _UserManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//新增用户按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);  
    WM_SetCallback(hItem, _UserManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//删除用户按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);  
    WM_SetCallback(hItem, _UserManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
	
	//设置默认用户按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);  
    WM_SetCallback(hItem, _UserManagePageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}

// USER END
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreateSetPage(void);
	extern WM_HWIN CreateDialogPage(void);
	extern WM_HWIN CreateUserManagePage(void);
	extern WM_HWIN CreateResetPswPage(void);
	extern WM_HWIN CreateSwitchDialogPage(void);
	extern WM_HWIN CreateAddUserPage(void);
	
	extern char* BKBmaDataBuf;
	extern MachInfo_s MachInfo;
	
	GUI_RECT Rect;
	HEADER_SKINFLEX_PROPS pProps;
	
	uint16_t TempU16 = 0;
	uint8_t i = 0;
	char Str[20] = {0};
	uint8_t RowNum = 0;
	
	CommonDialogPageData_s DialogPageData = {0};
	CommonSwitchDialogPageData_s SwitchDialogData = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		TEXT_SetFont(hItem,&HZ_SONGTI_24);
		WM_SetWindowPos(hItem,20, 13+63, 48, 30);
	}else{
		TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		WM_SetWindowPos(hItem,20, 13+63, 84, 30);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_HCENTER|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_Set[MachInfo.systemSet.eLanguage]);
	
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
	if(MachInfo.systemSet.eLanguage == LANGUAGE_CHINESE){
		WM_SetWindowPos(hItem,68, 20+63, 140, 20);
	}else{
		WM_SetWindowPos(hItem,104, 20+63, 140, 20);
	}
	TEXT_SetTextAlign(hItem,TEXT_CF_LEFT|TEXT_CF_VCENTER);
	TEXT_SetText(hItem,g_ucaLng_SET_User[MachInfo.systemSet.eLanguage]);
  
    //
    // Initialization of 'Listview'列表相关
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
  
	//设置HEADER皮肤属性
	LISTVIEW_GetHeader(hItem);
	HEADER_GetSkinFlexProps(&pProps,0);
	pProps.aColorLower[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorLower[1] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[0] = MachInfo.companyInfo.skin.title;
	pProps.aColorUpper[1] = MachInfo.companyInfo.skin.title;
	HEADER_SetSkinFlexProps(&pProps,0);
	
	LISTVIEW_SetFont(hItem,&HZ_SONGTI_16);
	LISTVIEW_AddColumn(hItem, 130, g_ucaLng_SET_UserName[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 80, g_ucaLng_SET_Limit[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 150, g_ucaLng_SET_Type[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_AddColumn(hItem, 120, g_ucaLng_SET_Default[MachInfo.systemSet.eLanguage], GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_SetRowHeight(hItem, 40);
    LISTVIEW_SetHeaderHeight(hItem, 40);
	LISTVIEW_SetBkColor(hItem,LISTVIEW_CI_SELFOCUS,MachInfo.companyInfo.skin.buttPress);
	LISTVIEW_SetAutoScrollV(hItem,1);
	
	//判断当前账号是否为超级用户，不是则不显示该账户
	if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type == ACCOUNT_TYPE_SUPER){
		i = 0;
	}else{
		i = 1;
	}
	
	//行号
	RowNum = 0;
	
	for(;i<MachInfo.accountMM.endIndex;i++){
		LISTVIEW_AddRow(hItem, NULL);
		LISTVIEW_SetItemText(hItem,0,RowNum,MachInfo.accountMM.accountInfo[i].user);
		
		memset(Str,0,20);
		sprintf(Str,"%u",MachInfo.accountMM.accountInfo[i].authority);
		LISTVIEW_SetItemText(hItem,1,RowNum,Str);
		
		switch(MachInfo.accountMM.accountInfo[i].type){
			case ACCOUNT_TYPE_SUPER:
				LISTVIEW_SetItemText(hItem,2,RowNum,g_ucaLng_SET_SuperUser[MachInfo.systemSet.eLanguage]);
			break;
			case ACCOUNT_TYPE_ADMIN:
				LISTVIEW_SetItemText(hItem,2,RowNum,g_ucaLng_SET_AdminUser[MachInfo.systemSet.eLanguage]);
			break;
			case ACCOUNT_TYPE_NORMAL:
				LISTVIEW_SetItemText(hItem,2,RowNum,g_ucaLng_SET_NormalUser[MachInfo.systemSet.eLanguage]);
			break;
			case ACCOUNT_TYPE_NEW:
				LISTVIEW_SetItemText(hItem,2,RowNum,g_ucaLng_SET_NewUserN[MachInfo.systemSet.eLanguage]);
			break;
			default :break;
		}
		
		if(MachInfo.accountMM.defaultIndex == i){
			LISTVIEW_SetItemText(hItem,3,RowNum,"√");
		}
		
		RowNum++;
	}
	
	//重绘按钮样式
	_UserManagePageRedrawWidgetType(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    //设置窗口颜色和背景颜色一致
    WINDOW_SetBkColor(pMsg->hWin, MachInfo.companyInfo.skin.bg);
    // USER END
    break;
	
	case WM_PAINT:
        WM_GetClientRect(&Rect); 
        GUI_SetColor(GUI_WHITE);
        GUI_AA_FillRoundedRect(Rect.x0+10, Rect.y0, Rect.x1-10, Rect.y1+10, 10);

		//画线
		GUI_SetColor(0x009ea0a2);
		GUI_DrawHLine(54,8,790);
	break;
	
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'return_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
        g_hActiveWin = CreateSetPage();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'changePassward_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetSel(hItem);
		
		//判断下是否具备权限修改密码
		if(TempU16 == 0xFFFF){
			GUI_EndDialog(pMsg->hWin, 0);
			g_hActiveWin = CreateDialogPage();
			
			//保存对话框内容
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
			strcpy(DialogPageData.str,g_ucaLng_SET_DianjiXuanxiang[MachInfo.systemSet.eLanguage]);
			
			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &DialogPageData;
			WM_SendMessage(g_hActiveWin,pMsg);
		}else{
			//判断当前账号是否为超级用户，不是，则需要加1
			if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
				TempU16 += 1;
			}
			
			if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[TempU16].authority){
				//没有权限修改
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateDialogPage();
				
				//保存对话框内容
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
				strcpy(DialogPageData.str,g_ucaLng_SET_NoLimit[MachInfo.systemSet.eLanguage]);
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.p = &DialogPageData;
				WM_SendMessage(g_hActiveWin,pMsg);
			}else{
				//有权限修改，进入修改密码界面
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateResetPswPage();
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.v = TempU16;										//传递要修改的账户索引值
				WM_SendMessage(g_hActiveWin,pMsg);
			}
		} 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'recoverPsw_b'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetSel(hItem);
		
		//判断下是否具备权限修改密码
		if(TempU16 == 0xFFFF){
			GUI_EndDialog(pMsg->hWin, 0);
			g_hActiveWin = CreateDialogPage();
			
			//保存对话框内容
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
			strcpy(DialogPageData.str,g_ucaLng_SET_DianjiXuanxiang[MachInfo.systemSet.eLanguage]);
			
			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &DialogPageData;
			WM_SendMessage(g_hActiveWin,pMsg);
		}else{
			//判断当前账号是否为超级用户，不是，则需要加1
			if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
				TempU16 += 1;
			}
			
			if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[TempU16].authority){
				//没有权限修改
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateDialogPage();
				
				//保存对话框内容
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
				strcpy(DialogPageData.str,g_ucaLng_SET_NoLimit[MachInfo.systemSet.eLanguage]);
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.p = &DialogPageData;
				WM_SendMessage(g_hActiveWin,pMsg);
			}else{
				//有权限修改，进入选择对话框确认界面
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateSwitchDialogPage();
				
				//恢复出厂密码
				SwitchDialogData.switchDialogItem = CONFIG_USERMANAGE_RECOVER_FACTORY_PSW;
				SwitchDialogData.u32 = TempU16;											//传递要修改的账户索引值
				SwitchDialogData.dialogData.bmpType = BMP_ALARM;
				SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
				SwitchDialogData.dialogData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
				strcpy(SwitchDialogData.dialogData.str,g_ucaLng_SET_ConfimPsw[MachInfo.systemSet.eLanguage]);
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.p = &SwitchDialogData;
				WM_SendMessage(g_hActiveWin,pMsg);
			}
		} 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
	  
	case ID_BUTTON_6: // Notifications sent by '设置默认账户'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetSel(hItem);
		
		//判断下是否具备权限修改密码
		if(TempU16 == 0xFFFF){
			GUI_EndDialog(pMsg->hWin, 0);
			g_hActiveWin = CreateDialogPage();
			
			//保存对话框内容
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
			strcpy(DialogPageData.str,g_ucaLng_SET_DianjiXuanxiang[MachInfo.systemSet.eLanguage]);
			
			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &DialogPageData;
			WM_SendMessage(g_hActiveWin,pMsg);
		}else{
			if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority){
				//没有权限修改
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateDialogPage();
				
				//保存对话框内容
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
				strcpy(DialogPageData.str,g_ucaLng_SET_NoLimit[MachInfo.systemSet.eLanguage]);
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.p = &DialogPageData;
				WM_SendMessage(g_hActiveWin,pMsg);
			}else{
				uint16_t Temp2 = 0;
				
				//有权限修改默认用户值
				hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
				Temp2 = LISTVIEW_GetNumRows(hItem);
				for(i=0;i<Temp2;i++){
					LISTVIEW_DeleteRow(hItem,0);
				}
				
				i = 0;
				
				//判断当前账号是否为超级用户
				if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
					TempU16 += 1;
					i = 1;
				}
				
				MachInfo.accountMM.defaultIndex = TempU16;
				EEPROMWriteData(EEPROM_24C32,MAIN_BORD_EEPROM_24C32,EPPROM_ADDR_MACHINFO_ACCOUNT_MM,(uint8_t*)&MachInfo.accountMM,sizeof(MachInfo.accountMM));
				
				//行号
				RowNum = 0;
				
				for(;i<MachInfo.accountMM.endIndex;i++){
					LISTVIEW_AddRow(hItem, NULL);
					LISTVIEW_SetItemText(hItem,0,RowNum,MachInfo.accountMM.accountInfo[i].user);
					
					memset(Str,0,20);
					sprintf(Str,"%u",MachInfo.accountMM.accountInfo[i].authority);
					LISTVIEW_SetItemText(hItem,1,RowNum,Str);
					
					switch(MachInfo.accountMM.accountInfo[i].type){
						case ACCOUNT_TYPE_SUPER:
							LISTVIEW_SetItemText(hItem,2,RowNum,g_ucaLng_SET_SuperUser[MachInfo.systemSet.eLanguage]);
						break;
						case ACCOUNT_TYPE_ADMIN:
							LISTVIEW_SetItemText(hItem,2,RowNum,g_ucaLng_SET_AdminUser[MachInfo.systemSet.eLanguage]);
						break;
						case ACCOUNT_TYPE_NORMAL:
							LISTVIEW_SetItemText(hItem,2,RowNum,g_ucaLng_SET_NormalUser[MachInfo.systemSet.eLanguage]);
						break;
						case ACCOUNT_TYPE_NEW:
							LISTVIEW_SetItemText(hItem,2,RowNum,g_ucaLng_SET_NewUserN[MachInfo.systemSet.eLanguage]);
						break;
						default :break;
					}
					
					if(MachInfo.accountMM.defaultIndex == i){
						LISTVIEW_SetItemText(hItem,3,RowNum,"√");
					}
					
					RowNum++;
				}
			}
		} 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
    break;
	  
	case ID_BUTTON_4: // Notifications sent by '新增用户'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority < MachInfo.accountMM.accountInfo[ACCOUNT_TYPE_ADMIN].authority){
			//没有权限修改
			GUI_EndDialog(pMsg->hWin, 0);
			g_hActiveWin = CreateDialogPage();
			
			//保存对话框内容
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
			strcpy(DialogPageData.str,g_ucaLng_SET_NoLimit[MachInfo.systemSet.eLanguage]);
			
			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &DialogPageData;
			WM_SendMessage(g_hActiveWin,pMsg);
		}else{
			//进入新增用户界面
			//判断是否还能新增用户
			if(MachInfo.accountMM.endIndex >= ACCOUNT_MAX_NUM){
				//用户数据量已满
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateDialogPage();
				
				//保存对话框内容
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
				strcpy(DialogPageData.str,g_ucaLng_SET_UserFull[MachInfo.systemSet.eLanguage]);
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.p = &DialogPageData;
				WM_SendMessage(g_hActiveWin,pMsg);
			}else{
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateAddUserPage();
			}
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
    break;  
	  
	case ID_BUTTON_5: // Notifications sent by '删除用户'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
		TempU16 = LISTVIEW_GetSel(hItem);
		
		//判断下是否具备权限修改密码
		if(TempU16 == 0xFFFF){
			GUI_EndDialog(pMsg->hWin, 0);
			g_hActiveWin = CreateDialogPage();
			
			//保存对话框内容
			DialogPageData.bmpType = BMP_ALARM;
			DialogPageData.confimButt = HAS_CONFIM_BUTTON;
			DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
			strcpy(DialogPageData.str,g_ucaLng_SET_DianjiXuanxiang[MachInfo.systemSet.eLanguage]);
			
			pMsg->MsgId = WM_USER_DATA;
			pMsg->Data.p = &DialogPageData;
			WM_SendMessage(g_hActiveWin,pMsg);
		}else{
			//判断当前账号是否为超级用户，不是，则需要加1
			if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].type != ACCOUNT_TYPE_SUPER){
				TempU16 += 1;
			}
			
			if(MachInfo.accountMM.accountInfo[MachInfo.accountMM.curIndex].authority <= MachInfo.accountMM.accountInfo[TempU16].authority){
				//没有权限删除
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateDialogPage();
				
				//保存对话框内容
				DialogPageData.bmpType = BMP_ALARM;
				DialogPageData.confimButt = HAS_CONFIM_BUTTON;
				DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
				strcpy(DialogPageData.str,g_ucaLng_SET_NoLimit[MachInfo.systemSet.eLanguage]);
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.p = &DialogPageData;
				WM_SendMessage(g_hActiveWin,pMsg);
			}else{
				if(MachInfo.accountMM.accountInfo[TempU16].type == ACCOUNT_TYPE_SUPER || MachInfo.accountMM.accountInfo[TempU16].type == ACCOUNT_TYPE_ADMIN || MachInfo.accountMM.accountInfo[TempU16].type == ACCOUNT_TYPE_NORMAL){
					//没有权限删除内置账号
					GUI_EndDialog(pMsg->hWin, 0);
					g_hActiveWin = CreateDialogPage();
					
					//保存对话框内容
					DialogPageData.bmpType = BMP_ALARM;
					DialogPageData.confimButt = HAS_CONFIM_BUTTON;
					DialogPageData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
					strcpy(DialogPageData.str,g_ucaLng_SET_NoLimit[MachInfo.systemSet.eLanguage]);
					
					pMsg->MsgId = WM_USER_DATA;
					pMsg->Data.p = &DialogPageData;
					WM_SendMessage(g_hActiveWin,pMsg);
					
					return;
				}
				
				//有权限删除，进入选择对话框确认界面
				GUI_EndDialog(pMsg->hWin, 0);
				g_hActiveWin = CreateSwitchDialogPage();
				
				//删除用户
				SwitchDialogData.switchDialogItem = CONFIG_DEL_USER;
				SwitchDialogData.u32 = TempU16;											//传递要删除的账户索引值
				SwitchDialogData.dialogData.bmpType = BMP_ALARM;
				SwitchDialogData.dialogData.confimButt = HAS_CONFIM_BUTTON;
				SwitchDialogData.dialogData.fun = CreateUserManagePage;					//保存进入对话框前的界面创建函数
				strcpy(SwitchDialogData.dialogData.str,g_ucaLng_SET_ConfimDelUser[MachInfo.systemSet.eLanguage]);
				
				pMsg->MsgId = WM_USER_DATA;
				pMsg->Data.p = &SwitchDialogData;
				WM_SendMessage(g_hActiveWin,pMsg);
			}
		} 
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
    break;
	
	  
    case ID_LISTVIEW_0: // Notifications sent by 'Listview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateUserManagePage
*/
WM_HWIN CreateUserManagePage(void);
WM_HWIN CreateUserManagePage(void) {
  WM_HWIN hWin;
	
	WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
	Public_Show_Widget();
	
	Disable_Algo_Task();

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
