/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "Public_menuDLG.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (DIALOG_PAGE_ID + 0x00)
//#define ID_IMAGE_0 (DIALOG_PAGE_ID + 0x01)
#define ID_TEXT_IMAGE_0 (DIALOG_PAGE_ID + 0x01)
#define ID_BUTTON_0 (DIALOG_PAGE_ID + 0x02)
#define ID_TEXT_0 (DIALOG_PAGE_ID + 0x03)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

//
static CommonDialogPageData_s DialogPageData = {0};


/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "DialogPage", ID_WINDOW_0, 180, 96, 440, 230, 0, 0x0, 20 },
  //{ IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 173, 27, 90, 90, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_TEXT_IMAGE_0, 173, 35, 90, 90, 0, 0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 190, 440, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 120, 440, 60, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// image text callback
static void _Text_Image_Callback(WM_MESSAGE* pMsg, DialogBmpType_e eBmpType)
{
    switch(pMsg->MsgId)
    {
        case WM_PAINT:
        {
            GUI_RECT Rect;
            GUI_GetClientRect(&Rect);
            GUI_SetColor(GUI_WHITE);
            GUI_FillRectEx(&Rect);
            
            switch(eBmpType){
				case BMP_ALARM:
					Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Err, 0, 0);
				break;
				
				case BMP_OK:
					Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_Ok, 0, 0);
				break;
				
				case BMP_SELF_CHECK:
					Show_BK_BMP(BK_SDRAM, BK_PICTURE_SERVICE_SelfCheck, 0, 0);
				break;
            }
        }
        break;
        default:
            TEXT_Callback(pMsg);
            break;
    }
}

//iamge 
static void Text_Image_Callback(WM_MESSAGE* pMsg)
{
    _Text_Image_Callback(pMsg, DialogPageData.bmpType);
}



// USER START (Optionally insert additional static code)
static void _DialogPageRedrawWidgetType_Callback(WM_MESSAGE* pMsg)
{
    switch (pMsg->MsgId)
    {
    case WM_PAINT:
    {
        GUI_RECT Rect;
        WM_GetClientRect(&Rect);

        if (BUTTON_IsPressed(pMsg->hWin)) {
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelect);
			GUI_FillRectEx(&Rect);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.highlightKJSelectFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJSelect);
			
			switch(WM_GetId(pMsg->hWin)){
				//确认按钮
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
        else{
			//填充
			GUI_SetColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
			GUI_FillRectEx(&Rect);
			
			//设置字符前景和背景色
			GUI_SetColor(MachInfo.companyInfo.skin.highlightKHNotSelectFont);
			GUI_SetBkColor(MachInfo.companyInfo.skin.highlightKJNotSelect);
			
			switch(WM_GetId(pMsg->hWin)){
				//确认按钮
				case ID_BUTTON_0:
					GUI_DispStringInRect(g_ucaLng_Sure[MachInfo.systemSet.eLanguage],&Rect,GUI_TA_HCENTER|GUI_TA_VCENTER);
				break;
				
				default :break;
			}
        }
    }
    break;
    default:
        BUTTON_Callback(pMsg);
        break;
    }
}



static void _DialogPageRedrawWidgetType(WM_MESSAGE* pMsg)
{
    WM_HWIN hItem;
	
    //确定按钮
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);  
    WM_SetCallback(hItem, _DialogPageRedrawWidgetType_Callback);
    WM_InvalidateWindow(hItem);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN      hItem;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
	extern WM_HWIN CreateUserManagePage(void);
	extern WM_HWIN DialogWin;
	
	GUI_RECT Rect;
    WM_GetClientRect(&Rect);
	
	//static CommonDialogPageData_s DialogPageData = {0};
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
	hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_0);
	TEXT_SetFont(hItem,&HZ_SONGTI_16);
	TEXT_SetTextColor(hItem,0x001a1a1a);
	TEXT_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
  
	//重绘按钮样式
	_DialogPageRedrawWidgetType(pMsg);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  
  case WM_DELETE:
  {
	DialogWin = NULL;
  }
  break;
  
	case WM_PAINT:
		//先设置弹窗和背景为相同的透明度
		GUI_SetColor(0x00525a4e);
		GUI_FillRectEx(&Rect);
	  
		//重绘弹窗为圆角矩形
		GUI_SetColor(0x00ffffff);
		GUI_AA_FillRoundedRectEx(&Rect,6);
  break;
  
  //用户数据
  case WM_USER_DATA:
		DialogPageData = *((CommonDialogPageData_s*)pMsg->Data.p);
  
		hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_0);
		TEXT_SetText(hItem,DialogPageData.str);
  
		//选择显示的图标
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_IMAGE_0);
        WM_SetCallback(hItem, Text_Image_Callback);
        WM_InvalidateWindow(hItem);
		
		//是否需要显示确认按键
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		if(DialogPageData.confimButt == NO_CONFIM_BUTTON){
			WM_HideWindow(hItem);
		}else{
			WM_ShowWindow(hItem);
		}
  break;
  
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		GUI_EndDialog(pMsg->hWin, 0);
		if(DialogPageData.fun == NULL){
			WM_ShowWindow(g_hActiveWin);
			WM_SetCallback(WM_HBKWIN, Public_cbBkWin);
			Public_Show_Widget();
		}else{
			g_hActiveWin = DialogPageData.fun();
		}
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateDialogPage
*/
WM_HWIN CreateDialogPage(void);
WM_HWIN CreateDialogPage(void) {
  WM_HWIN hWin;
	
	WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin);
	Public_Hide_Widget();

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
