/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

/*
*
*   GIF动画显示界面
*
*/

// USER END

#include "DIALOG.h"
#include "WM.h"
#include "GUI.h"
#include "LISTBOX.h"

//#include "Analysis_MenuDLG.h"
#include "file_operate.h"
#include "Public_menuDLG.h"
#include "ui_files.h"
#include "bsp_outin.h"
#include "PrinterTask.h"
#include "msg_def.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define OPERATE_GUIDE_ORG_X		100
#define OPERATE_GUIDE_ORG_Y		60




//背景窗口 回调函数
void GIF_Guide_cbBkWin(WM_MESSAGE* pMsg)
{
    extern __IO osSemaphoreId_t xSema_Count_Key;
    int8_t cTemp = 0;
    
    switch (pMsg->MsgId)
    {
		case WM_INPUT_GUIDE_GIF:
		{
			cTemp = Show_GIF(GIF_INPUT_GUIDE, OPERATE_GUIDE_ORG_X, OPERATE_GUIDE_ORG_Y);
            
            GUI_Delay(10);
			
            if(cTemp == 0){
				//由计数池检测状态变化退出GIF
				//切换到操作应到动画
				cTemp = Show_GIF(GIF_OPERATE_GUIDE, OPERATE_GUIDE_ORG_X, OPERATE_GUIDE_ORG_Y);
				g_hActiveWin = Analysis_Menu();
				
				if(cTemp == 2){
					Msg_Head_t tMsgHead = {0};
					
					tMsgHead.usCmd = CMD_OTHERS_START_COUNT;
					UI_Put_Msg((uint8_t*)&tMsgHead);
				}
			}else if(1 == cTemp){
				//操作指导动画，由进出仓键触发而退出
				g_hActiveWin = Analysis_Menu();
                WM_SendMessageNoPara(g_hActiveWin, WM_ANALYSIS_GIF_OPERATE_OUTIN_KEY);
            }else if(2 == cTemp){
				//操作指导动画，由计数键触发而退出
				g_hActiveWin = Analysis_Menu();
            }else{
				g_hActiveWin = Analysis_Menu();
			}
		}
		break;
        case WM_RE_INPUT_GUIDE_GIF:
		{
			cTemp = Show_GIF(GIF_RE_INPUT_GUIDE, OPERATE_GUIDE_ORG_X, OPERATE_GUIDE_ORG_Y);		
            
            GUI_Delay(10);
			
			if(cTemp == 0){
				//由计数池检测状态变化退出GIF
				//切换到操作应到动画
				cTemp = Show_GIF(GIF_OPERATE_GUIDE, OPERATE_GUIDE_ORG_X, OPERATE_GUIDE_ORG_Y);
				g_hActiveWin = Analysis_Menu();
				if(cTemp == 2){
					Msg_Head_t tMsgHead = {0};
					
					tMsgHead.usCmd = CMD_OTHERS_START_COUNT;
					UI_Put_Msg((uint8_t*)&tMsgHead);
				}
			}else if(1 == cTemp){
				//操作指导动画，由进出仓键触发而退出
				g_hActiveWin = Analysis_Menu();
                WM_SendMessageNoPara(g_hActiveWin, WM_ANALYSIS_GIF_OPERATE_OUTIN_KEY);
            }else if(2 == cTemp){
				//操作指导动画，由计数键触发而退出
				g_hActiveWin = Analysis_Menu();
            }else{
				g_hActiveWin = Analysis_Menu();
			}
		}
		break;
		case WM_OK_OUTPUT_GUIDE_GIF: //本次样本测试成功， 提示拿出计数池
		{     
			Show_GIF(GIF_OK_OUTPUT_GUIDE, OPERATE_GUIDE_ORG_X, OPERATE_GUIDE_ORG_Y);
            
            //请确认检测模块是否取出 界面
             WM_SetCallback(WM_HBKWIN, AlphaBk_cbBkWin); //AlphaBk_cbBkWin  None_cbBkWin
            g_hActiveWin = Confirm_Takeout_Cell_WindowDLG();
            GUI_Delay(10);  
		}
		break;
        case WM_FAIL_OUTPUT_GUIDE_GIF2:  //本次样本测试无效，请拿出血细胞模块（只包括GIF）
		{
			Show_GIF(GIF_FAIL_OUTPUT_GUIDE2, OPERATE_GUIDE_ORG_X, OPERATE_GUIDE_ORG_Y);
 
			g_hActiveWin = ReCount_PromptDLG();
		}
		break;
        case WM_OPERATE_GUIDE_GIF: //显示操作引导动画
        {           
			cTemp = Show_GIF(GIF_OPERATE_GUIDE, OPERATE_GUIDE_ORG_X, OPERATE_GUIDE_ORG_Y);
            
            g_hActiveWin = Analysis_Menu();
            if(2 == cTemp)
            {     
				Msg_Head_t tMsgHead = {0};

				tMsgHead.usCmd = CMD_OTHERS_START_COUNT;
				UI_Put_Msg((uint8_t*)&tMsgHead);
            }
        }
        default:
        {
            WM_DefaultProc(pMsg);
        }
        break;    
    }
}




// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
