/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: ËÎÌו24.c                                              *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        670D - 670D                                  *
* Range enabled:        52A1 - 52A1                                  *
* Range enabled:        8BBE - 8BBE                                  *
* Range enabled:        7F6E - 7F6E                                  *
* Range enabled:        8D28 - 8D28                                  *
* Range enabled:        63A7 - 63A7                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font24_52A1[ 72] = { /* code 52A1 */
  ________,________,________,
  ________,X_______,________,
  ________,XX______,________,
  _______X,XXXXXXXX,X_______,
  _______X,_______X,X_______,
  ______X_,X______X,________,
  ______X_,_X____XX,________,
  _____X__,__X__XX_,________,
  ____X___,___XXX__,________,
  ___X____,___XX___,________,
  ________,__X__XX_,________,
  ________,XXX___XX,XX______,
  ______XX,__XX____,XXXXXXX_,
  ___XXX__,__XX____,___XX___,
  _XX__XXX,XXXXXXXX,XX______,
  ________,__X_____,_X______,
  ________,_XX_____,_X______,
  ________,_X______,XX______,
  ________,XX______,XX______,
  ________,X_______,X_______,
  ______XX,____X___,X_______,
  ____XX__,_____XXX,X_______,
  ___X____,______XX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_63A7[ 72] = { /* code 63A7 */
  ________,________,________,
  _____X__,________,________,
  _____XX_,______X_,________,
  _____X__,_______X,X_______,
  _____X__,_______X,________,
  _____X__,__XXXXXX,XXXXXX__,
  _XXXXXXX,X_X_____,____XX__,
  _____X__,_XX__X__,____X___,
  _____X__,_____XX_,XX______,
  _____X__,____XX__,__XX____,
  _____X__,X__XX___,___XX___,
  _____X_X,__X_____,____X___,
  ____XXX_,_X______,____X___,
  _XXX_X__,__XXXXXX,XXXX____,
  _XX__X__,______XX,________,
  _____X__,______XX,________,
  _____X__,______XX,________,
  _____X__,______XX,________,
  _____X__,______XX,________,
  _____X__,______XX,________,
  _____X__,XXXXXXXX,XXXXXX__,
  __XXXX__,________,________,
  ____X___,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_670D[ 72] = { /* code 670D */
  ________,________,________,
  ________,________,________,
  ___XXXXX,XX__XXXX,XXXXX___,
  ____X___,_X__X___,___X____,
  ____X___,_X__X___,___X____,
  ____X___,_X__X___,___X____,
  ____X___,_X__X___,___X____,
  ____XXXX,XX__X__X,XXXX____,
  ____X___,_X__X___,_XX_____,
  ____X___,_X__X___,________,
  ____X___,_X__X___,________,
  ____X___,_X__XXXX,XXXXX___,
  ____X___,_X__X_X_,___XX___,
  ____XXXX,XX__X__X,___X____,
  ____X___,_X__X__X,___X____,
  ___XX___,_X__X___,X__X____,
  ___XX___,_X__X___,X_X_____,
  ___X____,_X__X___,_XX_____,
  ___X____,_X__X___,_XX_____,
  ___X____,_X__X___,X_XX____,
  __X__XX_,_X__X__X,___XXX__,
  __X____X,XX__XXX_,_____X__,
  _X______,____X___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_7F6E[ 72] = { /* code 7F6E */
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____X___,_X____X_,___X____,
  ____X___,_X____X_,___X____,
  ____X___,_X____X_,___X____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____X___,___X____,___X____,
  ________,___X____,___X____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,___X____,_X______,
  ______XX,XXXXXXXX,XXX_____,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X___X__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_8BBE[ 72] = { /* code 8BBE */
  ________,________,________,
  ________,________,________,
  ____X___,___XXXXX,XX______,
  _____X__,___XX___,_XX_____,
  _____XX_,___XX___,_X______,
  _____XX_,___XX___,_X______,
  ________,___X____,_X______,
  ________,___X____,_X______,
  ________,__X_____,_X______,
  _XXXXXX_,_XX_____,_XXXXXX_,
  _____X__,X_______,__X_____,
  _____X_X,__XXXXXX,XXXX____,
  _____X__,___X____,__X_____,
  _____X__,____X___,_XX_____,
  _____X__,____X___,_XX_____,
  _____X__,_____X__,_X______,
  _____X__,_X___X__,X_______,
  _____X__,X_____XX,X_______,
  _____X_X,______XX,________,
  _____XX_,_____XX_,XX______,
  _____XX_,___XX___,_XXX____,
  ________,_XX_____,___XXX__,
  _______X,X_______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font24_8D28[ 72] = { /* code 8D28 */
  ________,________,________,
  ________,________,__X_____,
  ________,_____XXX,XXXX____,
  ____XXXX,XXXXX___,________,
  ____X___,_____X__,________,
  ____X___,_____X__,___X____,
  ____X_XX,XXXXXXXX,XXXXX___,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____X___,XXXXXXXX,XXXX____,
  ____X___,X_______,__X_____,
  ____X___,X____X__,__X_____,
  ____X___,X____X__,__X_____,
  ____X___,X____X__,__X_____,
  ____X___,X___XX__,__X_____,
  ___XX___,X___XX__,__X_____,
  ___X____,X___X___,__X_____,
  ___X____,___XXXX_,________,
  __X_____,__XX___X,XX______,
  __X_____,_XX_____,_XXX____,
  _X_____X,X_______,___XX___,
  _____XX_,________,____X___,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font24_CharInfo[6] = {
   {  24,  24,  3, acGUI_Font24_52A1 } /* code 52A1 */
  ,{  24,  24,  3, acGUI_Font24_63A7 } /* code 63A7 */
  ,{  24,  24,  3, acGUI_Font24_670D } /* code 670D */
  ,{  24,  24,  3, acGUI_Font24_7F6E } /* code 7F6E */
  ,{  24,  24,  3, acGUI_Font24_8BBE } /* code 8BBE */
  ,{  24,  24,  3, acGUI_Font24_8D28 } /* code 8D28 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font24_Prop6 = {
   0x8D28 /* first character */
  ,0x8D28 /* last character  */
  ,&GUI_Font24_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font24_Prop5 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_Font24_CharInfo[  4] /* address of first character */
  ,&GUI_Font24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font24_Prop4 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Font24_CharInfo[  3] /* address of first character */
  ,&GUI_Font24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font24_Prop3 = {
   0x670D /* first character */
  ,0x670D /* last character  */
  ,&GUI_Font24_CharInfo[  2] /* address of first character */
  ,&GUI_Font24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font24_Prop2 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_Font24_CharInfo[  1] /* address of first character */
  ,&GUI_Font24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font24_Prop1 = {
   0x52A1 /* first character */
  ,0x52A1 /* last character  */
  ,&GUI_Font24_CharInfo[  0] /* address of first character */
  ,&GUI_Font24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

